//! `io/real_board.py::_copper_reach_mm` — how far a component's copper extends
//! from its own origin.
//!
//! `max over pads of (|offset| + pad_bounding_radius(...))`. Both halves already
//! live in this crate (`pad_geometry::py_hypot`, `pad_geometry::bounding_radius`),
//! which is why the kernel lives here rather than being duplicated into the
//! crate that owns `real_board.py`'s other concerns.
//!
//! ## The NaN contract
//!
//! The reference is CPython's builtin `max()` over a generator. That keeps the
//! FIRST NaN it encounters and then compares nothing against it — every later
//! candidate loses the `>` test against NaN. `f64::max` does the opposite: it
//! DISCARDS NaN and returns the other operand. Using it here would turn a NaN
//! reach into a finite one, and a NaN reach is what an unparseable pad produces,
//! so the difference is reachable from real boards rather than theoretical.
//!
//! `py_hypot` also returns `inf` before `nan` (CPython's `vector_norm` returns
//! `+inf` as soon as any coordinate is infinite, even alongside a NaN), so an
//! infinite offset yields `inf`, not NaN.

#[cfg(feature = "python")]
use pyo3::prelude::*;
#[cfg(feature = "python")]
use pyo3::types::PyModule;

use crate::pad_geometry::{bounding_radius, py_hypot};

/// One pad: `(offset_x, offset_y, width, height, shape_code, roundrect_ratio)`.
pub type PadRow = (f64, f64, f64, f64, i64, f64);

/// CPython's builtin `max()` over an iterable of floats.
///
/// Seeded with the first element and updated only on a strict `>`, so a NaN
/// seed is never displaced and a NaN encountered mid-stream is never adopted.
/// This is the same asymmetry recorded for `min`/`max` elsewhere in this repo.
fn cpython_max(values: impl Iterator<Item = f64>) -> Option<f64> {
    let mut it = values;
    let mut acc = it.next()?;
    for v in it {
        if v > acc {
            acc = v;
        }
    }
    Some(acc)
}

pub fn copper_reach_mm(pads: &[PadRow]) -> f64 {
    // `if not pads: return 0.0` — an empty component has no copper.
    cpython_max(pads.iter().map(|&(ox, oy, w, h, shape, ratio)| {
        py_hypot(ox, oy) + bounding_radius(w, h, shape, ratio)
    }))
    .unwrap_or(0.0)
}

/// `rotation_deg` is accepted by the Python reference purely to make the
/// rotation-invariance explicit at the call site; it is provably unused
/// (`|offset|` is rotation-invariant and so is the bounding radius). It is not
/// part of this signature — replicating a deliberately-ignored parameter would
/// invite a caller to believe it does something.
#[cfg(feature = "python")]
#[pyfunction]
#[pyo3(name = "copper_reach_mm_py")]
pub fn copper_reach_mm_py(pads: Vec<PadRow>) -> PyResult<f64> {
    temper_py_bridge::catch_unwind(|| copper_reach_mm(&pads))
        .map_err(temper_py_bridge::panic_to_err)
}

#[cfg(feature = "python")]
pub fn register(module: &Bound<'_, PyModule>) -> PyResult<()> {
    module.add_function(wrap_pyfunction!(copper_reach_mm_py, module)?)?;
    Ok(())
}

#[cfg(any(test, feature = "wasm-registry"))]
#[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]
pub(crate) mod tests {
    use super::*;

    #[cfg_attr(test, test)]
    fn empty_component_has_no_reach() {
        assert_eq!(copper_reach_mm(&[]), 0.0);
    }

    #[cfg_attr(test, test)]
    fn keeps_a_nan_the_way_cpython_max_does() {
        // A NaN offset must survive: `f64::max` would discard it and report the
        // finite pad's reach instead, understating the copper extent.
        let pads = vec![
            (f64::NAN, 0.0, 1.0, 1.0, 0, 0.25),
            (10.0, 0.0, 1.0, 1.0, 0, 0.25),
        ];
        assert!(copper_reach_mm(&pads).is_nan(), "first-NaN must not be displaced");
    }

    #[cfg_attr(test, test)]
    fn infinity_beats_nan_via_py_hypot() {
        let pads = vec![(f64::INFINITY, f64::NAN, 1.0, 1.0, 0, 0.25)];
        assert!(copper_reach_mm(&pads).is_infinite());
    }

// --- BEGIN generated by scripts/gen_oracle_freeze.py: copper_reach ---
    /// Frozen golden vectors for `copper_reach_mm` (FREEZE, U4/U5).
    /// Regenerate: `python3 scripts/gen_oracle_freeze.py --spec copper_reach`
    /// (requires reviving the deleted oracle from git history first -- see
    /// scripts/oracle_freeze_specs/copper_reach.py's module docstring).
    struct FrozenCopperReachCase {
        pads: &'static [PadRow],
        expected_bits: u64,
        tags: &'static [&'static str],
    }

    const FROZEN_COPPER_REACH_GOLDEN: &[FrozenCopperReachCase] = &[
        FrozenCopperReachCase {
            pads: &[],
            expected_bits: 0x0000000000000000_u64,
            tags: &["empty", "named:empty"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x0000000000000000_u64), f64::from_bits(0x0000000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x3ff1e3779b97f4a8_u64,
            tags: &["named:single_at_origin", "shape_rect", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x4008000000000000_u64), f64::from_bits(0x4010000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x401878dde6e5fd2a_u64,
            tags: &["named:single_offset", "shape_rect", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x0000000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64)), (f64::from_bits(0x4024000000000000_u64), f64::from_bits(0x0000000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x40263c6ef372fe95_u64,
            tags: &["multi_pad", "named:two_pads_second_further", "shape_rect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x4024000000000000_u64), f64::from_bits(0x0000000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64)), (f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x0000000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x40263c6ef372fe95_u64,
            tags: &["multi_pad", "named:two_pads_first_further", "shape_rect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC008000000000000_u64), f64::from_bits(0xC010000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x401878dde6e5fd2a_u64,
            tags: &["named:negative_offsets", "negative_offset", "shape_rect", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 0i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x4003504f333f9de6_u64,
            tags: &["named:circle_shape", "shape_circle", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 1i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x4003504f333f9de6_u64,
            tags: &["named:oval_shape", "shape_oval", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 3i64, f64::from_bits(0x3FD999999999999A_u64))],
            expected_bits: 0x400361425720638c_u64,
            tags: &["named:roundrect_shape", "shape_roundrect", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 4i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x4003504f333f9de6_u64,
            tags: &["named:thru_hole_shape", "shape_thru_hole", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 99i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x4004420b010b983a_u64,
            tags: &["named:unknown_shape_falls_back", "shape_unknown", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x4000000000000000_u64), f64::from_bits(0x0000000000000000_u64), f64::from_bits(0x0000000000000000_u64), f64::from_bits(0x0000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x4000000000000000_u64,
            tags: &["named:zero_size_pad", "shape_rect", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x4008000000000000_u64), f64::from_bits(0x4010000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64)), (f64::from_bits(0x4010000000000000_u64), f64::from_bits(0x4008000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x401878dde6e5fd2a_u64,
            tags: &["multi_pad", "named:tie_between_pads", "near_tie", "shape_rect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x0000000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64)), (f64::from_bits(0x4024000000000000_u64), f64::from_bits(0x0000000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x7ff8000000000000_u64,
            tags: &["multi_pad", "named:nan_offset_kept_not_discarded", "nan_present", "shape_rect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x4024000000000000_u64), f64::from_bits(0x0000000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64)), (f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x0000000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x40263c6ef372fe95_u64,
            tags: &["multi_pad", "named:nan_second_does_not_displace_finite_max", "nan_present", "shape_rect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x7FF0000000000000_u64), f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x3FF0000000000000_u64), f64::from_bits(0x4000000000000000_u64), 2i64, f64::from_bits(0x3FD0000000000000_u64))],
            expected_bits: 0x7ff0000000000000_u64,
            tags: &["inf_present", "named:infinity_beats_nan", "nan_present", "shape_rect", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0xC03C8EB86680A32E_u64), f64::from_bits(0x3FFC385109A68C4A_u64), f64::from_bits(0x40053D2808E18F16_u64), 99i64, f64::from_bits(0x3F8C8C8C85FB77E0_u64)), (f64::from_bits(0x40361AD966243B74_u64), f64::from_bits(0x403AC8FD0CD912E8_u64), f64::from_bits(0x3FD4F045C5E0E9F7_u64), f64::from_bits(0x4012A8A8A4E1AF54_u64), 0i64, f64::from_bits(0x3FDDCDCA2DFD118F_u64))],
            expected_bits: 0x7ff8000000000000_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_circle", "shape_unknown"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x404160E3ED59055C_u64), f64::from_bits(0x4038C43B96A5CAD8_u64), f64::from_bits(0x4006BF3A20A76ED9_u64), f64::from_bits(0x40095092162909AA_u64), 3i64, f64::from_bits(0x3FDC36994FB30857_u64)), (f64::from_bits(0x4035BE2D89DF3B6C_u64), f64::from_bits(0xC04622289BE255D2_u64), f64::from_bits(0x400AB06ED6162E51_u64), f64::from_bits(0x4004BACCFC7B1F48_u64), 0i64, f64::from_bits(0x3FC970374896957E_u64)), (f64::from_bits(0x401BED02CBC8F940_u64), f64::from_bits(0xC024C648CB223B60_u64), f64::from_bits(0x3FE278ACA286FDA6_u64), f64::from_bits(0x40057EA5A4A6D961_u64), 0i64, f64::from_bits(0x3FC94ADA98FA781C_u64))],
            expected_bits: 0x40497e4600131446_u64,
            tags: &["multi_pad", "negative_offset", "shape_circle", "shape_roundrect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0xC045F0A006E6E02E_u64), f64::from_bits(0x3FF1B3EA56A6AF95_u64), f64::from_bits(0x3FF7C429311E50E2_u64), 0i64, f64::from_bits(0x3FD80D778A958B17_u64)), (f64::from_bits(0x40459ADE2C37D8B2_u64), f64::from_bits(0xC0443008944C8FC7_u64), f64::from_bits(0x3FF70F4572CA23AE_u64), f64::from_bits(0x3FD1912DC2F1C063_u64), 1i64, f64::from_bits(0x3FCB488AB01D8F0E_u64)), (f64::from_bits(0x3FFEEF38D30CD500_u64), f64::from_bits(0xC048D195BD397E6F_u64), f64::from_bits(0x400590B888B9F5D5_u64), f64::from_bits(0x4011666D6B68D9DF_u64), 3i64, f64::from_bits(0x3FDA9FA6CCF4B327_u64))],
            expected_bits: 0x7ff8000000000000_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_circle", "shape_oval", "shape_roundrect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x40214C39027C839C_u64), f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x40087F268059256B_u64), f64::from_bits(0x3FF21578A6014D34_u64), 4i64, f64::from_bits(0x3FCF88CF91783EE4_u64)), (f64::from_bits(0x40382FBCEFB72E90_u64), f64::from_bits(0xC0450D2131A8A2AF_u64), f64::from_bits(0x40027623DA7E7BD0_u64), f64::from_bits(0x401268A54D5FB28F_u64), 2i64, f64::from_bits(0x3FCDD29CCF66DD56_u64)), (f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0xC045FB34B6442BC5_u64), f64::from_bits(0x3FB131FA40D6C89A_u64), f64::from_bits(0x3FF6F28EACED75B7_u64), 99i64, f64::from_bits(0x3FC66DFA7744A318_u64))],
            expected_bits: 0x7ff8000000000000_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_rect", "shape_thru_hole", "shape_unknown"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC038A5868129A00E_u64), f64::from_bits(0xC00AB2C04D45BBB0_u64), f64::from_bits(0x40063B68054C0E61_u64), f64::from_bits(0x4004F469A4728DB0_u64), 0i64, f64::from_bits(0x3FAF87CF86A58FA8_u64)), (f64::from_bits(0xC02E4CD19C3BE3F8_u64), f64::from_bits(0xC0424380F305B7CA_u64), f64::from_bits(0x4005BD0928BCFB3C_u64), f64::from_bits(0x400512E7CB679712_u64), 0i64, f64::from_bits(0x3FCF927665425A6A_u64))],
            expected_bits: 0x4044739c9229196e_u64,
            tags: &["multi_pad", "negative_offset", "shape_circle"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC010E9D9FF61A8F8_u64), f64::from_bits(0xC030B3C8EEB3BE82_u64), f64::from_bits(0x3FF793599026C3D4_u64), f64::from_bits(0x3FF6A65D963C82E2_u64), 3i64, f64::from_bits(0x3FDF131858350FFF_u64)), (f64::from_bits(0xC0039EBCAEA27200_u64), f64::from_bits(0x40041F10B535DA60_u64), f64::from_bits(0x3FD91F5BBD179B4A_u64), f64::from_bits(0x3FF1DBB0E0BE3E02_u64), 1i64, f64::from_bits(0x3FD2CCCDCD5A4F08_u64)), (f64::from_bits(0xC02732C175B0A70C_u64), f64::from_bits(0x7FF0000000000000_u64), f64::from_bits(0x3FD9DFD429D08F4D_u64), f64::from_bits(0x400F21A943D0721C_u64), 3i64, f64::from_bits(0x3FD38FF1108985FE_u64))],
            expected_bits: 0x7ff0000000000000_u64,
            tags: &["inf_present", "multi_pad", "negative_offset", "shape_oval", "shape_roundrect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC0447AF9FF95AA9A_u64), f64::from_bits(0xBFE0C890F980DC00_u64), f64::from_bits(0x4010FB5C02FD66C5_u64), f64::from_bits(0x4007A761AE803A6D_u64), 99i64, f64::from_bits(0x3FD49BAF311B9E27_u64))],
            expected_bits: 0x4045c684769de55a_u64,
            tags: &["negative_offset", "shape_unknown", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC047596A440019CE_u64), f64::from_bits(0xC0296ADDB447DFD4_u64), f64::from_bits(0x400F57F8F6772CCD_u64), f64::from_bits(0x400FCD6AF21C68F0_u64), 3i64, f64::from_bits(0x3FC38BA6E7127E02_u64)), (f64::from_bits(0x4027649286A7D670_u64), f64::from_bits(0xC00813E5742FE080_u64), f64::from_bits(0x4011695A489F967A_u64), f64::from_bits(0x400BD9D5D8472E6D_u64), 4i64, f64::from_bits(0x3FD747D136F9BC1D_u64))],
            expected_bits: 0x404978505bdafc25_u64,
            tags: &["multi_pad", "negative_offset", "shape_roundrect", "shape_thru_hole"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x4040B191D57EC19C_u64), f64::from_bits(0x403485BC3BC334A4_u64), f64::from_bits(0x3FF0BEBF4451AA48_u64), f64::from_bits(0x3FF06395ED895B4B_u64), 2i64, f64::from_bits(0x3FD08BAEE4D7670B_u64))],
            expected_bits: 0x4043f614472190d8_u64,
            tags: &["shape_rect", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC02295A3AA87071C_u64), f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x40030CD4211937D2_u64), f64::from_bits(0x3FAFD42C0C72D073_u64), 1i64, f64::from_bits(0x3FBBC0AAE8ED8DA0_u64)), (f64::from_bits(0xC030EA8D3A23380E_u64), f64::from_bits(0xC0414AA10EC12EB5_u64), f64::from_bits(0x40057500F5300D29_u64), f64::from_bits(0x4004FC42563F7518_u64), 1i64, f64::from_bits(0x3FD425C072F14467_u64)), (f64::from_bits(0xBFF4239C5FA36E60_u64), f64::from_bits(0xC04119D06DFF4B17_u64), f64::from_bits(0x3FFFB77F413D473A_u64), f64::from_bits(0x400010897A53603E_u64), 4i64, f64::from_bits(0x3FC3ED1BCA6F5EC6_u64)), (f64::from_bits(0x403FE21A7530A8E0_u64), f64::from_bits(0x4037C4C7E6D02104_u64), f64::from_bits(0x400C891E7B1BF995_u64), f64::from_bits(0x4000D3941C60D266_u64), 1i64, f64::from_bits(0x3FD584088FBFF2A2_u64))],
            expected_bits: 0x7ff8000000000000_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_oval", "shape_thru_hole"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x402BFC3001CD2494_u64), f64::from_bits(0x404620AE7B5E7AF2_u64), f64::from_bits(0x400C5435834A260D_u64), f64::from_bits(0x40126CE5AF66EDBF_u64), 2i64, f64::from_bits(0x3FD8E092D1B88D52_u64)), (f64::from_bits(0xC0337B5A1B796FB6_u64), f64::from_bits(0x40486E2E9B8BAD92_u64), f64::from_bits(0x3FF459ED707AF340_u64), f64::from_bits(0x4006F5F4544093EE_u64), 3i64, f64::from_bits(0x3FDD52F0A26B93C5_u64)), (f64::from_bits(0xC03C95FE6341BA48_u64), f64::from_bits(0x40476B9943B6F144_u64), f64::from_bits(0x3FEE97C74189B9B2_u64), f64::from_bits(0x4001AC9EE7E21EB8_u64), 3i64, f64::from_bits(0x3FDB0A34412C5674_u64))],
            expected_bits: 0x404bfdd0aa1ac18f_u64,
            tags: &["multi_pad", "negative_offset", "shape_rect", "shape_roundrect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0xC02C822A39891A90_u64), f64::from_bits(0x4010D22C6D762C96_u64), f64::from_bits(0x3FD91F205EA9477F_u64), 0i64, f64::from_bits(0x3FC0CAFB122002E6_u64)), (f64::from_bits(0x4045D3F099EF5CA4_u64), f64::from_bits(0xC04439FE16F60D58_u64), f64::from_bits(0x4006CD17FAA8D8DC_u64), f64::from_bits(0x4004C2AE37A45754_u64), 3i64, f64::from_bits(0x3FD735FBEFAD4800_u64))],
            expected_bits: 0x7ff8000000000000_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_circle", "shape_roundrect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x40414870742984A8_u64), f64::from_bits(0x4036DB504D1DABAC_u64), f64::from_bits(0x3FE3B266D2D11C76_u64), f64::from_bits(0x3FD7D13F16A55D14_u64), 1i64, f64::from_bits(0x3FCAB695BD7C1688_u64)), (f64::from_bits(0x400D12351417E2C0_u64), f64::from_bits(0xC0407BE4E266FCCE_u64), f64::from_bits(0x400A3C5C12DE56A6_u64), f64::from_bits(0x3FEA1DB01E29B0F5_u64), 3i64, f64::from_bits(0x3FD73551A77B6D46_u64))],
            expected_bits: 0x4044dfa6514ac843_u64,
            tags: &["multi_pad", "negative_offset", "shape_oval", "shape_roundrect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC0402E257068589C_u64), f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x3FDFB5BA8838E439_u64), f64::from_bits(0x3FF99C347F609382_u64), 3i64, f64::from_bits(0x3FDD61BBEC291527_u64)), (f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0xC041A7517FD842F0_u64), f64::from_bits(0x40112CAB20DB8CA3_u64), f64::from_bits(0x4011EC8B96306F34_u64), 99i64, f64::from_bits(0x3FD1B00CB345FB85_u64))],
            expected_bits: 0x7ff8000000000000_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_roundrect", "shape_unknown"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x402178636C32EF38_u64), f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x40086AFE706B1BD3_u64), f64::from_bits(0x3FF6287BA60EE3F3_u64), 99i64, f64::from_bits(0x3FBDAD6ED69B9E90_u64)), (f64::from_bits(0xC043E8546588375F_u64), f64::from_bits(0xC03E3CCA47ADA3AA_u64), f64::from_bits(0x400FC57A168E168F_u64), f64::from_bits(0x3FD1A06440EEB71F_u64), 2i64, f64::from_bits(0x3FD490F45F667426_u64))],
            expected_bits: 0x7ff8000000000000_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_rect", "shape_unknown"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x403C330685383CE0_u64), f64::from_bits(0x403295737BDB4FA8_u64), f64::from_bits(0x4008B393A0CE8061_u64), f64::from_bits(0x3FD34AF7BAA1C758_u64), 2i64, f64::from_bits(0x3FD085902CDA2708_u64)), (f64::from_bits(0xC047C960D7C271BC_u64), f64::from_bits(0x4014C9E0E73FD9E0_u64), f64::from_bits(0x3FF17BE857CF7BC2_u64), f64::from_bits(0x3FD8E86CF75A3041_u64), 2i64, f64::from_bits(0x3FDF36B29DA9919D_u64)), (f64::from_bits(0x4036AA50E7695984_u64), f64::from_bits(0x401BF780F3D21B60_u64), f64::from_bits(0x4013C5CCE3B93909_u64), f64::from_bits(0x400423B0A2A3E1CA_u64), 1i64, f64::from_bits(0x3FA2A6BBA30AFC98_u64)), (f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x404340536029E144_u64), f64::from_bits(0x3FF2B9D6DABD64CE_u64), f64::from_bits(0x3FFCB021DD14B09B_u64), 4i64, f64::from_bits(0x3FD9AE7082B8A85C_u64))],
            expected_bits: 0x404837d8b5f62b65_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_oval", "shape_rect", "shape_thru_hole"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC02DB34B587BA4F4_u64), f64::from_bits(0x4042F96B58DAB0DA_u64), f64::from_bits(0x400459D5B8573D9D_u64), f64::from_bits(0x3FCD384B9A43592A_u64), 3i64, f64::from_bits(0x3FD9334FB0C839B8_u64)), (f64::from_bits(0x4015874EF644E7D0_u64), f64::from_bits(0x4040E16F490615CC_u64), f64::from_bits(0x3FDD0A9899E23BA7_u64), f64::from_bits(0x3FFC724D2AA159B1_u64), 2i64, f64::from_bits(0x3FD9B07D658978A7_u64)), (f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0xC038810A3F86A637_u64), f64::from_bits(0x3FDE9150C33765C2_u64), f64::from_bits(0x400BCF7FBA2E6709_u64), 4i64, f64::from_bits(0x3FDB1EAB554BB882_u64))],
            expected_bits: 0x404502ef4aa534ed_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_rect", "shape_roundrect", "shape_thru_hole"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x402B23CC77A65694_u64), f64::from_bits(0x403B95FA61AC6FDC_u64), f64::from_bits(0x4013FDE06F534430_u64), f64::from_bits(0x4012E3B847964C7D_u64), 3i64, f64::from_bits(0x3FB9100EA8C319B0_u64)), (f64::from_bits(0xC0366EACE1FA0723_u64), f64::from_bits(0xC040A33854E78BC8_u64), f64::from_bits(0x3FD172848F2D687D_u64), f64::from_bits(0x400FDD1ABFCF887D_u64), 0i64, f64::from_bits(0x3FD4FEDD4D410CBB_u64)), (f64::from_bits(0x40413B401B34C7DA_u64), f64::from_bits(0xC04157CB33C5B4DC_u64), f64::from_bits(0x400749184BCA3390_u64), f64::from_bits(0x3FDE6DF1B566F88F_u64), 0i64, f64::from_bits(0x3FC50966320F816E_u64))],
            expected_bits: 0x40492cf33ac6cb76_u64,
            tags: &["multi_pad", "negative_offset", "shape_circle", "shape_roundrect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x4039C5A406C7FDC8_u64), f64::from_bits(0xC038BD0C72B5EA25_u64), f64::from_bits(0x401158FC779FDAAC_u64), f64::from_bits(0x3FFFD0A64D607DAE_u64), 99i64, f64::from_bits(0x3F66E082EE862B00_u64)), (f64::from_bits(0x40479BA746FD43C4_u64), f64::from_bits(0xC02CB25285B29634_u64), f64::from_bits(0x3FE4F825BADE3493_u64), f64::from_bits(0x400AC65E0E2C9333_u64), 1i64, f64::from_bits(0x3FD0D4D98DA0D17C_u64)), (f64::from_bits(0xFFF0000000000000_u64), f64::from_bits(0x404335A8F148CB76_u64), f64::from_bits(0x400816418CFC1A1D_u64), f64::from_bits(0x40119243E37685FE_u64), 4i64, f64::from_bits(0x3FC8FDD1586B0AC2_u64))],
            expected_bits: 0x7ff0000000000000_u64,
            tags: &["inf_present", "multi_pad", "negative_offset", "shape_oval", "shape_thru_hole", "shape_unknown"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC045C7F3C8594581_u64), f64::from_bits(0xBFF69E8FBCBEDC80_u64), f64::from_bits(0x40011B3BA959C840_u64), f64::from_bits(0x4010820AB60CE28A_u64), 0i64, f64::from_bits(0x3FD1025AC70D6554_u64)), (f64::from_bits(0x403CE2A02C5D872C_u64), f64::from_bits(0xC047DF6EB8189C95_u64), f64::from_bits(0x4013D1344A102308_u64), f64::from_bits(0x3FEF78DB04AAD6A5_u64), 4i64, f64::from_bits(0x3F779998DBDD3700_u64)), (f64::from_bits(0xC048E33E1C540436_u64), f64::from_bits(0xC039A20179E1B669_u64), f64::from_bits(0x3FEFE5176FC1864B_u64), f64::from_bits(0x400594D446F53C8C_u64), 2i64, f64::from_bits(0x3FBD0E47D1F6A53C_u64)), (f64::from_bits(0xC02A7602CF353B80_u64), f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x4006969F73C48866_u64), f64::from_bits(0x4006A46B6766EA1D_u64), 99i64, f64::from_bits(0x3FDC7068B92EC1DE_u64))],
            expected_bits: 0x404d23e2886d99a4_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_circle", "shape_rect", "shape_thru_hole", "shape_unknown"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC04534BEEC496D3C_u64), f64::from_bits(0x4047CEE5E9CEF3DC_u64), f64::from_bits(0x3FFBDA8CB5788C9F_u64), f64::from_bits(0x400ABCB00026E853_u64), 0i64, f64::from_bits(0x3FA985F270DE2878_u64))],
            expected_bits: 0x40505bf92d76b48c_u64,
            tags: &["negative_offset", "shape_circle", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x4019E6E742E90C00_u64), f64::from_bits(0x402434AEA997130C_u64), f64::from_bits(0x40116C1B4270F1FC_u64), f64::from_bits(0x4010ED11FD435348_u64), 2i64, f64::from_bits(0x3FCBCA02DC84C9F6_u64)), (f64::from_bits(0x40476D257D5EFB54_u64), f64::from_bits(0x402DCB2F58DCA748_u64), f64::from_bits(0x3FDE2EBD6AAD4CEE_u64), f64::from_bits(0x400AF6BF4761235A_u64), 0i64, f64::from_bits(0x3FD6F17259F26024_u64))],
            expected_bits: 0x40496cb1ac3bce27_u64,
            tags: &["multi_pad", "shape_circle", "shape_rect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x40189E87034029A8_u64), f64::from_bits(0x402801CF3F71E940_u64), f64::from_bits(0x400DF6311E80459E_u64), f64::from_bits(0x3FCE85C0544424D8_u64), 0i64, f64::from_bits(0x3FD6551233A7EBBE_u64))],
            expected_bits: 0x402eb96591859c99_u64,
            tags: &["shape_circle", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC03C44945609DF3B_u64), f64::from_bits(0x404899DCFC1F8658_u64), f64::from_bits(0x3FD28D39714A96E3_u64), f64::from_bits(0x4000CA940AA4690D_u64), 4i64, f64::from_bits(0x3FD5852A8DE96C5D_u64)), (f64::from_bits(0xC02B2EB273A01B0C_u64), f64::from_bits(0xC0444E1084F24DDC_u64), f64::from_bits(0x3FDD4137551D3714_u64), f64::from_bits(0x401346DB548AEC9D_u64), 2i64, f64::from_bits(0x3FCCA0E6DDD8A73E_u64)), (f64::from_bits(0x403681E0F92F7D14_u64), f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x40080CF15F92E5D7_u64), f64::from_bits(0x3FF1257C87EB291E_u64), 0i64, f64::from_bits(0x3FD62A9D4E431F38_u64)), (f64::from_bits(0xC04146B38CCFCFAE_u64), f64::from_bits(0x403DFB45F397457C_u64), f64::from_bits(0x3FB856676566FDB2_u64), f64::from_bits(0x3FD809627FC3FE6A_u64), 2i64, f64::from_bits(0x3FB23FAC4857EBCC_u64))],
            expected_bits: 0x404ce599eeb32580_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_circle", "shape_rect", "shape_thru_hole"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC0437987C61D68BA_u64), f64::from_bits(0xC011D8C2F79A1AB8_u64), f64::from_bits(0x40089D2F8FA71DBB_u64), f64::from_bits(0x3FFC511FAB45B27A_u64), 3i64, f64::from_bits(0x3FD850E831EE015E_u64)), (f64::from_bits(0x4011970ABE50FD80_u64), f64::from_bits(0xC037947BC8B0C118_u64), f64::from_bits(0x400AA248D7A9BF83_u64), f64::from_bits(0x400265770E2A814C_u64), 3i64, f64::from_bits(0x3FBD43B36DC5C70C_u64)), (f64::from_bits(0xC02DE018CBCC2B94_u64), f64::from_bits(0x40452F635D77F6E4_u64), f64::from_bits(0x3FF811C1F6EFEECB_u64), f64::from_bits(0x3FDDC2906B9C6779_u64), 4i64, f64::from_bits(0x3FD77FFFAC881275_u64)), (f64::from_bits(0x40370AC553D223D0_u64), f64::from_bits(0x40424A8170E3395C_u64), f64::from_bits(0x40069CAD26B1CFF6_u64), f64::from_bits(0x400CEE062FAE22E9_u64), 1i64, f64::from_bits(0x3FD5E2215E27EFCC_u64))],
            expected_bits: 0x4046d6d72cea057e_u64,
            tags: &["multi_pad", "negative_offset", "shape_oval", "shape_roundrect", "shape_thru_hole"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC02A6CE38FF24E54_u64), f64::from_bits(0xC03F51F4B0C02318_u64), f64::from_bits(0x3FF466FA38B06DF9_u64), f64::from_bits(0x40015FFE4C0DED58_u64), 4i64, f64::from_bits(0x3FDE970B280BA5C7_u64)), (f64::from_bits(0x404410D308C7AA18_u64), f64::from_bits(0x4043DB2FD79F9192_u64), f64::from_bits(0x3FDA5D0320F76BBA_u64), f64::from_bits(0x3FFE40F92F34BA54_u64), 4i64, f64::from_bits(0x3FCDD0E383016D8A_u64)), (f64::from_bits(0xFFF0000000000000_u64), f64::from_bits(0x404527910A96193C_u64), f64::from_bits(0x40061AA92D5665E2_u64), f64::from_bits(0x400DCB1DF10B84ED_u64), 2i64, f64::from_bits(0x3FDF62873E87CA5F_u64))],
            expected_bits: 0x7ff0000000000000_u64,
            tags: &["inf_present", "multi_pad", "negative_offset", "shape_rect", "shape_thru_hole"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x4041DC3582E1BD3C_u64), f64::from_bits(0xC041741073934F01_u64), f64::from_bits(0x40038A2E14FF5957_u64), f64::from_bits(0x3FFD211BA9ADD05D_u64), 2i64, f64::from_bits(0x3FC59083DEC2B760_u64)), (f64::from_bits(0xC047ED40867D55AC_u64), f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x400C4C836B8CE0EE_u64), f64::from_bits(0x400A6339E81E0100_u64), 99i64, f64::from_bits(0x3FC3817F4319CF10_u64))],
            expected_bits: 0x4049bbd4159bc425_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_rect", "shape_unknown"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC04301A8149BC25E_u64), f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x4004A76B405896B7_u64), f64::from_bits(0x401197EFD5A2A561_u64), 99i64, f64::from_bits(0x3FCB6CABA0D72F28_u64))],
            expected_bits: 0x7ff8000000000000_u64,
            tags: &["nan_present", "negative_offset", "shape_unknown", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC02AE9BB72A9CCDC_u64), f64::from_bits(0xC03753B9F5804F97_u64), f64::from_bits(0x4002FD3F619430C7_u64), f64::from_bits(0x4003AF5A8907D67E_u64), 1i64, f64::from_bits(0x3FA373D0246A0AA0_u64)), (f64::from_bits(0xFFF0000000000000_u64), f64::from_bits(0x4035906D738561A4_u64), f64::from_bits(0x4011A227752ADA4A_u64), f64::from_bits(0x3FF73FE84CE86183_u64), 1i64, f64::from_bits(0x3FBDF6B16B73B64C_u64)), (f64::from_bits(0x4047B509E69396D6_u64), f64::from_bits(0xC03264F4B038B257_u64), f64::from_bits(0x40078AD92A328595_u64), f64::from_bits(0x4007A1DB58C38D10_u64), 1i64, f64::from_bits(0x3FCFAAE8E89E62FE_u64))],
            expected_bits: 0x7ff0000000000000_u64,
            tags: &["inf_present", "multi_pad", "negative_offset", "shape_oval"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x40345B81C7DDCA3C_u64), f64::from_bits(0xC0417ACFD3D0B1FC_u64), f64::from_bits(0x3FFE3D3962BCA55B_u64), f64::from_bits(0x40128D345B6353A2_u64), 0i64, f64::from_bits(0x3FD845B79E5485BD_u64))],
            expected_bits: 0x40456309dabe77d1_u64,
            tags: &["negative_offset", "shape_circle", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x403098C3C20EB4FC_u64), f64::from_bits(0x401225EF47BB6488_u64), f64::from_bits(0x40135E026AA443DA_u64), 4i64, f64::from_bits(0x3FDBD504D0DF1D6E_u64)), (f64::from_bits(0x40253D9277AF21F4_u64), f64::from_bits(0xC0341B75AA57B1F4_u64), f64::from_bits(0x400E66EA7AE9487E_u64), f64::from_bits(0x3FF23280631C1D4F_u64), 99i64, f64::from_bits(0x3FB06EC585BBC3B8_u64)), (f64::from_bits(0xC036B45C64DF2A20_u64), f64::from_bits(0x40460FB0EDA60C04_u64), f64::from_bits(0x401261817F640978_u64), f64::from_bits(0x401028780F28355E_u64), 1i64, f64::from_bits(0x3FDDFB5F99E95F10_u64)), (f64::from_bits(0x404249C56FEF5DB2_u64), f64::from_bits(0x40455BA903C85B60_u64), f64::from_bits(0x4011814824838989_u64), f64::from_bits(0x4010AD3BB796CFC3_u64), 4i64, f64::from_bits(0x3F6B97DAF8A59E00_u64))],
            expected_bits: 0x7ff8000000000000_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_oval", "shape_thru_hole", "shape_unknown"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC0427385BC6F648E_u64), f64::from_bits(0x4042ED9B54A0244C_u64), f64::from_bits(0x4011DA1E582655C0_u64), f64::from_bits(0x400AC9CA3EA2C0A4_u64), 99i64, f64::from_bits(0x3FCEDE7F0469C164_u64)), (f64::from_bits(0x403DB5DCB6148844_u64), f64::from_bits(0xC023AEB1C6B7EB70_u64), f64::from_bits(0x4003F846F7B175CC_u64), f64::from_bits(0x3FD0EF9E47425BA7_u64), 3i64, f64::from_bits(0x3FD447BEC831A855_u64)), (f64::from_bits(0xC03F0CC06435FB64_u64), f64::from_bits(0x40459F4BE486838E_u64), f64::from_bits(0x3FE9A9E040ED721D_u64), f64::from_bits(0x3FF55334D1B4AF66_u64), 0i64, f64::from_bits(0x3FBABA8BC9911C10_u64)), (f64::from_bits(0xC034E1F671296BF7_u64), f64::from_bits(0x40431F9AB062BC46_u64), f64::from_bits(0x4012E73715610521_u64), f64::from_bits(0x401374B3F415779C_u64), 0i64, f64::from_bits(0x3FD8FB8A37AF9F0A_u64))],
            expected_bits: 0x404bd40949b5702f_u64,
            tags: &["multi_pad", "negative_offset", "shape_circle", "shape_roundrect", "shape_unknown"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x403168C17A6A4098_u64), f64::from_bits(0x3FD8AE96BF9F525C_u64), f64::from_bits(0x400442648C20F922_u64), 99i64, f64::from_bits(0x3FDC6D9CA76F2744_u64)), (f64::from_bits(0x4037CF3B3E87B998_u64), f64::from_bits(0xC0477FA632DCB300_u64), f64::from_bits(0x3FFDBD866D31AA4C_u64), f64::from_bits(0x400453217A3CAE71_u64), 4i64, f64::from_bits(0x3FDB60C00C6B56B2_u64))],
            expected_bits: 0x7ff8000000000000_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_thru_hole", "shape_unknown"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x4043E5009CB7D57A_u64), f64::from_bits(0x403FB6714632F3D0_u64), f64::from_bits(0x3FFC3D63666EFF0A_u64), f64::from_bits(0x4012B2857FBE42FA_u64), 99i64, f64::from_bits(0x3F91559338BB72D0_u64)), (f64::from_bits(0xC0404A7B6610429D_u64), f64::from_bits(0x4035E3E1A7690B60_u64), f64::from_bits(0x40095E539CF4B9AD_u64), f64::from_bits(0x3FF1773BA2B88BE2_u64), 3i64, f64::from_bits(0x3FD183B4A1A96F32_u64)), (f64::from_bits(0x4041D3F75F8520A0_u64), f64::from_bits(0x404416CEF81628D0_u64), f64::from_bits(0x3FF418CC4AA6B338_u64), f64::from_bits(0x400A6C583349BA7D_u64), 99i64, f64::from_bits(0x3FD30C6CC11C6CC7_u64))],
            expected_bits: 0x404bbe130b667468_u64,
            tags: &["multi_pad", "negative_offset", "shape_roundrect", "shape_unknown"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x40433F48EC157936_u64), f64::from_bits(0x40436BF2B898B250_u64), f64::from_bits(0x4007D0FA5F8480CF_u64), f64::from_bits(0x3FD1DCC3C57C96CA_u64), 0i64, f64::from_bits(0x3FA0B2B1E7D474E0_u64)), (f64::from_bits(0x403D1077B6CEF1A0_u64), f64::from_bits(0xC0406D3BE8670496_u64), f64::from_bits(0x400602871597331E_u64), f64::from_bits(0x3FFB877D07B1910D_u64), 2i64, f64::from_bits(0x3FD2EF57D349B87D_u64))],
            expected_bits: 0x404c166aa4d4a66b_u64,
            tags: &["multi_pad", "negative_offset", "shape_circle", "shape_rect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC0202443740B1528_u64), f64::from_bits(0x4029333F26D86D60_u64), f64::from_bits(0x400738FE13FE5CE6_u64), f64::from_bits(0x400DC6A2510DC1BA_u64), 4i64, f64::from_bits(0x3FDF1D8E4A068F87_u64))],
            expected_bits: 0x4030d3056a330d1e_u64,
            tags: &["negative_offset", "shape_thru_hole", "single_pad"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x4043B3F37A4DC888_u64), f64::from_bits(0x7FF8000000000000_u64), f64::from_bits(0x40046FD18D6B6099_u64), f64::from_bits(0x4010A82FC84515C9_u64), 0i64, f64::from_bits(0x3FCDAEDD9761F9A2_u64)), (f64::from_bits(0xC0448E78B7537DBA_u64), f64::from_bits(0x4023183DC50B0230_u64), f64::from_bits(0x400780EB1578223E_u64), f64::from_bits(0x40057711CBA462DD_u64), 3i64, f64::from_bits(0x3F9BABEBF1F004E0_u64)), (f64::from_bits(0xC0452520B24ABAD1_u64), f64::from_bits(0x4034D93E4EA4E404_u64), f64::from_bits(0x3FDA069B9981358F_u64), f64::from_bits(0x3FF6ACF8C5661DF8_u64), 1i64, f64::from_bits(0x3FC572F64866303C_u64))],
            expected_bits: 0x7ff8000000000000_u64,
            tags: &["multi_pad", "nan_present", "negative_offset", "shape_circle", "shape_oval", "shape_roundrect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0xC025E438BAD980C4_u64), f64::from_bits(0x403A168913CEDE48_u64), f64::from_bits(0x400BC74D5952C92B_u64), f64::from_bits(0x3FEEB7411C7268A4_u64), 3i64, f64::from_bits(0x3F9CF3309F5FA140_u64)), (f64::from_bits(0xC03BC7616175E340_u64), f64::from_bits(0x404419A615E39F96_u64), f64::from_bits(0x4000AE4C0A59312D_u64), f64::from_bits(0x4008B3E68CD4E2B4_u64), 1i64, f64::from_bits(0x3FB900236DC41C24_u64))],
            expected_bits: 0x4049344558f519bb_u64,
            tags: &["multi_pad", "negative_offset", "shape_oval", "shape_roundrect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x7FF0000000000000_u64), f64::from_bits(0xC03CC9BF6D1E0EFA_u64), f64::from_bits(0x40030BBFFFF9BE5D_u64), f64::from_bits(0x4012A0A5FF44A469_u64), 0i64, f64::from_bits(0x3FA8726251605530_u64)), (f64::from_bits(0xC03B5901F4835759_u64), f64::from_bits(0xC04597D09C517284_u64), f64::from_bits(0x40037403764C417E_u64), f64::from_bits(0x400A474D359B6C52_u64), 1i64, f64::from_bits(0x3FD36C981F75FEB7_u64)), (f64::from_bits(0xC03C3FA543F2CA7C_u64), f64::from_bits(0x403DD2AE5DFB699C_u64), f64::from_bits(0x3FCAACCE6619DE10_u64), f64::from_bits(0x400C85E39BAE42B0_u64), 3i64, f64::from_bits(0x3FD6ECF2285D7B2D_u64))],
            expected_bits: 0x7ff0000000000000_u64,
            tags: &["inf_present", "multi_pad", "negative_offset", "shape_circle", "shape_oval", "shape_roundrect"],
        },
        FrozenCopperReachCase {
            pads: &[(f64::from_bits(0x4048A23851B9F2B2_u64), f64::from_bits(0x4028513B4A655D08_u64), f64::from_bits(0x3FAFB66EF99D3C07_u64), f64::from_bits(0x4002404791F09EBC_u64), 1i64, f64::from_bits(0x3FDCC47C75F9AFA2_u64)), (f64::from_bits(0x40487115909A8550_u64), f64::from_bits(0x403A59BD12B15F30_u64), f64::from_bits(0x40053CC0056EDE12_u64), f64::from_bits(0x3FFFCE4BE01BAE0B_u64), 4i64, f64::from_bits(0x3FDA2E32696A4567_u64))],
            expected_bits: 0x404c6e28620a7335_u64,
            tags: &["multi_pad", "shape_oval", "shape_thru_hole"],
        },
    ];

    #[cfg_attr(test, test)]
    fn frozen_copper_reach_matches_golden_corpus() {
        for case in FROZEN_COPPER_REACH_GOLDEN {
            let got = copper_reach_mm(case.pads);
            let want = f64::from_bits(case.expected_bits);
            let ok = (got.is_nan() && want.is_nan()) || got.to_bits() == want.to_bits();
            assert!(ok, "tags={:?}: got {:?} want {:?}", case.tags, got, want);
        }
    }

    /// Q2 non-vacuity guard: fails closed if the frozen corpus above were
    /// ever hand-edited down to something trivially satisfiable. Mirrors the
    /// coverage-guard convention in creepage_check.rs / via_clearance.rs (PR
    /// #1007) and property_campaigns.rs's IPC-2221 bracket guard.
    #[cfg_attr(test, test)]
    fn frozen_copper_reach_corpus_is_non_vacuous() {
        let n = FROZEN_COPPER_REACH_GOLDEN.len() as u32;
        let count = |tag: &str| FROZEN_COPPER_REACH_GOLDEN.iter().filter(|c| c.tags.contains(&tag)).count() as u32;
        assert!(count("nan_present") * 100 >= n * 10, "nan_present: only {}/{} (need >= 10%) -- the NaN-is-kept-not-discarded contract is the entire point of this suite", count("nan_present"), n);
        assert!(count("inf_present") >= 1, "inf_present: only {}/{} (need >= 1) -- infinity-beats-nan via py_hypot must be exercised at least once", count("inf_present"), n);
        assert!(count("multi_pad") * 100 >= n * 40, "multi_pad: only {}/{} (need >= 40%) -- max()-over-pads reduction only exercised with >=2 pads", count("multi_pad"), n);
        assert!(count("negative_offset") * 100 >= n * 15, "negative_offset: only {}/{} (need >= 15%) -- offsets must not be exclusively non-negative", count("negative_offset"), n);
        assert!(count("near_tie") >= 1, "near_tie: only {}/{} (need >= 1) -- tie-break direction (first pad wins ties, strict `>`) must be exercised", count("near_tie"), n);
        assert!(count("empty") >= 1, "empty: only {}/{} (need >= 1) -- the `if not pads: return 0.0` branch must be exercised", count("empty"), n);
        assert!(count("shape_circle") >= 1, "shape_circle: only {}/{} (need >= 1) -- pad shape code coverage: shape_circle must appear at least once", count("shape_circle"), n);
        assert!(count("shape_oval") >= 1, "shape_oval: only {}/{} (need >= 1) -- pad shape code coverage: shape_oval must appear at least once", count("shape_oval"), n);
        assert!(count("shape_rect") >= 1, "shape_rect: only {}/{} (need >= 1) -- pad shape code coverage: shape_rect must appear at least once", count("shape_rect"), n);
        assert!(count("shape_roundrect") >= 1, "shape_roundrect: only {}/{} (need >= 1) -- pad shape code coverage: shape_roundrect must appear at least once", count("shape_roundrect"), n);
        assert!(count("shape_thru_hole") >= 1, "shape_thru_hole: only {}/{} (need >= 1) -- pad shape code coverage: shape_thru_hole must appear at least once", count("shape_thru_hole"), n);
        assert!(count("shape_unknown") >= 1, "shape_unknown: only {}/{} (need >= 1) -- pad shape code coverage: shape_unknown must appear at least once", count("shape_unknown"), n);
    }
// --- END generated by scripts/gen_oracle_freeze.py: copper_reach ---

    // --- BEGIN generated by scripts/gen_wasm_test_registry.py: tests ---
    /// Every `#[test]` in this module, as a callable the `wasm32`
    /// entry point can invoke by index.  Generated because these
    /// functions are private to this module and unreachable from
    /// anywhere a registry could otherwise live.
    pub const WASM_TESTS: &[(&str, fn())] = &[
        ("copper_reach::tests::empty_component_has_no_reach", empty_component_has_no_reach),
        ("copper_reach::tests::keeps_a_nan_the_way_cpython_max_does", keeps_a_nan_the_way_cpython_max_does),
        ("copper_reach::tests::infinity_beats_nan_via_py_hypot", infinity_beats_nan_via_py_hypot),
        ("copper_reach::tests::frozen_copper_reach_matches_golden_corpus", frozen_copper_reach_matches_golden_corpus),
        ("copper_reach::tests::frozen_copper_reach_corpus_is_non_vacuous", frozen_copper_reach_corpus_is_non_vacuous),
    ];
    // --- END generated by scripts/gen_wasm_test_registry.py: tests ---
}
