//! The `wasm32` test registry for `temper-geometry`.
//!
//! Generated by `scripts/gen_wasm_test_registry.py`; run it after adding a
//! test to any listed module, and `--check` gates drift in CI.
//!
//! `cargo test`'s libtest harness cannot target `wasm32-unknown-unknown`,
//! so the Worker tier calls each test function individually instead of
//! running a test binary.  This module is the flat, indexable list of them.
//!
//! Only modules that survive `--no-default-features` appear here.  Tests
//! inside `#[cfg(feature = "python")]` modules are structurally absent
//! from a `wasm32` build and cannot be registered here at all.
//!
//! Two exclusion classes apply here, both structural:
//!
//! * `#[cfg(feature = "python")]` modules (`escape_via`, `zone_pour`,
//!   `geometry_kernels`, `congestion_tensor`, `fixed_copper`,
//!   `area_sufficiency`, `occupancy_raster`) do not exist in a
//!   `--no-default-features` build, so neither do their tests.
//! * `proptest` modules use a dev-dependency, which is not linked into
//!   the ordinary (non-test) build this registry compiles into.  The
//!   same exclusion `temper-drc-rs` makes for its own `proptests`
//!   modules.
//!
//! `scripts/gen_wasm_test_registry.py --crate temper-geometry --census`
//! prints the full module census with per-module counts.
//!
//! A `#[should_panic]` test panics by design, and on this target a panic
//! aborts into a trap -- indistinguishable over the C ABI from a genuine
//! failure.  Those tests stay registered and are listed in
//! `tools/wasm/wasm_expected_failures_geometry.json`, whose gate is
//! bidirectional: one that stops panicking is reported, not ignored.
//!
//! ## Families
//!
//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`
//! feature, as in `temper-drc-rs`.  This crate is a flat set of
//! independent kernels with no rule-family taxonomy, so it declares a
//! single family (`geometry`) rather than inventing one; the mechanism
//! is in place if a size-driven split is ever wanted.

/// A single test: its fully qualified name and a nullary callable.
///
/// Failure is signalled by panicking, exactly as under libtest.  On
/// `wasm32-unknown-unknown` a panic aborts (the target has no unwinding on
/// stable), which surfaces to the host as a WebAssembly trap -- so the
/// runner catches the trap rather than a `Result`.
pub type WasmTest = (&'static str, fn());

/// All 2234 eligible tests, in a stable order.  Each entry is
/// gated on the per-family `wasm-registry-<family>` feature; enable
/// all families (`wasm-test-registry`) or individual ones.
pub const ALL: &[&[WasmTest]] = &[
    #[cfg(feature = "wasm-registry-geometry")] crate::audit::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::bottleneck_geometry::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::bottleneck_kernels::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::bundle_analyzer::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::channel_mapping::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::channel_skeleton::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::channel_widths::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::clearance_geometry::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::connected_components::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::connectivity_kernels::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::convex_hull::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::copper_coverage::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::copper_reach::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::core_graph_geometry::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::corridor::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::creepage_check::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::dense_package_detection::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::diff_pair_inference::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::drc_constraints_geometry::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::drc_inflate::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::edt::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::force::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::graph::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::grid_raster::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::grid_utils::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::heuristics::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::heuristics_geometry::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::hierarchical_clustering::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::host_math::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::kicad_transform::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::layer_capacity_kernels::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::nearest_neighbor::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::numeric::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::obstacle_map_kernels::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::organizational_geometry::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::overlap::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::pad_geometry::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::persistent_radius_index::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::placement::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::polygon::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::power_plane::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::primitives::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::projections::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::propagation::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::property_campaigns::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::radius_pairs::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::resource_bound::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::sdf::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::smooth::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::spice_estimators::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::style_geometry::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::trace_width_assignment::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::transform::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::units::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::via_clearance::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::via_placement::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-geometry")] crate::zone::tests::WASM_TESTS,
];

/// Total number of registered tests *in the currently-selected families*.
pub fn count() -> usize {
    ALL.iter().map(|m| m.len()).sum()
}

/// The test at `index` in the flattened registry.
pub fn get(index: usize) -> Option<&'static WasmTest> {
    let mut remaining = index;
    for module in ALL {
        if remaining < module.len() {
            return Some(&module[remaining]);
        }
        remaining -= module.len();
    }
    None
}
