// ERC check: net connectivity — every net must have at least two connected
// (non-mechanical) components.
//
// Placeholder — will be fully implemented in U4 (migrated DRC checks).
// Mechanical components (mounting holes, etc.) are excluded from connection
// counts since they carry no electrical nets by design.
//
// Origin: U4 of docs/plans/2026-06-30-003-feat-temper-drc-rs-engine-plan.md

use crate::board::BoardState;
use crate::constraints::ConstraintSet;
use crate::rules::{DrcCategory, DrcRule, Violation};

#[derive(Default)]
pub struct NetConnectivityCheck;

impl NetConnectivityCheck {
    pub fn new() -> Self {
        Self
    }
}
impl DrcRule for NetConnectivityCheck {
    fn name(&self) -> &str {
        "erc_net_connectivity"
    }
    fn category(&self) -> DrcCategory {
        DrcCategory::Erc
    }
    fn description(&self) -> &str {
        "Verify each net has at least two connected (non-mechanical) components."
    }
    fn check(&self, board: &BoardState, _constraints: &ConstraintSet) -> Vec<Violation> {
        // Only electrical components are in board.electrical_components —
        // mechanical components are separated at the type level.
        let _filtered_connection_counts: Vec<(&str, usize)> = board
            .nets
            .iter()
            .map(|net| {
                let count = net.components.len();
                (&*net.name, count)
            })
            .collect();

        // TODO(temper-xxx): Implement full net connectivity check using filtered counts.
        // Mechanical components are now excluded from connection tallies,
        // ready for the U4 implementation.
        vec![]
    }
}

#[cfg(any(test, feature = "wasm-registry"))]
#[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]
pub(crate) mod tests {
    use super::*;
    use crate::board::*;
    use crate::constraints::*;
    use std::collections::HashMap;

    #[cfg_attr(test, test)]
    fn net_connectivity_empty_board_no_violations() {
        let board = BoardState {
            width_mm: 100.0,
            height_mm: 100.0,
            margin_mm: 3.0,
            electrical_components: vec![],
            mechanical_components: vec![],
            nets: vec![],
            net_class_rules: HashMap::new(),
            traces: vec![],
            vias: vec![],
            zones: vec![],
        };
        let constraints = ConstraintSet::default();
        let check = NetConnectivityCheck::new();
        let violations = check.check(&board, &constraints);
        // Placeholder: currently always returns empty
        assert!(violations.is_empty());
    }

    #[cfg_attr(test, test)]
    fn net_connectivity_placeholder_compiles_and_runs() {
        // The check is a placeholder (TODO temper-xxx). Verify it compiles,
        // runs, and returns empty — this guards against future regressions
        // in the DrcRule trait contract.
        let board = BoardState {
            width_mm: 100.0,
            height_mm: 100.0,
            margin_mm: 3.0,
            electrical_components: vec![Component {
                refdes: ComponentRef("C1".into()),
                center: geo::Point::new(0.0, 0.0),
                rotation: 0.0,
                side: BoardSide::Top,
                width: 10.0,
                height: 10.0,
                net_class: NetClassName("Signal".into()),
                power_dissipation_w: None,
                package_type: PackageType::Smd,
                is_magnetic: false,
                is_electrolytic: false,
                vent_direction: None,
                footprint_polygon: None,
            }],
            mechanical_components: vec![],
            nets: vec![Net {
                name: NetName("N1".into()),
                components: vec![ComponentRef("C1".into())],
                class: NetClassName("Signal".into()),
                rules: NetClassRules::default(),
            }],
            net_class_rules: HashMap::new(),
            traces: vec![],
            vias: vec![],
            zones: vec![],
        };
        let constraints = ConstraintSet::default();
        let check = NetConnectivityCheck::new();
        let violations = check.check(&board, &constraints);
        assert!(violations.is_empty(), "placeholder should return empty");
        assert_eq!(check.name(), "erc_net_connectivity");
        assert_eq!(check.category(), DrcCategory::Erc);
    }

    // --- BEGIN generated by scripts/gen_wasm_test_registry.py: tests ---
    /// Every `#[test]` in this module, as a callable the `wasm32`
    /// entry point can invoke by index.  Generated because these
    /// functions are private to this module and unreachable from
    /// anywhere a registry could otherwise live.
    pub const WASM_TESTS: &[(&str, fn())] = &[
        ("rules::erc::net_connectivity::tests::net_connectivity_empty_board_no_violations", net_connectivity_empty_board_no_violations),
        ("rules::erc::net_connectivity::tests::net_connectivity_placeholder_compiles_and_runs", net_connectivity_placeholder_compiles_and_runs),
    ];
    // --- END generated by scripts/gen_wasm_test_registry.py: tests ---
}
