// Placeholder — will be implemented in U4 (migrated DRC checks).
//
// 2026-08-08 vacuity remediation
// (docs/evidence/2026-08-08-drc-safety-rule-vacuity-audit.md, Task 1):
// this rule was found registered live in `create_default_registry()` while
// `check()` unconditionally returned `vec![]` for any input — indistinguishable
// from a real "0 violations" pass. It has been DEREGISTERED
// (`rules::create_default_registry()` no longer constructs this type) rather
// than patched to fake a status, because a real implementation is not
// tractable with the data this crate's native `BoardState`/`Component`
// currently carry: no per-component or per-net "voltage domain" field exists
// on the native schema at all (only the legacy PyO3 differential-testing
// bridge in `drc_contracts.rs` carries a `voltage_domain`/`voltage_domains`
// concept, for parity-testing purposes only — it never reaches this rule).
// A pre-migration Python implementation existed
// (`packages/temper-drc/src/temper_drc/checks/erc/power_domain.py`, deleted
// in `2122544d`): for each net, collect the distinct `voltage_domain` values
// across its connected components and flag the net if more than one appears.
// To restore that behavior here, `board::Component` needs a
// `voltage_domain: Option<String>` field (or `BoardState`/`ConstraintSet`
// needs a `voltage_domains: HashMap<NetName, String>` map), populated by
// whichever board-dict builder is in use — that is a schema decision for a
// human, not something this remediation should invent silently. Until that
// lands, `PowerDomainCheck` stays unregistered so nothing can mistake its
// absence for a passing 0-violation result.
use crate::board::BoardState;
use crate::constraints::ConstraintSet;
use crate::rules::{DrcCategory, DrcRule, Violation};

#[derive(Default)]
pub struct PowerDomainCheck;

impl PowerDomainCheck {
    pub fn new() -> Self {
        Self
    }
}
impl DrcRule for PowerDomainCheck {
    fn name(&self) -> &str {
        "erc_power_domain"
    }
    fn category(&self) -> DrcCategory {
        DrcCategory::Erc
    }
    fn description(&self) -> &str {
        "Placeholder — U4"
    }
    fn check(&self, _board: &BoardState, _constraints: &ConstraintSet) -> Vec<Violation> {
        vec![]
    }
}

#[cfg(any(test, feature = "wasm-registry"))]
#[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]
pub(crate) mod tests {
    use super::*;
    use crate::board::*;
    use crate::constraints::*;
    use std::collections::BTreeMap;

    #[cfg_attr(test, test)]
    fn power_domain_empty_board_no_violations() {
        let board = BoardState {
            width_mm: 100.0,
            height_mm: 100.0,
            margin_mm: 3.0,
            electrical_components: vec![],
            mechanical_components: vec![],
            nets: vec![],
            net_class_rules: BTreeMap::new(),
            traces: vec![],
            vias: vec![],
            zones: vec![],
        };
        let constraints = ConstraintSet::default();
        let check = PowerDomainCheck::new();
        let violations = check.check(&board, &constraints);
        // Placeholder: currently always returns empty
        assert!(violations.is_empty());
    }

    #[cfg_attr(test, test)]
    fn power_domain_placeholder_compiles_and_runs() {
        // The check is a placeholder (TODO — U4). Verify it compiles,
        // runs, and returns empty — this guards against future regressions
        // in the DrcRule trait contract.
        let check = PowerDomainCheck::new();
        assert_eq!(check.name(), "erc_power_domain");
        assert_eq!(check.category(), DrcCategory::Erc);
        assert_eq!(check.description(), "Placeholder — U4");
    }

    // --- BEGIN generated by scripts/gen_wasm_test_registry.py: tests ---
    /// Every `#[test]` in this module, as a callable the `wasm32`
    /// entry point can invoke by index.  Generated because these
    /// functions are private to this module and unreachable from
    /// anywhere a registry could otherwise live.
    pub const WASM_TESTS: &[(&str, fn())] = &[
        ("rules::erc::power_domain::tests::power_domain_empty_board_no_violations", power_domain_empty_board_no_violations),
        ("rules::erc::power_domain::tests::power_domain_placeholder_compiles_and_runs", power_domain_placeholder_compiles_and_runs),
    ];
    // --- END generated by scripts/gen_wasm_test_registry.py: tests ---
}
