// Placeholder — will be implemented in U4 (migrated DRC checks).
use crate::board::BoardState;
use crate::constraints::ConstraintSet;
use crate::rules::{DrcCategory, DrcRule, Violation};

#[derive(Default)]
pub struct PowerDomainCheck;

impl PowerDomainCheck {
    pub fn new() -> Self {
        Self
    }
}
impl DrcRule for PowerDomainCheck {
    fn name(&self) -> &str {
        "erc_power_domain"
    }
    fn category(&self) -> DrcCategory {
        DrcCategory::Erc
    }
    fn description(&self) -> &str {
        "Placeholder — U4"
    }
    fn check(&self, _board: &BoardState, _constraints: &ConstraintSet) -> Vec<Violation> {
        vec![]
    }
}

#[cfg(any(test, feature = "wasm-test-registry"))]
#[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]
pub(crate) mod tests {
    use super::*;
    use crate::board::*;
    use crate::constraints::*;
    use std::collections::HashMap;

    #[cfg_attr(test, test)]
    fn power_domain_empty_board_no_violations() {
        let board = BoardState {
            width_mm: 100.0,
            height_mm: 100.0,
            margin_mm: 3.0,
            electrical_components: vec![],
            mechanical_components: vec![],
            nets: vec![],
            net_class_rules: HashMap::new(),
            traces: vec![],
            vias: vec![],
            zones: vec![],
        };
        let constraints = ConstraintSet::default();
        let check = PowerDomainCheck::new();
        let violations = check.check(&board, &constraints);
        // Placeholder: currently always returns empty
        assert!(violations.is_empty());
    }

    #[cfg_attr(test, test)]
    fn power_domain_placeholder_compiles_and_runs() {
        // The check is a placeholder (TODO — U4). Verify it compiles,
        // runs, and returns empty — this guards against future regressions
        // in the DrcRule trait contract.
        let check = PowerDomainCheck::new();
        assert_eq!(check.name(), "erc_power_domain");
        assert_eq!(check.category(), DrcCategory::Erc);
        assert_eq!(check.description(), "Placeholder — U4");
    }

    // --- BEGIN generated by scripts/gen_wasm_test_registry.py: tests ---
    /// Every `#[test]` in this module, as a callable the `wasm32`
    /// entry point can invoke by index.  Generated because these
    /// functions are private to this module and unreachable from
    /// anywhere a registry could otherwise live.
    pub const WASM_TESTS: &[(&str, fn())] = &[
        ("rules::erc::power_domain::tests::power_domain_empty_board_no_violations", power_domain_empty_board_no_violations),
        ("rules::erc::power_domain::tests::power_domain_placeholder_compiles_and_runs", power_domain_placeholder_compiles_and_runs),
    ];
    // --- END generated by scripts/gen_wasm_test_registry.py: tests ---
}
