//! The `wasm32` test registry for `temper-pcl-ir`.
//!
//! Generated by `scripts/gen_wasm_test_registry.py`; run it after adding a
//! test to any listed module, and `--check` gates drift in CI.
//!
//! `cargo test`'s libtest harness cannot target `wasm32-unknown-unknown`,
//! so the Worker tier calls each test function individually instead of
//! running a test binary.  This module is the flat, indexable list of them.
//!
//! Only modules that survive `--no-default-features` appear here.  Tests
//! inside `#[cfg(feature = "python")]` modules are structurally absent
//! from a `wasm32` build and cannot be registered here at all.
//!
//! No exclusion classes apply here.  This crate has no `python`
//! feature gate, and its one test-module dependency on `serde_json`
//! (`tests::all_pcl_kinds_round_trip_deterministically` round-trips
//! through JSON) is a normal, non-optional dependency rather than a
//! `dev-dependency`, so it links into the `--no-default-features`
//! build this registry compiles into -- the same promotion
//! `temper-drc-rs`/`temper-design-bundle`/`temper-io-types` make for
//! the same reason.
//!
//! `scripts/gen_wasm_test_registry.py --crate temper-pcl-ir --census`
//! prints the full module census with per-module counts.
//!
//! ## Families
//!
//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`
//! feature, as in `temper-drc-rs`.  One family (`pcl-ir`): this crate
//! is a flat typed data model (the shared PCL IR) with no taxonomy to
//! shard along.

/// A single test: its fully qualified name and a nullary callable.
///
/// Failure is signalled by panicking, exactly as under libtest.  On
/// `wasm32-unknown-unknown` a panic aborts (the target has no unwinding on
/// stable), which surfaces to the host as a WebAssembly trap -- so the
/// runner catches the trap rather than a `Result`.
pub type WasmTest = (&'static str, fn());

/// All 2 eligible tests, in a stable order.  Each entry is
/// gated on the per-family `wasm-registry-<family>` feature; enable
/// all families (`wasm-test-registry`) or individual ones.
pub const ALL: &[&[WasmTest]] = &[
    #[cfg(feature = "wasm-registry-pcl-ir")] crate::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-pcl-ir")] crate::key_tests::WASM_TESTS,
];

/// Total number of registered tests *in the currently-selected families*.
pub fn count() -> usize {
    ALL.iter().map(|m| m.len()).sum()
}

/// The test at `index` in the flattened registry.
pub fn get(index: usize) -> Option<&'static WasmTest> {
    let mut remaining = index;
    for module in ALL {
        if remaining < module.len() {
            return Some(&module[remaining]);
        }
        remaining -= module.len();
    }
    None
}
