#!/usr/bin/env bash
# Unified Setup for temper bd Workflow
#
# This single command configures everything needed for the bd-based workflow:
# - Loads worktree helpers and multiagent utilities
# - Installs git hooks
# - Configures shell rc files
# - Optionally enables protected branch mode
#
# Usage:
#   ./bd-setup.sh                    # Interactive setup
#   ./bd-setup.sh --quiet            # Non-interactive, use defaults
#   ./bd-setup.sh --status-only      # Just show current status
#
# Options:
#   --quiet, -q       Non-interactive mode (use defaults)
#   --status-only     Show current setup status only
#   --force           Re-run even if already configured
#   --no-hooks        Skip git hook installation
#   --no-shell        Skip shell configuration
#   --protected-branch  Enable beads protected branch mode
#   --help, -h        Show this help

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$SCRIPT_DIR"
TOOLS_DIR="$SCRIPT_DIR/tools"

info() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }
step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# ==============================================================================
# Utility Functions
# ==============================================================================

detect_shell() {
    if [[ -n "$ZSH_VERSION" ]]; then
        echo "zsh"
    elif [[ -n "$BASH_VERSION" ]]; then
        echo "bash"
    elif [[ "$SHELL" == *"fish"* ]]; then
        echo "fish"
    else
        echo "bash"
    fi
}

detect_shell_rc() {
    local shell="$1"
    case "$shell" in
        zsh) echo "$HOME/.zshrc" ;;
        fish) echo "$HOME/.config/fish/config.fish" ;;
        *) echo "$HOME/.bashrc" ;;
    esac
}

is_git_repo() {
    git rev-parse --git-dir &>/dev/null
}

# ==============================================================================
# Configuration Generation
# ==============================================================================

generate_shell_config_block() {
    local shell="$1"
    local worktree_root="${BD_WORKTREE_ROOT:-$HOME/worktrees}"
    local agent_id="${BEADS_AGENT_ID:-$USER}"

    case "$shell" in
        fish)
            cat <<FISH
# temper bd workflow - generated by bd-setup.sh
# DO NOT EDIT MANUALLY - rerun bd-setup.sh to regenerate

set -g BEADS_AGENT_ID "$agent_id"
set -g BD_WORKTREE_ROOT "$worktree_root"
set -g BEADS_STALE_MINUTES 30
set -g BEADS_AUTO_TAKEOVER false
set -g BEADS_AUTO_PR false

# Load worktree helpers (auto-sources multiagent utilities)
source "$TOOLS_DIR/bd-worktree-helpers.fish"
FISH
            ;;
        *)
            cat <<BASH
# temper bd workflow - generated by bd-setup.sh
# DO NOT EDIT MANUALLY - rerun bd-setup.sh to regenerate

export BEADS_AGENT_ID="$agent_id"
export BD_WORKTREE_ROOT="$worktree_root"
export BEADS_STALE_MINUTES=30
export BEADS_AUTO_TAKEOVER=false
export BEADS_AUTO_PR=false

# Load worktree helpers (auto-sources multiagent utilities)
source "$TOOLS_DIR/bd-worktree-helpers.sh"
BASH
            ;;
    esac
}

# ==============================================================================
# Component Checks
# ==============================================================================

check_shell_helpers() {
    if declare -f bd-work >/dev/null 2>&1; then
        echo "loaded"
        return 0
    else
        echo "not_loaded"
        return 1
    fi
}

check_hooks_installed() {
    local hook_file="$REPO_ROOT/.git/hooks/pre-push"
    if [[ -f "$hook_file" ]] && grep -q "_bd_prepush_check\|bd-multiagent" "$hook_file" 2>/dev/null; then
        echo "installed"
        return 0
    else
        echo "not_installed"
        return 1
    fi
}

check_protected_branch_mode() {
    if ! command -v bd &>/dev/null; then
        echo "not_available"
        return 1
    fi

    local sync_branch
    sync_branch=$(bd config get sync.branch 2>/dev/null || echo "")
    if [[ -n "$sync_branch" ]]; then
        echo "$sync_branch"
        return 0
    else
        echo "disabled"
        return 1
    fi
}

# ==============================================================================
# Installation Functions
# ==============================================================================

install_hooks() {
    local hook_installer="$TOOLS_DIR/git-hooks/install-multiagent.sh"

    if [[ ! -f "$hook_installer" ]]; then
        error "Hook installer not found: $hook_installer"
        return 1
    fi

    step "Installing git hooks..."
    if bash "$hook_installer"; then
        info "Git hooks installed successfully"
        return 0
    else
        error "Hook installation failed"
        return 1
    fi
}

configure_shell() {
    local shell="$1"
    local shell_rc
    shell_rc=$(detect_shell_rc "$shell")
    local config_block
    config_block=$(generate_shell_config_block "$shell")

    step "Configuring shell: $shell"

    # Create shell rc if needed
    if [[ ! -f "$shell_rc" ]]; then
        touch "$shell_rc"
        info "Created $shell_rc"
    fi

    # Check if already configured
    if grep -q "temper bd workflow" "$shell_rc" 2>/dev/null; then
        warn "temper bd workflow already configured in $shell_rc"
        if [[ "$FORCE_SETUP" != "true" ]]; then
            info "Skipping shell configuration (use --force to overwrite)"
            return 0
        fi
        # Remove old config
        sed -i.bak '/# temper bd workflow/,/bd-worktree-helpers/d' "$shell_rc" 2>/dev/null || true
    fi

    # Append new config
    echo "" >> "$shell_rc"
    echo "$config_block" >> "$shell_rc"
    info "Added workflow config to $shell_rc"

    # Auto-source for current session if shell matches
    local current_shell
    current_shell=$(detect_shell)
    if [[ "$shell" == "$current_shell" ]]; then
        echo ""
        info "Sourcing config for current session..."
        source "$shell_rc" 2>/dev/null || true
    fi
}

enable_protected_branch_mode() {
    if ! command -v bd &>/dev/null; then
        warn "bd command not found - skipping protected branch setup"
        return 0
    fi

    step "Configuring protected branch mode..."

    # Check if already configured
    local current
    current=$(bd config get sync.branch 2>/dev/null || echo "")
    if [[ -n "$current" ]]; then
        warn "Already using sync branch: $current"
        return 0
    fi

    # Configure
    bd config set sync.branch beads-sync
    info "Configured sync branch: beads-sync"

    # Offer to start daemon
    echo ""
    read -p "Start bd daemon with auto-commit? [Y/n] " confirm
    if [[ "$confirm" != "n" && "$confirm" != "N" ]]; then
        bd daemon --start --auto-commit
        info "Started daemon with auto-commit"
    fi
}

# ==============================================================================
# Status Display
# ==============================================================================

show_status() {
    echo ""
    echo -e "${BLUE}temper bd Workflow Status${NC}"
    echo "================================"
    echo ""

    # Shell helpers
    local helpers_status="not_loaded"
    helpers_status=$(check_shell_helpers 2>/dev/null || echo "error")
    case "$helpers_status" in
        loaded)   echo -e "  ${GREEN}✓${NC} Shell helpers: loaded" ;;
        *)        echo -e "  ${RED}✗${NC} Shell helpers: NOT LOADED" ;;
    esac

    # Hooks
    local hooks_status="not_installed"
    hooks_status=$(check_hooks_installed 2>/dev/null || echo "error")
    case "$hooks_status" in
        installed)   echo -e "  ${GREEN}✓${NC} Git hooks: installed" ;;
        *)           echo -e "  ${RED}✗${NC} Git hooks: NOT INSTALLED" ;;
    esac

    # Agent ID
    if [[ -n "$BEADS_AGENT_ID" ]]; then
        echo -e "  ${GREEN}✓${NC} Agent ID: $BEADS_AGENT_ID"
    else
        echo -e "  ${RED}✗${NC} Agent ID: NOT SET"
        echo "       Run: export BEADS_AGENT_ID=your-name"
    fi

    # Worktree root
    local wroot="${BD_WORKTREE_ROOT:-\$HOME/worktrees}"
    echo "  Worktree root: $wroot"

    # Protected branch mode
    local pb_status
    pb_status=$(check_protected_branch_mode 2>/dev/null || echo "unknown")
    case "$pb_status" in
        disabled)
            echo -e "  ${YELLOW}○${NC} Protected branch: disabled"
            echo "       Run with --protected-branch to enable"
            ;;
        not_available)
            echo -e "  ${YELLOW}○${NC} Protected branch: bd not found"
            ;;
        *)
            echo -e "  ${GREEN}✓${NC} Protected branch: $pb_status"
            ;;
    esac

    # Active worktrees
    echo ""
    echo "  Active worktrees:"
    if [[ -d "$HOME/worktrees/temper" ]]; then
        for wt in "$HOME/worktrees/temper"/*; do
            if [[ -d "$wt" ]]; then
                local task_id
                task_id=$(basename "$wt")
                echo "    - $task_id"
            fi
        done
    else
        echo "    (none)"
    fi

    echo ""
    echo "  Quick commands:"
    echo "    bd ready           # Find unblocked work"
    echo "    bd-work <id>       # Start work on a task"
    echo "    bd-done            # Complete task"
    echo "    bd-claims          # See active claims"

    echo ""
}

# ==============================================================================
# Main Logic
# ==============================================================================

main() {
    local mode="interactive"
    local install_hooks_flag=true
    local configure_shell_flag=true
    local protected_branch_flag=false

    # Parse arguments
    while [[ "$1" == --* ]]; do
        case "$1" in
            --quiet|-q)
                mode="quiet"
                shift
                ;;
            --status-only)
                mode="status"
                shift
                ;;
            --force)
                FORCE_SETUP="true"
                shift
                ;;
            --no-hooks)
                install_hooks_flag=false
                shift
                ;;
            --no-shell)
                configure_shell_flag=false
                shift
                ;;
            --protected-branch)
                protected_branch_flag=true
                shift
                ;;
            --help|-h)
                echo "Usage: bd-setup.sh [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --quiet, -q          Non-interactive mode (use defaults)"
                echo "  --status-only        Show current setup status"
                echo "  --force              Re-run even if already configured"
                echo "  --no-hooks           Skip git hook installation"
                echo "  --no-shell           Skip shell configuration"
                echo "  --protected-branch   Enable beads protected branch mode"
                echo "  --help, -h           Show this help"
                echo ""
                echo "Examples:"
                echo "  bd-setup.sh                  # Interactive setup"
                echo "  bd-setup.sh --quiet          # Non-interactive"
                echo "  bd-setup.sh --status-only    # Check status"
                exit 0
                ;;
            *)
                error "Unknown option: $1"
                exit 1
                ;;
        esac
    done

    # Validate we're in a git repo
    if ! is_git_repo; then
        error "Not in a git repository"
        exit 1
    fi

    # Show status if requested
    if [[ "$mode" == "status" ]]; then
        show_status
        exit 0
    fi

    echo ""
    echo -e "${BLUE}temper bd Workflow Setup${NC}"
    echo "============================"
    echo ""

    local shell
    shell=$(detect_shell)
    info "Detected shell: $shell"

    # Step 1: Git hooks
    if [[ "$install_hooks_flag" == "true" ]]; then
        install_hooks || true
    else
        info "Skipping hook installation (--no-hooks)"
    fi

    # Step 2: Shell configuration
    if [[ "$configure_shell_flag" == "true" ]]; then
        configure_shell "$shell" || true
    else
        info "Skipping shell configuration (--no-shell)"
    fi

    # Step 3: Protected branch mode
    if [[ "$protected_branch_flag" == "true" ]]; then
        enable_protected_branch_mode || true
    fi

    # Summary
    echo ""
    echo -e "${GREEN}Setup Complete!${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. Restart your shell OR source your rc file:"
    if [[ "$shell" == "fish" ]]; then
        echo "     source ~/.config/fish/config.fish"
    else
        echo "     source ~/.bashrc  # or ~/.zshrc"
    fi
    echo "  2. Verify setup: ./bd-setup.sh --status-only"
    echo "  3. Find work: bd ready"
    echo ""
    echo "Commands available after sourcing:"
    echo "  bd-work <task-id>   # Start work (creates worktree, claims task)"
    echo "  bd-pause            # Pause work (commit + push for sync)"
    echo "  bd-done             # Complete task (close issue, post reflection)"
    echo "  bd-claims           # See active claims"
    echo "  bd-cleanup-worktrees # Clean up closed+merged worktrees"
    echo ""
}

# Run main
main "$@"
