"""Property tests for the RTD hardware-fault path through the SR latch.

The redundant RTD comparator is intentionally represented here as a single
``RTD_HW_FAULT`` boolean.  That is its electrical contract at the fault OR:
the latch must react without firmware polling, an SPI transaction, or a live
MCU.  Comparator sizing and analogue corners are proved separately in
``test_rtd_window_comparator_pbt.py``.
"""

from __future__ import annotations

from hypothesis import given, settings
from hypothesis import strategies as st

from temper_placer.validation.rtd_safety import rtd_hardware_fault_asserted


def _latch_step(
    s_bar: bool,
    r_bar: bool,
    q: bool,
    q_bar: bool,
) -> tuple[bool, bool]:
    """Evaluate the set-dominant NAND latch used by the UCC21550 contract."""

    for _ in range(8):
        next_q = not (s_bar and q_bar)
        next_q_bar = not (r_bar and next_q)
        q, q_bar = next_q, next_q_bar
    return q, q_bar


def _rtd_latch_step(
    *,
    rtd_hw_fault: bool,
    other_hardware_fault: bool,
    reset_request: bool,
    q: bool,
    q_bar: bool,
) -> tuple[bool, bool]:
    """Apply the fault-OR and fault-qualified reset contract.

    ``rtd_hw_fault`` is generated by the independent analogue path.  No MCU
    state or SPI event appears in this function because neither is electrically
    permitted to be a precondition for asserting UCC21550 shutdown.
    """

    fault = rtd_hw_fault or other_hardware_fault
    # R_bar is fault-qualified: a live fault holds reset inactive even if the
    # MCU is simultaneously requesting a reset. This avoids the invalid NAND
    # latch input pair and makes shutdown set-dominant by construction.
    return _latch_step(not fault, fault or not reset_request, q, q_bar)


@st.composite
def _fault_events(draw: st.DrawFn) -> tuple[bool, bool, bool, bool, bool, bool]:
    """Generate RTD fault, unrelated fault, reset, MCU, and SPI conditions."""

    return (
        draw(st.booleans()),  # comparator threshold fault (short or open)
        draw(st.booleans()),  # comparator supply is present
        draw(st.booleans()),  # another source on the hardware fault OR
        draw(st.booleans()),  # firmware reset request
        draw(st.booleans()),  # MCU is powered/running
        draw(st.booleans()),  # SPI transfer is in progress
    )


@given(events=st.lists(_fault_events(), min_size=1, max_size=50))
@settings(max_examples=200, deadline=10_000)
def test_rtd_hardware_fault_dominates_reset_without_mcu_or_spi(
    events: list[tuple[bool, bool, bool, bool, bool, bool]],
) -> None:
    """RTD faults must assert UCC21550 shutdown in every reset/MCU/SPI state."""

    q, q_bar = False, True
    for (
        comparator_fault,
        comparator_supply_present,
        other_fault,
        reset_request,
        _mcu_running,
        _spi_active,
    ) in events:
        rtd_hw_fault = rtd_hardware_fault_asserted(
            comparator_fault=comparator_fault,
            comparator_supply_present=comparator_supply_present,
        )
        q, q_bar = _rtd_latch_step(
            rtd_hw_fault=rtd_hw_fault,
            other_hardware_fault=other_fault,
            reset_request=reset_request,
            q=q,
            q_bar=q_bar,
        )

        # ``q`` is the asserted hardware-fault state that drives the active-
        # high UCC21550 DIS/SHUTDOWN signal.  A simultaneous reset request
        # makes the complementary NAND node electrically indeterminate, but
        # must not clear Q.  The deliberately unused MCU/SPI values make the
        # independence requirement explicit in the generated state space.
        if rtd_hw_fault:
            assert q is True


@given(
    prefix=st.lists(
        st.tuples(st.booleans(), st.booleans(), st.booleans()),
        min_size=0,
        max_size=30,
    ),
    post_fault_reset_requests=st.lists(st.booleans(), min_size=0, max_size=30),
)
@settings(max_examples=200, deadline=10_000)
def test_rtd_fault_stays_latched_after_fault_clears_until_reset(
    prefix: list[tuple[bool, bool, bool]],
    post_fault_reset_requests: list[bool],
) -> None:
    """A transient RTD short/open/supply-loss event cannot self-clear."""

    q, q_bar = False, True
    for rtd_hw_fault, other_fault, reset_request in prefix:
        q, q_bar = _rtd_latch_step(
            rtd_hw_fault=rtd_hw_fault,
            other_hardware_fault=other_fault,
            reset_request=reset_request,
            q=q,
            q_bar=q_bar,
        )

    # The independent comparator asserts once, then clears.  No reset request
    # during the clear interval may release its latched shutdown state.
    q, q_bar = _rtd_latch_step(
        rtd_hw_fault=rtd_hardware_fault_asserted(
            comparator_fault=True,
            comparator_supply_present=True,
        ),
        other_hardware_fault=False,
        reset_request=False,
        q=q,
        q_bar=q_bar,
    )
    assert q is True

    for reset_request in post_fault_reset_requests:
        q, q_bar = _rtd_latch_step(
            rtd_hw_fault=False,
            other_hardware_fault=False,
            reset_request=False,
            q=q,
            q_bar=q_bar,
        )
        assert q is True

        # An explicit reset is the only permitted release after the fault is
        # clear.  This also checks that an arbitrary number of previous
        # no-reset samples has no effect on the latched state.
        if reset_request:
            q, q_bar = _rtd_latch_step(
                rtd_hw_fault=False,
                other_hardware_fault=False,
                reset_request=True,
                q=q,
                q_bar=q_bar,
            )
            assert (q, q_bar) == (False, True)
            # Re-establish the set condition for later generated iterations.
            q, q_bar = _rtd_latch_step(
                rtd_hw_fault=rtd_hardware_fault_asserted(
                    comparator_fault=True,
                    comparator_supply_present=True,
                ),
                other_hardware_fault=False,
                reset_request=False,
                q=q,
                q_bar=q_bar,
            )
            assert q is True


@given(
    reset_request=st.booleans(),
    mcu_running=st.booleans(),
    spi_active=st.booleans(),
)
@settings(max_examples=50, deadline=10_000)
def test_rtd_supply_loss_is_a_latched_hardware_shutdown(
    reset_request: bool,
    mcu_running: bool,
    spi_active: bool,
) -> None:
    """A loss of the RTD path's supply is no less urgent than an RTD open."""

    q, q_bar = _rtd_latch_step(
        rtd_hw_fault=rtd_hardware_fault_asserted(
            comparator_fault=False,
            comparator_supply_present=False,
        ),
        other_hardware_fault=False,
        reset_request=reset_request,
        q=False,
        q_bar=True,
    )
    assert q is True
