// export_types: TraceSegment.
//
// Pure data holders, always compiled (including on wasm32). The
// `#[cfg(feature = "python")]` submodule below wraps each one in a
// pyclass with the same Python-visible name and field set as before;
// the wrapper is a plain struct (not a newtype over the pure one) because
// pyo3's `#[pyo3(get, set)]` field shorthand must be resolved by the
// `#[pyclass]` macro itself, which only sees literal `#[pyo3(...)]`
// attributes — `#[cfg_attr(feature = "python", pyo3(get, set))]` does not
// work here (the inner `cfg_attr` is still unresolved token soup when
// `#[pyclass]` expands, so it can't recognise it as its own helper
// attribute). Keeping the wrapper's fields flat and delegating formatting
// to the pure struct's methods keeps the two from drifting.

#[derive(Clone, Debug, PartialEq)]
pub struct TraceSegment {
    pub net: String,
    pub start: (f64, f64),
    pub end: (f64, f64),
    pub width: f64,
    pub layer: String,
}

impl TraceSegment {
    pub fn repr(&self) -> String {
        format!(
            "TraceSegment(net={:?}, start={:?}, end={:?}, width={}, layer={:?})",
            self.net, self.start, self.end, self.width, self.layer
        )
    }
}

#[cfg(feature = "python")]
mod py_bridge {
    use super::*;
    use pyo3::prelude::*;

    #[pyclass(name = "TraceSegment", from_py_object)]
    #[derive(Clone)]
    pub struct PyTraceSegment {
        #[pyo3(get, set)]
        pub net: String,
        #[pyo3(get, set)]
        pub start: (f64, f64),
        #[pyo3(get, set)]
        pub end: (f64, f64),
        #[pyo3(get, set)]
        pub width: f64,
        #[pyo3(get, set)]
        pub layer: String,
    }

    impl PyTraceSegment {
        fn pure(&self) -> TraceSegment {
            TraceSegment {
                net: self.net.clone(),
                start: self.start,
                end: self.end,
                width: self.width,
                layer: self.layer.clone(),
            }
        }
    }

    #[pymethods]
    impl PyTraceSegment {
        #[new]
        fn new(net: String, start: (f64, f64), end: (f64, f64), width: f64, layer: String) -> Self {
            PyTraceSegment {
                net,
                start,
                end,
                width,
                layer,
            }
        }

        fn __repr__(&self) -> String {
            self.pure().repr()
        }
    }

}

#[cfg(feature = "python")]
pub use py_bridge::PyTraceSegment;

#[cfg(any(test, feature = "wasm-registry"))]
#[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]
pub(crate) mod tests {
    use super::*;

    #[cfg_attr(test, test)]
    fn trace_segment_repr() {
        let seg = TraceSegment {
            net: "GND".into(),
            start: (0.0, 0.0),
            end: (1.0, 1.0),
            width: 0.25,
            layer: "F.Cu".into(),
        };
        assert_eq!(
            seg.repr(),
            "TraceSegment(net=\"GND\", start=(0.0, 0.0), end=(1.0, 1.0), width=0.25, layer=\"F.Cu\")"
        );
    }

    // --- BEGIN generated by scripts/gen_wasm_test_registry.py: tests ---
    /// Every `#[test]` in this module, as a callable the `wasm32`
    /// entry point can invoke by index.  Generated because these
    /// functions are private to this module and unreachable from
    /// anywhere a registry could otherwise live.
    pub const WASM_TESTS: &[(&str, fn())] = &[
        ("export_types::tests::trace_segment_repr", trace_segment_repr),
    ];
    // --- END generated by scripts/gen_wasm_test_registry.py: tests ---
}
