// isolation_slot_geometry: isolation_slot_aabb.
//
// The AABB computation is pure arithmetic; only the extraction of
// `start_offset` / `end_offset` / `width_mm` from an arbitrary Python
// `IsolationSlot`-like object needs pyo3.

#[cfg(feature = "python")]
use pyo3::prelude::*;

/// Compute the world-space axis-aligned bounding box of an isolation slot
/// (a thin rectangular keepout strip between `start_offset` and
/// `end_offset`, `width_mm` wide) anchored at `component_xy`.
pub fn isolation_slot_aabb(
    start_offset: (f64, f64),
    end_offset: (f64, f64),
    width_mm: f64,
    component_xy: (f64, f64),
) -> ((f64, f64), (f64, f64)) {
    let (cx, cy) = component_xy;
    let (sx, sy) = start_offset;
    let (ex, ey) = end_offset;

    let mut x_lo = sx.min(ex);
    let mut x_hi = sx.max(ex);
    let mut y_lo = sy.min(ey);
    let mut y_hi = sy.max(ey);

    let dx = ex - sx;
    let dy = ey - sy;
    let half_w = width_mm / 2.0;

    if dx.abs() >= dy.abs() {
        y_lo -= half_w;
        y_hi += half_w;
    } else {
        x_lo -= half_w;
        x_hi += half_w;
    }

    ((cx + x_lo, cy + y_lo), (cx + x_hi, cy + y_hi))
}

#[cfg(feature = "python")]
#[pyfunction(name = "isolation_slot_aabb")]
pub fn isolation_slot_aabb_py(
    slot: Bound<'_, PyAny>,
    component_xy: (f64, f64),
) -> PyResult<((f64, f64), (f64, f64))> {
    let start_offset: (f64, f64) = slot.getattr("start_offset")?.extract()?;
    let end_offset: (f64, f64) = slot.getattr("end_offset")?.extract()?;
    let width_mm: f64 = slot.getattr("width_mm")?.extract()?;
    Ok(isolation_slot_aabb(
        start_offset,
        end_offset,
        width_mm,
        component_xy,
    ))
}

#[cfg(any(test, feature = "wasm-registry"))]
#[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]
pub(crate) mod tests {
    use super::*;

    #[cfg_attr(test, test)]
    fn horizontal_slot_expands_in_y() {
        let aabb = isolation_slot_aabb((0.0, 0.0), (10.0, 0.0), 4.0, (100.0, 100.0));
        assert_eq!(aabb, ((100.0, 98.0), (110.0, 102.0)));
    }

    #[cfg_attr(test, test)]
    fn vertical_slot_expands_in_x() {
        let aabb = isolation_slot_aabb((0.0, 0.0), (0.0, 10.0), 4.0, (0.0, 0.0));
        assert_eq!(aabb, ((-2.0, 0.0), (2.0, 10.0)));
    }

    // --- BEGIN generated by scripts/gen_wasm_test_registry.py: tests ---
    /// Every `#[test]` in this module, as a callable the `wasm32`
    /// entry point can invoke by index.  Generated because these
    /// functions are private to this module and unreachable from
    /// anywhere a registry could otherwise live.
    pub const WASM_TESTS: &[(&str, fn())] = &[
        ("isolation::tests::horizontal_slot_expands_in_y", horizontal_slot_expands_in_y),
        ("isolation::tests::vertical_slot_expands_in_x", vertical_slot_expands_in_x),
    ];
    // --- END generated by scripts/gen_wasm_test_registry.py: tests ---
}
