//! The `wasm32` test registry for `temper-io-types`.
//!
//! Generated by `scripts/gen_wasm_test_registry.py`; run it after adding a
//! test to any listed module, and `--check` gates drift in CI.
//!
//! `cargo test`'s libtest harness cannot target `wasm32-unknown-unknown`,
//! so the Worker tier calls each test function individually instead of
//! running a test binary.  This module is the flat, indexable list of them.
//!
//! Only modules that survive `--no-default-features` appear here.  Tests
//! inside `#[cfg(feature = "python")]` modules are structurally absent
//! from a `wasm32` build and cannot be registered here at all.
//!
//! Two exclusion classes apply here, both structural:
//!
//! * `#[cfg(feature = "python")]` modules -- `explain`, `report`,
//!   `reference_aliases`, `footprint_library`, `dsn_pyo3` and
//!   `zone_filler`.  Each is a *whole* pyo3 surface: its entry
//!   points take and return `Bound<'_, PyAny>` and read Python
//!   runtime semantics (`str()`, `yaml.safe_load`, `str.strip`)
//!   back across the boundary, so there is no kernel underneath to
//!   compile without pyo3.  Their tests are not skipped on
//!   `wasm32`: they are not compiled.
//! * `proptest` modules use a dev-dependency, which is not linked into
//!   the ordinary (non-test) build this registry compiles into.
//!
//! `scripts/gen_wasm_test_registry.py --crate temper-io-types
//! --census` prints the full module census with per-module counts.
//!
//! ## Families
//!
//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`
//! feature, as in `temper-drc-rs`.  One family (`io-types`): what
//! survives `--no-default-features` is a flat set of KiCad/DSN
//! serialisers, parsers and placer CONTRACT kernels with no
//! taxonomy to shard along.

/// A single test: its fully qualified name and a nullary callable.
///
/// Failure is signalled by panicking, exactly as under libtest.  On
/// `wasm32-unknown-unknown` a panic aborts (the target has no unwinding on
/// stable), which surfaces to the host as a WebAssembly trap -- so the
/// runner catches the trap rather than a `Result`.
pub type WasmTest = (&'static str, fn());

/// All 6638 eligible tests, in a stable order.  Each entry is
/// gated on the per-family `wasm-registry-<family>` feature; enable
/// all families (`wasm-test-registry`) or individual ones.
pub const ALL: &[&[WasmTest]] = &[
    #[cfg(feature = "wasm-registry-io-types")] crate::dag_expr::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::dag_expr::depth_boundary::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::dsn::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::dsn_exporter::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::dsn_exporter::property_campaigns::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::dsn_types::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::export_types::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::footprint_spec::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::golden_diff::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::isolation::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::kicad_write_geometry::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::placer_core::adjacency::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::placer_core::manufacturing::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::placer_core::netclass::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::placer_core::placement_drc::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::placer_core::placer_compute::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::placer_core::pyrepr::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::placer_core::rect::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::placer_core::units::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::property_campaigns::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::provenance::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::pyfmt::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::stackup_validator::helper_tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-io-types")] crate::strip_copper::tests::WASM_TESTS,
];

/// Total number of registered tests *in the currently-selected families*.
pub fn count() -> usize {
    ALL.iter().map(|m| m.len()).sum()
}

/// The test at `index` in the flattened registry.
pub fn get(index: usize) -> Option<&'static WasmTest> {
    let mut remaining = index;
    for module in ALL {
        if remaining < module.len() {
            return Some(&module[remaining]);
        }
        remaining -= module.len();
    }
    None
}
