// Router V6 topology stage — PyO3 entry point.
//
// Origin: U3/U4/U7 of docs/plans/2026-06-28-001-feat-router-v6-rust-topology-plan.md

pub mod layer_assignment;
pub mod net_ordering;
pub mod terminal_planning;

// `loop_extractor`, `net_batching`, `theta_star` and
// `types_py_bridge` are pyo3 surfaces with no pure subset:
// `types_py_bridge` is `#[pyclass]`-era Python-dict extraction,
// `theta_star`/`loop_extractor::bridge`/`net_batching` take
// `&Bound<'_, PyAny>` (or plain marshalled types with no kernel underneath --
// `net_batching`'s pure logic lives in the registered
// `temper-rust-router-core::net_batching`, Phase E E5).  None of them have a
// `#[test]` of their own that exercises anything beyond the pyo3 boundary
// itself.  `layer_assignment`/`net_ordering`/`terminal_planning` above are
// the crate's three pure kernels and stay unconditional; see
// `scripts/gen_wasm_test_registry.py --crate temper-rust-router --census`.
#[cfg(feature = "python")]
pub mod loop_extractor;
#[cfg(feature = "python")]
pub mod net_batching;
#[cfg(feature = "python")]
pub mod theta_star;
#[cfg(feature = "python")]
#[cfg(feature = "python")]
mod types_py_bridge;

// Exposes every eligible `#[test]` in `layer_assignment`/`net_ordering`/
// `terminal_planning` as a flat, indexable `(&'static str, fn())` list so a
// `wasm32` entry point (`temper-wasm-test-runner`) can call each one --
// `cargo test`'s libtest harness cannot target `wasm32-unknown-unknown`. Off
// by default; never enabled for the Python extension module. Generated by
// `scripts/gen_wasm_test_registry.py --crate temper-rust-router`.
#[cfg(feature = "wasm-registry")]
pub mod wasm_test_registry;

/// The little-endian f32 decode shared by [`py::astar_kernel_3d_py`]'s
/// congestion/thermal buffers and `proptests` below.  Stays outside `py`
/// (unlike every other item past this point) because it has zero pyo3
/// coupling and is the thing `proptests` actually exercises.
fn f32s_from_le_bytes(bytes: &[u8], expected: usize) -> Vec<f32> {
    debug_assert_eq!(bytes.len() % 4, 0);
    let mut out = Vec::with_capacity(bytes.len() / 4);
    for c in bytes.chunks_exact(4) {
        let mut buf = [0u8; 4];
        buf.copy_from_slice(c);
        out.push(f32::from_le_bytes(buf));
    }
    debug_assert!(expected == 0 || out.len() == expected);
    out
}

#[cfg(test)]
mod proptests {
    use proptest::prelude::*;

    proptest! {
        // -----------------------------------------------------------------
        // f32s_from_le_bytes
        // -----------------------------------------------------------------

        /// P1. round-trip: encoding f32 values to bytes then back yields the
        /// same values.
        #[test]
        fn p1_f32s_round_trip(
            vals in prop::collection::vec(prop::num::f32::ANY, 0..=100),
        ) {
            let mut bytes = Vec::with_capacity(vals.len() * 4);
            for &v in &vals {
                bytes.extend_from_slice(&v.to_le_bytes());
            }
            let recovered = super::f32s_from_le_bytes(&bytes, vals.len());
            prop_assert_eq!(recovered.len(), vals.len());
            for (i, (&orig, &rec)) in vals.iter().zip(recovered.iter()).enumerate() {
                // NaN has multiple bit representations, so compare bits
                if orig.is_nan() {
                    prop_assert!(rec.is_nan(), "index {}: expected NaN, got {}", i, rec);
                } else {
                    prop_assert_eq!(orig.to_bits(), rec.to_bits(),
                        "index {}: orig={} rec={}", i, orig, rec);
                }
            }
        }

        /// P2. Output length equals input byte length divided by 4.
        #[test]
        fn p2_output_length_input_div_4(
            bytes in prop::collection::vec(any::<u8>(), 0..=400),
        ) {
            // Truncate to multiple of 4
            let n = (bytes.len() / 4) * 4;
            let bytes = &bytes[..n];
            let result = super::f32s_from_le_bytes(bytes, 0);
            prop_assert_eq!(result.len(), bytes.len() / 4);
        }

        /// P3. Zero bytes decode to +0.0 f32.
        #[test]
        fn p3_zero_bytes_decode_to_zero(
            count in 1usize..=20,
        ) {
            let bytes = vec![0u8; count * 4];
            let result = super::f32s_from_le_bytes(&bytes, count);
            for v in result {
                prop_assert_eq!(v, 0.0f32);
                prop_assert!(v.is_sign_positive());
            }
        }
    }
}

// Everything in `py` below is the pyo3 boundary: the SAT-solver pipeline
// entry point, the constraint auditor, the loop-extraction/classification
// JSON bridges, the A*/line-of-sight kernels' `#[pyfunction]` wrappers, and
// the `#[pymodule]` entry point itself.  None of it exists in a
// `--no-default-features` (`wasm32`) build --
// `scripts/gen_wasm_test_registry.py --crate temper-rust-router --census`
// prints the full module census.  `classify_component_py`/
// `parse_capacitance_py`/`astar_kernel_3d`/etc. -- the pure kernels these
// wrappers call -- already live in the registered `temper-rust-router-core`;
// nothing pure is lost by gating this module away as a whole.
#[cfg(feature = "python")]
mod py {
    use std::collections::HashMap;

    use pyo3::prelude::*;
    use pyo3::types::{PyDict, PyList};

    use temper_rust_router_core::astar::AstarInput;
    use temper_rust_router_core::loop_extractor::classify::CompInfo;
    use temper_rust_router_core::loop_extractor::classify_py::{
        classify_component_py, parse_capacitance_py, MalformedNumber,
    };
    use temper_rust_router_core::types as core_types;
    use temper_rust_router_core::types::{InternalConstraintModel, SolverStatus, TopologyResult};
    use temper_rust_router_core::{audit, combinator, encoding, extraction, solver};

    /// Python-callable entry point: solve the topology stage in Rust.
    ///
    /// Accepts a list of variable dicts, constraint dicts, and net names
    /// matching the Python `ConstraintModel` shape, and returns a dict with
    /// solver status, variable assignments, and topology graph.
    ///
    /// `conflict_limit` and `time_limit_ms` bound the CaDiCaL solve (see
    /// `temper_rust_router_core::solver::SolveLimits`). Both default to
    /// `None` (unbounded) at this FFI boundary -- the recommended production
    /// bound is applied by the caller
    /// (`RouterV6Pipeline.sat_conflict_limit` in
    /// `packages/temper-placer/src/temper_placer/router_v6/_pipeline_core.py`),
    /// not hard-coded here, so any other caller of this function is
    /// unaffected unless it opts in.
    #[pyfunction]
    #[pyo3(signature = (variables, constraints, net_names, conflict_limit=None, time_limit_ms=None))]
    fn solve_topology_rust(
        py: Python<'_>,
        variables: &Bound<'_, PyList>,
        constraints: &Bound<'_, PyList>,
        net_names: Vec<String>,
        conflict_limit: Option<u32>,
        time_limit_ms: Option<u64>,
    ) -> PyResult<Py<PyDict>> {
        // Diagnostic phase timing, enabled by TEMPER_REWRITE_TRACE (same env
        // var the rewrite engine's own instrumentation uses -- see
        // docs/evidence/2026-07-27-stage3-model-and-rewrite.md). Off by
        // default: one env::var() call, no cost otherwise.
        let phase_trace = std::env::var("TEMPER_REWRITE_TRACE").is_ok();
        let t_start = std::time::Instant::now();

        // Convert Python objects to internal model.
        let py_vars: Vec<Py<PyAny>> = variables.iter().map(|v| v.into()).collect();
        let py_cons: Vec<Py<PyAny>> = constraints.iter().map(|c| c.into()).collect();

        let model: InternalConstraintModel =
            crate::types_py_bridge::model_from_python(py_vars, py_cons, py)?;
        if phase_trace {
            eprintln!("[phase-trace t={:.3}s] model_from_python done", t_start.elapsed().as_secs_f64());
        }

        // Apply combinator rewrite engine (RW1-RW7) to simplify the model
        // before CNF encoding.  Detects structural contradictions (RW7) pre-solve.
        //
        // TEMPER_SKIP_REWRITE bypasses this step entirely -- a measurement-only
        // escape hatch (default: unset, rewrite always runs) used to compare
        // "rewrite on" vs "rewrite off" model size / solve time. See
        // docs/evidence/2026-07-27-stage3-model-and-rewrite.md.
        let model = if std::env::var("TEMPER_SKIP_REWRITE").is_ok() {
            model
        } else {
            combinator::rewrite::rewrite(&model)
                .map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(format!("{:?}", e)))?
        };
        if phase_trace {
            eprintln!("[phase-trace t={:.3}s] rewrite done, {} constraints", t_start.elapsed().as_secs_f64(), model.constraints.len());
        }

        // Encode to CNF (cardinality constraints encoded as CNF clauses).
        let (cnf, var_names) = encoding::encode_to_cnf(&model);
        let num_vars = cnf.num_vars;
        let num_clauses = cnf.clauses.len();
        if phase_trace {
            eprintln!("[phase-trace t={:.3}s] encode_to_cnf done, {num_vars} vars, {num_clauses} clauses", t_start.elapsed().as_secs_f64());
        }

        // Solve with CaDiCaL via rustsat traits, under the caller-supplied bound.
        let limits = solver::SolveLimits {
            conflict_limit,
            time_limit_ms,
        };
        let mut result: TopologyResult = solver::solve_with_cadical(&cnf, limits);
        result.num_vars = num_vars;
        result.num_clauses = num_clauses;
        if phase_trace {
            eprintln!("[phase-trace t={:.3}s] solve done, status={:?}", t_start.elapsed().as_secs_f64(), result.status);
        }

        // Extract topology if satisfiable.
        let topology = if result.status == SolverStatus::Satisfiable {
            extraction::extract_topology(&model, &result.assignments, &var_names, &net_names)
        } else {
            core_types::TopologyGraph {
                net_topologies: HashMap::new(),
            }
        };

        // Build Python return value.
        let d = PyDict::new(py);
        d.set_item(
            "status",
            match result.status {
                SolverStatus::Satisfiable => "sat",
                SolverStatus::Unsatisfiable => "unsat",
                SolverStatus::Unknown => "unknown",
            },
        )?;

        // Variable assignments: name → bool
        let py_assignments = PyDict::new(py);
        for (idx, val) in &result.assignments {
            if *idx < var_names.len() {
                py_assignments.set_item(&var_names[*idx], *val)?;
            }
        }
        d.set_item("assignments", py_assignments)?;

        // Topology graph: net_name → {uses_channels, path_graph, total_length_estimate}
        let py_topology = PyDict::new(py);
        for (net_name, net_topo) in &topology.net_topologies {
            let entry = PyDict::new(py);
            entry.set_item("uses_channels", net_topo.uses_channels.clone())?;
            let py_path: Vec<(String, String)> = net_topo.path_graph.clone();
            entry.set_item("path_graph", py_path)?;
            entry.set_item("total_length_estimate", net_topo.total_length_estimate)?;
            py_topology.set_item(net_name, entry)?;
        }
        d.set_item("topology_graph", py_topology)?;

        d.set_item("solver_time_ms", result.solver_time_ms)?;
        d.set_item("num_vars", result.num_vars)?;
        d.set_item("num_clauses", result.num_clauses)?;

        // Unsat core
        let py_core = PyList::new(py, Vec::<Py<PyAny>>::new())?;
        for idx in &result.unsat_core {
            py_core.append(idx)?;
        }
        d.set_item("unsat_core", py_core)?;

        // Solver statistics.
        if let Some(ref stats) = result.solver_stats {
            let py_stats = PyDict::new(py);
            py_stats.set_item("conflicts", stats.conflicts)?;
            py_stats.set_item("decisions", stats.decisions)?;
            py_stats.set_item("propagations", stats.propagations)?;
            py_stats.set_item("decision_level_histogram",
                stats.decision_level_histogram.to_vec())?;
            py_stats.set_item("unsat_core_size", stats.unsat_core_size)?;
            py_stats.set_item("variable_count", stats.variable_count)?;
            py_stats.set_item("clause_count", stats.clause_count)?;
            py_stats.set_item("cpu_solve_time_ms", stats.cpu_solve_time_ms)?;
            let clause_to_var_ratio = if stats.variable_count > 0 {
                stats.clause_count as f64 / stats.variable_count as f64
            } else {
                0.0
            };
            py_stats.set_item("clause_to_var_ratio", clause_to_var_ratio)?;
            let solve_throughput = if stats.cpu_solve_time_ms > 0.001 {
                (stats.variable_count * stats.clause_count) as f64 / stats.cpu_solve_time_ms
            } else {
                0.0
            };
            py_stats.set_item("solve_throughput", solve_throughput)?;
            d.set_item("solver_stats", py_stats)?;
        }

        // Var-to-net mapping.
        //
        // NOTE: cnf.var_to_net is 42M usizes for the full production board -- a
        // ~336 MB Rust Vec that serializes to a ~1.2 GB Python list of ints.
        // Nothing downstream reads it (grep '.var_to_net' across the repo: zero
        // Python consumers outside this assignment site and the type annotation),
        // so we elide the clone and pass an empty list instead.  The original
        // intent (docs/plans/2026-06-28-007-feat-routability-gradient-signal-plan.md
        // U3, per-net routability scoring) was never implemented.  When it is,
        // it should receive a compact format (flat bytes, not a Python list of
        // 42M individual int objects).
        //
        // See docs/evidence/2026-08-07-router-oom-diagnosis.md §5.
        d.set_item("var_to_net", Vec::<usize>::new())?;

        Ok(d.into())
    }

    /// Audit solver output against the constraint model itself.
    ///
    /// Validates that every CapacityConstraint, DiffPairConstraint, and
    /// LayerConstraint in the input model is satisfied by the solver's
    /// assignments.  Returns a list of violation dicts (empty = clean).
    #[pyfunction]
    fn audit_result(
        py: Python<'_>,
        variables: &Bound<'_, PyList>,
        constraints: &Bound<'_, PyList>,
        assignments: &Bound<'_, PyDict>,
        _net_names: Vec<String>,
    ) -> PyResult<Py<PyList>> {
        let py_vars: Vec<Py<PyAny>> = variables.iter().map(|v| v.into()).collect();
        let py_cons: Vec<Py<PyAny>> = constraints.iter().map(|c| c.into()).collect();

        let model = crate::types_py_bridge::model_from_python(py_vars, py_cons, py)?;

        // Build var_names from model
        let var_names: Vec<String> = model.variables.iter().map(|v| match v {
            core_types::InternalVariable::NetChannel { name, .. } => name.clone(),
            core_types::InternalVariable::NetLayer { name, .. } => name.clone(),
            core_types::InternalVariable::Via { name, .. } => name.clone(),
            core_types::InternalVariable::Ordering { name, .. } => name.clone(),
        }).collect();

        let name_to_idx: std::collections::HashMap<String, usize> = var_names
            .iter().enumerate().map(|(i, n)| (n.clone(), i)).collect();

        // Build assignments hashmap from Python dict
        let mut assignment_map: std::collections::HashMap<usize, bool> = std::collections::HashMap::new();
        for (py_name, py_val) in assignments.iter() {
            let name: String = py_name.extract()?;
            let val: bool = py_val.extract()?;
            if let Some(&idx) = name_to_idx.get(&name) {
                assignment_map.insert(idx, val);
            }
        }

        let result = core_types::TopologyResult {
            status: core_types::SolverStatus::Satisfiable,
            num_vars: 0,
            num_clauses: 0,
            assignments: assignment_map,
            unsat_core: Vec::new(),
            solver_time_ms: 0.0,
            solver_stats: None,
        };

        let violations = audit::audit_constraints(&model, &result, &var_names);

        let py_list = PyList::new(py, Vec::<Py<PyAny>>::new())?;
        for v in &violations {
            let d = PyDict::new(py);
            match v {
                audit::AuditViolation::Capacity { channel_id, max_nets, actual_count, violating_vars } => {
                    d.set_item("type", "capacity")?;
                    d.set_item("channel_id", channel_id.clone())?;
                    d.set_item("max_nets", *max_nets)?;
                    d.set_item("actual_count", *actual_count)?;
                    d.set_item("violating_vars", violating_vars.clone())?;
                }
                audit::AuditViolation::DiffPairMismatch { channel_id, p_var, n_var, p_value, n_value } => {
                    d.set_item("type", "diff_pair")?;
                    d.set_item("channel_id", channel_id.clone())?;
                    d.set_item("p_var", p_var.clone())?;
                    d.set_item("n_var", n_var.clone())?;
                    d.set_item("p_value", *p_value)?;
                    d.set_item("n_value", *n_value)?;
                }
                audit::AuditViolation::LayerViolation { var_name, expected, actual } => {
                    d.set_item("type", "layer")?;
                    d.set_item("var_name", var_name.clone())?;
                    d.set_item("expected", *expected)?;
                    d.set_item("actual", *actual)?;
                }
                audit::AuditViolation::UnexplainedUnsat => {
                    d.set_item("type", "unexplained_unsat")?;
                }
                audit::AuditViolation::NoAssignmentForVar(vname) => {
                    d.set_item("type", "no_assignment")?;
                    d.set_item("var_name", vname.clone())?;
                }
            }
            py_list.append(d)?;
        }
        Ok(py_list.into())
    }

    /// Python module entry point.
    #[pymodule]
    fn temper_rust_router(m: &Bound<'_, PyModule>) -> PyResult<()> {
        // Register constraint model types.

        // Register the solver entry point and constraint auditor.
        m.add_function(wrap_pyfunction!(solve_topology_rust, m)?)?;
        m.add_function(wrap_pyfunction!(audit_result, m)?)?;
        m.add_function(wrap_pyfunction!(auto_extract_loops_rust, m)?)?;
        m.add_function(wrap_pyfunction!(classify_component_rs, m)?)?;
        m.add_function(wrap_pyfunction!(parse_capacitance_rs, m)?)?;
        m.add_function(wrap_pyfunction!(astar_kernel_3d_py, m)?)?;
        m.add_function(wrap_pyfunction!(line_of_sight_py, m)?)?;

        // Wave-4 Phase B: the router_v6/net_ordering kernels.
        crate::net_ordering::register(m)?;
        // Wave-4 Phase 3: the router_v6/layer_assignment kernel.
        crate::layer_assignment::register(m)?;

        // Wave-4: the router_v6 terminal-tree slice (terminal_extraction,
        // terminal_tree).
        crate::terminal_planning::register(m)?;
        // Wave-4: the router_v6 Theta* cluster (_astar_theta_star).
        crate::theta_star::register(m)?;

        // Phase E E5 (Rust Orchestration Engine plan 2026-08-09-001): the
        // net-batching batch-loop orchestration primitives.
        crate::net_batching::register(m)?;
        Ok(())
    }

    /// Python-callable A* kernel (U5) — the Rust port of the retired JIT
    /// kernel (`_astar_kernel_3d`). Inputs mirror the retired kernel's
    /// arguments; congestion/thermal fields are passed as little-
    /// endian float32 byte buffers (None = absent). Returns (path, iterations).
    ///
    /// S8 (same-net wiring): when `grid_bytes` is supplied, the kernel does
    /// inline bounds + occupancy checks per expansion instead of consulting
    /// the validity tensor.  `net_id` controls the same-net predicate
    /// (cells with this value are traversable at 0.25× cost; foreign cells
    /// with any other non-zero value are BLOCKED).  When `grid_bytes` is
    /// None, behaviour is identical to before S8 (validity-tensor path).
    #[pyfunction]
    #[pyo3(signature = (
        start_idx, goal_idx, rows, cols, validity_bytes, max_iterations,
        congestion_bytes=None, congestion_weight=1.0, max_congestion_cost=100.0,
        thermal_bytes=None, thermal_weight=0.0,
        grid_bytes=None, net_id=-1i64, corridor_mask_bytes=None,
    ))]
    #[expect(
        clippy::too_many_arguments,
        reason = "Pyo3 boundary mirrors the Python signature 1:1; a config struct would change the FFI"
    )]
    fn astar_kernel_3d_py(
        start_idx: i64,
        goal_idx: i64,
        rows: usize,
        cols: usize,
        validity_bytes: Vec<u8>,
        max_iterations: u64,
        congestion_bytes: Option<Vec<u8>>,
        congestion_weight: f32,
        max_congestion_cost: f32,
        thermal_bytes: Option<Vec<u8>>,
        thermal_weight: f32,
        grid_bytes: Option<Vec<u8>>,
        net_id: i64,
        corridor_mask_bytes: Option<Vec<u8>>,
    ) -> (Vec<i32>, u64) {
        let n_cells = rows * cols;
        let congestion = congestion_bytes.map(|b| crate::f32s_from_le_bytes(&b, n_cells));
        let thermal = thermal_bytes.map(|b| crate::f32s_from_le_bytes(&b, n_cells));
        // SAFETY: grid_bytes / corridor_mask_bytes are Vec<u8> owned by
        // this frame; the AstarInput borrows them for the duration of
        // astar_kernel_3d and they are dropped when this frame returns.
        let grid_slice: Option<&[i8]> = grid_bytes.as_ref().map(|b| {
            // Reinterpret the u8 bytes as i8 — both are single-byte, no
            // alignment issues, and the source is a contiguous Vec<u8>.
            // This is the same pattern line_of_sight_py already uses
            // (grid_bytes is int8-encoded there too).
            unsafe { std::slice::from_raw_parts(b.as_ptr() as *const i8, b.len()) }
        });
        let corridor_slice: Option<&[u8]> = corridor_mask_bytes.as_deref();
        let out = temper_rust_router_core::astar::astar_kernel_3d(&AstarInput {
            start_idx,
            goal_idx,
            rows,
            cols,
            validity: &validity_bytes,
            max_iterations,
            congestion: congestion.as_deref(),
            congestion_weight,
            max_congestion_cost,
            thermal: thermal.as_deref(),
            thermal_weight,
            grid: grid_slice,
            net_id,
            corridor_mask: corridor_slice,
        });
        (out.path, out.iterations)
    }

    /// Python-callable Bresenham line-of-sight check (U5) — the Rust port of
    /// the retired JIT LOS kernel. `grid_bytes` is a
    /// row-major (height, width) int8 occupancy grid.
    #[pyfunction]
    #[pyo3(signature = (x0, y0, x1, y1, grid_bytes, width_cells, height_cells, net_id))]
    #[expect(
        clippy::too_many_arguments,
        reason = "Pyo3 boundary mirrors the Python signature 1:1; a config struct would change the FFI"
    )]
    fn line_of_sight_py(
        x0: i64,
        y0: i64,
        x1: i64,
        y1: i64,
        grid_bytes: Vec<u8>,
        width_cells: i64,
        height_cells: i64,
        net_id: i64,
    ) -> bool {
        let grid = &grid_bytes;
        let (w, h) = (width_cells, height_cells);
        let (mut x, mut y) = (x0, y0);
        let (dx, dy) = ((x1 - x0).abs(), (y1 - y0).abs());
        let sx = if x0 < x1 { 1 } else { -1 };
        let sy = if y0 < y1 { 1 } else { -1 };
        let mut err = dx - dy;
        loop {
            if x < 0 || x >= w || y < 0 || y >= h {
                return false;
            }
            let cell = grid.get((y * w + x) as usize).copied().unwrap_or(1) as i64;
            if cell != 0 && cell != net_id {
                return false;
            }
            if x == x1 && y == y1 {
                return true;
            }
            let e2 = 2 * err;
            if e2 > -dy {
                err -= dy;
                x += sx;
            }
            if e2 < dx {
                err += dx;
                y += sy;
            }
        }
    }

    /// Python-callable entry point for loop extraction via JSON.
    #[pyfunction]
    fn auto_extract_loops_rust(
        py: Python<'_>,
        json_str: &str,
    ) -> PyResult<String> {
        crate::loop_extractor::bridge::auto_extract_loops_rust(py, json_str)
    }

    // -----------------------------------------------------------------------
    // Wave-4: Python-compatible classification kernel
    // (temper-rust-router-core/src/loop_extractor/classify_py.rs) -- the
    // bit-identical port of core/loop_extractor.py::classify_component and
    // _parse_capacitance, exposed for the delegation shim and the
    // differential suite (tests/core/test_loop_extractor_rust_differential.py).
    // -----------------------------------------------------------------------

    /// A finite-or-saturating f64 for JSON: finite values serialize as JSON
    /// numbers; `inf`/`-inf` serialize as the strings `"inf"`/`"-inf"` (JSON
    /// has no infinity literal; CPython `float()` saturation is preserved).
    struct F64Json(f64);

    impl serde::Serialize for F64Json {
        fn serialize<S: serde::Serializer>(&self, ser: S) -> Result<S::Ok, S::Error> {
            if self.0.is_finite() {
                ser.serialize_f64(self.0)
            } else if self.0 > 0.0 {
                ser.serialize_str("inf")
            } else {
                ser.serialize_str("-inf")
            }
        }
    }

    /// Python-callable: classify a component using the bit-identical port of
    /// `loop_extractor.classify_component`. Input: JSON dict
    /// `{"ref", "footprint", "value", "mpn"}`. Output: JSON dict
    /// `{"ref", "category", "subcategory", "confidence"}`. Raises `ValueError`
    /// for a malformed capacitance value, mirroring CPython `float()`.
    #[pyfunction]
    fn classify_component_rs(component_json: &str) -> PyResult<String> {
        use serde::Deserialize;

        #[derive(Deserialize)]
        struct ClassifyInput {
            r#ref: String,
            #[serde(default)]
            footprint: String,
            #[serde(default)]
            value: String,
            #[serde(default)]
            mpn: String,
        }

        #[derive(serde::Serialize)]
        struct ClassifyOutput {
            r#ref: String,
            category: String,
            subcategory: Option<String>,
            confidence: f64,
        }

        let input: ClassifyInput = serde_json::from_str(component_json).map_err(|e| {
            PyErr::new::<pyo3::exceptions::PyValueError, _>(format!(
                "Failed to parse component JSON: {e}"
            ))
        })?;

        let comp = CompInfo {
            ref_des: input.r#ref,
            footprint: input.footprint,
            mpn: input.mpn,
            value: input.value,
        };

        match classify_component_py(&comp) {
            Ok(cls) => {
                let out = ClassifyOutput {
                    r#ref: cls.component_ref,
                    category: cls.category,
                    subcategory: cls.subcategory,
                    confidence: cls.confidence,
                };
                Ok(serde_json::to_string(&out).map_err(|e| {
                    PyErr::new::<pyo3::exceptions::PyValueError, _>(format!(
                        "serialize output: {e}"
                    ))
                })?)
            }
            Err(MalformedNumber) => Err(pyo3::exceptions::PyValueError::new_err(
                "could not convert string to float (malformed capacitance value)",
            )),
        }
    }

    /// Python-callable: parse a capacitance value (bit-identical port of
    /// `loop_extractor._parse_capacitance`). Output: JSON dict `{"uf": <f64>}`
    /// or `{"uf": null}`. Raises `ValueError` where CPython `float()` raises.
    #[pyfunction]
    fn parse_capacitance_rs(value: &str) -> PyResult<String> {
        #[derive(serde::Serialize)]
        struct ParseOut {
            uf: Option<F64Json>,
        }

        match parse_capacitance_py(value) {
            Ok(parsed) => {
                let out = ParseOut {
                    uf: parsed.map(F64Json),
                };
                Ok(serde_json::to_string(&out).map_err(|e| {
                    PyErr::new::<pyo3::exceptions::PyValueError, _>(format!(
                        "serialize output: {e}"
                    ))
                })?)
            }
            Err(MalformedNumber) => Err(pyo3::exceptions::PyValueError::new_err(
                "could not convert string to float (malformed capacitance value)",
            )),
        }
    }
}
