//! The `wasm32` test registry for `temper-constraint-compiler`.
//!
//! Generated by `scripts/gen_wasm_test_registry.py`; run it after adding a
//! test to any listed module, and `--check` gates drift in CI.
//!
//! `cargo test`'s libtest harness cannot target `wasm32-unknown-unknown`,
//! so the Worker tier calls each test function individually instead of
//! running a test binary.  This module is the flat, indexable list of them.
//!
//! Only modules that survive `--no-default-features` appear here.  Tests
//! inside `#[cfg(feature = "python")]` modules are structurally absent
//! from a `wasm32` build and cannot be registered here at all.
//!
//! Two exclusion classes apply here, both structural:
//!
//! * `#[cfg(feature = "python")]` modules -- `pcl_contracts` and
//!   `pyo3_bridge`, plus `constraints::py`, which are the pyo3
//!   boundary and do not exist in a `--no-default-features` build.
//! * `proptest` modules use a dev-dependency, which is not linked into
//!   the ordinary (non-test) build this registry compiles into.
//!
//! `scripts/gen_wasm_test_registry.py --crate temper-constraint-compiler
//! --census` prints the full module census with per-module counts.
//!
//! ## Families
//!
//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`
//! feature, as in `temper-drc-rs`.  One family
//! (`constraint-compiler`): the lowering tiers are a flat pipeline
//! with no taxonomy to shard along.

/// A single test: its fully qualified name and a nullary callable.
///
/// Failure is signalled by panicking, exactly as under libtest.  On
/// `wasm32-unknown-unknown` a panic aborts (the target has no unwinding on
/// stable), which surfaces to the host as a WebAssembly trap -- so the
/// runner catches the trap rather than a `Result`.
pub type WasmTest = (&'static str, fn());

/// All 1648 eligible tests, in a stable order.  Each entry is
/// gated on the per-family `wasm-registry-<family>` feature; enable
/// all families (`wasm-test-registry`) or individual ones.
pub const ALL: &[&[WasmTest]] = &[
    #[cfg(feature = "wasm-registry-constraint-compiler")] crate::constraints::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-constraint-compiler")] crate::constraints::report::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-constraint-compiler")] crate::constraints::slot::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-constraint-compiler")] crate::constraints::validate::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-constraint-compiler")] crate::desugar_tier0::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-constraint-compiler")] crate::desugar_tier1::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-constraint-compiler")] crate::ir_tier0::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-constraint-compiler")] crate::ir_tier1::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-constraint-compiler")] crate::property_campaigns::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-constraint-compiler")] crate::provenance::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-constraint-compiler")] crate::type_lattice::tests::WASM_TESTS,
];

/// Total number of registered tests *in the currently-selected families*.
pub fn count() -> usize {
    ALL.iter().map(|m| m.len()).sum()
}

/// The test at `index` in the flattened registry.
pub fn get(index: usize) -> Option<&'static WasmTest> {
    let mut remaining = index;
    for module in ALL {
        if remaining < module.len() {
            return Some(&module[remaining]);
        }
        remaining -= module.len();
    }
    None
}
