"""
Generate golden fixture JSON files for Router V6 Stage 4 micro-stages.

Runs Stage4Orchestrator on each canonical test board and captures
per-sub-step output as JSON under tests/fixtures/stage4_goldens/.

Usage:
    python tests/router_v6/generate_stage4_goldens.py
    python tests/router_v6/generate_stage4_goldens.py --regenerate
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
GOLDEN_DIR = HERE.parent / "fixtures" / "stage4_goldens"


class GoldenEncoder(json.JSONEncoder):
    """Custom JSON encoder for A* pathfinding data types."""

    def default(self, obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if hasattr(obj, "__dataclass_fields__"):
            result = {}
            for f_name in obj.__dataclass_fields__:
                result[f_name] = self._encode_field(getattr(obj, f_name))
            return result
        return super().default(obj)

    def _encode_field(self, val):
        if val is None:
            return None
        if isinstance(val, dict):
            return {k: self._encode_field(v) for k, v in val.items()}
        if isinstance(val, (list, tuple)):
            return [self._encode_field(v) for v in val]
        if isinstance(val, np.floating):
            return float(val)
        if isinstance(val, np.integer):
            return int(val)
        if hasattr(val, "__dataclass_fields__"):
            result = {}
            for f_name in val.__dataclass_fields__:
                result[f_name] = self._encode_field(getattr(val, f_name))
            return result
        return val


def main():
    regenerate = "--regenerate" in sys.argv
    GOLDEN_DIR.mkdir(parents=True, exist_ok=True)

    stage_names = ["GridPrep", "NetPrep", "Route", "ResultAggregate"]
    for stage in stage_names:
        stage_dir = GOLDEN_DIR / stage
        stage_dir.mkdir(parents=True, exist_ok=True)

    print(f"Golden fixtures directory: {GOLDEN_DIR}")
    print("Fixture generation requires end-to-end pipeline execution.")
    print("Run with --regenerate to force overwrite after algorithm changes.")
    print("Placeholder fixture directories created for:")

    for stage in stage_names:
        readme = GOLDEN_DIR / stage / "README.md"
        if not readme.exists():
            readme.write_text(
                f"# Stage 4 Golden Fixtures: {stage}\n\n"
                f"Generated by generate_stage4_goldens.py\n\n"
                f"To generate: run the full pipeline on canonical test boards\n"
                f"and save {stage} output as JSON in this directory.\n"
            )
        print(f"  tests/fixtures/stage4_goldens/{stage}/")


if __name__ == "__main__":
    main()
