"""Golden fixture parity tests for Router V6 Stage 3 topology stage.

Loads committed JSON fixtures and asserts the corrected Python topology
solver produces output consistent with the golden data on each canonical
board.  These fixtures must be generated by `generate_stage3_goldens.py`
before the tests will run.

When the Rust solver is later integrated (via TEMPER_SAT_BACKEND=rust),
this same test suite validates the Rust solver against the same golden
fixtures — the correctness gate for origin requirement R5.

Tolerances: coordinate equality to 1e-6, exact integer equality for
variable/clause/constraint counts.

Origin: U2 of docs/plans/2026-06-28-001-feat-router-v6-rust-topology-plan.md
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
GOLDEN_DIR = HERE.parent / "fixtures" / "stage3_goldens"


def _available_board_names() -> list[str]:
    """List board names that have golden fixtures."""
    names: list[str] = []
    if GOLDEN_DIR.exists():
        for d in sorted(GOLDEN_DIR.iterdir()):
            if d.is_dir() and (d / "stage3_topology.json").exists():
                names.append(d.name)
    return names


AVAILABLE_BOARDS = _available_board_names()


def _run_stage3_for_board(board_name: str) -> dict:
    """Run the topology stage on a canonical board and return output as a dict.

    Mirrors the generation path in `generate_stage3_goldens.py` so fixture
    generation and validation use the same code path.
    """
    from temper_placer.io.kicad_parser import parse_kicad_pcb_v6
    from temper_placer.router_v6.channel_skeleton import ChannelSkeleton
    from temper_placer.router_v6.channel_widths import ChannelWidths
    from temper_placer.router_v6.constraint_model import (
        ConstraintModel,
        ModelBuilder,
    )
    from temper_placer.router_v6.diff_pair_inference import infer_differential_pairs
    from temper_placer.router_v6.sat_model import (
        build_sat_model,
        populate_sat_from_constraints,
    )
    from temper_placer.router_v6.stage0_data import ParsedPCB
    from temper_placer.router_v6.stage2_orchestrator import Stage2Orchestrator
    from temper_placer.router_v6.topology_extraction import extract_topology_solution
    from temper_placer.router_v6.topology_solver import solve_topology

    board_path = GOLDEN_DIR / board_name / "stage3_topology.json"
    with open(board_path) as f:
        fixture = json.load(f)

    source_path = fixture.get("board_path")
    assert source_path and Path(source_path).exists(), (
        f"Board file not found: {source_path}"
    )
    pcb: ParsedPCB = parse_kicad_pcb_v6(str(source_path))

    orch = Stage2Orchestrator(verbose=False)
    stage2_state = orch.run(pcb, escape_vias=[])

    skeletons: dict[str, ChannelSkeleton] = stage2_state.channel_skeletons or {}
    widths: dict[str, ChannelWidths] = stage2_state.channel_widths or {}

    diff_pairs = infer_differential_pairs([net.name for net in pcb.nets])
    builder = ModelBuilder(
        skeletons=skeletons,
        nets=pcb.nets,
        channel_widths=widths,
        design_rules=pcb.design_rules,
        diff_pairs=diff_pairs,
        pcb=pcb,
    )
    constraint_model: ConstraintModel = builder.build()

    sat_model = build_sat_model()
    net_names = [net.name for net in pcb.nets]
    populate_sat_from_constraints(sat_model, constraint_model, net_names)
    solution = solve_topology(sat_model)

    topology_graph = None
    if solution.is_satisfiable:
        topology_graph = extract_topology_solution(solution, net_names)

    return {
        "constraint_model": {
            "variable_count": constraint_model.variable_count,
            "constraint_count": constraint_model.constraint_count,
            "net_channel_var_count": len(constraint_model.net_channel_vars),
            "via_var_count": len(constraint_model.via_vars),
        },
        "sat_model": {
            "variable_count": sat_model.variable_count,
            "clause_count": sat_model.clause_count,
        },
        "solution_status": solution.status.value,
        "solution_satisfiable": solution.is_satisfiable,
        "topology_net_count": (
            len(topology_graph.net_topologies) if topology_graph else 0
        ),
    }


def _load_fixture(board_name: str) -> dict | None:
    path = GOLDEN_DIR / board_name / "stage3_topology.json"
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return None


if not AVAILABLE_BOARDS:
    pytest.skip(
        "No Stage 3 golden fixtures available — run "
        "tests/router_v6/generate_stage3_goldens.py first",
        allow_module_level=True,
    )


@pytest.mark.parametrize("board_name", AVAILABLE_BOARDS)
def test_stage3_variable_count(board_name: str) -> None:
    """SAT model variable count matches golden fixture."""
    fixture = _load_fixture(board_name)
    assert fixture is not None
    actual = _run_stage3_for_board(board_name)

    expected = fixture["sat_model"]["variable_count"]
    got = actual["sat_model"]["variable_count"]
    assert got == expected, (
        f"{board_name}: SAT variable count {got} != golden {expected}"
    )


@pytest.mark.parametrize("board_name", AVAILABLE_BOARDS)
def test_stage3_clause_count(board_name: str) -> None:
    """SAT model clause count matches golden fixture."""
    fixture = _load_fixture(board_name)
    actual = _run_stage3_for_board(board_name)

    expected = fixture["sat_model"]["clause_count"]
    got = actual["sat_model"]["clause_count"]
    assert got == expected, (
        f"{board_name}: SAT clause count {got} != golden {expected}"
    )


@pytest.mark.parametrize("board_name", AVAILABLE_BOARDS)
def test_stage3_constraint_model_counts(board_name: str) -> None:
    """Constraint model variable/constraint counts match golden fixture."""
    fixture = _load_fixture(board_name)
    actual = _run_stage3_for_board(board_name)

    fc = fixture["constraint_model"]
    ac = actual["constraint_model"]
    assert ac["variable_count"] == fc["variable_count"]
    assert ac["constraint_count"] == fc["constraint_count"]
    assert ac["net_channel_var_count"] == fc["net_channel_var_count"]
    assert ac["via_var_count"] == fc["via_var_count"]


@pytest.mark.parametrize("board_name", AVAILABLE_BOARDS)
def test_stage3_solution_status(board_name: str) -> None:
    """Solution status (SAT/UNSAT) matches golden fixture."""
    fixture = _load_fixture(board_name)
    actual = _run_stage3_for_board(board_name)

    assert actual["solution_status"] == fixture["solution"]["status"], (
        f"{board_name}: solution status {actual['solution_status']} "
        f"!= golden {fixture['solution']['status']}"
    )
    assert actual["solution_satisfiable"] == fixture["solution"]["is_satisfiable"]
    assert actual["topology_net_count"] == len(
        fixture.get("topology_graph", {}).get("net_topologies", {}) if fixture.get("topology_graph") else {}
    )
