"""Retired oracle-comparison differential for the terminal-tree planner
(``plan_terminal_tree``).

The pinned oracle ``tests/router_v6/_terminal_tree_py_oracle.py`` was retired
by FREEZE on 2026-08-21 (batch 3): its golden vectors are baked into
``terminal_planning.rs``'s own ``frozen_terminal_tree_tests`` module
(``frozen_terminal_tree_matches_golden_corpus`` /
``frozen_terminal_tree_corpus_is_non_vacuous``, 92 cases over the PURE Rust
core -- no Python interpreter needed), generated by
``scripts/oracle_freeze_specs/terminal_tree.py``.

The oracle-comparison tests this file used to carry are fully superseded by
that frozen corpus. What remains below is a single wiring check: the
pyo3-visible ``plan_terminal_tree_py`` the production shim delegates through
must still be callable and must return the Rust kernel's output shape on a
representative input (including the identity tie-break case).
"""

from __future__ import annotations

import temper_rust_router as _trr

RS_PLAN = _trr.plan_terminal_tree_py


def _pad_wire(ref: str, index: int, x: float, y: float, layers=(0,)) -> tuple:
    x, y = float(x), float(y)
    return (ref, str(index), "NET", x, y, list(layers), x, y)


def test_shipped_kernel_callable_via_pyo3():
    """The pyo3-visible ``plan_terminal_tree_py`` the production shim
    delegates to must exist and return the expected plan shape on a
    representative input -- a Stage-7 wiring check, not a differential."""
    pads = [
        _pad_wire("U1", 2, 10.0, 0.0),
        _pad_wire("U1", 1, 0.0, 0.0),
        _pad_wire("U1", 3, 0.0, 10.0),
    ]
    plan = RS_PLAN(pads)
    root, edges = plan
    # Root is the lexicographically smallest identity ("U1"/"1").
    assert root[1] == "1"
    assert len(edges) == 2


def test_shipped_kernel_identity_tie_break_via_pyo3():
    """B and C are both distance 5 from A; identity order must pick B."""
    pads = [
        _pad_wire("A", 1, 0.0, 0.0),
        _pad_wire("B", 1, 5.0, 0.0),
        _pad_wire("C", 1, 0.0, 5.0),
    ]
    _root, edges = RS_PLAN(pads)
    assert edges[0][0][0] == "A"
    assert edges[0][1][0] == "B"


def test_shipped_kernel_empty_input_raises():
    try:
        RS_PLAN([])
    except ValueError as exc:
        assert "terminal tree requires at least one pad" in str(exc)
    else:
        raise AssertionError("empty pad list must raise")
