"""Property-based tests for Router V6 output validity invariants.

Tests invariants of ParsedPCB and RoutingResults strategies and
RouterV6Result construction, enforcing shape and field correctness.
"""

from __future__ import annotations

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import seed as hseed
from hypothesis import strategies as st

from temper_placer.router_v6.astar_pathfinding import PathfindingResult
from temper_placer.router_v6.bottleneck_analysis import BottleneckAnalysis
from temper_placer.router_v6.constraint_model import ConstraintModel
from temper_placer.router_v6.pipeline import (
    RouterV6Result,
    Stage2Output,
    Stage3Output,
    Stage4Output,
)
from temper_placer.router_v6.routing_demand import RoutingDemand
from temper_placer.router_v6.routing_results import RoutingResults
from temper_placer.router_v6.sat_model import SATModel
from temper_placer.router_v6.stage0_data import ParsedPCB
from temper_placer.router_v6.topology_extraction import TopologyGraph
from temper_placer.router_v6.topology_solver import SolverStatus, TopologicalSolution
from temper_placer.router_v6.trace_width_assignment import TraceWidthAssignment
from temper_placer.router_v6.via_placement import ViaPlacement

from .router_v6_property_strategies import parsed_pcb, routing_results

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_minimal_stage2() -> Stage2Output:
    """Build a minimal Stage2Output with empty/default fields."""
    return Stage2Output(
        obstacle_maps={},
        routing_spaces={},
        skeletons={},
        channel_widths={},
        occupancy_grids={},
        layer_capacities={},
        routing_demand=RoutingDemand(
            total_nets=0,
            routable_nets=0,
            total_pins=0,
            signal_nets=0,
            power_nets=0,
            diff_pair_nets=0,
            avg_pins_per_net=0.0,
            max_pins_per_net=0,
        ),
        bottleneck_analysis=BottleneckAnalysis(
            bottlenecks=[], total_capacity=0, total_demand=0
        ),
    )


def _make_minimal_stage3() -> Stage3Output:
    """Build a minimal Stage3Output with empty/default fields."""
    return Stage3Output(
        constraint_model=ConstraintModel(),
        sat_model=SATModel(variables=[], clauses=[]),
        solution=TopologicalSolution(
            status=SolverStatus.SATISFIABLE, assignment={}, solver_time_ms=0.0
        ),
        topology_graph=TopologyGraph(net_topologies={}),
    )


def _make_minimal_stage4(results: RoutingResults) -> Stage4Output:
    """Build a Stage4Output carrying the given RoutingResults."""
    return Stage4Output(
        pathfinding_result=PathfindingResult(routed_paths={}, failed_nets=[]),
        via_placement=ViaPlacement(vias=[]),
        width_assignment=TraceWidthAssignment(assignments={}),
        routing_results=results,
    )


def _draw_parsed_pcb_from_seed(seed_val: int) -> ParsedPCB:
    """Deterministically draw a ParsedPCB from a fixed seed.

    Captures the result via a closure to satisfy Hypothesis's requirement
    that ``@given``-decorated functions not return a value.
    """
    result: list[ParsedPCB] = []

    @hseed(seed_val)
    @settings(max_examples=1, database=None)
    @given(data=st.data())
    def _draw(data: st.DataObject) -> None:
        result.append(data.draw(parsed_pcb()))

    _draw()
    return result[0]


# ---------------------------------------------------------------------------
# R1: Stage output shape invariants
# ---------------------------------------------------------------------------


@given(pcb=parsed_pcb())
@settings(max_examples=100, deadline=30000)
@pytest.mark.property
def test_parsed_pcb_valid_structure(pcb: ParsedPCB) -> None:
    """ParsedPCB generated by strategy has valid structure."""
    assert isinstance(pcb, ParsedPCB)
    assert pcb.board.width > 0
    assert pcb.board.height > 0
    assert len(pcb.components) >= 2
    assert pcb.design_rules is not None
    assert pcb.stackup is not None
    assert len(pcb.nets) >= 1
    assert pcb.design_rules.default_clearance_mm > 0
    assert pcb.stackup.layer_count >= 2


@given(results=routing_results())
@settings(max_examples=100, deadline=30000)
@pytest.mark.property
def test_routing_results_valid_structure(results: RoutingResults) -> None:
    """RoutingResults generated by strategy has valid structure."""
    assert isinstance(results, RoutingResults)
    assert isinstance(results.compiled_routes, dict)
    assert isinstance(results.failed_nets, list)
    assert results.success_count >= 0
    assert results.failure_count >= 0
    # success_count = len(compiled_routes) + plane_net_count
    assert results.success_count >= len(results.compiled_routes)
    assert results.failure_count == len(results.failed_nets)
    assert results.success_count + results.failure_count >= 1


# ---------------------------------------------------------------------------
# R1 (cont.): Idempotence — same seed → same shape
# ---------------------------------------------------------------------------


@given(seed_val=st.integers(0, 9999))
@settings(
    max_examples=50,
    deadline=30000,
    suppress_health_check=[HealthCheck.nested_given],
)
@pytest.mark.property
def test_strategy_idempotent_shape(seed_val: int) -> None:
    """Drawing ParsedPCB twice with the same seed produces same shape."""
    pcb1 = _draw_parsed_pcb_from_seed(seed_val)
    pcb2 = _draw_parsed_pcb_from_seed(seed_val)

    assert len(pcb1.components) == len(pcb2.components)
    assert len(pcb1.nets) == len(pcb2.nets)
    assert pcb1.board.width == pcb2.board.width
    assert pcb1.board.height == pcb2.board.height
    assert pcb1.stackup.layer_count == pcb2.stackup.layer_count
    assert len(pcb1.design_rules.net_classes) == len(pcb2.design_rules.net_classes)
    assert pcb1.design_rules.default_clearance_mm == pcb2.design_rules.default_clearance_mm


# ---------------------------------------------------------------------------
# R2: RouterV6Result fields populated, completion_rate in [0,1]
# ---------------------------------------------------------------------------


@given(
    pcb=parsed_pcb(),
    results=routing_results(),
)
@settings(max_examples=100, deadline=30000)
@pytest.mark.property
def test_router_v6_result_invariants(
    pcb: ParsedPCB,
    results: RoutingResults,
) -> None:
    """RouterV6Result constructed from generated inputs has valid fields."""
    stage2 = _make_minimal_stage2()
    stage3 = _make_minimal_stage3()
    stage4 = _make_minimal_stage4(results)

    result = RouterV6Result(
        pcb=pcb,
        escape_vias=[],
        stage2=stage2,
        stage3=stage3,
        stage4=stage4,
        manufacturing_report=None,
        runtime_seconds=1.5,
    )

    # All fields populated
    assert result.pcb is not None
    assert isinstance(result.escape_vias, list)
    assert result.stage2 is not None
    assert result.stage3 is not None
    assert result.stage4 is not None
    assert isinstance(result.runtime_seconds, float)
    assert result.runtime_seconds >= 0

    # success_count + failure_count matches net data
    assert result.success_count >= 0
    assert result.failure_count >= 0
    total_nets = result.success_count + result.failure_count
    assert total_nets == len(results.compiled_routes) + len(results.failed_nets) + results.plane_net_count

    # completion_rate in [0, 1]
    assert 0.0 <= result.completion_rate <= 1.0
    if total_nets > 0:
        assert result.completion_rate == result.success_count / total_nets
    else:
        assert result.completion_rate == 0.0
