//! The `wasm32` test registry for `temper-orchestration`.
//!
//! Generated by `scripts/gen_wasm_test_registry.py`; run it after adding a
//! test to any listed module, and `--check` gates drift in CI.
//!
//! `cargo test`'s libtest harness cannot target `wasm32-unknown-unknown`,
//! so the Worker tier calls each test function individually instead of
//! running a test binary.  This module is the flat, indexable list of them.
//!
//! Only modules that survive `--no-default-features` appear here.  Tests
//! inside `#[cfg(feature = "python")]` modules are structurally absent
//! from a `wasm32` build and cannot be registered here at all.
//!
//! Three exclusion classes apply here, all structural:
//!
//! * `#[cfg(feature = "python")]` items.  Unlike the other crates on
//!   this tier, the gate here is mostly per-*item* rather than
//!   per-*module*: almost every stage module wraps the shared
//!   `BoardState` type (`board_state.rs`), whose fields are
//!   `Option<pyo3::Py<PyAny>>` placeholders (Phase A marshalling has
//!   not landed yet -- see `board_state.rs`'s doc), so `BoardState`
//!   itself, the `Stage<BoardState>` impls, and every `#[pyfunction]`
//!   FFI entry point built on it do not exist in a
//!   `--no-default-features` build. A handful of `#[test]` functions
//!   are individually `#[cfg(feature = "python")]`-gated alongside
//!   otherwise-pure sibling tests in the same module, for the same
//!   reason at function scope (`feasibility::record_loss` mirrors a
//!   CPython `ZeroDivisionError` through `PyResult`;
//!   `phased_component_assignment_validator_stage::is_hv_safety` and
//!   `grid_hv`'s whole `tests` module attach a live interpreter via
//!   `Python::attach` to exercise real CPython attribute-lookup
//!   semantics; `pipeline_state::PipelinePhase`'s tests call its
//!   `#[pymethods]` `__hash__`).
//! * `proptest` modules use a dev-dependency, which is not linked into
//!   the ordinary (non-test) build this registry compiles into.
//! * `Stage<S>` itself has no default type parameter in a
//!   `--no-default-features` build (`stage.rs` declares a second,
//!   parameter-free definition under `#[cfg(not(feature = "python"))]`
//!   since the default -- `BoardState` -- does not exist), which is
//!   why `stage::tests` (the trivial `Stage<u32>` pin) registers fully:
//!   nothing in it depends on the default.
//!
//! `scripts/gen_wasm_test_registry.py --crate temper-orchestration
//! --census` prints the full module census with per-module counts.
//!
//! ## Families
//!
//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`
//! feature, as in `temper-drc-rs`.  One family (`orchestration`): what
//! survives `--no-default-features` is a flat set of pure kernels
//! (timing, feasibility, copper-length, the `Stage`/`PipelineRunner`
//! scaffolding) with no rule-family taxonomy to shard along.

/// A single test: its fully qualified name and a nullary callable.
///
/// Failure is signalled by panicking, exactly as under libtest.  On
/// `wasm32-unknown-unknown` a panic aborts (the target has no unwinding on
/// stable), which surfaces to the host as a WebAssembly trap -- so the
/// runner catches the trap rather than a `Result`.
pub type WasmTest = (&'static str, fn());

/// All 1032 eligible tests, in a stable order.  Each entry is
/// gated on the per-family `wasm-registry-<family>` feature; enable
/// all families (`wasm-test-registry`) or individual ones.
pub const ALL: &[&[WasmTest]] = &[
    #[cfg(feature = "wasm-registry-orchestration")] crate::channel_mapping::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::clearance::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::copper_length::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::explainability::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::feasibility::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::grid_stage::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::host_math::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::netclass::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::phased_assignment_stage::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::phased_component_assignment_validator_stage::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::pipeline::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::pipeline_route::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::pipeline_state::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::router_pipeline::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::stage::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::timing::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::wasm_campaign_prng::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration")] crate::zone_aware_slot_generation_stage::tests::WASM_TESTS,
];

/// Total number of registered tests *in the currently-selected families*.
pub fn count() -> usize {
    ALL.iter().map(|m| m.len()).sum()
}

/// The test at `index` in the flattened registry.
pub fn get(index: usize) -> Option<&'static WasmTest> {
    let mut remaining = index;
    for module in ALL {
        if remaining < module.len() {
            return Some(&module[remaining]);
        }
        remaining -= module.len();
    }
    None
}
