#!/usr/bin/env python3
"""Generate (and drift-check) ``tools/wasm/test_family_map.json`` from the
*live* wasm32 test registry.

Why this exists
----------------
``tools/wasm/test_family_map.json`` is a hand-curated, richer classification
of every wasm32-registered ``temper-drc-rs`` test into one of nine rule
families (``drc``, ``emc``, ``erc``, ``safety``, ``placement``, ``routing``,
``dfm``, ``types``, ``integration``) -- richer than the six-bucket
``wasm-registry-<family>`` Cargo feature split (which folds everything not
under ``rules/<drc|emc|erc|placement|routing>/`` into a single ``infra``
bucket). ``coverage_report.py`` joins this map against a wasm32 run's results
to produce the R7/R8 per-family non-vacuity report.

The map was written once (2026-08-07, commit ``934cfbb2``) against a 95-test
registry. Two commits later (``4261eb4e`` +17, ``a6ccfefd`` +35) grew the
*registry* (``packages/temper-drc-rs/src/wasm_test_registry.rs``, generated by
``scripts/gen_wasm_test_registry.py``) to 147 tests, closing the family
coverage gaps the Phase 1 U4 verdict had named as a Phase 2 precondition
(``erc`` had 0 registered tests). Nobody regenerated the family map alongside
that growth -- there was no generator to run. This script is that generator,
so the map can never again silently fall behind the registry it classifies.

Classification source of truth
-------------------------------
Every eligible module (``scripts/gen_wasm_test_registry.py``'s ``ELIGIBLE``
list) maps to exactly one family, by module identity -- e.g.
``rules::emc::ground_plane`` -> ``emc``, ``types::fuse`` -> ``safety``,
``dfm::tests`` -> ``dfm``. The one exception is ``validation_kernels``, whose
tests exercise five *portable kernels* extracted from ``validation.rs``, each
individually classified in that module's own doc comment (the ``| Kernel |
Python origin | Family |`` table at the top of
``packages/temper-drc-rs/src/validation_kernels.rs``). Those five per-kernel
families are reproduced here as ``VALIDATION_KERNEL_FAMILY`` and matched by
test-name prefix, so a test that exercises ``min_hv_lv_trace_clearance`` is
classified ``safety`` (like the rest of HV/LV separation) rather than folded
into a blanket ``drc``/``infra`` bucket the way the coarse Cargo-feature
split does.

Usage
-----
    python3 tools/wasm/gen_test_family_map.py            # write
    python3 tools/wasm/gen_test_family_map.py --check    # CI drift gate
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from gen_wasm_test_registry import ELIGIBLE, SRC, module_path  # noqa: E402

OUT_PATH = REPO_ROOT / "tools" / "wasm" / "test_family_map.json"

GENERATED_BLOCK = re.compile(
    r"// --- BEGIN generated by scripts/gen_wasm_test_registry\.py: (?P<ident>\S+) ---"
    r"(?P<body>.*?)"
    r"// --- END generated by scripts/gen_wasm_test_registry\.py: (?P=ident) ---",
    re.DOTALL,
)
TEST_NAME = re.compile(r'\("([^"]+)",\s*[A-Za-z_][A-Za-z0-9_]*\)')

FAMILIES = ("drc", "emc", "erc", "safety", "placement", "routing", "dfm", "types", "integration")

# (module_path, ident) -> family, for every ELIGIBLE module *except*
# validation_kernels (classified per-test below, since it aggregates kernels
# from several original families -- see module docstring).
MODULE_FAMILY: dict[tuple[str, str], str] = {
    ("board", "tests"): "types",
    ("board", "board_state_tests"): "types",
    ("dfm", "tests"): "dfm",
    ("pyfmt", "tests"): "types",
    ("pymath", "tests"): "types",
    ("rules", "integration_tests"): "integration",
    ("rules::drc::clearance", "tests"): "drc",
    ("rules::emc::ground_plane", "tests"): "emc",
    ("rules::emc::loop_area", "tests"): "emc",
    ("rules::emc::noise_coupling", "tests"): "emc",
    ("rules::erc::floating_pins", "tests"): "erc",
    ("rules::erc::net_connectivity", "tests"): "erc",
    ("rules::erc::power_domain", "tests"): "erc",
    ("rules::placement::thermal_via_count", "tests"): "placement",
    ("rules::placement::wave_solder_keepout", "tests"): "placement",
    ("rules::routing::power_pad_teardrop", "tests"): "routing",
    ("types::clock", "tests"): "placement",
    ("types::esd", "tests"): "emc",
    ("types::fuse", "tests"): "safety",
    ("types::guard", "tests"): "emc",
    ("types::hv_net", "tests"): "safety",
    ("types::magnetic", "tests"): "emc",
    ("types::noise", "tests"): "emc",
    ("types::vent", "tests"): "placement",
}

# validation_kernels.rs's own doc-comment table: kernel -> Python origin ->
# family. Test function names are prefixed with the kernel they exercise
# (e.g. `min_hv_lv_clearance_diagonal` tests `min_hv_lv_trace_clearance`).
# Ordered longest-prefix-first so `tht_hole_collisions` doesn't get shadowed.
VALIDATION_KERNEL_FAMILY: list[tuple[str, str]] = [
    ("infer_package_type", "drc"),
    ("issue_fingerprint", "drc"),
    ("min_hv_lv_clearance", "safety"),
    ("tht_hole_collisions", "drc"),
    ("trace_length", "drc"),
]


def _read_generated_block(rel: str, ident: str) -> str:
    """Return the body of the ``ident`` module's generated ``WASM_TESTS`` block.

    Mirrors ``gen_wasm_test_registry.py``'s own module resolution: an inline
    ``mod ident { ... }`` keeps the block in ``rel`` itself; a file module
    (``mod tests;``) keeps it in ``<stem>/<ident>.rs``.
    """
    candidates = [SRC / rel]
    stem = rel[: -len(".rs")]
    candidates.append(SRC / stem / f"{ident}.rs")
    for path in candidates:
        if not path.exists():
            continue
        text = path.read_text()
        for m in GENERATED_BLOCK.finditer(text):
            if m.group("ident") == ident:
                return m.group("body")
    raise SystemExit(
        f"could not find a generated WASM_TESTS block for mod {ident} in {rel} "
        f"(or {stem}/{ident}.rs) -- run scripts/gen_wasm_test_registry.py first"
    )


def live_registered_tests() -> list[tuple[str, str, str]]:
    """Every test in the live wasm32 registry, as ``(mod_path, ident, name)``.

    Reads straight from the ``pub const WASM_TESTS`` blocks that
    ``scripts/gen_wasm_test_registry.py`` writes into each ``ELIGIBLE``
    module -- the same source ``wasm_test_registry.rs`` aggregates from. This
    is therefore the true, current test surface: whatever's registered here
    is exactly what a live ``cargo build --features wasm-registry-all``
    compiles into the wasm32 registry, independent of whether anyone
    remembered to update this JSON map.
    """
    out = []
    for rel, ident in ELIGIBLE:
        body = _read_generated_block(rel, ident)
        for m in TEST_NAME.finditer(body):
            out.append((module_path(rel), ident, m.group(1)))
    return out


def classify(mod_path: str, ident: str, name: str) -> str:
    if mod_path == "validation_kernels":
        # name looks like "validation_kernels::tests::<fn>"
        fn = name.rsplit("::", 1)[-1]
        for prefix, family in VALIDATION_KERNEL_FAMILY:
            if fn.startswith(prefix):
                return family
        raise SystemExit(
            f"validation_kernels test {name!r} doesn't match any kernel prefix in "
            "VALIDATION_KERNEL_FAMILY -- add the new kernel's family per its entry "
            "in validation_kernels.rs's doc-comment table"
        )
    family = MODULE_FAMILY.get((mod_path, ident))
    if family is None:
        raise SystemExit(
            f"no family classification for module ({mod_path!r}, {ident!r}) -- "
            "add an entry to MODULE_FAMILY in tools/wasm/gen_test_family_map.py"
        )
    return family


def build_map() -> dict:
    live = live_registered_tests()
    per_test: dict[str, list[str]] = {}
    for mod_path, ident, name in live:
        per_test[name] = [classify(mod_path, ident, name)]

    family_counts = dict.fromkeys(FAMILIES, 0)
    for families in per_test.values():
        for fam in families:
            family_counts[fam] += 1

    # canary_defects is independent, hand-curated evidence (a planted-defect
    # smoke test per family, see docs/evidence/2026-08-07-phase1-u4-coverage.md)
    # -- preserved verbatim from the existing file rather than regenerated,
    # but every referenced test is checked against the live registry below.
    existing = json.loads(OUT_PATH.read_text()) if OUT_PATH.exists() else {}
    canary_defects = existing.get("canary_defects", {})
    live_names = {name for _, _, name in live}
    for family, canary in canary_defects.items():
        if canary["test"] not in live_names:
            raise SystemExit(
                f"canary_defects[{family!r}] names {canary['test']!r}, which is "
                "not in the live wasm32 registry -- update or remove the canary"
            )

    total = len(per_test)
    comment = [
        f"Static mapping from each of the {total} wasm32-registered temper-drc-rs tests",
        "to the rule family (or families) it exercises.",
        "",
        "Families: drc, emc, erc, safety, placement, routing, dfm, types, integration",
        "- `types` covers type-system invariants, math utilities, board infrastructure",
        "- `integration` covers whole-registry integration tests that exercise all families",
        "",
        "Generated by tools/wasm/gen_test_family_map.py from the live wasm32 test",
        "registry (packages/temper-drc-rs/src/wasm_test_registry.rs, produced by",
        "scripts/gen_wasm_test_registry.py). Run `python3",
        "tools/wasm/gen_test_family_map.py` after adding/renaming a wasm-eligible",
        "test; `--check` is the CI drift gate. Checked for staleness against a run's",
        "results by tools/wasm/coverage_report.py.",
        "",
        "A test with multiple families means it exercises more than one rule domain;",
        "integration tests are the primary example.",
    ]

    return {
        "_comment": comment,
        "per_test": dict(sorted(per_test.items())),
        "family_counts": family_counts,
        "canary_defects": canary_defects,
    }


def diff_registration(live_names: set[str], mapped_names: set[str]) -> tuple[set[str], set[str]]:
    """``(missing, stale)``: registered-but-unmapped, and mapped-but-nonexistent."""
    return live_names - mapped_names, mapped_names - live_names


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    args = ap.parse_args()

    new_map = build_map()
    new_text = json.dumps(new_map, indent=2) + "\n"
    current_text = OUT_PATH.read_text() if OUT_PATH.exists() else None

    if args.check:
        if current_text == new_text:
            print(f"wasm test family map up to date: {len(new_map['per_test'])} tests mapped")
            return 0
        print(f"{OUT_PATH.relative_to(REPO_ROOT)} is stale; run tools/wasm/gen_test_family_map.py")
        if current_text is not None:
            live_names = set(new_map["per_test"])
            mapped_names = set(json.loads(current_text).get("per_test", {}))
            missing, stale = diff_registration(live_names, mapped_names)
            if missing:
                print(f"  {len(missing)} registered test(s) missing from the map:")
                for n in sorted(missing):
                    print(f"    + {n}")
            if stale:
                print(f"  {len(stale)} mapped test(s) no longer in the registry:")
                for n in sorted(stale):
                    print(f"    - {n}")
        return 1

    OUT_PATH.write_text(new_text)
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}: {len(new_map['per_test'])} tests mapped")
    print("family counts:", json.dumps(new_map["family_counts"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
