"""
Data loader for PCB dataset generated by PcbCrawler.
"""

from __future__ import annotations

import json
from pathlib import Path

import jax.numpy as jnp
from jax import Array

from temper_placer.core.graph import NetlistGraph, netlist_to_graph
from temper_placer.io.kicad_parser import parse_kicad_pcb


class PcbDataset:
    """Dataset of PCB graphs and quality labels."""

    def __init__(self, dataset_dir: Path):
        self.dataset_dir = dataset_dir
        self.samples = []
        self._load_dataset()

    def _load_dataset(self):
        """Discover all processed designs in the dataset directory."""
        if not self.dataset_dir.exists():
            return

        for design_dir in self.dataset_dir.iterdir():
            if design_dir.is_dir():
                metadata_path = design_dir / "metadata.json"
                pcb_path = design_dir / "board.kicad_pcb"

                if metadata_path.exists() and pcb_path.exists():
                    self.samples.append({
                        "id": design_dir.name,
                        "metadata": metadata_path,
                        "pcb": pcb_path
                    })

    def __len__(self) -> int:
        return len(self.samples)

    def get_sample(self, index: int) -> tuple[NetlistGraph, Array, Array]:
        """
        Load a single sample.
        
        Returns:
            - graph: NetlistGraph (nodes, edges, weights)
            - positions: (N, 2) component positions
            - score: (1,) quality score (based on DRC results)
        """
        sample = self.samples[index]

        # 1. Parse PCB
        parse_result = parse_kicad_pcb(sample["pcb"])
        netlist = parse_result.netlist

        # 2. Extract positions
        # Use initial_position if set (which it is for crawler output)
        positions = jnp.array([c.initial_position or (0.0, 0.0) for c in netlist.components])

        # 3. Create Graph
        graph = netlist_to_graph(netlist)

        # 4. Determine Target Score (Label)
        # Higher score = better placement
        with open(sample["metadata"]) as f:
            meta = json.load(f)

        drc = meta.get("drc", {})
        if drc.get("error") or not drc.get("success", False):
            score = 0.0 # Failed to even run or hard failure
        else:
            # 1.0 for clean DRC, minus penalty for errors
            err_count = drc.get("error_count", 0)
            warn_count = drc.get("warning_count", 0)
            # Heuristic penalty
            score = max(0.0, 1.0 - (err_count * 0.1) - (warn_count * 0.01))

        return graph, positions, jnp.array([score])

def create_batch(samples: list[tuple[NetlistGraph, Array, Array]]) -> tuple[NetlistGraph, Array, Array]:
    """Batch multiple samples into a single large graph."""
    from temper_placer.core.graph import batch_graphs

    graphs = [s[0] for s in samples]
    positions = [s[1] for s in samples]
    scores = [s[2] for s in samples]

    batched_graph = batch_graphs(graphs)
    batched_pos = jnp.concatenate(positions, axis=0)
    batched_scores = jnp.concatenate(scores, axis=0)

    return batched_graph, batched_pos, batched_scores
