//! Wave 4 Phase 4 — regression slice: CP-SAT comparison kernel.
//!
//! `temper_placer/regression/cp_sat_comparison.py` (pinned verbatim as the
//! oracle `_cp_sat_comparison_py_oracle.py`, commit `0a29f15e3`) is fully
//! portable compute — `compare_metric_dicts` (the Pareto-style per-metric
//! gate, the wirelength ratio/tolerance rule, the `:.2f`/`:.3f`/`:.4f`
//! detail strings, the summary line, and the failing-metric list repr)
//! migrated into `temper-design-bundle`. The Python module becomes a
//! delegation shim over the returned records.
//!
//! Numeric-fidelity notes (each pinned by the differential):
//!
//! - Values are converted with Python `builtins.float` (the oracle's
//!   `float(candidate_scores.get(...))`) — int/float/str-number leaves all
//!   convert exactly like the oracle, and a non-numeric leaf raises the same
//!   `ValueError`/`TypeError` family the oracle's `float()` raises.
//! - Fixed-point `:.2f`/`:.3f`/`:.4f` formatting is measured CPython-parity
//!   (the validation-slice precedent, 100k/100k on random values), including
//!   Python's NaN spelling — `f"{nan:.Nf}"` is `"nan"`, not Rust's `"NaN"`
//!   (`py_fixed`), pinned by the NaN-leaf differential case.
//! - The summary's `Failing: ['a', 'b']` list is Python's repr of a list of
//!   str; rendered here as single-quoted names joined by `, `. Metric names
//!   are score-dict keys (realistically simple identifiers); a name carrying
//!   a quote/backslash is a documented narrowing (Python repr would escape
//!   it).
//! - `bool` interpolation in the detail lines renders `True`/`False`
//!   (Python), never Rust's `true`/`false`.
//! - The metric iteration order is `sorted()` of the key intersection —
//!   deterministic, so no set/dict hash-order dependence survives.
//! - Empty intersection: `passed=True`, no comparisons, summary
//!   `"Parity comparison: 0/0 metrics passed"` — the oracle's vacuous-true
//!   semantics, preserved exactly.
//! - Non-string keys: a candidate key that fails `String` extraction but is
//!   ALSO present in the baseline is in the oracle's key intersection, where
//!   the oracle's `sorted(metrics)` raises `TypeError` on the mixed-type key
//!   set (the realistic shape — a stray non-string key alongside string
//!   metric names). The kernel raises the same class rather than silently
//!   dropping the metric; a non-string key on ONE side only is not in the
//!   intersection and is ignored by both arms.

use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Plain-Rust core (no pyo3) — the FREEZE target.
//
// `compare_metric_maps` is the portable compute behind the pyfunction
// `compare_metric_dicts`: it takes the score dicts as plain
// `HashMap<String, String>` (leaf values in their string form) and returns
// plain rows. The pyo3 wrapper below is a thin adapter: PyDict -> HashMap ->
// core -> boxed rows. Keeping the core pyo3-free lets the frozen golden
// corpus (generated by scripts/gen_oracle_freeze.py --spec cp_sat_comparison)
// exercise it without a Python interpreter, i.e. on the wasm32 tier.
// ---------------------------------------------------------------------------

/// One per-metric comparison row (the portable projection of the oracle's
/// `MetricComparison` dataclass): `expected` is the baseline (JAX) value,
/// `actual` the candidate (CP-SAT) value, and `note` the human-readable
/// detail string rendered exactly like the oracle's `detail`.
#[derive(Debug, Clone, PartialEq)]
pub struct MetricComparisonRow {
    pub name: String,
    pub expected: f64,
    pub actual: f64,
    pub passed: bool,
    pub note: String,
}

/// A score leaf failed Python's builtin `float()` conversion (the oracle
/// raises `ValueError` for a non-numeric string; the pyo3 wrapper maps this
/// onto `PyValueError`). Key/type errors on non-string KEYS cannot occur in
/// this core by construction (`HashMap<String, _>`); the pyo3 wrapper owns
/// that check and raises the oracle's `TypeError` class itself.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FloatCoerceError {
    pub key: String,
    pub value: String,
}

impl FloatCoerceError {
    /// Mirrors CPython's `ValueError` text for `float("...")`.
    pub fn message(&self) -> String {
        format!(
            "could not convert string to float: {}",
            debug_quote(&self.value)
        )
    }
}

/// Minimal single-quoted Python-repr-style quoting for the error message
/// (metric leaves are realistically simple; escapes beyond backslash/quote
/// are a documented narrowing, same as the failing-list repr below).
fn debug_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for c in s.chars() {
        match c {
            '\'' => out.push_str("\\'"),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('\'');
    out
}

/// Python's `bool` string rendering ("True"/"False").
fn py_bool(b: bool) -> &'static str {
    if b {
        "True"
    } else {
        "False"
    }
}

/// Python's fixed-point `:.Nf` rendering, including its NaN spelling: Rust's
/// `{:.N}` writes `NaN`, Python's `f"{nan:.Nf}"` writes `nan` (infinities
/// already agree — `inf`/`-inf` on both arms).
fn py_fixed(value: f64, precision: usize) -> String {
    if value.is_nan() {
        "nan".to_string()
    } else {
        format!("{value:.precision$}")
    }
}

/// Parse a string leaf exactly like Python's builtin `float(str)`
/// (the oracle's `float(candidate_scores.get(...))` semantics):
///
/// - surrounding Unicode whitespace is stripped;
/// - an optional sign; case-insensitive `inf`/`infinity`/`nan`;
/// - otherwise a decimal significand with optional exponent, where `_` is
///   accepted only BETWEEN digits (Python's numeric-literal underscore rule:
///   `"1_000.5"` parses, `"1__0"`, `"1_"`, `"._5"`, `"1e_5"` do not);
/// - anything else is `None` (the caller raises the ValueError class);
/// - the cleaned literal is delegated to `f64::from_str`, which is correctly
///   rounded exactly like CPython's dtoa, so accepted strings convert
///   bit-identically to the oracle.
fn py_float_str(raw: &str) -> Option<f64> {
    let t = raw.trim();
    let mut rest = t;
    let mut neg = false;
    if let Some(r) = rest.strip_prefix('+') {
        rest = r;
    } else if let Some(r) = rest.strip_prefix('-') {
        rest = r;
        neg = true;
    }
    let lower = rest.to_ascii_lowercase();
    match lower.as_str() {
        "inf" | "infinity" => {
            return Some(if neg {
                f64::NEG_INFINITY
            } else {
                f64::INFINITY
            });
        }
        "nan" => return Some(f64::NAN),
        _ => {}
    }
    let cleaned = clean_decimal(rest)?;
    let v: f64 = cleaned.parse().ok()?;
    Some(if neg { -v } else { v })
}

/// Validate + normalize a Python decimal-float literal: digits with
/// underscore separators (only ever between two digits), an optional
/// fractional part, and an optional exponent. Returns the literal with
/// underscores removed (Rust's parser rejects them), or `None` when the
/// string is not a valid Python float literal.
fn clean_decimal(body: &str) -> Option<String> {
    let cs: Vec<char> = body.chars().collect();
    let mut out = String::with_capacity(cs.len());
    let mut i = 0usize;
    let mut last_was_digit = false;
    let mut mantissa_digits = 0usize;

    let scan_digits = |out: &mut String, i: &mut usize, last_was_digit: &mut bool| -> usize {
        let mut count = 0usize;
        while *i < cs.len() {
            match cs[*i] {
                c if c.is_ascii_digit() => {
                    out.push(c);
                    count += 1;
                    *last_was_digit = true;
                    *i += 1;
                }
                '_' => {
                    let next_is_digit = matches!(cs.get(*i + 1), Some(c) if c.is_ascii_digit());
                    if !(next_is_digit && *last_was_digit) {
                        break;
                    }
                    *last_was_digit = false;
                    *i += 1;
                }
                _ => break,
            }
        }
        count
    };

    mantissa_digits += scan_digits(&mut out, &mut i, &mut last_was_digit);
    if matches!(cs.get(i), Some('.')) {
        i += 1;
        out.push('.');
        last_was_digit = false;
        mantissa_digits += scan_digits(&mut out, &mut i, &mut last_was_digit);
    }
    if mantissa_digits == 0 {
        return None;
    }
    if matches!(cs.get(i), Some('e') | Some('E')) {
        i += 1;
        out.push('e');
        last_was_digit = false;
        if matches!(cs.get(i), Some('+')) {
            i += 1;
        } else if matches!(cs.get(i), Some('-')) {
            out.push('-');
            i += 1;
        }
        if scan_digits(&mut out, &mut i, &mut last_was_digit) == 0 {
            return None;
        }
    }
    if i != cs.len() {
        return None;
    }
    Some(out)
}

/// Encode a value that has ALREADY been converted through Python's builtin
/// `float()` (int/float/bool/... leaves in the wrapper) into the string form
/// the plain core parses back bit-identically. Rust's `Display` for `f64` is
/// the shortest round-trip repr, and `f64::from_str` is correctly rounded, so
/// the round trip is exact; infinities and NaN get their Python spellings.
fn encode_f64(v: f64) -> String {
    if v.is_nan() {
        "nan".to_string()
    } else if v == f64::INFINITY {
        "inf".to_string()
    } else if v == f64::NEG_INFINITY {
        "-inf".to_string()
    } else {
        format!("{v}")
    }
}

/// Compare two score maps per-metric — the verbatim port of the oracle's
/// `compare_metric_dicts` loop over the sorted key intersection (see the
/// module docs above for the pinned numeric/format semantics).
///
/// `expected` holds the baseline (JAX) scores, `actual` the candidate
/// (CP-SAT) scores, and `context` the metric name the lower-is-better 5%
/// tolerance rule applies to (the oracle's `wirelength_metric` argument).
pub fn compare_metric_maps(
    expected: &HashMap<String, String>,
    actual: &HashMap<String, String>,
    context: &str,
) -> Result<Vec<MetricComparisonRow>, FloatCoerceError> {
    let mut names: Vec<&String> = expected
        .keys()
        .filter(|k| actual.contains_key(*k))
        .collect();
    names.sort_unstable();

    let mut rows: Vec<MetricComparisonRow> = Vec::new();
    for name in names {
        // Candidate value first, then baseline — the oracle's evaluation
        // order (which of the two `float()` calls raises first is pinned).
        let av = &actual[name];
        let ev = &expected[name];
        let cand_val = py_float_str(av)
            .ok_or_else(|| FloatCoerceError { key: name.clone(), value: av.clone() })?;
        let base_val = py_float_str(ev)
            .ok_or_else(|| FloatCoerceError { key: name.clone(), value: ev.clone() })?;

        let (passed, note) = if name.as_str() == context {
            // Lower is better, within a 5% tolerance.
            let (ratio, passed) = if base_val > 0.0 {
                (cand_val / base_val, cand_val <= base_val * 1.05)
            } else {
                // baseline 0: candidate must be 0 too.
                (f64::INFINITY, cand_val <= 0.0)
            };
            (
                passed,
                format!(
                    "{name}: candidate={}, baseline={}, ratio={}, tolerance=1.05, passed={}",
                    py_fixed(cand_val, 2),
                    py_fixed(base_val, 2),
                    py_fixed(ratio, 3),
                    py_bool(passed)
                ),
            )
        } else {
            // Higher is better (default for all oracle metrics), 1e-9 slack.
            let passed = cand_val >= base_val - 1e-9;
            let delta = cand_val - base_val;
            (
                passed,
                format!(
                    "{name}: candidate={}, baseline={}, delta={}, passed={}",
                    py_fixed(cand_val, 4),
                    py_fixed(base_val, 4),
                    py_fixed(delta, 4),
                    py_bool(passed)
                ),
            )
        };

        rows.push(MetricComparisonRow {
            name: name.clone(),
            expected: base_val,
            actual: cand_val,
            passed,
            note,
        });
    }
    Ok(rows)
}

/// Compose the aggregate verdict and the summary line from the comparison
/// rows — the oracle's tail (overall pass flag + the
/// `Parity comparison: n/m metrics passed` /
/// `Parity FAILED: ... Failing: ['a', 'b']` strings).
pub fn parity_summary(rows: &[MetricComparisonRow]) -> (bool, String) {
    let all_passed = rows.iter().all(|r| r.passed);
    let passed_metrics = rows.iter().filter(|r| r.passed).count();
    let total_metrics = rows.len();

    let summary = if all_passed {
        format!("Parity comparison: {passed_metrics}/{total_metrics} metrics passed")
    } else {
        let failing: Vec<String> = rows
            .iter()
            .filter(|r| !r.passed)
            .map(|r| format!("'{}'", r.name))
            .collect();
        format!(
            "Parity FAILED: {passed_metrics}/{total_metrics} metrics passed. Failing: [{}]",
            failing.join(", ")
        )
    };
    (all_passed, summary)
}

// --- BEGIN generated by scripts/gen_oracle_freeze.py: cp_sat_comparison ---
    /// Frozen golden vectors for `compare_metric_maps` + `parity_summary`
    /// (FREEZE, U4/U5). Regenerate:
    /// `python3 scripts/gen_oracle_freeze.py --spec cp_sat_comparison`
    /// (requires reviving the deleted oracle from git history first -- see
    /// scripts/oracle_freeze_specs/cp_sat_comparison.py's module docstring).
    #[cfg(test)]
    mod frozen_tests {
        use super::*;
        use std::collections::HashMap;

        struct FrozenCpSatComparisonCase<'a> {
            candidate: &'a [(&'a str, &'a str)],
            baseline: &'a [(&'a str, &'a str)],
            /// None = expect FloatCoerceError on this key
            coerce_error_key: Option<&'static str>,
            expected_rows: &'a [(&'a str, u64, u64, bool)],
            expected_passed: bool,
            expected_summary: &'a str,
            tags: &'static [&'static str],
        }

        fn to_map(pairs: &[(&str, &str)]) -> HashMap<String, String> {
            pairs.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect()
        }

        const FROZEN_CP_SAT_COMPARISON_GOLDEN: &[FrozenCpSatComparisonCase] = &[
            FrozenCpSatComparisonCase {
                candidate: &[],
                baseline: &[],
                coerce_error_key: None,
                expected_rows: &[],
                expected_passed: true,
                expected_summary: "Parity comparison: 0/0 metrics passed",
                tags: &["both_empty", "named:empty_both"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", "1.5")],
                baseline: &[("m", "1.5")],
                coerce_error_key: None,
                expected_rows: &[("m", 0x3ff8000000000000_u64, 0x3ff8000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["float_leaf", "named:single_equal"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", "2.0")],
                baseline: &[("m", "1.0")],
                coerce_error_key: None,
                expected_rows: &[("m", 0x4000000000000000_u64, 0x3ff0000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["float_leaf", "named:candidate_higher"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", "0.9999999995")],
                baseline: &[("m", "1.0")],
                coerce_error_key: None,
                expected_rows: &[("m", 0x3fefffffffbb47d0_u64, 0x3ff0000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["float_leaf", "named:candidate_lower_epsilon_pass"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", "0.9")],
                baseline: &[("m", "1.0")],
                coerce_error_key: None,
                expected_rows: &[("m", 0x3feccccccccccccd_u64, 0x3ff0000000000000_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 0/1 metrics passed. Failing: ['m']",
                tags: &["float_leaf", "named:candidate_lower_real_fail"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("clearance_3mm", "4.0"), ("clearance_6mm", "8.0")],
                baseline: &[("clearance_3mm", "4.0"), ("clearance_6mm", "9.0")],
                coerce_error_key: None,
                expected_rows: &[("clearance_3mm", 0x4010000000000000_u64, 0x4010000000000000_u64, true), ("clearance_6mm", 0x4020000000000000_u64, 0x4022000000000000_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 1/2 metrics passed. Failing: ['clearance_6mm']",
                tags: &["float_leaf", "named:clearance_style_keys"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("thermal_score", "10.0")],
                baseline: &[("thermal_score", "9.999999999")],
                coerce_error_key: None,
                expected_rows: &[("thermal_score", 0x4024000000000000_u64, 0x4023fffffff768fa_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["float_leaf", "named:thermal_score_pass"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("thermal_score", "9.0")],
                baseline: &[("thermal_score", "10.0")],
                coerce_error_key: None,
                expected_rows: &[("thermal_score", 0x4022000000000000_u64, 0x4024000000000000_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 0/1 metrics passed. Failing: ['thermal_score']",
                tags: &["float_leaf", "named:thermal_score_fail"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("total_manhattan_wirelength", "104.0")],
                baseline: &[("total_manhattan_wirelength", "100.0")],
                coerce_error_key: None,
                expected_rows: &[("total_manhattan_wirelength", 0x405a000000000000_u64, 0x4059000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["context_case", "float_leaf", "named:wirelength_within_tolerance", "wirelength_in_intersection"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("total_manhattan_wirelength", "105.0")],
                baseline: &[("total_manhattan_wirelength", "100.0")],
                coerce_error_key: None,
                expected_rows: &[("total_manhattan_wirelength", 0x405a400000000000_u64, 0x4059000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["context_case", "float_leaf", "named:wirelength_at_tolerance_edge", "wirelength_in_intersection"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("total_manhattan_wirelength", "106.0")],
                baseline: &[("total_manhattan_wirelength", "100.0")],
                coerce_error_key: None,
                expected_rows: &[("total_manhattan_wirelength", 0x405a800000000000_u64, 0x4059000000000000_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 0/1 metrics passed. Failing: ['total_manhattan_wirelength']",
                tags: &["context_case", "float_leaf", "named:wirelength_outside_tolerance", "wirelength_in_intersection"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("total_manhattan_wirelength", "95.0")],
                baseline: &[("total_manhattan_wirelength", "100.0")],
                coerce_error_key: None,
                expected_rows: &[("total_manhattan_wirelength", 0x4057c00000000000_u64, 0x4059000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["context_case", "float_leaf", "named:wirelength_improving", "wirelength_in_intersection"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("total_manhattan_wirelength", "0.0")],
                baseline: &[("total_manhattan_wirelength", "0")],
                coerce_error_key: None,
                expected_rows: &[("total_manhattan_wirelength", 0x0000000000000000_u64, 0x0000000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["context_case", "float_leaf", "int_leaf", "named:wirelength_zero_baseline_candidate_zero", "wirelength_in_intersection", "zero_baseline_context"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("total_manhattan_wirelength", "1.0")],
                baseline: &[("total_manhattan_wirelength", "0")],
                coerce_error_key: None,
                expected_rows: &[("total_manhattan_wirelength", 0x3ff0000000000000_u64, 0x0000000000000000_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 0/1 metrics passed. Failing: ['total_manhattan_wirelength']",
                tags: &["context_case", "float_leaf", "int_leaf", "named:wirelength_zero_baseline_candidate_pos", "wirelength_in_intersection", "zero_baseline_context"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("total_manhattan_wirelength", "-1.0")],
                baseline: &[("total_manhattan_wirelength", "0")],
                coerce_error_key: None,
                expected_rows: &[("total_manhattan_wirelength", 0xbff0000000000000_u64, 0x0000000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["context_case", "float_leaf", "int_leaf", "named:wirelength_zero_baseline_candidate_neg", "wirelength_in_intersection", "zero_baseline_context"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", "2.5")],
                baseline: &[("m", "1.5")],
                coerce_error_key: None,
                expected_rows: &[("m", 0x4004000000000000_u64, 0x3ff8000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["named:numeric_str_leaves", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", "3")],
                baseline: &[("m", "4")],
                coerce_error_key: None,
                expected_rows: &[("m", 0x4008000000000000_u64, 0x4010000000000000_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 0/1 metrics passed. Failing: ['m']",
                tags: &["named:numeric_str_int_spelling", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", "inf")],
                baseline: &[("m", "1.0")],
                coerce_error_key: None,
                expected_rows: &[("m", 0x7ff0000000000000_u64, 0x3ff0000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["inf_leaf", "named:numeric_str_inf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", "-inf")],
                baseline: &[("m", "1.0")],
                coerce_error_key: None,
                expected_rows: &[("m", 0xfff0000000000000_u64, 0x3ff0000000000000_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 0/1 metrics passed. Failing: ['m']",
                tags: &["inf_leaf", "named:numeric_str_neg_inf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", "nan")],
                baseline: &[("m", "1.0")],
                coerce_error_key: None,
                expected_rows: &[("m", 0x7ff8000000000000_u64, 0x3ff0000000000000_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 0/1 metrics passed. Failing: ['m']",
                tags: &["named:numeric_str_nan", "nan_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", "1e3")],
                baseline: &[("m", "500")],
                coerce_error_key: None,
                expected_rows: &[("m", 0x408f400000000000_u64, 0x407f400000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["named:numeric_str_scientific", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", " 2.5 ")],
                baseline: &[("m", "1.5")],
                coerce_error_key: None,
                expected_rows: &[("m", 0x4004000000000000_u64, 0x3ff8000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["named:numeric_str_whitespace", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", "1_000")],
                baseline: &[("m", "999")],
                coerce_error_key: None,
                expected_rows: &[("m", 0x408f400000000000_u64, 0x408f380000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["named:numeric_str_underscore", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("only_c", "1.0"), ("shared", "2.0")],
                baseline: &[("shared", "1.0")],
                coerce_error_key: None,
                expected_rows: &[("shared", 0x4000000000000000_u64, 0x3ff0000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["candidate_only_key", "float_leaf", "named:candidate_only_key"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("shared", "2.0")],
                baseline: &[("only_b", "1.0"), ("shared", "1.0")],
                coerce_error_key: None,
                expected_rows: &[("shared", 0x4000000000000000_u64, 0x3ff0000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["baseline_only_key", "float_leaf", "named:baseline_only_key"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("m", "1.0")],
                baseline: &[("m", "0.0")],
                coerce_error_key: None,
                expected_rows: &[("m", 0x3ff0000000000000_u64, 0x0000000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["bool_leaf", "named:bool_leaves"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("clearance_3mm", "4.0"), ("total_manhattan_wirelength", "102.5"), ("thermal_score", "7")],
                baseline: &[("clearance_3mm", "4.0"), ("total_manhattan_wirelength", "100.0"), ("thermal_score", "6.5")],
                coerce_error_key: None,
                expected_rows: &[("clearance_3mm", 0x4010000000000000_u64, 0x4010000000000000_u64, true), ("thermal_score", 0x401c000000000000_u64, 0x401a000000000000_u64, true), ("total_manhattan_wirelength", 0x4059a00000000000_u64, 0x4059000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 3/3 metrics passed",
                tags: &["context_case", "float_leaf", "int_leaf", "named:kitchen_sink", "numeric_str", "wirelength_in_intersection"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("a0", "162"), ("z1", "9.815274e-01")],
                baseline: &[("a0", "10.612266015805936")],
                coerce_error_key: None,
                expected_rows: &[("a0", 0x4064400000000000_u64, 0x4025397aee64ad6c_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["candidate_only_key", "float_leaf", "int_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("b0", "45.944282640713006"), ("h1", "119.61632829849106"), ("s2", "29.93693931270343")],
                baseline: &[("b0", "1.2.3"), ("h1", "1.2.3"), ("s2", "46")],
                coerce_error_key: Some("b0"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["float_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("i0", "21.518206787324175"), ("i1", "-27.911120592079474"), ("k2", "194"), ("h3", "-22.789951996889847"), ("k4", "148")],
                baseline: &[("i0", "0.0"), ("i1", "nan"), ("h3", "6.359152e+01"), ("k4", "-30.30702187433887")],
                coerce_error_key: None,
                expected_rows: &[("h3", 0xc036ca3a4b480d42_u64, 0x404fcbb6ed677708_u64, false), ("i0", 0x403584a933341f60_u64, 0x0000000000000000_u64, true), ("i1", 0xc03be93f32f9b189_u64, 0x7ff8000000000000_u64, false), ("k4", 0x4062800000000000_u64, 0xc03e4e98fc4d712b_u64, true)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 2/4 metrics passed. Failing: ['h3', 'i1']",
                tags: &["bool_leaf", "candidate_only_key", "float_leaf", "int_leaf", "nan_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("y0", "abc"), ("t1", "60.518019310352116"), ("j2", ""), ("o3", "inf")],
                baseline: &[("y0", "140.11273429954286"), ("t1", "144.04656055934151"), ("j2", "107.19264761151061"), ("o3", "0.0")],
                coerce_error_key: Some("j2"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["bool_leaf", "float_leaf", "inf_leaf", "non_numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("g0", "1.2.3"), ("r1", "117.51669012816032")],
                baseline: &[("g0", "121.77464264663092"), ("r1", "12x")],
                coerce_error_key: Some("g0"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["float_leaf", "non_numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("h0", "51.837756118506746"), ("t1", "122.61119893906582"), ("t2", "-3.846688723128281"), ("c3", "2.971713e+01")],
                baseline: &[("h0", ""), ("t1", "-42.34951680306713"), ("t2", "1.0"), ("c3", "192")],
                coerce_error_key: Some("h0"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["bool_leaf", "float_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("e0", "0.4198651059278298"), ("y1", "8.073"), ("p2", "52"), ("t3", "-32.01376964539515"), ("p4", "abc")],
                baseline: &[("e0", "1.2.3"), ("y1", "148.5734592762439"), ("p2", "1.0"), ("t3", "-inf"), ("p4", "0.7620560908981739")],
                coerce_error_key: Some("e0"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["bool_leaf", "float_leaf", "inf_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("b0", "119.99245527684275"), ("j1", "104.46039751746855"), ("f2", "130.56417916745812")],
                baseline: &[("b0", "30.072008667872897"), ("j1", "1.0"), ("f2", "22")],
                coerce_error_key: None,
                expected_rows: &[("b0", 0x405dff8463233210_u64, 0x403e126f28f98ae9_u64, true), ("f2", 0x4060520dc1782a26_u64, 0x4036000000000000_u64, true), ("j1", 0x405a1d7727262bf8_u64, 0x3ff0000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 3/3 metrics passed",
                tags: &["bool_leaf", "float_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("d0", "168"), ("w1", "-0.9744998714779314"), ("a2", "1.0"), ("j3", "--"), ("v4", "108")],
                baseline: &[("a2", "-41.92571951840662"), ("j3", "21.84231162501481")],
                coerce_error_key: Some("j3"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["bool_leaf", "candidate_only_key", "float_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("p0", "0.0"), ("q1", "176"), ("p2", "0.0"), ("k3", "48")],
                baseline: &[("p0", "1.0"), ("q1", "nan"), ("k3", "4")],
                coerce_error_key: None,
                expected_rows: &[("k3", 0x4048000000000000_u64, 0x4010000000000000_u64, true), ("p0", 0x0000000000000000_u64, 0x3ff0000000000000_u64, false), ("q1", 0x4066000000000000_u64, 0x7ff8000000000000_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 1/3 metrics passed. Failing: ['p0', 'q1']",
                tags: &["bool_leaf", "candidate_only_key", "int_leaf", "nan_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[],
                baseline: &[],
                coerce_error_key: None,
                expected_rows: &[],
                expected_passed: true,
                expected_summary: "Parity comparison: 0/0 metrics passed",
                tags: &["both_empty"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[],
                baseline: &[],
                coerce_error_key: None,
                expected_rows: &[],
                expected_passed: true,
                expected_summary: "Parity comparison: 0/0 metrics passed",
                tags: &["both_empty"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("l0", "1.0"), ("k1", "141"), ("a2", "33.01694540352706")],
                baseline: &[("l0", "1.0"), ("k1", "nan"), ("a2", "47")],
                coerce_error_key: None,
                expected_rows: &[("a2", 0x4040822b4458fbae_u64, 0x4047800000000000_u64, false), ("k1", 0x4061a00000000000_u64, 0x7ff8000000000000_u64, false), ("l0", 0x3ff0000000000000_u64, 0x3ff0000000000000_u64, true)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 1/3 metrics passed. Failing: ['a2', 'k1']",
                tags: &["bool_leaf", "float_leaf", "int_leaf", "nan_leaf"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("n0", "0"), ("y1", "0.0")],
                baseline: &[("n0", "31.936"), ("y1", "21.94215255460354"), ("g2", "79")],
                coerce_error_key: None,
                expected_rows: &[("n0", 0x0000000000000000_u64, 0x403fef9db22d0e56_u64, false), ("y1", 0x0000000000000000_u64, 0x4035f130e8e9dd74_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 0/2 metrics passed. Failing: ['n0', 'y1']",
                tags: &["baseline_only_key", "bool_leaf", "float_leaf", "int_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("c0", "9.943508e+01"), ("n1", "87.91387227515969")],
                baseline: &[("c0", "73.124"), ("n1", "60.24018925995975")],
                coerce_error_key: None,
                expected_rows: &[("c0", 0x4058dbd859c8c932_u64, 0x405247ef9db22d0e_u64, true), ("n1", 0x4055fa7ce223a20c_u64, 0x404e1ebe858c3054_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 2/2 metrics passed",
                tags: &["float_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("y0", "109")],
                baseline: &[("q1", "9")],
                coerce_error_key: None,
                expected_rows: &[],
                expected_passed: true,
                expected_summary: "Parity comparison: 0/0 metrics passed",
                tags: &["baseline_only_key", "candidate_only_key", "int_leaf"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("d1", "-3"), ("q2", "141.70692069494518")],
                baseline: &[("h0", "189"), ("d1", "54.80071356993727"), ("q2", "67.880")],
                coerce_error_key: None,
                expected_rows: &[("d1", 0xc008000000000000_u64, 0x404b667dc8422c08_u64, false), ("q2", 0x4061b69f182634f7_u64, 0x4050f851eb851eb8_u64, true)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 1/2 metrics passed. Failing: ['d1']",
                tags: &["baseline_only_key", "float_leaf", "int_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[],
                baseline: &[],
                coerce_error_key: None,
                expected_rows: &[],
                expected_passed: true,
                expected_summary: "Parity comparison: 0/0 metrics passed",
                tags: &["both_empty"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("j1", "-20"), ("g4", "66.02693122358183")],
                baseline: &[("v0", "123.28132987929698"), ("j1", "-22.142326299411064"), ("b2", "122"), ("m3", "20.522502546931122"), ("g4", "15.841")],
                coerce_error_key: None,
                expected_rows: &[("g4", 0x405081b93dbd219d_u64, 0x402fae978d4fdf3b_u64, true), ("j1", 0xc034000000000000_u64, 0xc036246f7f1154cb_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 2/2 metrics passed",
                tags: &["baseline_only_key", "float_leaf", "int_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("s0", "21.111588269731207"), ("l1", "70.34515826919545"), ("i2", ""), ("c3", "--")],
                baseline: &[("s0", "7.301776e+01"), ("l1", "72"), ("i2", "109.02825186028036"), ("c3", "13.587")],
                coerce_error_key: Some("c3"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["float_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("v1", "9.473131e+01"), ("l2", "12x"), ("r3", "-9.138405978248997"), ("h4", "77.838")],
                baseline: &[("b0", "-7.098123979221469"), ("v1", "-9.833297683718946"), ("l2", "-22.97560833056056"), ("r3", "11"), ("h4", "17.287052916632774")],
                coerce_error_key: Some("l2"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["baseline_only_key", "float_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("n0", "1.398231e+01"), ("x1", "80.51080535550241"), ("z2", "71.973"), ("l3", "139")],
                baseline: &[("n0", "-21.628322271549074"), ("x1", "26.07087207245648"), ("z2", ""), ("l3", "0.0")],
                coerce_error_key: Some("z2"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["bool_leaf", "float_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("n0", "84.72425249029621"), ("t1", "62.37942829630762"), ("f2", "0.5164575277294006")],
                baseline: &[("n0", "0.0"), ("t1", "41.49715803423102"), ("f2", "19")],
                coerce_error_key: None,
                expected_rows: &[("f2", 0x3fe086d1efebdd80_u64, 0x4033000000000000_u64, false), ("n0", 0x40552e5a271df79a_u64, 0x0000000000000000_u64, true), ("t1", 0x404f30911b3de8bc_u64, 0x4044bfa2dfdcfba2_u64, true)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 2/3 metrics passed. Failing: ['f2']",
                tags: &["bool_leaf", "float_leaf", "int_leaf"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("v0", "99.335"), ("e1", "163"), ("u2", "-14"), ("f3", "107")],
                baseline: &[("v0", "70.15807077358318"), ("e1", "145.31079060838775"), ("u2", "0.0"), ("f3", "inf")],
                coerce_error_key: None,
                expected_rows: &[("e1", 0x4064600000000000_u64, 0x406229f1ff255dbd_u64, true), ("f3", 0x405ac00000000000_u64, 0x7ff0000000000000_u64, false), ("u2", 0xc02c000000000000_u64, 0x0000000000000000_u64, false), ("v0", 0x4058d570a3d70a3d_u64, 0x40518a1dd4e0bf90_u64, true)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 2/4 metrics passed. Failing: ['f3', 'u2']",
                tags: &["bool_leaf", "float_leaf", "inf_leaf", "int_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("p0", "nan")],
                baseline: &[("p0", "16.890163299259143")],
                coerce_error_key: None,
                expected_rows: &[("p0", 0x7ff8000000000000_u64, 0x4030e3e1bdf26ae0_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 0/1 metrics passed. Failing: ['p0']",
                tags: &["float_leaf", "nan_leaf"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("w0", "40.76039924248842"), ("j1", "--"), ("v2", "123.25398330638217")],
                baseline: &[("w0", "132"), ("j1", "95.27507695393754"), ("v2", "52.580051350197394")],
                coerce_error_key: Some("j1"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["float_leaf", "int_leaf", "non_numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("o0", "0.0"), ("f1", "61")],
                baseline: &[("o0", ""), ("f1", "61.759318021574614")],
                coerce_error_key: Some("o0"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["bool_leaf", "float_leaf", "int_leaf", "non_numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[],
                baseline: &[("e0", "71")],
                coerce_error_key: None,
                expected_rows: &[],
                expected_passed: true,
                expected_summary: "Parity comparison: 0/0 metrics passed",
                tags: &["baseline_only_key", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("a0", "59.99941363220309"), ("r1", "inf"), ("n2", "abc"), ("t3", "81"), ("c4", "24")],
                baseline: &[("a0", "-12"), ("r1", "-24.59013707215203"), ("n2", "1.0"), ("t3", "1.2.3")],
                coerce_error_key: Some("n2"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["bool_leaf", "candidate_only_key", "float_leaf", "inf_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[],
                baseline: &[],
                coerce_error_key: None,
                expected_rows: &[],
                expected_passed: true,
                expected_summary: "Parity comparison: 0/0 metrics passed",
                tags: &["both_empty"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("g0", "0.8056999035316215"), ("q1", "148.73631384492197"), ("j2", "78.718")],
                baseline: &[("g0", "1.0"), ("q1", "inf"), ("j2", "1.0")],
                coerce_error_key: None,
                expected_rows: &[("g0", 0x3fe9c84b2a01e09e_u64, 0x3ff0000000000000_u64, false), ("j2", 0x4053adf3b645a1cb_u64, 0x3ff0000000000000_u64, true), ("q1", 0x4062978fe20d7105_u64, 0x7ff0000000000000_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 1/3 metrics passed. Failing: ['g0', 'q1']",
                tags: &["bool_leaf", "float_leaf", "inf_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("t0", "5"), ("s1", "0.0"), ("q2", "0.888263525103943"), ("s3", "130")],
                baseline: &[("t0", "1.2.3"), ("s1", "-7.86835564410768"), ("q2", "167"), ("s3", "31.695305397611435")],
                coerce_error_key: Some("t0"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["bool_leaf", "float_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("k0", "32.19925386095818"), ("f1", "154"), ("d2", "131.37171100462888"), ("s3", "77.443")],
                baseline: &[("f1", "188"), ("d2", "7.575136e+01"), ("s3", "39.190277169056074")],
                coerce_error_key: None,
                expected_rows: &[("d2", 0x40606be50e7a0e38_u64, 0x4052f0164840e172_u64, true), ("f1", 0x4063400000000000_u64, 0x4067800000000000_u64, false), ("s3", 0x40535c5a1cac0831_u64, 0x4043985b009522ba_u64, true)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 2/3 metrics passed. Failing: ['f1']",
                tags: &["candidate_only_key", "float_leaf", "int_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("k1", "38.31523613708695"), ("i2", "nan"), ("n3", "147"), ("s4", "89.389")],
                baseline: &[("f0", "-8.49386884303263"), ("k1", "99"), ("i2", "0.0"), ("n3", "196"), ("s4", "41")],
                coerce_error_key: None,
                expected_rows: &[("i2", 0x7ff8000000000000_u64, 0x0000000000000000_u64, false), ("k1", 0x40432859a861a725_u64, 0x4058c00000000000_u64, false), ("n3", 0x4062600000000000_u64, 0x4068800000000000_u64, false), ("s4", 0x405658e560418937_u64, 0x4044800000000000_u64, true)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 1/4 metrics passed. Failing: ['i2', 'k1', 'n3']",
                tags: &["baseline_only_key", "bool_leaf", "float_leaf", "int_leaf", "nan_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("s0", "113"), ("w1", "58.568035852454756"), ("z2", "--"), ("t3", "65.08345386289076"), ("d4", "95.253")],
                baseline: &[("s0", "96"), ("w1", "145"), ("z2", "24.237513839328184"), ("t3", "129.206460152617"), ("d4", "abc")],
                coerce_error_key: Some("d4"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["float_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("l0", "180"), ("f1", "86.93305893023002"), ("i2", "70.72701702935518"), ("m3", "39.76761424193684")],
                baseline: &[("l0", "0.718636130868534"), ("f1", "97.14409500436213"), ("i2", "35"), ("m3", "27")],
                coerce_error_key: None,
                expected_rows: &[("f1", 0x4055bbb73ccda509_u64, 0x40584938da40d026_u64, false), ("i2", 0x4051ae87726f2dcc_u64, 0x4041800000000000_u64, true), ("l0", 0x4066800000000000_u64, 0x3fe6ff1132f9bd11_u64, true), ("m3", 0x4043e2412ef88802_u64, 0x403b000000000000_u64, true)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 3/4 metrics passed. Failing: ['f1']",
                tags: &["float_leaf", "int_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("o0", "0.8983487245179524"), ("o1", "nan")],
                baseline: &[("o1", "24.741374527689118")],
                coerce_error_key: None,
                expected_rows: &[("o1", 0x7ff8000000000000_u64, 0x4038bdcab8968320_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 0/1 metrics passed. Failing: ['o1']",
                tags: &["candidate_only_key", "float_leaf", "nan_leaf"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[],
                baseline: &[],
                coerce_error_key: None,
                expected_rows: &[],
                expected_passed: true,
                expected_summary: "Parity comparison: 0/0 metrics passed",
                tags: &["both_empty"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[],
                baseline: &[],
                coerce_error_key: None,
                expected_rows: &[],
                expected_passed: true,
                expected_summary: "Parity comparison: 0/0 metrics passed",
                tags: &["both_empty"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("o1", "inf")],
                baseline: &[("r0", "--"), ("o1", "1.0")],
                coerce_error_key: None,
                expected_rows: &[("o1", 0x7ff0000000000000_u64, 0x3ff0000000000000_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["baseline_only_key", "bool_leaf", "inf_leaf", "non_numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("w0", "--"), ("k1", "135.37315331526415")],
                baseline: &[("w0", "0.8067921154210228"), ("k1", "-28.096037319433286")],
                coerce_error_key: Some("w0"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["float_leaf", "non_numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("s0", "12x"), ("s1", "80"), ("h2", "45")],
                baseline: &[("s0", "170"), ("s1", "0.0"), ("h2", "-19.89074498038377")],
                coerce_error_key: Some("s0"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["bool_leaf", "float_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("w0", "90.68582847050658"), ("x1", "43"), ("s2", "47.934346539698")],
                baseline: &[("w0", "0.6631577162910296"), ("x1", "126.22820840919826"), ("s2", "1.2.3")],
                coerce_error_key: Some("s2"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["float_leaf", "int_leaf", "non_numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("r0", "30.137526941423616")],
                baseline: &[("r0", "0.6311187729262334")],
                coerce_error_key: None,
                expected_rows: &[("r0", 0x403e2334f733bbbc_u64, 0x3fe4321fff3383ab_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["float_leaf"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("f1", "-17"), ("a2", "-32.64639278333765"), ("b3", "15.259692501354593")],
                baseline: &[("l0", "2.382250e+01"), ("f1", "1.0"), ("b3", "")],
                coerce_error_key: Some("b3"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["baseline_only_key", "bool_leaf", "candidate_only_key", "float_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("h0", "5.368524e+01"), ("v1", "0.9176280930134267"), ("p2", "nan")],
                baseline: &[("h0", "0.11685788409820419"), ("v1", "41.27551718082259"), ("p2", "41.29256479537682")],
                coerce_error_key: None,
                expected_rows: &[("h0", 0x404ad7b5f1bef49d_u64, 0x3fbdea65f67b4690_u64, true), ("p2", 0x7ff8000000000000_u64, 0x4044a572c3620d5c_u64, false), ("v1", 0x3fed5d35972c45bf_u64, 0x4044a34425a08f40_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 1/3 metrics passed. Failing: ['p2', 'v1']",
                tags: &["float_leaf", "nan_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("e0", "0.0")],
                baseline: &[("e0", "90")],
                coerce_error_key: None,
                expected_rows: &[("e0", 0x0000000000000000_u64, 0x4056800000000000_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 0/1 metrics passed. Failing: ['e0']",
                tags: &["bool_leaf", "int_leaf"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("n0", "-35.36553019037778"), ("j1", "1.0"), ("v2", "5.055727e+01")],
                baseline: &[("n0", "37.996962120100264"), ("j1", "1.2.3"), ("v2", "1.0"), ("o3", "3.426487e+01")],
                coerce_error_key: Some("j1"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["baseline_only_key", "bool_leaf", "float_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("k0", "119.99602619116243")],
                baseline: &[("k0", "97.10440320278744"), ("c1", "inf")],
                coerce_error_key: None,
                expected_rows: &[("k0", 0x405dffbee4a34022_u64, 0x405846ae8ac56476_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["baseline_only_key", "float_leaf", "inf_leaf"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("p0", "abc"), ("h1", "6.613474146165254"), ("x2", "26.71708650013204")],
                baseline: &[("p0", "95"), ("x2", "84"), ("x3", "181")],
                coerce_error_key: Some("p0"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["baseline_only_key", "candidate_only_key", "float_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[],
                baseline: &[("t0", "43.647899968807934")],
                coerce_error_key: None,
                expected_rows: &[],
                expected_passed: true,
                expected_summary: "Parity comparison: 0/0 metrics passed",
                tags: &["baseline_only_key", "float_leaf"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("n0", "31"), ("o1", "85"), ("f2", "102.3983562922559"), ("a3", "12x"), ("i4", "52.9114221757855")],
                baseline: &[("n0", "135.58879626566429"), ("o1", "60.786"), ("f2", "1.0"), ("a3", "54.01653620640312"), ("i4", "7.4789342739855265")],
                coerce_error_key: Some("a3"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["bool_leaf", "float_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("d0", "140.26804079212312"), ("f1", "7.923019983707505"), ("s2", "1.0")],
                baseline: &[("d0", "-33.72549213421998"), ("f1", "-22.691829011635466"), ("s2", "-44.419634377744764")],
                coerce_error_key: None,
                expected_rows: &[("d0", 0x40618893ca488535_u64, 0xc040dcdced1efd72_u64, true), ("f1", 0x401fb12c268e5010_u64, 0xc036b11bb4c365f9_u64, true), ("s2", 0x3ff0000000000000_u64, 0xc04635b6944c5875_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 3/3 metrics passed",
                tags: &["bool_leaf", "float_leaf"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[],
                baseline: &[],
                coerce_error_key: None,
                expected_rows: &[],
                expected_passed: true,
                expected_summary: "Parity comparison: 0/0 metrics passed",
                tags: &["both_empty"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("f0", "102.80343721193796"), ("q1", "-3.3580783487120485"), ("p2", "49"), ("r3", "nan")],
                baseline: &[("f0", ""), ("q1", "55"), ("p2", "18.74431080723069"), ("r3", "127.79858821529936")],
                coerce_error_key: Some("f0"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["float_leaf", "int_leaf", "nan_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("t0", "--"), ("r1", "39"), ("s2", "--")],
                baseline: &[("t0", "68.85738303218811"), ("r1", "63.63780924454987"), ("s2", "abc")],
                coerce_error_key: Some("s2"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["float_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("e0", ""), ("w1", "-10.45264960475565"), ("j2", "121"), ("p3", "12x"), ("r4", "1.0")],
                baseline: &[("e0", "37.129685164774564"), ("w1", "79.493"), ("j2", "1.0"), ("p3", "-26.62935255703518")],
                coerce_error_key: Some("e0"),
                expected_rows: &[],
                expected_passed: false,
                expected_summary: "",
                tags: &["bool_leaf", "candidate_only_key", "float_leaf", "int_leaf", "non_numeric_str", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("f0", "30.29840622382642"), ("m1", "0.0"), ("l2", "45.570958832966895"), ("x3", "0.0")],
                baseline: &[("f0", "27"), ("m1", "0.38197584118082195"), ("l2", "10.53027167542173"), ("x3", "26.302101641677055")],
                coerce_error_key: None,
                expected_rows: &[("f0", 0x403e4c6459ac41e0_u64, 0x403b000000000000_u64, true), ("l2", 0x4046c9152dd57a42_u64, 0x40250f7fc4dfdce8_u64, true), ("m1", 0x0000000000000000_u64, 0x3fd8724acc6ef546_u64, false), ("x3", 0x0000000000000000_u64, 0x403a4d56887f1224_u64, false)],
                expected_passed: false,
                expected_summary: "Parity FAILED: 2/4 metrics passed. Failing: ['m1', 'x3']",
                tags: &["bool_leaf", "float_leaf", "numeric_str"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[("g0", "147")],
                baseline: &[("g0", "69.22837316448005")],
                coerce_error_key: None,
                expected_rows: &[("g0", 0x4062600000000000_u64, 0x40514e9daa7a2e74_u64, true)],
                expected_passed: true,
                expected_summary: "Parity comparison: 1/1 metrics passed",
                tags: &["float_leaf", "int_leaf"],
            },
            FrozenCpSatComparisonCase {
                candidate: &[],
                baseline: &[("q0", "18"), ("v1", "8.666307e+01")],
                coerce_error_key: None,
                expected_rows: &[],
                expected_passed: true,
                expected_summary: "Parity comparison: 0/0 metrics passed",
                tags: &["baseline_only_key", "int_leaf", "numeric_str"],
            },
        ];

        #[test]
        fn frozen_cp_sat_comparison_matches_golden_corpus() {
            for case in FROZEN_CP_SAT_COMPARISON_GOLDEN {
                let expected = to_map(case.baseline);
                let actual = to_map(case.candidate);
                let result = compare_metric_maps(&expected, &actual, "total_manhattan_wirelength");
                match (case.coerce_error_key, result) {
                    (Some(key), Err(err)) => assert_eq!(&err.key, key, "tags={:?}", case.tags),
                    (Some(key), Ok(_)) => panic!("expected coerce error on {:?}, got rows -- tags={:?}", key, case.tags),
                    (None, Err(err)) => panic!("unexpected coerce error on {:?} -- tags={:?}", err.key, case.tags),
                    (None, Ok(rows)) => {
                        assert_eq!(rows.len(), case.expected_rows.len(), "tags={:?}", case.tags);
                        for (got, want) in rows.iter().zip(case.expected_rows.iter()) {
                            assert_eq!(got.name, want.0, "tags={:?}", case.tags);
                            let got_a = f64::from_bits(got.actual.to_bits());
                            let want_a = f64::from_bits(want.1);
                            let got_e = f64::from_bits(got.expected.to_bits());
                            let want_e = f64::from_bits(want.2);
                            let bits_ok = |g: f64, w: f64| (g.is_nan() && w.is_nan()) || g.to_bits() == w.to_bits();
                            assert!(bits_ok(got_a, want_a) && bits_ok(got_e, want_e), "tags={:?}: got row {{}} vs expected {{?}}", case.tags);
                            assert_eq!(got.passed, want.3, "tags={:?}", case.tags);
                        }
                        let (passed, summary) = parity_summary(&rows);
                        assert_eq!(passed, case.expected_passed, "tags={:?}", case.tags);
                        assert_eq!(summary, case.expected_summary, "tags={:?}", case.tags);
                    }
                }
            }
        }

        /// Q2 non-vacuity guard.
        #[test]
        fn frozen_cp_sat_comparison_corpus_is_non_vacuous() {
            let n = FROZEN_CP_SAT_COMPARISON_GOLDEN.len() as u32;
            let count = |tag: &str| FROZEN_CP_SAT_COMPARISON_GOLDEN.iter()
                .filter(|c| c.tags.contains(&tag)).count() as u32;
            assert!(count("numeric_str") * 100 >= n * 15, "numeric_str: only {}/{} (need >= 15%) -- string-number coercion leaves must be common (the oracle's float('...') path)", count("numeric_str"), n);
            assert!(count("non_numeric_str") >= 3, "non_numeric_str: only {} (need >= 3) -- non-numeric strings must be present (coercion failure boundary)", count("non_numeric_str"));
            assert!(count("wirelength_in_intersection") >= 8, "wirelength_in_intersection: only {} (need >= 8) -- the 5%-tolerance context rule must be exercised", count("wirelength_in_intersection"));
            assert!(count("candidate_only_key") >= 3, "candidate_only_key: only {} (need >= 3) -- asymmetric candidate-only keys must be exercised", count("candidate_only_key"));
            assert!(count("baseline_only_key") >= 3, "baseline_only_key: only {} (need >= 3) -- asymmetric baseline-only keys must be exercised", count("baseline_only_key"));
            assert!(count("nan_leaf") >= 2, "nan_leaf: only {} (need >= 2) -- NaN must appear among raw leaves", count("nan_leaf"));
            assert!(count("inf_leaf") >= 2, "inf_leaf: only {} (need >= 2) -- infinities must appear among raw leaves", count("inf_leaf"));
            assert!(count("bool_leaf") >= 2, "bool_leaf: only {} (need >= 2) -- float(True)==1.0 semantics must be pinned", count("bool_leaf"));
            assert!(count("both_empty") >= 1, "both_empty: only {} (need >= 1) -- the empty-vs-empty shape must be exercised", count("both_empty"));
            assert!(count("zero_baseline_context") >= 3, "zero_baseline_context: only {} (need >= 3) -- the baseline==0 wirelength branch must be exercised", count("zero_baseline_context"));
        }
    }
// --- END generated by scripts/gen_oracle_freeze.py: cp_sat_comparison ---

#[cfg(test)]
// compare_metric_maps returns a Result whose Err arm is unreachable for the
// well-formed HashMaps these tests construct; unwrap is the readable form and
// this module is test-only, so the deny lints are relaxed here (house style:
// constraint_merge.rs's own test module does the same).
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod cp_sat_comparison_core_tests {
    use super::*;

    #[cfg_attr(test, test)]
    fn py_float_str_matches_python_float() {
        for (s, want) in [
            ("1.5", 1.5),
            (" 2.5 ", 2.5),
            ("+3.0", 3.0),
            ("-4", -4.0),
            (".5", 0.5),
            ("5.", 5.0),
            ("1_000.5", 1000.5),
            ("1e3", 1000.0),
            ("1E-2", 0.01),
            ("inf", f64::INFINITY),
            ("-Infinity", f64::NEG_INFINITY),
            ("nan", f64::NAN),
            ("\t7.25\n", 7.25),
        ] {
            let got = py_float_str(s).unwrap_or(f64::NAN);
            let ok = (got.is_nan() && want.is_nan()) || got == want;
            assert!(ok, "float({s:?}): got {got:?} want {want:?}");
        }
    }

    #[cfg_attr(test, test)]
    fn py_float_str_rejects_like_python() {
        for s in [
            "", "   ", "_", "_1", "1_", "1__0", "abc", "1.5x", "e5", "1e_5",
            "1._5", ".5_", "0x10", "1,5", "-",
        ] {
            assert!(py_float_str(s).is_none(), "float({s:?}) must raise");
        }
    }

    #[cfg_attr(test, test)]
    fn encode_f64_round_trips_through_py_float_str() {
        for v in [
            0.0, -0.0, 1.5, -1234.5678901234567, 1e300, 5e-324, f64::INFINITY,
            f64::NEG_INFINITY, f64::NAN,
        ] {
            let back = py_float_str(&encode_f64(v)).unwrap_or(f64::NAN);
            let ok = (back.is_nan() && v.is_nan())
                || back.to_bits() == v.to_bits();
            assert!(ok, "round trip of {v:?}: got {back:?}");
        }
    }

    #[cfg_attr(test, test)]
    fn core_matches_oracle_semantics_on_key_shapes() {
        // empty intersection -> vacuous pass
        let rows = compare_metric_maps(
            &hm(&[("a", "1.0")]),
            &hm(&[("b", "2.0")]),
            "none",
        )
        .unwrap();
        assert!(rows.is_empty());
        let (passed, summary) = parity_summary(&rows);
        assert!(passed);
        assert_eq!(summary, "Parity comparison: 0/0 metrics passed");

        // wirelength tolerance boundary: 105/100 passes, 105.1/100 fails
        let rows = compare_metric_maps(
            &hm(&[("wl", "100.0")]),
            &hm(&[("wl", "105.0")]),
            "wl",
        )
        .unwrap();
        assert!(rows[0].passed);

        // failing summary carries the Python list repr
        let rows = compare_metric_maps(
            &hm(&[("a", "2.0"), ("b", "3.0")]),
            &hm(&[("a", "1.0"), ("b", "2.0")]),
            "none",
        )
        .unwrap();
        let (passed, summary) = parity_summary(&rows);
        assert!(!passed);
        assert!(summary.contains("Failing: ['a', 'b']"));
        assert!(summary.starts_with("Parity FAILED: 0/2 metrics passed"));
    }

    fn hm(pairs: &[(&str, &str)]) -> HashMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| ((*k).to_string(), (*v).to_string()))
            .collect()
    }
}

// --- BEGIN generated by scripts/gen_wasm_test_registry.py: cp_sat_comparison ---
/// Every `#[test]` in this module, as a callable the `wasm32`
/// entry point can invoke by index.  Generated because these
/// functions are private to this module and unreachable from
/// anywhere a registry could otherwise live.
pub const WASM_TESTS: &[(&str, fn())] = &[
    ("cp_sat_comparison::py_float_str_matches_python_float", py_float_str_matches_python_float),
    ("cp_sat_comparison::py_float_str_rejects_like_python", py_float_str_rejects_like_python),
    ("cp_sat_comparison::encode_f64_round_trips_through_py_float_str", encode_f64_round_trips_through_py_float_str),
    ("cp_sat_comparison::core_matches_oracle_semantics_on_key_shapes", core_matches_oracle_semantics_on_key_shapes),
];
// --- END generated by scripts/gen_wasm_test_registry.py: cp_sat_comparison ---
