//! Wave 4 Phase 4 — regression slice: CP-SAT comparison kernel.
//!
//! `temper_placer/regression/cp_sat_comparison.py` (pinned verbatim as the
//! oracle `_cp_sat_comparison_py_oracle.py`, commit `0a29f15e3`) is fully
//! portable compute — `compare_metric_dicts` (the Pareto-style per-metric
//! gate, the wirelength ratio/tolerance rule, the `:.2f`/`:.3f`/`:.4f`
//! detail strings, the summary line, and the failing-metric list repr)
//! migrated into `temper-design-bundle`. The Python module becomes a
//! delegation shim over the returned records.
//!
//! Numeric-fidelity notes (each pinned by the differential):
//!
//! - Values are converted with Python `builtins.float` (the oracle's
//!   `float(candidate_scores.get(...))`) — int/float/str-number leaves all
//!   convert exactly like the oracle, and a non-numeric leaf raises the same
//!   `ValueError`/`TypeError` family the oracle's `float()` raises.
//! - Fixed-point `:.2f`/`:.3f`/`:.4f` formatting is measured CPython-parity
//!   (the validation-slice precedent, 100k/100k on random values), including
//!   Python's NaN spelling — `f"{nan:.Nf}"` is `"nan"`, not Rust's `"NaN"`
//!   (`py_fixed`), pinned by the NaN-leaf differential case.
//! - The summary's `Failing: ['a', 'b']` list is Python's repr of a list of
//!   str; rendered here as single-quoted names joined by `, `. Metric names
//!   are score-dict keys (realistically simple identifiers); a name carrying
//!   a quote/backslash is a documented narrowing (Python repr would escape
//!   it).
//! - `bool` interpolation in the detail lines renders `True`/`False`
//!   (Python), never Rust's `true`/`false`.
//! - The metric iteration order is `sorted()` of the key intersection —
//!   deterministic, so no set/dict hash-order dependence survives.
//! - Empty intersection: `passed=True`, no comparisons, summary
//!   `"Parity comparison: 0/0 metrics passed"` — the oracle's vacuous-true
//!   semantics, preserved exactly.
//! - Non-string keys: a candidate key that fails `String` extraction but is
//!   ALSO present in the baseline is in the oracle's key intersection, where
//!   the oracle's `sorted(metrics)` raises `TypeError` on the mixed-type key
//!   set (the realistic shape — a stray non-string key alongside string
//!   metric names). The kernel raises the same class rather than silently
//!   dropping the metric; a non-string key on ONE side only is not in the
//!   intersection and is ignored by both arms.

use std::collections::HashMap;

use pyo3::exceptions::{PyTypeError, PyValueError};
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyDictMethods, PyList, PyModule, PyString};

// ---------------------------------------------------------------------------
// Plain-Rust core (no pyo3) — the FREEZE target.
//
// `compare_metric_maps` is the portable compute behind the pyfunction
// `compare_metric_dicts`: it takes the score dicts as plain
// `HashMap<String, String>` (leaf values in their string form) and returns
// plain rows. The pyo3 wrapper below is a thin adapter: PyDict -> HashMap ->
// core -> boxed rows. Keeping the core pyo3-free lets the frozen golden
// corpus (generated by scripts/gen_oracle_freeze.py --spec cp_sat_comparison)
// exercise it without a Python interpreter, i.e. on the wasm32 tier.
// ---------------------------------------------------------------------------

/// One per-metric comparison row (the portable projection of the oracle's
/// `MetricComparison` dataclass): `expected` is the baseline (JAX) value,
/// `actual` the candidate (CP-SAT) value, and `note` the human-readable
/// detail string rendered exactly like the oracle's `detail`.
#[derive(Debug, Clone, PartialEq)]
pub struct MetricComparisonRow {
    pub name: String,
    pub expected: f64,
    pub actual: f64,
    pub passed: bool,
    pub note: String,
}

/// A score leaf failed Python's builtin `float()` conversion (the oracle
/// raises `ValueError` for a non-numeric string; the pyo3 wrapper maps this
/// onto `PyValueError`). Key/type errors on non-string KEYS cannot occur in
/// this core by construction (`HashMap<String, _>`); the pyo3 wrapper owns
/// that check and raises the oracle's `TypeError` class itself.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FloatCoerceError {
    pub key: String,
    pub value: String,
}

impl FloatCoerceError {
    /// Mirrors CPython's `ValueError` text for `float("...")`.
    pub fn message(&self) -> String {
        format!(
            "could not convert string to float: {}",
            debug_quote(&self.value)
        )
    }
}

/// Minimal single-quoted Python-repr-style quoting for the error message
/// (metric leaves are realistically simple; escapes beyond backslash/quote
/// are a documented narrowing, same as the failing-list repr below).
fn debug_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for c in s.chars() {
        match c {
            '\'' => out.push_str("\\'"),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('\'');
    out
}

/// Python's `bool` string rendering ("True"/"False").
fn py_bool(b: bool) -> &'static str {
    if b {
        "True"
    } else {
        "False"
    }
}

/// Python's fixed-point `:.Nf` rendering, including its NaN spelling: Rust's
/// `{:.N}` writes `NaN`, Python's `f"{nan:.Nf}"` writes `nan` (infinities
/// already agree — `inf`/`-inf` on both arms).
fn py_fixed(value: f64, precision: usize) -> String {
    if value.is_nan() {
        "nan".to_string()
    } else {
        format!("{value:.precision$}")
    }
}

/// Parse a string leaf exactly like Python's builtin `float(str)`
/// (the oracle's `float(candidate_scores.get(...))` semantics):
///
/// - surrounding Unicode whitespace is stripped;
/// - an optional sign; case-insensitive `inf`/`infinity`/`nan`;
/// - otherwise a decimal significand with optional exponent, where `_` is
///   accepted only BETWEEN digits (Python's numeric-literal underscore rule:
///   `"1_000.5"` parses, `"1__0"`, `"1_"`, `"._5"`, `"1e_5"` do not);
/// - anything else is `None` (the caller raises the ValueError class);
/// - the cleaned literal is delegated to `f64::from_str`, which is correctly
///   rounded exactly like CPython's dtoa, so accepted strings convert
///   bit-identically to the oracle.
fn py_float_str(raw: &str) -> Option<f64> {
    let t = raw.trim();
    let mut rest = t;
    let mut neg = false;
    if let Some(r) = rest.strip_prefix('+') {
        rest = r;
    } else if let Some(r) = rest.strip_prefix('-') {
        rest = r;
        neg = true;
    }
    let lower = rest.to_ascii_lowercase();
    match lower.as_str() {
        "inf" | "infinity" => {
            return Some(if neg {
                f64::NEG_INFINITY
            } else {
                f64::INFINITY
            });
        }
        "nan" => return Some(f64::NAN),
        _ => {}
    }
    let cleaned = clean_decimal(rest)?;
    let v: f64 = cleaned.parse().ok()?;
    Some(if neg { -v } else { v })
}

/// Validate + normalize a Python decimal-float literal: digits with
/// underscore separators (only ever between two digits), an optional
/// fractional part, and an optional exponent. Returns the literal with
/// underscores removed (Rust's parser rejects them), or `None` when the
/// string is not a valid Python float literal.
fn clean_decimal(body: &str) -> Option<String> {
    let cs: Vec<char> = body.chars().collect();
    let mut out = String::with_capacity(cs.len());
    let mut i = 0usize;
    let mut last_was_digit = false;
    let mut mantissa_digits = 0usize;

    let scan_digits = |out: &mut String, i: &mut usize, last_was_digit: &mut bool| -> usize {
        let mut count = 0usize;
        while *i < cs.len() {
            match cs[*i] {
                c if c.is_ascii_digit() => {
                    out.push(c);
                    count += 1;
                    *last_was_digit = true;
                    *i += 1;
                }
                '_' => {
                    let next_is_digit = matches!(cs.get(*i + 1), Some(c) if c.is_ascii_digit());
                    if !(next_is_digit && *last_was_digit) {
                        break;
                    }
                    *last_was_digit = false;
                    *i += 1;
                }
                _ => break,
            }
        }
        count
    };

    mantissa_digits += scan_digits(&mut out, &mut i, &mut last_was_digit);
    if matches!(cs.get(i), Some('.')) {
        i += 1;
        out.push('.');
        last_was_digit = false;
        mantissa_digits += scan_digits(&mut out, &mut i, &mut last_was_digit);
    }
    if mantissa_digits == 0 {
        return None;
    }
    if matches!(cs.get(i), Some('e') | Some('E')) {
        i += 1;
        out.push('e');
        last_was_digit = false;
        if matches!(cs.get(i), Some('+')) {
            i += 1;
        } else if matches!(cs.get(i), Some('-')) {
            out.push('-');
            i += 1;
        }
        if scan_digits(&mut out, &mut i, &mut last_was_digit) == 0 {
            return None;
        }
    }
    if i != cs.len() {
        return None;
    }
    Some(out)
}

/// Encode a value that has ALREADY been converted through Python's builtin
/// `float()` (int/float/bool/... leaves in the wrapper) into the string form
/// the plain core parses back bit-identically. Rust's `Display` for `f64` is
/// the shortest round-trip repr, and `f64::from_str` is correctly rounded, so
/// the round trip is exact; infinities and NaN get their Python spellings.
fn encode_f64(v: f64) -> String {
    if v.is_nan() {
        "nan".to_string()
    } else if v == f64::INFINITY {
        "inf".to_string()
    } else if v == f64::NEG_INFINITY {
        "-inf".to_string()
    } else {
        format!("{v}")
    }
}

/// Compare two score maps per-metric — the verbatim port of the oracle's
/// `compare_metric_dicts` loop over the sorted key intersection (see the
/// module docs above for the pinned numeric/format semantics).
///
/// `expected` holds the baseline (JAX) scores, `actual` the candidate
/// (CP-SAT) scores, and `context` the metric name the lower-is-better 5%
/// tolerance rule applies to (the oracle's `wirelength_metric` argument).
pub fn compare_metric_maps(
    expected: &HashMap<String, String>,
    actual: &HashMap<String, String>,
    context: &str,
) -> Result<Vec<MetricComparisonRow>, FloatCoerceError> {
    let mut names: Vec<&String> = expected
        .keys()
        .filter(|k| actual.contains_key(*k))
        .collect();
    names.sort_unstable();

    let mut rows: Vec<MetricComparisonRow> = Vec::new();
    for name in names {
        // Candidate value first, then baseline — the oracle's evaluation
        // order (which of the two `float()` calls raises first is pinned).
        let av = &actual[name];
        let ev = &expected[name];
        let cand_val = py_float_str(av)
            .ok_or_else(|| FloatCoerceError { key: name.clone(), value: av.clone() })?;
        let base_val = py_float_str(ev)
            .ok_or_else(|| FloatCoerceError { key: name.clone(), value: ev.clone() })?;

        let (passed, note) = if name.as_str() == context {
            // Lower is better, within a 5% tolerance.
            let (ratio, passed) = if base_val > 0.0 {
                (cand_val / base_val, cand_val <= base_val * 1.05)
            } else {
                // baseline 0: candidate must be 0 too.
                (f64::INFINITY, cand_val <= 0.0)
            };
            (
                passed,
                format!(
                    "{name}: candidate={}, baseline={}, ratio={}, tolerance=1.05, passed={}",
                    py_fixed(cand_val, 2),
                    py_fixed(base_val, 2),
                    py_fixed(ratio, 3),
                    py_bool(passed)
                ),
            )
        } else {
            // Higher is better (default for all oracle metrics), 1e-9 slack.
            let passed = cand_val >= base_val - 1e-9;
            let delta = cand_val - base_val;
            (
                passed,
                format!(
                    "{name}: candidate={}, baseline={}, delta={}, passed={}",
                    py_fixed(cand_val, 4),
                    py_fixed(base_val, 4),
                    py_fixed(delta, 4),
                    py_bool(passed)
                ),
            )
        };

        rows.push(MetricComparisonRow {
            name: name.clone(),
            expected: base_val,
            actual: cand_val,
            passed,
            note,
        });
    }
    Ok(rows)
}

/// Compose the aggregate verdict and the summary line from the comparison
/// rows — the oracle's tail (overall pass flag + the
/// `Parity comparison: n/m metrics passed` /
/// `Parity FAILED: ... Failing: ['a', 'b']` strings).
pub fn parity_summary(rows: &[MetricComparisonRow]) -> (bool, String) {
    let all_passed = rows.iter().all(|r| r.passed);
    let passed_metrics = rows.iter().filter(|r| r.passed).count();
    let total_metrics = rows.len();

    let summary = if all_passed {
        format!("Parity comparison: {passed_metrics}/{total_metrics} metrics passed")
    } else {
        let failing: Vec<String> = rows
            .iter()
            .filter(|r| !r.passed)
            .map(|r| format!("'{}'", r.name))
            .collect();
        format!(
            "Parity FAILED: {passed_metrics}/{total_metrics} metrics passed. Failing: [{}]",
            failing.join(", ")
        )
    };
    (all_passed, summary)
}

/// Call Python's builtin `float()` on a value (the oracle's `float(x)`
/// semantics for NON-string leaves — `float(True)` is `1.0`,
/// `float(None)` raises TypeError). String leaves bypass this and go through
/// [`py_float_str`] inside the core, so `float("1.5")`-style coercions and
/// their error class stay reproducible without a Python interpreter.
fn py_builtin_float(py: Python<'_>, value: &Bound<'_, PyAny>) -> PyResult<f64> {
    let f = py.import("builtins")?.getattr("float")?;
    let out = f.call1((value,))?;
    out.extract::<f64>()
}

/// Compare two score dicts per-metric. Thin pyo3 adapter over the plain
/// [`compare_metric_maps`] core: PyDict -> HashMap -> core -> boxed rows.
/// Returns a dict with `passed`, `comparisons` (a list of `{name,
/// cp_sat_value, jax_value, passed, detail}` dicts in sorted metric-name
/// order) and `summary`. Public API unchanged.
#[pyfunction]
#[pyo3(signature = (candidate_scores, baseline_scores, wirelength_metric))]
fn compare_metric_dicts(
    py: Python<'_>,
    candidate_scores: &Bound<'_, PyDict>,
    baseline_scores: &Bound<'_, PyDict>,
    wirelength_metric: String,
) -> PyResult<Py<PyDict>> {
    // metrics = set(candidate.keys()) & set(baseline.keys())
    let mut metric_names: Vec<String> = Vec::new();
    for key in candidate_scores.keys() {
        match key.extract::<String>() {
            Ok(name) => {
                if baseline_scores.get_item(&name)?.is_some() {
                    metric_names.push(name);
                }
            }
            // A non-string candidate key that is also present in the baseline
            // is in the oracle's key intersection. The oracle's
            // `sorted(metrics)` then raises TypeError on a mixed-type key set
            // (the realistic shape — a stray non-string key alongside string
            // metric names); raise the same class rather than silently
            // dropping the metric from the comparison.
            Err(_) => {
                if baseline_scores.get_item(&key)?.is_some() {
                    return Err(PyTypeError::new_err(
                        "score-dict keys must be strings: non-string key present in both dicts (the oracle's sorted(metrics) raises TypeError on a mixed-type key set)",
                    ));
                }
            }
        }
    }

    // PyDict -> HashMap<String, String>. String leaves pass through verbatim
    // (the core re-implements Python's `float(str)` coercion, including its
    // ValueError class); every other leaf type is converted through Python's
    // builtin `float()` exactly like the oracle and encoded into an exact
    // string round trip.
    let mut expected_map: HashMap<String, String> = HashMap::new();
    let mut actual_map: HashMap<String, String> = HashMap::new();
    for name in &metric_names {
        let cand_leaf = candidate_scores.get_item(name)?.unwrap();
        actual_map.insert(
            name.clone(),
            if cand_leaf.is_instance_of::<PyString>() {
                cand_leaf.extract::<String>()?
            } else {
                encode_f64(py_builtin_float(py, &cand_leaf)?)
            },
        );
        let base_leaf = baseline_scores.get_item(name)?.unwrap();
        expected_map.insert(
            name.clone(),
            if base_leaf.is_instance_of::<PyString>() {
                base_leaf.extract::<String>()?
            } else {
                encode_f64(py_builtin_float(py, &base_leaf)?)
            },
        );
    }

    let rows = compare_metric_maps(&expected_map, &actual_map, &wirelength_metric)
        .map_err(|e| PyValueError::new_err(e.message()))?;
    let (all_passed, summary) = parity_summary(&rows);

    let d = PyDict::new(py);
    d.set_item("passed", all_passed)?;
    let comps = PyList::empty(py);
    for row in &rows {
        let cd = PyDict::new(py);
        cd.set_item("name", &row.name)?;
        cd.set_item("cp_sat_value", row.actual)?;
        cd.set_item("jax_value", row.expected)?;
        cd.set_item("passed", row.passed)?;
        cd.set_item("detail", &row.note)?;
        comps.append(cd)?;
    }
    d.set_item("comparisons", comps)?;
    d.set_item("summary", &summary)?;
    Ok(d.into())
}

#[cfg(test)]
mod cp_sat_comparison_core_tests {
    use super::*;

    #[test]
    fn py_float_str_matches_python_float() {
        for (s, want) in [
            ("1.5", 1.5),
            (" 2.5 ", 2.5),
            ("+3.0", 3.0),
            ("-4", -4.0),
            (".5", 0.5),
            ("5.", 5.0),
            ("1_000.5", 1000.5),
            ("1e3", 1000.0),
            ("1E-2", 0.01),
            ("inf", f64::INFINITY),
            ("-Infinity", f64::NEG_INFINITY),
            ("nan", f64::NAN),
            ("\t7.25\n", 7.25),
        ] {
            let got = py_float_str(s).unwrap_or(f64::NAN);
            let ok = (got.is_nan() && want.is_nan()) || got == want;
            assert!(ok, "float({s:?}): got {got:?} want {want:?}");
        }
    }

    #[test]
    fn py_float_str_rejects_like_python() {
        for s in [
            "", "   ", "_", "_1", "1_", "1__0", "abc", "1.5x", "e5", "1e_5",
            "1._5", ".5_", "0x10", "1,5", "-",
        ] {
            assert!(py_float_str(s).is_none(), "float({s:?}) must raise");
        }
    }

    #[test]
    fn encode_f64_round_trips_through_py_float_str() {
        for v in [
            0.0, -0.0, 1.5, -1234.5678901234567, 1e300, 5e-324, f64::INFINITY,
            f64::NEG_INFINITY, f64::NAN,
        ] {
            let back = py_float_str(&encode_f64(v)).unwrap_or(f64::NAN);
            let ok = (back.is_nan() && v.is_nan())
                || back.to_bits() == v.to_bits();
            assert!(ok, "round trip of {v:?}: got {back:?}");
        }
    }

    #[test]
    fn core_matches_oracle_semantics_on_key_shapes() {
        // empty intersection -> vacuous pass
        let rows = compare_metric_maps(
            &hm(&[("a", "1.0")]),
            &hm(&[("b", "2.0")]),
            "none",
        )
        .unwrap();
        assert!(rows.is_empty());
        let (passed, summary) = parity_summary(&rows);
        assert!(passed);
        assert_eq!(summary, "Parity comparison: 0/0 metrics passed");

        // wirelength tolerance boundary: 105/100 passes, 105.1/100 fails
        let rows = compare_metric_maps(
            &hm(&[("wl", "100.0")]),
            &hm(&[("wl", "105.0")]),
            "wl",
        )
        .unwrap();
        assert!(rows[0].passed);

        // failing summary carries the Python list repr
        let rows = compare_metric_maps(
            &hm(&[("a", "2.0"), ("b", "3.0")]),
            &hm(&[("a", "1.0"), ("b", "2.0")]),
            "none",
        )
        .unwrap();
        let (passed, summary) = parity_summary(&rows);
        assert!(!passed);
        assert!(summary.contains("Failing: ['a', 'b']"));
        assert!(summary.starts_with("Parity FAILED: 0/2 metrics passed"));
    }

    fn hm(pairs: &[(&str, &str)]) -> HashMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| ((*k).to_string(), (*v).to_string()))
            .collect()
    }
}

/// Register the comparison kernel on the `temper_design_bundle_python` module.
pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(compare_metric_dicts, m)?)?;
    Ok(())
}
