//! Wave 4 Phase 4 — regression slice: closure-measurement kernel.
//!
//! The portable compute of `temper_placer/regression/measure_closure.py`
//! (pinned verbatim as the oracle `_measure_closure_py_oracle.py`, commit
//! `0a29f15e3`) migrated into `temper-design-bundle`:
//!
//! | Kernel | Python origin |
//! |---|---|
//! | `compute_drc_clearance_pass_pct` | the `drc_clearance_pass_pct` three-branch rule in `measure_closure` |
//!
//! Oracle retired 2026-08-20 (FREEZE, batch 1): the differential against
//! `_measure_closure_py_oracle.py` is replaced by the frozen golden-vector
//! corpus in this file's own `frozen_tests` module (see
//! `scripts/oracle_freeze_specs/measure_closure.py` for provenance; the
//! oracle file itself is deleted and can be revived from git history only).
//!
//! Design boundaries (argued in-source; see
//! `packages/temper-design-bundle/VERIFICATION.md`):
//!
//! - `measure_closure.py` is a THIN harness over the kept `ClosureTest.run()`
//!   (a JUSTIFIED-KEEP-adjacent harness); its only portable compute is this
//!   one formula. Everything else — ClosureTest construction, the payload
//!   dict assembly (including the `closure_summary` string and the
//!   `errors!r` in the zero-results raise), the JSON CLI — is marshalling
//!   over the kept `ClosureResult` and stays in the delegation module.
//! - The `10.0 * drc_errors` multiplication promotes the int count to float
//!   (the oracle's int*float), and the result is clamped at 0.0 (the
//!   oracle's `max(0.0, ...)`, which also floors a negative count's effect).
//! - The `stages_exercised >= 4` boundary is inclusive, and a negative count
//!   is impossible in the pipeline (guarded anyway by the clamp).
//!
//! pyo3 panic policy: pyo3's default `catch_unwind` at the `#[pyfunction]`
//! boundary (R1g).

use pyo3::prelude::*;
use pyo3::types::PyModule;

/// DRC clearance pass percentage (verbatim port of the oracle's three-branch
/// rule): 100.0 when the DRC stage ran clean, `max(0, 100 - 10*errors)` when
/// it ran with errors, 0.0 when the DRC stage did not run.
#[pyfunction]
fn compute_drc_clearance_pass_pct(stages_exercised: i64, drc_errors: i64) -> f64 {
    if stages_exercised >= 4 && drc_errors == 0 {
        100.0
    } else if stages_exercised >= 4 {
        (100.0 - 10.0 * drc_errors as f64).max(0.0)
    } else {
        0.0
    }
}

// --- BEGIN generated by scripts/gen_oracle_freeze.py: measure_closure ---
    /// Frozen golden vectors for `compute_drc_clearance_pass_pct` (FREEZE, U4/U5).
    /// Regenerate: `python3 scripts/gen_oracle_freeze.py --spec measure_closure`
    /// (requires reviving the deleted oracle from git history first -- see
    /// scripts/oracle_freeze_specs/measure_closure.py's module docstring).
    #[cfg(test)]
    mod frozen_tests {
        use super::*;

        struct FrozenMeasureClosureCase {
            stages: i64,
            errors: i64,
            expected_bits: u64,
            tags: &'static [&'static str],
        }

        const FROZEN_MEASURE_CLOSURE_GOLDEN: &[FrozenMeasureClosureCase] = &[
            FrozenMeasureClosureCase {
                stages: 0i64,
                errors: 0i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_zero", "named:empty_pipeline", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 1i64,
                errors: 0i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_zero", "named:single_stage", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 3i64,
                errors: 0i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_zero", "named:three_stages", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 3i64,
                errors: 50i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "named:three_stages_many_errors", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 0i64,
                expected_bits: 0x4059000000000000_u64,
                tags: &["clean_run", "errors_zero", "named:boundary_four_clean", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 1i64,
                expected_bits: 0x4056800000000000_u64,
                tags: &["errors_positive", "linear_region", "named:boundary_four_one_error", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 9i64,
                expected_bits: 0x4024000000000000_u64,
                tags: &["errors_positive", "linear_region", "named:boundary_four_nine_errors", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 10i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "named:boundary_four_ten_errors_clamp", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 20i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "named:boundary_four_twenty_errors_clamp", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 5i64,
                errors: 3i64,
                expected_bits: 0x4051800000000000_u64,
                tags: &["errors_positive", "linear_region", "named:five_stages_three_errors", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 6i64,
                errors: 0i64,
                expected_bits: 0x4059000000000000_u64,
                tags: &["clean_run", "errors_zero", "named:six_clean", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 7i64,
                errors: 12i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "named:seven_twelve_errors_clamp", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 2i64,
                errors: -3i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_negative", "named:two_stages_negative_errors", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: -5i64,
                expected_bits: 0x4062c00000000000_u64,
                tags: &["errors_negative", "named:four_stages_negative_errors_unclamped", "stages_eq_4", "unclamped_negative"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: -1i64,
                expected_bits: 0x405b800000000000_u64,
                tags: &["errors_negative", "named:four_stages_negative_one_unclamped", "stages_eq_4", "unclamped_negative"],
            },
            FrozenMeasureClosureCase {
                stages: 9i64,
                errors: 10000i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "named:huge_error_count_clamp", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: -4i64,
                expected_bits: 0x4061800000000000_u64,
                tags: &["errors_negative", "stages_eq_4", "unclamped_negative"],
            },
            FrozenMeasureClosureCase {
                stages: 10i64,
                errors: 37i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 0i64,
                expected_bits: 0x4059000000000000_u64,
                tags: &["clean_run", "errors_zero", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 2i64,
                errors: 0i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_zero", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 8i64,
                errors: 15i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 18i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 2i64,
                errors: 44i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 22i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 2i64,
                errors: 40i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 5i64,
                errors: -4i64,
                expected_bits: 0x4061800000000000_u64,
                tags: &["errors_negative", "stages_gt_4", "unclamped_negative"],
            },
            FrozenMeasureClosureCase {
                stages: 3i64,
                errors: 16i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 9i64,
                errors: 8i64,
                expected_bits: 0x4034000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 5i64,
                errors: 8i64,
                expected_bits: 0x4034000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 0i64,
                errors: 47i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 12i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 3i64,
                errors: 5i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 4i64,
                expected_bits: 0x404e000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 2i64,
                errors: 48i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 35i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 6i64,
                errors: 0i64,
                expected_bits: 0x4059000000000000_u64,
                tags: &["clean_run", "errors_zero", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 12i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 10i64,
                errors: 7i64,
                expected_bits: 0x403e000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 0i64,
                expected_bits: 0x4059000000000000_u64,
                tags: &["clean_run", "errors_zero", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 3i64,
                errors: 7i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 4i64,
                expected_bits: 0x404e000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 10i64,
                errors: 35i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 8i64,
                errors: 50i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 6i64,
                errors: 11i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 60i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 2i64,
                expected_bits: 0x4054000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 10i64,
                errors: 6i64,
                expected_bits: 0x4044000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 2i64,
                errors: 39i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 1i64,
                errors: 4i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 50i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 6i64,
                errors: 5i64,
                expected_bits: 0x4049000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 55i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 10i64,
                errors: 0i64,
                expected_bits: 0x4059000000000000_u64,
                tags: &["clean_run", "errors_zero", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 2i64,
                errors: 39i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 7i64,
                errors: 4i64,
                expected_bits: 0x404e000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 8i64,
                errors: 34i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 0i64,
                expected_bits: 0x4059000000000000_u64,
                tags: &["clean_run", "errors_zero", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: -2i64,
                expected_bits: 0x405e000000000000_u64,
                tags: &["errors_negative", "stages_eq_4", "unclamped_negative"],
            },
            FrozenMeasureClosureCase {
                stages: 5i64,
                errors: 2i64,
                expected_bits: 0x4054000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 5i64,
                errors: 45i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 5i64,
                errors: 0i64,
                expected_bits: 0x4059000000000000_u64,
                tags: &["clean_run", "errors_zero", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 8i64,
                expected_bits: 0x4034000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 8i64,
                errors: 4i64,
                expected_bits: 0x404e000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 5i64,
                errors: 6i64,
                expected_bits: 0x4044000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 2i64,
                errors: 25i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 10i64,
                errors: 40i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 8i64,
                errors: 11i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 10i64,
                errors: -3i64,
                expected_bits: 0x4060400000000000_u64,
                tags: &["errors_negative", "stages_gt_4", "unclamped_negative"],
            },
            FrozenMeasureClosureCase {
                stages: 9i64,
                errors: 3i64,
                expected_bits: 0x4051800000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 2i64,
                errors: 50i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 7i64,
                errors: 2i64,
                expected_bits: 0x4054000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 2i64,
                errors: 14i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 8i64,
                errors: 0i64,
                expected_bits: 0x4059000000000000_u64,
                tags: &["clean_run", "errors_zero", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 28i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 10i64,
                errors: 0i64,
                expected_bits: 0x4059000000000000_u64,
                tags: &["clean_run", "errors_zero", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 7i64,
                errors: 13i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 9i64,
                errors: -1i64,
                expected_bits: 0x405b800000000000_u64,
                tags: &["errors_negative", "stages_gt_4", "unclamped_negative"],
            },
            FrozenMeasureClosureCase {
                stages: 7i64,
                errors: 19i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 41i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 0i64,
                errors: 46i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 2i64,
                expected_bits: 0x4054000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 43i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 6i64,
                errors: 9i64,
                expected_bits: 0x4024000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 5i64,
                errors: 7i64,
                expected_bits: 0x403e000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 10i64,
                errors: 5i64,
                expected_bits: 0x4049000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 21i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 2i64,
                errors: 7i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 4i64,
                errors: 22i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_eq_4"],
            },
            FrozenMeasureClosureCase {
                stages: 9i64,
                errors: 24i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 7i64,
                errors: 9i64,
                expected_bits: 0x4024000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 5i64,
                errors: 27i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 5i64,
                errors: 0i64,
                expected_bits: 0x4059000000000000_u64,
                tags: &["clean_run", "errors_zero", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 8i64,
                errors: 54i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["clamp_region", "errors_positive", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 2i64,
                errors: 60i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 7i64,
                errors: 7i64,
                expected_bits: 0x403e000000000000_u64,
                tags: &["errors_positive", "linear_region", "stages_gt_4"],
            },
            FrozenMeasureClosureCase {
                stages: 1i64,
                errors: 3i64,
                expected_bits: 0x0000000000000000_u64,
                tags: &["errors_positive", "stages_lt_4"],
            },
        ];

        #[test]
        fn frozen_measure_closure_matches_golden_corpus() {
            for case in FROZEN_MEASURE_CLOSURE_GOLDEN {
                let got = compute_drc_clearance_pass_pct(case.stages, case.errors);
                let want = f64::from_bits(case.expected_bits);
                let ok = (got.is_nan() && want.is_nan()) || got.to_bits() == want.to_bits();
                assert!(ok, "tags={:?}: got {:?} want {:?}", case.tags, got, want);
            }
        }

        /// Q2 non-vacuity guard: fails closed if the frozen corpus above were
        /// ever hand-edited down to something trivially satisfiable. Mirrors the
        /// coverage-guard convention in creepage_check.rs / via_clearance.rs (PR
        /// #1007), property_campaigns.rs's IPC-2221 bracket guard, and
        /// copper_reach.rs's own frozen-corpus guard.
        #[test]
        fn frozen_measure_closure_corpus_is_non_vacuous() {
            let n = FROZEN_MEASURE_CLOSURE_GOLDEN.len() as u32;
            let count = |tag: &str| FROZEN_MEASURE_CLOSURE_GOLDEN.iter().filter(|c| c.tags.contains(&tag)).count() as u32;
            assert!(count("clean_run") >= 2, "clean_run: only {}/{} (need >= 2) -- the 100.0 (stages>=4, errors==0) branch must be exercised", count("clean_run"), n);
            assert!(count("linear_region") >= 5, "linear_region: only {}/{} (need >= 5) -- the 100 - 10*errors regime (0 < errors < 10) must be exercised", count("linear_region"), n);
            assert!(count("clamp_region") >= 5, "clamp_region: only {}/{} (need >= 5) -- the max(0.0, ...) clamp (errors >= 10) must be exercised", count("clamp_region"), n);
            assert!(count("unclamped_negative") >= 3, "unclamped_negative: only {}/{} (need >= 3) -- the oracle's missing upper clamp (negative errors -> >100) is pinned, not fixed", count("unclamped_negative"), n);
            assert!(count("stages_lt_4") >= 5, "stages_lt_4: only {}/{} (need >= 5) -- the stages<4 -> 0.0 branch must be exercised", count("stages_lt_4"), n);
            assert!(count("stages_eq_4") >= 10, "stages_eq_4: only {}/{} (need >= 10) -- the inclusive stages==4 hinge must be exercised", count("stages_eq_4"), n);
            assert!(count("errors_zero") * 100 >= n * 10, "errors_zero: only {}/{} (need >= 10%) -- the errors==0 case must be common, not a rare fluke", count("errors_zero"), n);
        }
    }
// --- END generated by scripts/gen_oracle_freeze.py: measure_closure ---

/// Register the kernel on the `temper_design_bundle_python` module.
pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(compute_drc_clearance_pass_pct, m)?)?;
    Ok(())
}
