//! Wave 4 Phase 4 — regression slice: metric schema validation kernel.
//!
//! The validation decision compute of
//! `temper_placer/regression/schema_validator.py` (pinned verbatim as the
//! oracle `_schema_validator_py_oracle.py`, commit `0a29f15e3`) migrated
//! into `temper-design-bundle`:
//!
//! | Kernel | Python origin |
//! |---|---|
//! | `validate_schema` | `SchemaValidator.validate` — the two-pass check (unknown-field sweep, then min/max/zero_is_valid range checks) |
//!
//! Oracle retired 2026-08-20 (FREEZE, batch 1): the differential against
//! `_schema_validator_py_oracle.py` is replaced by the frozen golden-vector
//! corpus in this file's own `frozen_tests` module (see
//! `scripts/oracle_freeze_specs/schema_validator.py` for provenance; the
//! oracle file itself is deleted and can be revived from git history only).
//!
//! Design boundaries (argued in-source; see
//! `packages/temper-design-bundle/VERIFICATION.md`):
//!
//! - YAML loading and the schema-shape checks in `SchemaValidator.__init__`
//!   stay Python (I/O + marshalling). The kernel operates on the parsed
//!   field table marshalled by the delegation module.
//! - The kernel returns a `(field, reason_code)` pair; the delegation module
//!   formats the exact message with Python `str()` on the ORIGINAL dict
//!   values. No-format `str(float)` is a Python library semantic (`1.0` vs
//!   `1`) — int-vs-float leaves are type-carried Python-side, while the
//!   numeric *decision* (`value < min` etc.) is identical for the exact f64
//!   conversions of the schema/values involved.
//! - Iteration is over the metric dict's insertion order (a `Vec`, not a
//!   `HashMap`) — the two-pass, first-violation-raises semantics are
//!   preserved exactly: pass 1 reports the first UNKNOWN field (before any
//!   range check), pass 2 reports the first out-of-range field.
//! - A schema field without a `zero_is_valid` key defaults to True (the
//!   oracle's `constraints.get("zero_is_valid", True)`), applied by the
//!   delegation module while marshalling.
//! - A field with neither min nor max is unconstrained (except
//!   `zero_is_valid`); `value == 0.0` matches Python's `value == 0` for the
//!   float values this schema validates.
//!
//! pyo3 panic policy: pyo3's default `catch_unwind` at the `#[pyfunction]`
//! boundary (R1g).

use std::collections::HashMap;

use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;
use pyo3::types::PyModule;

/// Validate a metrics dict against a schema field table. Returns
/// `(field, reason_code)` for the first violation, or `None` when every
/// metric satisfies its constraints. Reason codes: `unknown`, `below_min`,
/// `above_max`, `zero_invalid` (mapped to messages by the delegation module).
#[pyfunction]
fn validate_schema(
    metrics: Vec<(String, f64)>,
    schema: Vec<(String, Option<f64>, Option<f64>, bool)>,
) -> PyResult<Option<(String, String)>> {
    let lookup: HashMap<&str, (&Option<f64>, &Option<f64>, &bool)> = schema
        .iter()
        .map(|(name, min, max, ziv)| (name.as_str(), (min, max, ziv)))
        .collect();

    // Pass 1: every metric field must be declared (first unknown in
    // insertion order), BEFORE any range check.
    for (field, _) in &metrics {
        if !lookup.contains_key(field.as_str()) {
            return Ok(Some((field.clone(), "unknown".to_string())));
        }
    }

    // Pass 2: min/max/zero_is_valid range checks in insertion order.
    for (field, value) in &metrics {
        let Some((min, max, zero_is_valid)) = lookup.get(field.as_str()) else {
            // Unreachable after pass 1; fail closed rather than silently
            // skipping the field.
            return Err(PyValueError::new_err(
                "schema invariant violated: declared field missing from lookup",
            ));
        };
        if let Some(min) = min
            && *value < *min
        {
            return Ok(Some((field.clone(), "below_min".to_string())));
        }
        if let Some(max) = max
            && *value > *max
        {
            return Ok(Some((field.clone(), "above_max".to_string())));
        }
        if !**zero_is_valid && *value == 0.0 {
            return Ok(Some((field.clone(), "zero_invalid".to_string())));
        }
    }
    Ok(None)
}

// --- BEGIN generated by scripts/gen_oracle_freeze.py: schema_validator ---
    /// Frozen golden vectors for `validate_schema` (FREEZE, U4/U5).
    /// Regenerate: `python3 scripts/gen_oracle_freeze.py --spec schema_validator`
    /// (requires reviving the deleted oracle from git history first -- see
    /// scripts/oracle_freeze_specs/schema_validator.py's module docstring).
    // Frozen cases are pinned oracle output; the module sits where the
    // generator emits it, and unwrapping a frozen-known-Ok result is the
    // assertion, not an oversight.
    #[allow(clippy::items_after_test_module, clippy::unwrap_used)]
    #[cfg(test)]
    mod frozen_tests {
        use super::*;

        struct FrozenSchemaValidatorCase {
            metrics: &'static [(&'static str, f64)],
            schema: &'static [(&'static str, Option<f64>, Option<f64>, bool)],
            expected: Option<(&'static str, &'static str)>,
            tags: &'static [&'static str],
        }

        const FROZEN_SCHEMA_VALIDATOR_GOLDEN: &[FrozenSchemaValidatorCase] = &[
            FrozenSchemaValidatorCase {
                metrics: &[("wall_time_ms", f64::from_bits(0x4049000000000000_u64))],
                schema: &[("wall_time_ms", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: None,
                tags: &["named:valid_pass", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("wall_time_ms", f64::from_bits(0xBFF0000000000000_u64))],
                schema: &[("wall_time_ms", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: Some(("wall_time_ms", "below_min")),
                tags: &["below_min", "named:below_min"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("wall_time_ms", f64::from_bits(0x4059400000000000_u64))],
                schema: &[("wall_time_ms", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: Some(("wall_time_ms", "above_max")),
                tags: &["above_max", "named:above_max"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("wall_time_ms", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("wall_time_ms", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: None,
                tags: &["exact_boundary", "named:exactly_min_passes", "pass", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("wall_time_ms", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("wall_time_ms", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: None,
                tags: &["exact_boundary", "named:exactly_max_passes", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("x", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("x", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4024000000000000_u64)), false)],
                expected: Some(("x", "zero_invalid")),
                tags: &["exact_boundary", "named:zero_invalid", "zero_invalid", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("x", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("x", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4024000000000000_u64)), true)],
                expected: None,
                tags: &["exact_boundary", "named:zero_valid_passes", "pass", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("nope", f64::from_bits(0x3FF0000000000000_u64))],
                schema: &[("x", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4024000000000000_u64)), true)],
                expected: Some(("nope", "unknown")),
                tags: &["named:unknown_field", "pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[],
                schema: &[("x", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4024000000000000_u64)), false)],
                expected: None,
                tags: &["empty_metrics", "named:empty_metrics_pass", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m", f64::from_bits(0xC1CDCD6500000000_u64))],
                schema: &[("m", None, None, true)],
                expected: None,
                tags: &["named:unconstrained_passes", "pass", "unconstrained"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m", f64::from_bits(0xC1CDCD6500000000_u64))],
                schema: &[("m", None, Some(f64::from_bits(0x0000000000000000_u64)), true)],
                expected: None,
                tags: &["named:no_min_only", "no_min", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m", f64::from_bits(0x41CDCD6500000000_u64))],
                schema: &[("m", Some(f64::from_bits(0x0000000000000000_u64)), None, true)],
                expected: None,
                tags: &["named:no_max_only", "no_max", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xC014000000000000_u64)), ("m1", f64::from_bits(0x408F380000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: Some(("m1", "unknown")),
                tags: &["named:pass1_unknown_beats_range", "pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("a", f64::from_bits(0x407F400000000000_u64)), ("b", f64::from_bits(0x4049000000000000_u64))],
                schema: &[("a", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("b", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: Some(("a", "above_max")),
                tags: &["above_max", "named:insertion_order_first_violation"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m", Some(f64::from_bits(0x3FF0000000000000_u64)), Some(f64::from_bits(0x4024000000000000_u64)), false)],
                expected: Some(("m", "below_min")),
                tags: &["below_min", "named:below_min_precedes_zero", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m", f64::from_bits(0x7FF8000000000000_u64))],
                schema: &[("m", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4024000000000000_u64)), true)],
                expected: None,
                tags: &["named:nan_value_passes", "nan_value", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m", f64::from_bits(0xC023000000000000_u64))],
                schema: &[("m", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4024000000000000_u64)), true)],
                expected: None,
                tags: &["named:negative_in_range", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m", f64::from_bits(0x4024000000000001_u64))],
                schema: &[("m", Some(f64::from_bits(0x3FF0000000000000_u64)), Some(f64::from_bits(0x4024000000000000_u64)), true)],
                expected: Some(("m", "above_max")),
                tags: &["above_max", "named:ulp_above_max"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m", f64::from_bits(0x4014000000000000_u64))],
                schema: &[("m", Some(f64::from_bits(0x4024000000000000_u64)), Some(f64::from_bits(0x4034000000000000_u64)), true)],
                expected: Some(("m", "below_min")),
                tags: &["below_min", "named:int_leaf_below_float_min"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x0000000000000000_u64)), false)],
                expected: Some(("m", "zero_invalid")),
                tags: &["exact_boundary", "named:zero_at_pinned_min_invalid", "zero_invalid", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m", f64::from_bits(0x40F86A0000000000_u64))],
                schema: &[("m", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true)],
                expected: None,
                tags: &["exact_boundary", "named:high_max_pass", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m", f64::from_bits(0x3FF8000000000000_u64))],
                schema: &[("m", Some(f64::from_bits(0x3FE0000000000000_u64)), Some(f64::from_bits(0x4004000000000000_u64)), true)],
                expected: None,
                tags: &["named:fractional_min", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m", f64::from_bits(0x3FD999999999999A_u64))],
                schema: &[("m", Some(f64::from_bits(0x3FE0000000000000_u64)), Some(f64::from_bits(0x4004000000000000_u64)), true)],
                expected: Some(("m", "below_min")),
                tags: &["below_min", "named:below_fractional_min"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("a", f64::from_bits(0x4014000000000000_u64)), ("b", f64::from_bits(0x407F400000000000_u64))],
                schema: &[("a", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4024000000000000_u64)), true), ("b", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4024000000000000_u64)), true)],
                expected: Some(("b", "above_max")),
                tags: &["above_max", "named:multiple_metrics_one_bad"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x3FF8000000000000_u64)), ("m1", f64::from_bits(0xBFF0000000000000_u64)), ("m2", f64::from_bits(0x3FF8000000000000_u64)), ("m3", f64::from_bits(0x7FF8000000000000_u64)), ("_unknown_", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), None, true), ("m2", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false), ("m3", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["nan_value", "no_max", "pass1_unknown", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4014000000000000_u64)), ("m1", f64::from_bits(0x0000000000000000_u64)), ("m2", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m2", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("m1", "below_min")),
                tags: &["below_min", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045800000000000_u64)), ("m1", f64::from_bits(0xBFF0000000000000_u64)), ("m2", f64::from_bits(0x4045000000000000_u64)), ("m3", f64::from_bits(0x4045000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), None, false), ("m1", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), false), ("m2", Some(f64::from_bits(0xC025000000000000_u64)), None, true), ("m3", None, Some(f64::from_bits(0x40F86A0000000000_u64)), true)],
                expected: None,
                tags: &["no_max", "no_min", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045800000000000_u64)), ("m1", f64::from_bits(0x4045000000000000_u64)), ("m2", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), None, true), ("m1", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m2", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false)],
                expected: Some(("m2", "above_max")),
                tags: &["above_max", "exact_boundary", "no_max"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4014000000000000_u64)), ("m1", f64::from_bits(0xBFF0000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x40F86A0000000000_u64)), false), ("m1", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: None,
                tags: &["no_min", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xC024000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: Some(("m0", "below_min")),
                tags: &["below_min"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x4045000000000000_u64)), None, false)],
                expected: None,
                tags: &["exact_boundary", "no_max", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xBFF0000000000000_u64)), ("m1", f64::from_bits(0x4058F9999999999A_u64)), ("m2", f64::from_bits(0x4014000000000000_u64)), ("m3", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", Some(f64::from_bits(0x4045000000000000_u64)), None, true), ("m2", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m3", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("m2", "below_min")),
                tags: &["below_min", "exact_boundary", "no_max", "no_min"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("m1", f64::from_bits(0x3FF8000000000000_u64)), ("m2", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), false), ("m2", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: Some(("m0", "below_min")),
                tags: &["below_min", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x7FF8000000000000_u64)), ("_unknown_", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["nan_value", "pass1_unknown", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x7FF8000000000000_u64)), ("m1", f64::from_bits(0x0000000000000000_u64)), ("m2", f64::from_bits(0x4045000000000000_u64)), ("m3", f64::from_bits(0x4045000000000000_u64)), ("_unknown_", f64::from_bits(0x7FF8000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m1", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false), ("m2", None, None, false), ("m3", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["nan_value", "no_min", "pass1_unknown", "unconstrained", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x7FF8000000000000_u64)), ("_unknown_", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x40F86A0000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["nan_value", "no_min", "pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4058F9999999999A_u64)), ("_unknown_", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["pass1_unknown", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xC024000000000000_u64)), ("m1", f64::from_bits(0x4045800000000000_u64)), ("m2", f64::from_bits(0xBFF0000000000000_u64)), ("m3", f64::from_bits(0xBFF0000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), None, true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m2", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m3", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("m0", "below_min")),
                tags: &["below_min", "no_max"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("m1", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x4049400000000000_u64)), true), ("m1", None, Some(f64::from_bits(0x4049400000000000_u64)), true)],
                expected: Some(("m1", "above_max")),
                tags: &["above_max", "no_min", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4014000000000000_u64)), ("m1", f64::from_bits(0x7FF8000000000000_u64)), ("m2", f64::from_bits(0x4045000000000000_u64)), ("_unknown_", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m2", Some(f64::from_bits(0x4045000000000000_u64)), None, false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["exact_boundary", "nan_value", "no_max", "pass1_unknown", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x3FF8000000000000_u64)), ("_unknown_", f64::from_bits(0x3FF8000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x4049400000000000_u64)), false)],
                expected: Some(("m0", "zero_invalid")),
                tags: &["no_min", "zero_invalid", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xC024000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: None,
                tags: &["pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045000000000000_u64)), ("m1", f64::from_bits(0x7FF8000000000000_u64)), ("m2", f64::from_bits(0x3FF8000000000000_u64)), ("m3", f64::from_bits(0x4045000000000000_u64)), ("_unknown_", f64::from_bits(0x4045000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", None, Some(f64::from_bits(0x4059000000000000_u64)), false), ("m2", None, None, false), ("m3", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["exact_boundary", "nan_value", "no_min", "pass1_unknown", "unconstrained", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045800000000000_u64)), ("m1", f64::from_bits(0x4058F9999999999A_u64)), ("m2", f64::from_bits(0xBFF0000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false), ("m2", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: Some(("m1", "above_max")),
                tags: &["above_max"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x7FF8000000000000_u64)), ("m1", f64::from_bits(0xC024000000000000_u64)), ("_unknown_", f64::from_bits(0x4045000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["nan_value", "pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x4049400000000000_u64)), false)],
                expected: Some(("m0", "above_max")),
                tags: &["above_max", "no_min"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4014000000000000_u64)), ("_unknown_", f64::from_bits(0x4045800000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x7FF8000000000000_u64)), ("m1", f64::from_bits(0x0000000000000000_u64)), ("_unknown_", f64::from_bits(0xBFF0000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["exact_boundary", "nan_value", "pass1_unknown", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xBFF0000000000000_u64)), ("m1", f64::from_bits(0x0000000000000000_u64)), ("m2", f64::from_bits(0x4045000000000000_u64)), ("m3", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false), ("m2", None, Some(f64::from_bits(0x4059000000000000_u64)), true), ("m3", None, Some(f64::from_bits(0x4049400000000000_u64)), true)],
                expected: Some(("m1", "zero_invalid")),
                tags: &["exact_boundary", "no_min", "zero_invalid", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xC024000000000000_u64)), ("m1", f64::from_bits(0x4045800000000000_u64)), ("m2", f64::from_bits(0x0000000000000000_u64)), ("m3", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true), ("m2", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m3", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("m3", "zero_invalid")),
                tags: &["zero_invalid", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045000000000000_u64)), ("m1", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), false)],
                expected: None,
                tags: &["pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xC024000000000000_u64)), ("m1", f64::from_bits(0x7FF8000000000000_u64)), ("m2", f64::from_bits(0x0000000000000000_u64)), ("m3", f64::from_bits(0xBFF0000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), false), ("m1", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true), ("m2", None, None, true), ("m3", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("m3", "below_min")),
                tags: &["below_min", "nan_value", "unconstrained", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("m1", f64::from_bits(0x4014000000000000_u64)), ("m2", f64::from_bits(0x4058F9999999999A_u64)), ("m3", f64::from_bits(0xC024000000000000_u64)), ("_unknown_", f64::from_bits(0xBFF0000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m2", None, None, true), ("m3", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["no_min", "pass1_unknown", "unconstrained", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x3FF8000000000000_u64)), ("m1", f64::from_bits(0xC024000000000000_u64)), ("m2", f64::from_bits(0x3FF8000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), None, true), ("m1", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false), ("m2", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: None,
                tags: &["exact_boundary", "no_max", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4059000000000000_u64)), ("_unknown_", f64::from_bits(0x4014000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["exact_boundary", "pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x7FF8000000000000_u64)), ("m1", f64::from_bits(0xC024000000000000_u64)), ("m2", f64::from_bits(0xBFF0000000000000_u64)), ("m3", f64::from_bits(0x7FF8000000000000_u64)), ("_unknown_", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m1", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m2", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m3", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["nan_value", "pass1_unknown", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x3FF8000000000000_u64)), ("_unknown_", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xC024000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), None, true)],
                expected: None,
                tags: &["exact_boundary", "no_max", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xBFF0000000000000_u64)), ("m1", f64::from_bits(0x4014000000000000_u64)), ("_unknown_", f64::from_bits(0xBFF0000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("m1", f64::from_bits(0x4045800000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: None,
                tags: &["pass", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x7FF8000000000000_u64)), ("_unknown_", f64::from_bits(0x4014000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["nan_value", "pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("m1", f64::from_bits(0x4059000000000000_u64)), ("m2", f64::from_bits(0x4045800000000000_u64)), ("_unknown_", f64::from_bits(0x7FF8000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m2", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["exact_boundary", "nan_value", "pass1_unknown", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x3FF8000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), false)],
                expected: None,
                tags: &["pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x3FF8000000000000_u64)), ("_unknown_", f64::from_bits(0xC024000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x4045000000000000_u64)), None, true)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["no_max", "pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x3FF8000000000000_u64)), ("m1", f64::from_bits(0xC024000000000000_u64)), ("m2", f64::from_bits(0x4014000000000000_u64)), ("m3", f64::from_bits(0x4045000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", None, Some(f64::from_bits(0x4049400000000000_u64)), false), ("m2", Some(f64::from_bits(0x0000000000000000_u64)), None, false), ("m3", None, Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: None,
                tags: &["no_max", "no_min", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4058F9999999999A_u64)), ("_unknown_", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x4045000000000000_u64)), None, true)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["no_max", "pass1_unknown", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4058F9999999999A_u64)), ("m1", f64::from_bits(0x3FF8000000000000_u64)), ("m2", f64::from_bits(0xBFF0000000000000_u64)), ("m3", f64::from_bits(0xBFF0000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), false), ("m2", None, Some(f64::from_bits(0x4059000000000000_u64)), false), ("m3", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true)],
                expected: Some(("m3", "below_min")),
                tags: &["below_min", "no_min"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045000000000000_u64)), ("m1", f64::from_bits(0x0000000000000000_u64)), ("m2", f64::from_bits(0x4045800000000000_u64)), ("m3", f64::from_bits(0x3FF8000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m2", None, Some(f64::from_bits(0x4049400000000000_u64)), true), ("m3", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true)],
                expected: None,
                tags: &["exact_boundary", "no_min", "pass", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("_unknown_", f64::from_bits(0x4058F9999999999A_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["no_min", "pass1_unknown", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x3FF8000000000000_u64)), ("m1", f64::from_bits(0x0000000000000000_u64)), ("m2", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m2", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: None,
                tags: &["exact_boundary", "pass", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x3FF8000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x4045000000000000_u64)), None, true)],
                expected: Some(("m0", "below_min")),
                tags: &["below_min", "no_max"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xBFF0000000000000_u64)), ("m1", f64::from_bits(0x4014000000000000_u64)), ("m2", f64::from_bits(0x4058F9999999999A_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m1", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true), ("m2", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), false)],
                expected: None,
                tags: &["pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x40F86A0000000000_u64)), true)],
                expected: None,
                tags: &["no_min", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x7FF8000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: None,
                tags: &["nan_value", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: None,
                tags: &["pass", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045000000000000_u64)), ("m1", f64::from_bits(0x4014000000000000_u64)), ("m2", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m1", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m2", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), false)],
                expected: Some(("m1", "below_min")),
                tags: &["below_min"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("m1", f64::from_bits(0x0000000000000000_u64)), ("m2", f64::from_bits(0x4045000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m2", Some(f64::from_bits(0x0000000000000000_u64)), None, false)],
                expected: Some(("m0", "zero_invalid")),
                tags: &["exact_boundary", "no_max", "no_min", "zero_invalid", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045800000000000_u64)), ("_unknown_", f64::from_bits(0x3FF8000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true)],
                expected: Some(("m0", "above_max")),
                tags: &["above_max"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4058F9999999999A_u64)), ("m1", f64::from_bits(0xC024000000000000_u64)), ("m2", f64::from_bits(0x4014000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), None, false), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m2", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true)],
                expected: Some(("m1", "below_min")),
                tags: &["below_min", "no_max"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x7FF8000000000000_u64)), ("m1", f64::from_bits(0xC024000000000000_u64)), ("_unknown_", f64::from_bits(0x4014000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["nan_value", "pass1_unknown", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4014000000000000_u64)), ("m1", f64::from_bits(0x4045000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false), ("m1", None, Some(f64::from_bits(0x4049400000000000_u64)), true)],
                expected: None,
                tags: &["no_min", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("m1", f64::from_bits(0x4014000000000000_u64)), ("m2", f64::from_bits(0x4014000000000000_u64)), ("m3", f64::from_bits(0x0000000000000000_u64)), ("_unknown_", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false), ("m2", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m3", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["exact_boundary", "pass1_unknown", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("m1", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x4045000000000000_u64)), None, true), ("m1", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true)],
                expected: Some(("m0", "below_min")),
                tags: &["below_min", "no_max", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4059000000000000_u64)), ("m1", f64::from_bits(0x4058F9999999999A_u64)), ("m2", f64::from_bits(0xBFF0000000000000_u64)), ("m3", f64::from_bits(0x4045800000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true), ("m1", None, Some(f64::from_bits(0x4059000000000000_u64)), true), ("m2", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false), ("m3", None, None, false)],
                expected: Some(("m0", "above_max")),
                tags: &["above_max", "no_min", "unconstrained"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4059000000000000_u64)), ("m1", f64::from_bits(0x4059000000000000_u64)), ("m2", f64::from_bits(0x3FF8000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true), ("m2", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("m0", "above_max")),
                tags: &["above_max"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045000000000000_u64)), ("m1", f64::from_bits(0x4045800000000000_u64)), ("m2", f64::from_bits(0x4045000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x4049400000000000_u64)), false), ("m1", Some(f64::from_bits(0x4045000000000000_u64)), None, true), ("m2", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true)],
                expected: None,
                tags: &["exact_boundary", "no_max", "no_min", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("_unknown_", f64::from_bits(0x4058F9999999999A_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["pass1_unknown", "unknown", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045000000000000_u64)), ("m1", f64::from_bits(0x3FF8000000000000_u64)), ("_unknown_", f64::from_bits(0x3FF8000000000000_u64))],
                schema: &[("m0", None, None, true), ("m1", None, Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["no_min", "pass1_unknown", "unconstrained", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xBFF0000000000000_u64)), ("m1", f64::from_bits(0x4059000000000000_u64)), ("m2", f64::from_bits(0x4059000000000000_u64)), ("m3", f64::from_bits(0x0000000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), None, true), ("m1", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false), ("m2", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false), ("m3", None, Some(f64::from_bits(0x4049400000000000_u64)), false)],
                expected: Some(("m0", "below_min")),
                tags: &["below_min", "exact_boundary", "no_max", "no_min", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4014000000000000_u64)), ("m1", f64::from_bits(0x4059000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x40F86A0000000000_u64)), true), ("m1", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false)],
                expected: Some(("m1", "above_max")),
                tags: &["above_max", "no_min"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("m1", f64::from_bits(0xBFF0000000000000_u64)), ("m2", f64::from_bits(0x4014000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), None, false), ("m1", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false), ("m2", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: Some(("m0", "zero_invalid")),
                tags: &["exact_boundary", "no_max", "zero_invalid", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045000000000000_u64)), ("m1", f64::from_bits(0x4014000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", None, Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: None,
                tags: &["no_min", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4058F9999999999A_u64)), ("m1", f64::from_bits(0x0000000000000000_u64)), ("m2", f64::from_bits(0xC024000000000000_u64)), ("m3", f64::from_bits(0x4014000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m2", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m3", None, Some(f64::from_bits(0x40F86A0000000000_u64)), true)],
                expected: Some(("m2", "below_min")),
                tags: &["below_min", "no_min", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("m1", f64::from_bits(0xBFF0000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), false), ("m1", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false)],
                expected: Some(("m0", "zero_invalid")),
                tags: &["exact_boundary", "zero_invalid", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4058F9999999999A_u64)), ("m1", f64::from_bits(0x4058F9999999999A_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x40F86A0000000000_u64)), true)],
                expected: None,
                tags: &["no_min", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x0000000000000000_u64)), ("m1", f64::from_bits(0x4059000000000000_u64)), ("m2", f64::from_bits(0x3FF8000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), false), ("m1", Some(f64::from_bits(0xC024000000000000_u64)), None, true), ("m2", None, Some(f64::from_bits(0x40F86A0000000000_u64)), false)],
                expected: Some(("m0", "below_min")),
                tags: &["below_min", "no_max", "no_min", "zero_value"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4014000000000000_u64)), ("m1", f64::from_bits(0x4014000000000000_u64)), ("_unknown_", f64::from_bits(0x4014000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", None, None, false)],
                expected: Some(("_unknown_", "unknown")),
                tags: &["pass1_unknown", "unconstrained", "unknown"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4059000000000000_u64)), ("m1", f64::from_bits(0x4045000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), None, true)],
                expected: Some(("m0", "above_max")),
                tags: &["above_max", "no_max"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xC024000000000000_u64)), ("m1", f64::from_bits(0x7FF8000000000000_u64)), ("m2", f64::from_bits(0x4045000000000000_u64)), ("m3", f64::from_bits(0x4045800000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0x0000000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", Some(f64::from_bits(0x0000000000000000_u64)), None, true), ("m2", Some(f64::from_bits(0x4045000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m3", Some(f64::from_bits(0x0000000000000000_u64)), None, false)],
                expected: Some(("m0", "below_min")),
                tags: &["below_min", "exact_boundary", "nan_value", "no_max"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4045000000000000_u64)), ("m1", f64::from_bits(0x4058F9999999999A_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC024000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), true), ("m1", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4049400000000000_u64)), true)],
                expected: Some(("m1", "above_max")),
                tags: &["above_max"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0xC024000000000000_u64))],
                schema: &[("m0", None, Some(f64::from_bits(0x4059000000000000_u64)), true)],
                expected: None,
                tags: &["no_min", "pass"],
            },
            FrozenSchemaValidatorCase {
                metrics: &[("m0", f64::from_bits(0x4058F9999999999A_u64)), ("m1", f64::from_bits(0x4045000000000000_u64))],
                schema: &[("m0", Some(f64::from_bits(0xC025000000000000_u64)), Some(f64::from_bits(0x4059000000000000_u64)), false), ("m1", None, None, false)],
                expected: None,
                tags: &["pass", "unconstrained"],
            },
        ];

        #[test]
        fn frozen_schema_validator_matches_golden_corpus() {
            for case in FROZEN_SCHEMA_VALIDATOR_GOLDEN {
                let got = validate_schema(
                    case.metrics.iter().map(|(n, v)| (n.to_string(), *v)).collect(),
                    case.schema.iter().map(|(n, mn, mx, zv)| (n.to_string(), *mn, *mx, *zv)).collect(),
                )
                .unwrap();
                let want = case.expected.map(|(f, r)| (f.to_string(), r.to_string()));
                assert_eq!(got, want, "tags={:?}", case.tags);
            }
        }

        /// Q2 non-vacuity guard: fails closed if the frozen corpus above were
        /// ever hand-edited down to something trivially satisfiable. Mirrors the
        /// coverage-guard convention in creepage_check.rs / via_clearance.rs (PR
        /// #1007), property_campaigns.rs's IPC-2221 bracket guard, and
        /// copper_reach.rs's own frozen-corpus guard.
        #[test]
        fn frozen_schema_validator_corpus_is_non_vacuous() {
            let n = FROZEN_SCHEMA_VALIDATOR_GOLDEN.len() as u32;
            let count = |tag: &str| FROZEN_SCHEMA_VALIDATOR_GOLDEN.iter().filter(|c| c.tags.contains(&tag)).count() as u32;
            assert!(count("pass") * 100 >= n * 25, "pass: only {}/{} (need >= 25%) -- the pass (None) outcome must be well represented, not a rare fluke", count("pass"), n);
            assert!(count("below_min") >= 8, "below_min: only {}/{} (need >= 8) -- the below-min branch must be exercised", count("below_min"), n);
            assert!(count("above_max") >= 8, "above_max: only {}/{} (need >= 8) -- the above-max branch must be exercised", count("above_max"), n);
            assert!(count("unknown") >= 6, "unknown: only {}/{} (need >= 6) -- the pass-1 unknown-field branch must be exercised", count("unknown"), n);
            assert!(count("zero_invalid") >= 5, "zero_invalid: only {}/{} (need >= 5) -- the zero_is_valid=False branch must be exercised", count("zero_invalid"), n);
            assert!(count("empty_metrics") >= 1, "empty_metrics: only {}/{} (need >= 1) -- the empty-metrics vacuous-pass branch must be exercised", count("empty_metrics"), n);
            assert!(count("nan_value") >= 2, "nan_value: only {}/{} (need >= 2) -- NaN metric values (which pass every range check) must be exercised", count("nan_value"), n);
            assert!(count("exact_boundary") >= 2, "exact_boundary: only {}/{} (need >= 2) -- value == min / value == max inclusive boundaries must be exercised", count("exact_boundary"), n);
            assert!(count("pass1_unknown") >= 1, "pass1_unknown: only {}/{} (need >= 1) -- pass 1 must run before pass 2 (unknown beats range) -- the ordering contract", count("pass1_unknown"), n);
            assert!(count("unconstrained") >= 3, "unconstrained: only {}/{} (need >= 3) -- a field with neither min nor max must be exercised", count("unconstrained"), n);
        }
    }
// --- END generated by scripts/gen_oracle_freeze.py: schema_validator ---

/// Register the kernel on the `temper_design_bundle_python` module.
pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(validate_schema, m)?)?;
    Ok(())
}
