/**
 * @file test_transition_table_generated.c
 * @brief AUTO-GENERATED by firmware/test/gen_transition_table.py
 * 
 * Transition-table-driven state machine validation.
 * DO NOT EDIT BY HAND — edit gen_transition_table.py and regenerate.
 */

#include "test_common.h"
#include "../main/state_machine.h"
#include <string.h>
#include <stdio.h>

/* Mock control functions from state_machine_stubs.c */
extern void mock_sm_reset(void);
extern void mock_sm_advance_time(uint32_t ms);
extern void mock_sm_set_pan_temperature(float temp_c);
extern void mock_sm_set_heatsink_temperature(float temp_c);
extern void mock_sm_set_dc_bus_current(float amps);
extern void mock_sm_set_rtd_resistance(float ohms);
extern void mock_sm_set_pan_status(int status);
extern void mock_sm_set_pan_impedance(float impedance);
extern void mock_sm_set_fan_running(bool running);
extern void mock_sm_press_button(button_id_t button);
extern void mock_sm_fail_selftest_adc(void);

#define MOCK_PAN_ABSENT  0
#define MOCK_PAN_PRESENT 1

/* Transition descriptor */
typedef struct {
    system_state_t from;
    const char *event;
    system_state_t expected_to;
    fault_code_t expected_fault;
    bool has_fault;
} transition_row_t;

/* The transition table (generated from gen_transition_table.py) */
static const transition_row_t transition_table[] = {
    { STATE_INIT, "SELFTEST_PASS", STATE_IDLE, FAULT_NONE, false },
    { STATE_INIT, "SELFTEST_FAIL", STATE_FAULT, FAULT_SELF_TEST_FAILED, true },
    { STATE_IDLE, "START_BUTTON", STATE_PAN_DET, FAULT_NONE, false },
    { STATE_PAN_DET, "PAN_DETECTED", STATE_PREHEAT, FAULT_NONE, false },
    { STATE_PAN_DET, "PAN_TIMEOUT", STATE_IDLE, FAULT_NONE, false },
    { STATE_PREHEAT, "NEAR_TARGET", STATE_HEATING, FAULT_NONE, false },
    { STATE_PREHEAT, "PREHEAT_TIMEOUT", STATE_FAULT, FAULT_THERMAL_RUNAWAY, true },
    { STATE_PREHEAT, "OVER_TEMP", STATE_FAULT, FAULT_OVER_TEMP, true },
    { STATE_PREHEAT, "OVER_CURRENT", STATE_FAULT, FAULT_OVER_CURRENT, true },
    { STATE_PREHEAT, "FAN_FAILURE", STATE_FAULT, FAULT_FAN_FAILURE, true },
    { STATE_PREHEAT, "PROBE_OPEN", STATE_FAULT, FAULT_PROBE_OPEN, true },
    { STATE_PREHEAT, "PROBE_SHORT", STATE_FAULT, FAULT_PROBE_SHORT, true },
    { STATE_PREHEAT, "PAN_REMOVED", STATE_NO_PAN, FAULT_NONE, false },
    { STATE_PREHEAT, "STOP_BUTTON", STATE_COOLDOWN, FAULT_NONE, false },
    { STATE_HEATING, "NEAR_TARGET", STATE_HEATING, FAULT_NONE, false },  /* self-loop (PID control continues) */
    { STATE_HEATING, "OVER_TEMP", STATE_FAULT, FAULT_OVER_TEMP, true },
    { STATE_HEATING, "OVER_CURRENT", STATE_FAULT, FAULT_OVER_CURRENT, true },
    { STATE_HEATING, "FAN_FAILURE", STATE_FAULT, FAULT_FAN_FAILURE, true },
    { STATE_HEATING, "PROBE_OPEN", STATE_FAULT, FAULT_PROBE_OPEN, true },
    { STATE_HEATING, "PROBE_SHORT", STATE_FAULT, FAULT_PROBE_SHORT, true },
    { STATE_HEATING, "THERMAL_RUNAWAY", STATE_FAULT, FAULT_THERMAL_RUNAWAY, true },
    { STATE_HEATING, "PAN_REMOVED", STATE_NO_PAN, FAULT_NONE, false },
    { STATE_HEATING, "STOP_BUTTON", STATE_COOLDOWN, FAULT_NONE, false },
    { STATE_HEATING, "TIMER_EXPIRED", STATE_COOLDOWN, FAULT_NONE, false },
    { STATE_NO_PAN, "PAN_REPLACED_SAME", STATE_PREHEAT, FAULT_NONE, false },  /* same impedance -> resumes PREHEAT */
    { STATE_NO_PAN, "PAN_REPLACED_DIFFERENT", STATE_COOLDOWN, FAULT_NONE, false },  /* different impedance -> COOLDOWN */
    { STATE_NO_PAN, "NO_PAN_TIMEOUT", STATE_COOLDOWN, FAULT_NONE, false },
    { STATE_COOLDOWN, "COOLED_DOWN", STATE_IDLE, FAULT_NONE, false },
    { STATE_COOLDOWN, "COOLDOWN_OVERHEAT", STATE_FAULT, FAULT_COOLDOWN_OVERHEAT, true },
    { STATE_FAULT, "FAULT_RESET_CLEARED", STATE_INIT, FAULT_NONE, false },
    { STATE_FAULT, "FAULT_RESET_PERSISTS", STATE_FAULT, FAULT_NONE, false },
    { STATE_RUNAWAY_FAULT, "FAULT_RESET_PERSISTS", STATE_RUNAWAY_FAULT, FAULT_NONE, false },
    { STATE_PAN_DET, "RUNAWAY_ABSOLUTE_TEMP", STATE_RUNAWAY_FAULT, FAULT_RUNAWAY_BOUNDARY, false },
    { STATE_PREHEAT, "RUNAWAY_ABSOLUTE_TEMP", STATE_RUNAWAY_FAULT, FAULT_RUNAWAY_BOUNDARY, false },
    { STATE_HEATING, "RUNAWAY_ABSOLUTE_TEMP", STATE_RUNAWAY_FAULT, FAULT_RUNAWAY_BOUNDARY, false },
    { STATE_NO_PAN, "RUNAWAY_ABSOLUTE_TEMP", STATE_RUNAWAY_FAULT, FAULT_RUNAWAY_BOUNDARY, false },
    { STATE_COOLDOWN, "RUNAWAY_ABSOLUTE_TEMP", STATE_RUNAWAY_FAULT, FAULT_RUNAWAY_BOUNDARY, false },
    { STATE_PAN_DET, "RUNAWAY_RISE_RATE", STATE_RUNAWAY_FAULT, FAULT_RUNAWAY_BOUNDARY, false },
    { STATE_PREHEAT, "RUNAWAY_RISE_RATE", STATE_RUNAWAY_FAULT, FAULT_RUNAWAY_BOUNDARY, false },
    { STATE_HEATING, "RUNAWAY_RISE_RATE", STATE_RUNAWAY_FAULT, FAULT_RUNAWAY_BOUNDARY, false },
    { STATE_NO_PAN, "RUNAWAY_RISE_RATE", STATE_RUNAWAY_FAULT, FAULT_RUNAWAY_BOUNDARY, false },
    { STATE_COOLDOWN, "RUNAWAY_RISE_RATE", STATE_RUNAWAY_FAULT, FAULT_RUNAWAY_BOUNDARY, false },
};
static const size_t transition_count = sizeof(transition_table) / sizeof(transition_table[0]);

static void apply_event_stubs(const char *event) {
    if (strcmp(event, "SELFTEST_FAIL") == 0) {
        mock_sm_fail_selftest_adc();
        return;
    }
    if (strcmp(event, "START_BUTTON") == 0) {
        mock_sm_press_button(BUTTON_START);
        return;
    }
    if (strcmp(event, "PAN_DETECTED") == 0) {
        mock_sm_set_pan_status(MOCK_PAN_PRESENT);
        return;
    }
    if (strcmp(event, "PAN_TIMEOUT") == 0) {
        mock_sm_advance_time(6000);
        return;
    }
    if (strcmp(event, "NEAR_TARGET") == 0) {
        mock_sm_set_pan_temperature(92.0f);
        return;
    }
    if (strcmp(event, "PREHEAT_TIMEOUT") == 0) {
        mock_sm_advance_time(600001);
        return;
    }
    if (strcmp(event, "OVER_TEMP") == 0) {
        mock_sm_set_heatsink_temperature(105.0f);
        return;
    }
    if (strcmp(event, "OVER_CURRENT") == 0) {
        mock_sm_set_dc_bus_current(40.0f);
        return;
    }
    if (strcmp(event, "FAN_FAILURE") == 0) {
        mock_sm_set_fan_running(false);
        return;
    }
    if (strcmp(event, "PROBE_OPEN") == 0) {
        mock_sm_set_rtd_resistance(15000.0f);
        return;
    }
    if (strcmp(event, "PROBE_SHORT") == 0) {
        mock_sm_set_rtd_resistance(5.0f);
        return;
    }
    if (strcmp(event, "PAN_REMOVED") == 0) {
        mock_sm_set_pan_status(MOCK_PAN_ABSENT);
        mock_sm_set_pan_temperature(25.0f);
        return;
    }
    if (strcmp(event, "STOP_BUTTON") == 0) {
        mock_sm_press_button(BUTTON_STOP);
        return;
    }
    if (strcmp(event, "THERMAL_RUNAWAY") == 0) {
        mock_sm_set_pan_temperature(115.0f);
        return;
    }
    if (strcmp(event, "TIMER_EXPIRED") == 0) {
        state_machine_set_timer(true, 1000);
        mock_sm_advance_time(2500);
        return;
    }
    if (strcmp(event, "PAN_REPLACED_SAME") == 0) {
        mock_sm_set_pan_status(MOCK_PAN_PRESENT);
        mock_sm_set_pan_impedance(5.0f);
        return;
    }
    if (strcmp(event, "PAN_REPLACED_DIFFERENT") == 0) {
        mock_sm_set_pan_status(MOCK_PAN_PRESENT);
        mock_sm_set_pan_impedance(5.0f);
        return;
    }
    if (strcmp(event, "NO_PAN_TIMEOUT") == 0) {
        mock_sm_advance_time(4000);
        return;
    }
    if (strcmp(event, "COOLED_DOWN") == 0) {
        mock_sm_set_heatsink_temperature(45.0f);
        return;
    }
    if (strcmp(event, "COOLDOWN_OVERHEAT") == 0) {
        mock_sm_set_heatsink_temperature(105.0f);
        return;
    }
    if (strcmp(event, "FAULT_RESET_CLEARED") == 0) {
        mock_sm_set_heatsink_temperature(65.0f);
        mock_sm_press_button(BUTTON_RESET);
        return;
    }
    if (strcmp(event, "FAULT_RESET_PERSISTS") == 0) {
        mock_sm_set_heatsink_temperature(105.0f);
        mock_sm_press_button(BUTTON_RESET);
        return;
    }
    if (strcmp(event, "RUNAWAY_ABSOLUTE_TEMP") == 0) {
        mock_sm_set_pan_temperature(310.0f);
        return;
    }
    if (strcmp(event, "RUNAWAY_RISE_RATE") == 0) {
        mock_sm_set_pan_temperature(30.0f);
        state_machine_update();
        mock_sm_advance_time(100);
        mock_sm_set_pan_temperature(200.0f);
        return;
    }
}

static void trigger_fault_entry(fault_code_t code) {
    /* Prevent secondary transitions: pan present, sensors nominal.
       Keep pan_temp far from target so NEAR_TARGET doesn't fire
       before check_safety_interlocks() in PREHEAT. */
    mock_sm_set_pan_status(MOCK_PAN_PRESENT);
    mock_sm_set_pan_temperature(25.0f);
    mock_sm_set_fan_running(true);
    mock_sm_set_dc_bus_current(0.0f);
    mock_sm_set_rtd_resistance(100.0f);
    switch (code) {
    case FAULT_OVER_TEMP:
        mock_sm_set_heatsink_temperature(105.0f);
        state_machine_force_state(STATE_PREHEAT);
        state_machine_update();
        break;
    case FAULT_SELF_TEST_FAILED:
        mock_sm_fail_selftest_adc();
        state_machine_force_state(STATE_INIT);
        state_machine_update();
        break;
    default:
        break;
    }
}

static void apply_preconditions(const transition_row_t *row) {
    switch (row->from) {
    case STATE_INIT:
        break;
    case STATE_IDLE:
        break;
    case STATE_PAN_DET:
        break;
    case STATE_PREHEAT:
    case STATE_HEATING:
        mock_sm_set_pan_status(MOCK_PAN_PRESENT);
        mock_sm_set_pan_temperature(92.0f);
        state_machine_reset_temp_baseline();
        break;
    case STATE_NO_PAN:
        mock_sm_set_pan_status(MOCK_PAN_ABSENT);
        break;
    case STATE_COOLDOWN:
        mock_sm_set_heatsink_temperature(65.0f);
        break;
    case STATE_FAULT:
        break;
    }
}

/* Events using show_message_then_transition() need a second update pass.
   MESSAGE_DISPLAY_TIME_MS = 2000 from state_machine.c */
#define MESSAGE_DRAIN_TIME_MS 2001

/* Drain any pending non-blocking message and return the settled state */
static system_state_t drain_message(void) {
    state_machine_update();
    return state_machine_get_state();
}

void test_transition_table(void) {
    for (size_t i = 0; i < transition_count; i++) {
        const transition_row_t *row = &transition_table[i];
        char msg[128];
        snprintf(msg, sizeof(msg), "Row %zu: %s + %s", i,
                 state_machine_get_state_string(row->from), row->event);

        /* Reset mock state to safe defaults */
        mock_sm_reset();

        /* Initialize state machine (sets last_update_time_ms = 0) */
        state_machine_init();

        /* Baseline: keep target > 0 so START_BUTTON fires in IDLE */
        state_machine_set_target_temp(100.0f);

        /* Prime the update cycle so last_update_time_ms is non-zero.
           Needed for dt_ms calculation in timer-expiry tests. */
        mock_sm_advance_time(1);
        state_machine_update();  /* INIT -> IDLE (self-tests pass) */

        /* ============================================================
         * Special case: FAULT-from tests (two-step: trigger fault, then
         * test reset behaviour).
         * ============================================================ */
        if (row->from == STATE_FAULT) {
            /* Step 1: trigger a known fault (OVER_TEMP) to reach FAULT */
            trigger_fault_entry(FAULT_OVER_TEMP);

            /* Step 2: set up reset conditions and test */
            apply_event_stubs(row->event);
            system_state_t result = drain_message();

            TEST_ASSERT_EQUAL_INT_MESSAGE(row->expected_to, result, msg);
            if (row->has_fault) {
                TEST_ASSERT_EQUAL_INT_MESSAGE(
                    row->expected_fault, state_machine_get_fault(), msg);
            }
            continue;
        }

        /* ============================================================
         * Standard single-update pattern for most transitions.
         * ============================================================ */

        /* Apply per-state preconditions (pan present, etc.) */
        apply_preconditions(row);

        /* Force to the starting state */
        state_machine_force_state(row->from);

        /* Apply event-specific stubs (button presses, sensor values) */
        apply_event_stubs(row->event);

        /* PAN_REPLACED_DIFFERENT: needs initial_pan_impedance set
           (normally set during PAN_DET). Go through PAN_DET first,
           then force to NO_PAN and re-apply the event stubs. */
        if (strcmp(row->event, "PAN_REPLACED_DIFFERENT") == 0) {
            /* First go through PAN_DET to establish initial impedance */
            state_machine_force_state(STATE_PAN_DET);
            mock_sm_set_pan_status(MOCK_PAN_PRESENT);
            for (int j = 0; j < 4; j++) {
                state_machine_update(); /* PAN_DET -> PREHEAT */
            }
            /* initial_pan_impedance is now set to get_pan_impedance() */
            /* Now transition to NO_PAN with a different impedance */
            state_machine_force_state(STATE_NO_PAN);
            mock_sm_set_pan_status(MOCK_PAN_PRESENT);
            mock_sm_set_pan_impedance(10.0f);  /* 100% error vs 5.0 */
            state_machine_update();  /* triggers show_message */
            mock_sm_advance_time(MESSAGE_DRAIN_TIME_MS);
            state_machine_update();
            system_state_t result2 = state_machine_get_state();
            TEST_ASSERT_EQUAL_INT_MESSAGE(row->expected_to, result2, msg);
            if (row->has_fault) {
                TEST_ASSERT_EQUAL_INT_MESSAGE(row->expected_fault,
                    state_machine_get_fault(), msg);
            }
            continue;
        }

        /* PAN_DETECTED: the confidence counter needs multiple updates. */
        if (strcmp(row->event, "PAN_DETECTED") == 0) {
            for (int j = 0; j < 4; j++) {
                state_machine_update();
            }
            TEST_ASSERT_EQUAL_INT_MESSAGE(row->expected_to,
                state_machine_get_state(), msg);
            continue;
        }

        /* PAN_REMOVED: needs temp reset (avoid near-target steal)
           and in HEATING multiple updates to clear debounce. */
        if (strcmp(row->event, "PAN_REMOVED") == 0) {
            for (int j = 0; j < 12; j++) {
                state_machine_update();
            }
            system_state_t result3 = state_machine_get_state();
            /* If we ended up in a message-pending state, drain it */
            if (result3 != row->expected_to) {
                mock_sm_advance_time(MESSAGE_DRAIN_TIME_MS);
                result3 = drain_message();
            }
            TEST_ASSERT_EQUAL_INT_MESSAGE(row->expected_to, result3, msg);
            if (row->has_fault) {
                TEST_ASSERT_EQUAL_INT_MESSAGE(row->expected_fault,
                    state_machine_get_fault(), msg);
            }
            continue;
        }

        /* Run the state update once */
        state_machine_update();

        /* Events that use show_message_then_transition() need a second
           update to drain the pending message and reach the target. */
        system_state_t actual = state_machine_get_state();
        if (actual != row->expected_to) {
            /* Advance time past the non-blocking message period */
            mock_sm_advance_time(MESSAGE_DRAIN_TIME_MS);
            actual = drain_message();
        }

        /* Assertions */
        TEST_ASSERT_EQUAL_INT_MESSAGE(row->expected_to, actual, msg);
        if (row->has_fault) {
            TEST_ASSERT_EQUAL_INT_MESSAGE(row->expected_fault,
                state_machine_get_fault(), msg);
        }
    }
}
