"""export command for temper-placer CLI."""

from __future__ import annotations

import click
import json
import sys
from pathlib import Path
from ._io import console

@click.command()
@click.option(
    "--placements",
    "-p",
    type=click.Path(exists=True, path_type=Path),
    required=True,
    help="Placements JSON file (from optimize command).",
)
@click.option(
    "--pcb",
    type=click.Path(exists=True, path_type=Path),
    required=True,
    help="Template KiCad PCB file.",
)
@click.option(
    "-o",
    "--output",
    type=click.Path(path_type=Path),
    required=True,
    help="Output .kicad_pcb file path.",
)
def export(
    placements: Path,
    pcb: Path,
    output: Path,
) -> None:
    """
    Export placements JSON to a KiCad PCB file.

    This command applies a placements JSON file (generated by the optimize
    command) to a template PCB file.

    Example:
        temper-placer export -p placements.json --pcb template.kicad_pcb -o output.kicad_pcb
    """
    console.print(f"[bold blue]temper-placer export[/] v{__version__}")

    try:
        import json

        from temper_placer.io.kicad_writer import (
            placements_from_json,
            write_placements_to_pcb,
        )

        # Load placements
        with open(placements) as f:
            placements_data = json.load(f)

        placements_dict = placements_from_json(placements_data)
        console.print(f"[green]✓[/] Loaded {len(placements_dict)} placements")

        # Write to PCB
        result = write_placements_to_pcb(pcb, output, placements_dict)

        console.print(f"[green]✓[/] Wrote {output}")
        console.print(f"  Updated: {result.components_updated}")
        console.print(f"  Skipped: {result.components_skipped}")

        if result.has_warnings:
            for w in result.warnings:
                console.print(f"  [yellow]Warning:[/] {w}")

    except Exception as e:
        console.print(f"[red]Failed: {e}[/]")
        sys.exit(1)
