#![allow(clippy::collapsible_if)]
#![allow(clippy::empty_line_after_doc_comments)]
#![allow(clippy::type_complexity)]
#![allow(clippy::manual_slice_fill)]
#![allow(clippy::needless_range_loop)]
//! Router V6 core logic — SAT-based topology solving.
//!
//! Many nested if-let chains use || conditions not supported in let-chains.

pub mod astar;
pub mod audit;
#[cfg(feature = "sat")]
pub mod bmc;
pub mod combinator;
pub mod encoding;
pub mod esl;
pub mod extraction;
pub mod loop_extractor;
pub mod provenance;
pub mod pruning;
pub mod theta_star;
#[cfg(feature = "sat")]
pub mod solver;
#[cfg(feature = "sat")]
pub mod equivalence;
pub mod tension;
pub mod types;
#[cfg(feature = "sat")]
pub mod watchdog;

// NOT gated on `python` or `sat`. The wasm32 tier builds with
// --no-default-features (which turns `sat` OFF, because rustsat-cadical is a
// C++ solver with no wasm32-unknown-unknown build), so a gate here would
// silently exclude the registry and the runner would fail to compile against
// it. `wasm-registry` is implied by every per-family feature and by
// `wasm-test-registry`, so any wasm build compiles this module.
// Generated by
// `scripts/gen_wasm_test_registry.py --crate temper-rust-router-core`.
#[cfg(feature = "wasm-registry")]
pub mod wasm_test_registry;

#[cfg(feature = "sat")]
pub use solver::{solve_with_cadical, SolveLimits};
pub use extraction::{extract_bundled, extract_topology, expand_assignments};
pub use loop_extractor::extract::auto_extract_loops;
pub use types::{
    BundleClass, BundledSolverResult, InternalBundleManifest, InternalConstraint,
    InternalConstraintModel, InternalVariable, SolverStats, SolverStatus, TopologyGraph,
    TopologyResult,
};
