//! The `wasm32` test registry for `temper-rust-router-core`.
//!
//! Generated by `scripts/gen_wasm_test_registry.py`; run it after adding a
//! test to any listed module, and `--check` gates drift in CI.
//!
//! `cargo test`'s libtest harness cannot target `wasm32-unknown-unknown`,
//! so the Worker tier calls each test function individually instead of
//! running a test binary.  This module is the flat, indexable list of them.
//!
//! Only modules that survive `--no-default-features` appear here.  Tests
//! inside `#[cfg(feature = "python")]` modules are structurally absent
//! from a `wasm32` build and cannot be registered here at all.
//!
//! Three exclusion classes apply here, all structural:
//!
//! * `#[cfg(feature = "sat")]` modules -- `solver`, `bmc`,
//!   `equivalence`, `watchdog`.  `sat` is a *default* feature, but it
//!   pulls `rustsat-cadical`, a C++ solver with no
//!   `wasm32-unknown-unknown` build, so those modules cannot exist on
//!   this target at all.  This is the first crate on the tier whose
//!   absent feature is not `python`.
//! * `#[cfg(feature = "python")]` modules, as elsewhere on the tier.
//! * `proptest` modules use a dev-dependency, which is not linked into
//!   the ordinary (non-test) build this registry compiles into.
//!
//! `scripts/gen_wasm_test_registry.py --crate temper-rust-router-core
//! --census` prints the full module census with per-module counts.
//!
//! ## Families
//!
//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`
//! feature, as in `temper-drc-rs`.  One family (`router-core`): the
//! solver-free core is a flat set of graph and rewrite kernels.

/// A single test: its fully qualified name and a nullary callable.
///
/// Failure is signalled by panicking, exactly as under libtest.  On
/// `wasm32-unknown-unknown` a panic aborts (the target has no unwinding on
/// stable), which surfaces to the host as a WebAssembly trap -- so the
/// runner catches the trap rather than a `Result`.
pub type WasmTest = (&'static str, fn());

/// All 3465 eligible tests, in a stable order.  Each entry is
/// gated on the per-family `wasm-registry-<family>` feature; enable
/// all families (`wasm-test-registry`) or individual ones.
pub const ALL: &[&[WasmTest]] = &[
    #[cfg(feature = "wasm-registry-router-core")] crate::astar::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::astar_nlayer::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::audit::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::combinator::integration::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::combinator::lower::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::combinator::rewrite::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::combinator::types::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::direct_topology::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::encoding::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::esl::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::extraction::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::loop_extractor::classify::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::loop_extractor::extract::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::loop_extractor::types::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::net_batching::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::property_campaigns::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::provenance::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::pruning::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::tension::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-router-core")] crate::theta_star::tests::WASM_TESTS,
];

/// Total number of registered tests *in the currently-selected families*.
pub fn count() -> usize {
    ALL.iter().map(|m| m.len()).sum()
}

/// The test at `index` in the flattened registry.
pub fn get(index: usize) -> Option<&'static WasmTest> {
    let mut remaining = index;
    for module in ALL {
        if remaining < module.len() {
            return Some(&module[remaining]);
        }
        remaining -= module.len();
    }
    None
}
