"""Tests for ci_check_drc.py's ``pcb/temper.kicad_dru`` regeneration.

``pcb/temper.kicad_dru`` is generated by ``scripts/generate_kicad_dru.py``
from ``TEMPER_NET_CLASSES`` (the SSOT), but before this fix it was neither
git-tracked nor gitignored, and no code path ever generated it -- so a
local run could measure kicad-cli DRC with a stale or absent rules file
while CI measured with a different one (or none at all), for byte-identical
board content. Custom rules add categories bare kicad-cli never reports
(e.g. ``track_width``; see the KiCad ``rule_severities`` schema and
``generate_kicad_dru.py``'s per-netclass trace-width rules) -- so this
ambient, unpinned input made the DRC ratchet's answer depend on local
machine state instead of committed inputs. See
docs/evidence/2026-07-27-drc-truth-gate-discrepancy.md.

``ci_check_drc._regenerate_kicad_dru`` closes this by regenerating the file
unconditionally, from the SSOT script, before every kicad-cli-backend run
(CI and local alike). These tests operate against the real repo's
``pcb/temper.kicad_dru`` path (the same path ``generate_kicad_dru.py``
itself writes, computed from its own ``__file__``) since that path is not
parameterizable without diverging from the SSOT script -- prior content is
saved and restored around each test.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import ci_check_drc  # noqa: E402
import generate_kicad_dru  # noqa: E402


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


@pytest.fixture
def preserve_kicad_dru():
    """Save/restore whatever is at pcb/temper.kicad_dru around a test that
    exercises the real regeneration path, so the test suite never leaves
    the working tree in a different state than it found it.
    """
    dru_path = generate_kicad_dru.OUTPUT_PATH
    original = dru_path.read_text(encoding="utf-8") if dru_path.exists() else None
    try:
        yield dru_path
    finally:
        if original is not None:
            dru_path.write_text(original, encoding="utf-8")
        elif dru_path.exists():
            dru_path.unlink()


class TestRegenerateKicadDru:
    def test_writes_to_the_ssot_generators_own_output_path(self, preserve_kicad_dru):
        """The function must never invent its own path -- it has to defer
        to generate_kicad_dru.py's own OUTPUT_PATH, or the two could drift
        apart and regenerate the wrong file.
        """
        dru_path = ci_check_drc._regenerate_kicad_dru(_repo_root())
        assert dru_path == generate_kicad_dru.OUTPUT_PATH

    def test_content_matches_ssot_generator_exactly(self, preserve_kicad_dru):
        dru_path = ci_check_drc._regenerate_kicad_dru(_repo_root())
        assert dru_path.read_text(encoding="utf-8") == generate_kicad_dru.generate_dru()

    def test_stale_content_is_overwritten_not_preserved(self, preserve_kicad_dru):
        """This is the reproducibility hole itself, reproduced directly:
        a stale/garbage .kicad_dru left over from a prior local run (or
        simply absent, as in CI before this fix) would previously persist
        unchanged and silently change kicad-cli's measured DRC categories
        for a board whose bytes never changed. Regeneration must always
        win over whatever was on disk before.
        """
        dru_path = preserve_kicad_dru
        dru_path.parent.mkdir(parents=True, exist_ok=True)
        dru_path.write_text(
            "GARBAGE -- stale rules file left by a prior local run\n", encoding="utf-8"
        )
        assert "GARBAGE" in dru_path.read_text(encoding="utf-8")

        ci_check_drc._regenerate_kicad_dru(_repo_root())

        content = dru_path.read_text(encoding="utf-8")
        assert "GARBAGE" not in content
        assert content == generate_kicad_dru.generate_dru()

    def test_absent_file_is_created(self, preserve_kicad_dru):
        """Mirrors the CI side of the hole: no .kicad_dru present at all
        (the documented CI state before this fix) must also converge to
        the SSOT content, not be skipped because there was 'nothing to
        overwrite'.
        """
        dru_path = preserve_kicad_dru
        if dru_path.exists():
            dru_path.unlink()
        assert not dru_path.exists()

        ci_check_drc._regenerate_kicad_dru(_repo_root())

        assert dru_path.exists()
        assert dru_path.read_text(encoding="utf-8") == generate_kicad_dru.generate_dru()

    def test_only_runs_for_kicad_cli_backend(self, monkeypatch, tmp_path):
        """The rust backend never consults .kicad_dru at all (it parses the
        board directly, bypassing kicad-cli entirely) -- regenerating it
        for that backend would be pointless churn, not a fix."""
        calls: list[Path] = []
        monkeypatch.setattr(
            ci_check_drc,
            "_regenerate_kicad_dru",
            lambda repo_root: calls.append(repo_root) or generate_kicad_dru.OUTPUT_PATH,
        )
        monkeypatch.setattr(sys, "argv", ["ci_check_drc.py", "--backend", "rust"])
        monkeypatch.setattr(ci_check_drc, "_find_repo_root", lambda: tmp_path)
        # No ceiling file at tmp_path -> main() exits early with SKIPPED,
        # which is fine: the only thing under test is whether regeneration
        # was attempted before that point.
        ci_check_drc.main()
        assert calls == []


# ---------------------------------------------------------------------------
# R11 full-board DRC oracle differential wiring (plan 2026-08-02-008 U3)
# ---------------------------------------------------------------------------

_FALSIFIER = (
    "packages/temper-placer/tests/fixtures/drc_differential_courtyard_falsifier.kicad_pcb"
)


def _kicad_available() -> bool:
    from temper_placer.validation._drc_api import is_kicad_cli_available

    return is_kicad_cli_available()


def _internal_available() -> bool:
    try:
        import temper_drc_rs  # noqa: F401

        return True
    except ImportError:
        return False


class TestDrcDifferentialWiring:
    def test_kicad_cli_backend_emits_differential_verdict_for_committed_board(
        self, capsys, preserve_kicad_dru, monkeypatch
    ):
        """U3 test 2 (integration): ``ci_check_drc.py --backend kicad-cli``
        emits the differential verdict for the committed board and exits 0.
        """
        if not (_kicad_available() and _internal_available()):
            pytest.skip("kicad-cli and/or temper_drc_rs not available")
        monkeypatch.setattr(ci_check_drc, "_find_repo_root", lambda: _repo_root())
        old_argv = sys.argv
        sys.argv = ["ci_check_drc.py", "--backend", "kicad-cli"]
        try:
            exit_code = ci_check_drc.main()
        finally:
            sys.argv = old_argv
        out = capsys.readouterr().out
        assert "DRC differential" in out
        assert "verdict: PASS" in out, "committed board differential must pass"
        assert exit_code < 4, f"differential verdict must not fail the run: {exit_code}"

    def test_falsifier_substitution_exits_nonzero(
        self, capsys, preserve_kicad_dru, monkeypatch
    ):
        """U3 test 3 (integration): with the D3/C4 fixture substituted as the
        board under test, the wired gate exits nonzero (beyond-band courtyard
        delta)."""
        if not (_kicad_available() and _internal_available()):
            pytest.skip("kicad-cli and/or temper_drc_rs not available")
        monkeypatch.setattr(ci_check_drc, "_find_repo_root", lambda: _repo_root())

        # Point --differential-board at the falsifier via argv; main() reads
        # it relative to repo root.
        old_argv = sys.argv
        sys.argv = [
            "ci_check_drc.py",
            "--backend",
            "kicad-cli",
            "--differential-board",
            _FALSIFIER,
        ]
        try:
            exit_code = ci_check_drc.main()
        finally:
            sys.argv = old_argv
        out = capsys.readouterr().out
        assert "DRC differential" in out
        assert "FAIL courtyard" in out, "falsifier courtyard delta must be beyond band"
        assert exit_code == 4, f"beyond-band verdict must exit 4, got {exit_code}"

    def test_skipped_differential_is_reported_not_passed(self, monkeypatch, tmp_path):
        """A SKIPPED differential (missing engine) is reported with its cause
        and never counted as a pass or a failure of the gate."""
        from temper_placer.validation.drc_differential import DifferentialVerdict

        def _fake_run_differential(_pcb_path):
            return DifferentialVerdict(passed=False, skipped=True, skip_reason="no kicad-cli")

        monkeypatch.setattr(
            "temper_placer.validation.drc_differential.run_differential",
            _fake_run_differential,
        )
        results, any_beyond = ci_check_drc._run_differential(tmp_path, [("b", tmp_path / "x.kicad_pcb")])
        assert any_beyond is False
        assert results[0][1].skipped is True
        assert "kicad-cli" in results[0][1].skip_reason
