"""Tests for ci_check_drc.py's ``pcb/temper.kicad_dru`` regeneration.

``pcb/temper.kicad_dru`` is generated by ``scripts/generate_kicad_dru.py``
from ``TEMPER_NET_CLASSES`` (the SSOT), but before this fix it was neither
git-tracked nor gitignored, and no code path ever generated it -- so a
local run could measure kicad-cli DRC with a stale or absent rules file
while CI measured with a different one (or none at all), for byte-identical
board content. Custom rules add categories bare kicad-cli never reports
(e.g. ``track_width``; see the KiCad ``rule_severities`` schema and
``generate_kicad_dru.py``'s per-netclass trace-width rules) -- so this
ambient, unpinned input made the DRC ratchet's answer depend on local
machine state instead of committed inputs. See
docs/evidence/2026-07-27-drc-truth-gate-discrepancy.md.

``ci_check_drc._regenerate_kicad_dru`` closes this by regenerating the file
unconditionally, from the SSOT script, before every kicad-cli-backend run
(CI and local alike). These tests operate against the real repo's
``pcb/temper.kicad_dru`` path (the same path ``generate_kicad_dru.py``
itself writes, computed from its own ``__file__``) since that path is not
parameterizable without diverging from the SSOT script -- prior content is
saved and restored around each test.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import ci_check_drc  # noqa: E402
import generate_kicad_dru  # noqa: E402


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


@pytest.fixture
def preserve_kicad_dru():
    """Save/restore whatever is at pcb/temper.kicad_dru around a test that
    exercises the real regeneration path, so the test suite never leaves
    the working tree in a different state than it found it.
    """
    dru_path = generate_kicad_dru.OUTPUT_PATH
    original = dru_path.read_text(encoding="utf-8") if dru_path.exists() else None
    try:
        yield dru_path
    finally:
        if original is not None:
            dru_path.write_text(original, encoding="utf-8")
        elif dru_path.exists():
            dru_path.unlink()


class TestRegenerateKicadDru:
    def test_writes_to_the_ssot_generators_own_output_path(self, preserve_kicad_dru):
        """The function must never invent its own path -- it has to defer
        to generate_kicad_dru.py's own OUTPUT_PATH, or the two could drift
        apart and regenerate the wrong file.
        """
        dru_path = ci_check_drc._regenerate_kicad_dru(_repo_root())
        assert dru_path == generate_kicad_dru.OUTPUT_PATH

    def test_content_matches_ssot_generator_exactly(self, preserve_kicad_dru):
        dru_path = ci_check_drc._regenerate_kicad_dru(_repo_root())
        assert dru_path.read_text(encoding="utf-8") == generate_kicad_dru.generate_dru()

    def test_stale_content_is_overwritten_not_preserved(self, preserve_kicad_dru):
        """This is the reproducibility hole itself, reproduced directly:
        a stale/garbage .kicad_dru left over from a prior local run (or
        simply absent, as in CI before this fix) would previously persist
        unchanged and silently change kicad-cli's measured DRC categories
        for a board whose bytes never changed. Regeneration must always
        win over whatever was on disk before.
        """
        dru_path = preserve_kicad_dru
        dru_path.parent.mkdir(parents=True, exist_ok=True)
        dru_path.write_text(
            "GARBAGE -- stale rules file left by a prior local run\n", encoding="utf-8"
        )
        assert "GARBAGE" in dru_path.read_text(encoding="utf-8")

        ci_check_drc._regenerate_kicad_dru(_repo_root())

        content = dru_path.read_text(encoding="utf-8")
        assert "GARBAGE" not in content
        assert content == generate_kicad_dru.generate_dru()

    def test_absent_file_is_created(self, preserve_kicad_dru):
        """Mirrors the CI side of the hole: no .kicad_dru present at all
        (the documented CI state before this fix) must also converge to
        the SSOT content, not be skipped because there was 'nothing to
        overwrite'.
        """
        dru_path = preserve_kicad_dru
        if dru_path.exists():
            dru_path.unlink()
        assert not dru_path.exists()

        ci_check_drc._regenerate_kicad_dru(_repo_root())

        assert dru_path.exists()
        assert dru_path.read_text(encoding="utf-8") == generate_kicad_dru.generate_dru()

    def test_only_runs_for_kicad_cli_backend(self, monkeypatch, tmp_path):
        """The rust backend never consults .kicad_dru at all (it parses the
        board directly, bypassing kicad-cli entirely) -- regenerating it
        for that backend would be pointless churn, not a fix."""
        calls: list[Path] = []
        monkeypatch.setattr(
            ci_check_drc,
            "_regenerate_kicad_dru",
            lambda repo_root: calls.append(repo_root) or generate_kicad_dru.OUTPUT_PATH,
        )
        monkeypatch.setattr(sys, "argv", ["ci_check_drc.py", "--backend", "rust"])
        monkeypatch.setattr(ci_check_drc, "_find_repo_root", lambda: tmp_path)
        # No ceiling file at tmp_path -> main() exits early with SKIPPED,
        # which is fine: the only thing under test is whether regeneration
        # was attempted before that point.
        ci_check_drc.main()
        assert calls == []


class TestNoiseHeadroomGuardWiring:
    """``DrcRatchet.check()`` runs ``run_drc`` exactly once per invocation
    and was, before this guard, the ONLY thing deciding a PR's DRC
    pass/fail -- the file's own documented >= 120-sample protocol
    (AGENTS.md's "Board Change -> DRC Ceiling Re-measurement" section) was
    enforced only at ceiling-raise time (``check_drc_ceiling_approval.py``),
    never on every PR. These tests are the missing wiring check: ``main()``
    must surface ``DrcRatchet.check_noise_headroom()`` as its own exit-code
    3 failure, independent of whatever ``check()`` itself returned -- a
    category the guard has identified as unsafe for single-sampling must
    not stay invisible to CI just because the one sample that run happened
    to land under the ceiling anyway.

    ``DrcRatchet.check`` is monkeypatched in every test here so these are
    pure wiring tests: they exercise ``main()``'s exit-code composition,
    not a real (or even Rust-backend) DRC run -- ``check_noise_headroom``
    itself, and the false-fail scenario it is a proxy for, are exercised
    directly against a synthetic noisy oracle in
    ``packages/temper-placer/tests/regression/test_drc_ratchet.py``'s
    ``TestNoiseHeadroomGuard``/``TestNoiseHeadroomAntiVacuity``.
    """

    @staticmethod
    def _write_ceiling(tmp_path: Path, *, nondet: dict, by_type: dict) -> None:
        ceiling_dir = tmp_path / "power_pcb_dataset"
        ceiling_dir.mkdir(parents=True, exist_ok=True)
        (ceiling_dir / "drc_ceiling.json").write_text(
            json.dumps(
                {
                    "boards": [
                        {
                            "board_id": "b",
                            "path": "pcb/b.kicad_pcb",
                            "error_ceiling": 1000,
                            "warning_ceiling": 0,
                            "violations_by_type": by_type,
                            "nondeterministic_error_types": nondet,
                        }
                    ]
                }
            )
        )

    @staticmethod
    def _stub_check_passes(monkeypatch) -> None:
        """Force DrcRatchet.check() (the per-board ceiling comparison) to
        report a clean PASS, so exit code 3 in these tests can only come
        from the noise-headroom guard, never from the unrelated per-board
        check."""
        ci_check_drc._setup_path(Path(__file__).resolve().parents[2])
        from temper_placer.regression.drc_ratchet import DrcRatchet, DrcRatchetResult

        monkeypatch.setattr(
            DrcRatchet,
            "check",
            lambda self, repo_root: [DrcRatchetResult(passed=True, board_id="b", message="ok")],
        )

    def test_insufficient_headroom_sets_exit_code_3(self, monkeypatch, tmp_path, capsys):
        """Reproduces this repo's real recorded ``creepage`` category
        (observed 185-187 over 120 samples, spread 2) behind a ``max + 1``
        ceiling (188, headroom 1) -- exactly the shape
        ``check_noise_headroom`` flags as unsafe."""
        self._write_ceiling(
            tmp_path,
            nondet={"creepage": {"observed": [185, 186, 187], "samples": 120}},
            by_type={"creepage": 188},
        )
        self._stub_check_passes(monkeypatch)
        monkeypatch.setattr(sys, "argv", ["ci_check_drc.py", "--backend", "rust"])
        monkeypatch.setattr(ci_check_drc, "_find_repo_root", lambda: tmp_path)

        exit_code = ci_check_drc.main()
        out = capsys.readouterr().out

        assert exit_code == 3
        assert "noise-headroom guard" in out
        assert "creepage" in out

    def test_sufficient_headroom_leaves_exit_code_at_check_result(
        self, monkeypatch, tmp_path, capsys
    ):
        """The file's own ``max + 1`` convention on a two-valued category
        (spread 1, headroom 1) is exactly at the safe boundary -- must not
        trip the guard, and ``check()``'s own clean PASS must be the only
        thing exit code 0 depends on."""
        self._write_ceiling(
            tmp_path,
            nondet={"clearance": {"observed": [377, 378], "samples": 120}},
            by_type={"clearance": 379},
        )
        self._stub_check_passes(monkeypatch)
        monkeypatch.setattr(sys, "argv", ["ci_check_drc.py", "--backend", "rust"])
        monkeypatch.setattr(ci_check_drc, "_find_repo_root", lambda: tmp_path)

        exit_code = ci_check_drc.main()
        out = capsys.readouterr().out

        assert exit_code == 0
        assert "PASS: noise-headroom guard" in out


class TestCapSaturationGuardWiring:
    """``main()`` must fail loudly (exit 4) whenever a DRC category count
    saturates KiCad's reporting cap (ERROR_LIMIT 199 / EXTENDED_ERROR_LIMIT
    499): a capped count is a FLOOR (true count >= N), not a count, so the
    ceiling comparison on it is inconclusive -- the true count can exceed
    the ceiling while the capped reading never crosses it. Two independent
    surfaces, both must be caught:

    * the *measured* counts (``DrcRatchetResult.capped_error_categories`` /
      ``capped_warning_categories``, populated by the kicad-cli backend's
      cap classification), and
    * the committed *ceiling file* itself -- a ceiling value at its
      category's cap protects nothing ("do not ratchet a saturated
      number"; the de-saturation correction in PR #1178 raised ceilings to
      true counts for exactly this reason).

    ``DrcRatchet.check`` is monkeypatched in every test here so these are
    pure wiring tests; the classification itself (DrcCount, the per-category
    cap table) is exercised in ``temper-drc-rs``'s Rust proptest suite and
    through ``temper_placer.validation._drc_api`` shim tests.
    """

    @staticmethod
    def _write_ceiling(tmp_path: Path, *, by_type: dict) -> None:
        ceiling_dir = tmp_path / "power_pcb_dataset"
        ceiling_dir.mkdir(parents=True, exist_ok=True)
        (ceiling_dir / "drc_ceiling.json").write_text(
            json.dumps(
                {
                    "boards": [
                        {
                            "board_id": "b",
                            "path": "pcb/b.kicad_pcb",
                            "error_ceiling": 1000,
                            "warning_ceiling": 0,
                            "violations_by_type": by_type,
                        }
                    ]
                }
            )
        )

    @staticmethod
    def _stub_check(monkeypatch, result) -> None:
        ci_check_drc._setup_path(Path(__file__).resolve().parents[2])
        from temper_placer.regression.drc_ratchet import DrcRatchet

        monkeypatch.setattr(DrcRatchet, "check", lambda self, repo_root: [result])

    def test_measured_capped_count_sets_exit_code_4(self, monkeypatch, tmp_path, capsys):
        """A measured track_width count at exactly 199 (its ERROR_LIMIT) is
        a floor -- even when the ceiling comparison itself passes, the
        result must be inconclusive and the gate must say so."""
        self._write_ceiling(tmp_path, by_type={"track_width": 300})
        from temper_placer.regression.drc_ratchet import DrcRatchetResult

        self._stub_check(
            monkeypatch,
            DrcRatchetResult(
                passed=True,
                board_id="b",
                message="ok",
                capped_error_categories={"track_width": "199 (CAPPED — true count >= 199)"},
            ),
        )
        monkeypatch.setattr(sys, "argv", ["ci_check_drc.py", "--backend", "rust"])
        monkeypatch.setattr(ci_check_drc, "_find_repo_root", lambda: tmp_path)

        exit_code = ci_check_drc.main()
        out = capsys.readouterr().out

        assert exit_code == 4
        assert "cap-saturation guard" in out
        assert "track_width" in out
        assert "CAPPED — true count >= 199" in out

    def test_saturated_ceiling_value_sets_exit_code_4(self, monkeypatch, tmp_path, capsys):
        """A committed ceiling at its category's cap protects nothing: the
        ratchet would compare the current count against a floor. Must fail
        loudly, independently of what the per-board check measured."""
        self._write_ceiling(tmp_path, by_type={"track_width": 199})
        from temper_placer.regression.drc_ratchet import DrcRatchetResult

        self._stub_check(
            monkeypatch,
            DrcRatchetResult(passed=True, board_id="b", message="ok"),
        )
        monkeypatch.setattr(sys, "argv", ["ci_check_drc.py", "--backend", "rust"])
        monkeypatch.setattr(ci_check_drc, "_find_repo_root", lambda: tmp_path)

        exit_code = ci_check_drc.main()
        out = capsys.readouterr().out

        assert exit_code == 4
        assert "cap-saturation guard" in out
        assert "track_width" in out

    def test_uncapped_categories_never_trip_the_guard(self, monkeypatch, tmp_path, capsys):
        """creepage at 199 is a real count (its provider bypasses the cap)
        and clearance at 199 is below ITS cap -- neither may trip exit 4."""
        self._write_ceiling(
            tmp_path, by_type={"creepage": 199, "clearance": 199}
        )
        from temper_placer.regression.drc_ratchet import DrcRatchetResult

        self._stub_check(
            monkeypatch,
            DrcRatchetResult(
                passed=True, board_id="b", message="ok", capped_error_categories={}
            ),
        )
        monkeypatch.setattr(sys, "argv", ["ci_check_drc.py", "--backend", "rust"])
        monkeypatch.setattr(ci_check_drc, "_find_repo_root", lambda: tmp_path)

        exit_code = ci_check_drc.main()
        out = capsys.readouterr().out

        assert exit_code == 0
        assert "PASS: cap-saturation guard" in out
