"""P1 U4 step 1: fresh MCU candidate generation + committed compact index.

Regenerates the candidate from the current Atopile source through the U2
strict bridge (never copies the abandoned `zapote/runs/...` tree) and writes
`INDEX.json`: the source manifest plus a per-file sha256 census of every
generated byte. Operator-controlled; requires TEMPER_BLOCK_GENERATE=1.
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
from pathlib import Path

RUN = Path(__file__).resolve().parent
REPO = RUN.parents[2]
sys.path.insert(0, str(REPO / "harness-lab"))

import run_block  # noqa: E402


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    if os.environ.get("TEMPER_BLOCK_GENERATE") != "1":
        raise SystemExit("set TEMPER_BLOCK_GENERATE=1 to generate")
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="candidate")
    parser.add_argument("--index", default="INDEX.json")
    args = parser.parse_args()
    output = RUN / args.output
    index_path = RUN / args.index
    manifest = run_block.generate_candidate(
        REPO,
        REPO / "pcb" / "blocks" / "control-assembly" / "target-context.json",
        output,
        confirm=True,
    )
    files = sorted(
        str(path.relative_to(output)) for path in output.rglob("*") if path.is_file()
    )
    record = {
        "schema": "temper.mcu-run-index.v1",
        "run_id": RUN.name,
        "generated_by": "harness-lab/runs/mcu-20260910-a/generate_candidate.py",
        "artifact": args.output,
        "assisted": args.output != "candidate",
        "entry": manifest["entry"],
        "atopile_pinned": manifest["atopile_pinned"],
        "kicad_cli": manifest["kicad_cli"],
        "target_context_sha256": manifest["target_context"]["sha256"],
        "netlist_sha256": manifest["inputs"]["netlist_sha256"],
        "bom_sha256": manifest["inputs"]["bom_sha256"],
        "components": len(manifest["converted"]["components"]),
        "board": manifest["board"],
        "files": [{"path": name, "sha256": sha256(output / name)} for name in files],
    }
    index_path.write_text(
        json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(
        json.dumps(
            {
                "run": RUN.name,
                "artifact": args.output,
                "n_files": len(files),
                "components": record["components"],
                "board": record["board"],
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
