"""Stub for OR-Tools CP-SAT cp_model module.

Provides type annotations for the OR-Tools API surface used by temper-placer.
Only methods/attributes actually consumed by the codebase are declared.
"""

from __future__ import annotations
from typing import List

# ---------------------------------------------------------------------------
# Solver status constants
# ---------------------------------------------------------------------------
OPTIMAL: int
FEASIBLE: int
INFEASIBLE: int
MODEL_INVALID: int
UNKNOWN: int

# ---------------------------------------------------------------------------
# Expression types
# ---------------------------------------------------------------------------


class BoundedLinearExpression:
    """A linear expression that can be used as a constraint argument.

    CP-SAT overloads arithmetic and comparison operators to produce these
    rather than Python bools, so that Add() can treat them as constraints.
    """

    # Comparison operators chain BoundedLinearExpressions
    def __eq__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...  # type: ignore[override]
    def __ne__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...  # type: ignore[override]
    def __le__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...
    def __ge__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...
    def __lt__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...
    def __gt__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...

    # Arithmetic operators for summing expressions
    def __add__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...
    def __radd__(self, other: int) -> BoundedLinearExpression: ...
    def __sub__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...
    def __rsub__(self, other: int) -> BoundedLinearExpression: ...
    def __mul__(self, other: int) -> BoundedLinearExpression: ...
    def __rmul__(self, other: int) -> BoundedLinearExpression: ...
    def __neg__(self) -> BoundedLinearExpression: ...
    def __hash__(self) -> int: ...


class IntVar:
    """Integer variable in the CP-SAT model (domain [lb, ub]).

    Overloads arithmetic and comparison operators to produce
    :class:`BoundedLinearExpression` objects, enabling the fluent
    ``model.Add(x + y == 2 * z)`` idiom.
    """

    def Index(self) -> int: ...
    def Name(self) -> str: ...
    def Not(self) -> IntVar: ...

    # Arithmetic operators
    def __add__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...
    def __radd__(self, other: int) -> BoundedLinearExpression: ...
    def __sub__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...
    def __rsub__(self, other: int) -> BoundedLinearExpression: ...
    def __mul__(self, other: int) -> BoundedLinearExpression: ...
    def __rmul__(self, other: int) -> BoundedLinearExpression: ...
    def __neg__(self) -> BoundedLinearExpression: ...

    # Comparison operators (return BoundedLinearExpression, not bool)
    def __eq__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...  # type: ignore[override]
    def __ne__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...  # type: ignore[override]
    def __le__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...
    def __ge__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...
    def __lt__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...
    def __gt__(self, other: int | IntVar | BoundedLinearExpression) -> BoundedLinearExpression: ...

    # Required for sum()
    def __hash__(self) -> int: ...


class Constraint:
    """A CP-SAT constraint returned by ``CpModel.Add()`` etc."""

    def OnlyEnforceIf(self, boolvar: IntVar) -> Constraint: ...


class IntervalVar:
    """An interval variable (start, size, end)."""


# ---------------------------------------------------------------------------
# Solver types
# ---------------------------------------------------------------------------


class SatParameters:
    """Solver parameter bag."""
    max_time_in_seconds: float
    num_search_workers: int
    random_seed: int
    log_search_progress: bool


class CpSolverSolutionCallback:
    """Base class for solution callbacks."""


class CpSolver:
    """CP-SAT solver."""

    parameters: SatParameters

    def __init__(self) -> None: ...
    def Solve(self, model: CpModel) -> int: ...
    def Value(self, var: IntVar) -> int: ...
    def ObjectiveValue(self) -> float: ...
    def WallTime(self) -> float: ...
    def SufficientAssumptionsForInfeasibility(self) -> List[int]: ...


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------


class CpModel:
    """CP-SAT constraint programming model."""

    def __init__(self) -> None: ...

    # --- Variable creation ---
    def NewIntVar(self, lb: int, ub: int, name: str) -> IntVar: ...
    def NewBoolVar(self, name: str) -> IntVar: ...
    def NewConstant(self, value: int) -> IntVar: ...
    def NewIntervalVar(self, start: IntVar, size: IntVar, end: IntVar, name: str) -> IntervalVar: ...

    # --- Constraints ---
    def Add(self, ct: BoundedLinearExpression | Constraint) -> Constraint: ...
    def AddHint(self, var: IntVar, value: int) -> None: ...
    def AddElement(self, index: IntVar, values: List[int], target: IntVar) -> None: ...
    def AddNoOverlap2D(self, x_intervals: List[IntervalVar], y_intervals: List[IntervalVar]) -> None: ...
    def AddMultiplicationEquality(self, target: IntVar, exprs: List[IntVar]) -> Constraint: ...
    def AddAssumption(self, lit: IntVar) -> None: ...
    def AddAssumptions(self, lits: List[IntVar]) -> None: ...
    def ClearAssumptions(self) -> None: ...
    def AddBoolOr(self, literals: List[IntVar]) -> Constraint: ...
    def AddAbsEquality(self, target: IntVar, expr: BoundedLinearExpression) -> Constraint: ...

    # --- Objective ---
    def Minimize(self, expr: BoundedLinearExpression) -> None: ...
    def Maximize(self, expr: BoundedLinearExpression) -> None: ...

    # --- Serialization ---
    def Proto(self) -> object: ...
