"""Keep bulky retained evidence out of git and restore it on demand.

A tracked file under zapote/ is bulk when it ends in .gz or .npz, or exceeds
5 MB. Rust workspace inputs under zapote/packages/ (e.g. include_bytes!
fixtures) are exempt from the suffix rule but not the size cap. Bulk lives in
GitHub release assets (plain tar parts); the manifest
zapote/evidence-archive.json records each file's path, size, sha256 and the
asset that holds it. `check` is the CI gate that keeps bulk from returning.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

SCHEMA = "zapote.evidence-archive.v1"
MANIFEST = "zapote/evidence-archive.json"
BULK_SUFFIXES = (".gz", ".npz")
MAX_TRACKED_BYTES = 5 * 1024 * 1024
WORKSPACE = "zapote/packages/"
GITIGNORE_BEGIN = "# --- evidence-archive (generated by tools/evidence_archive.py) ---"
GITIGNORE_END = "# --- end evidence-archive ---"


def is_bulk(path: str, size: int, max_bytes: int = MAX_TRACKED_BYTES) -> bool:
    return size > max_bytes or (path.endswith(BULK_SUFFIXES) and not path.startswith(WORKSPACE))


def tracked_files(repo: Path) -> list[tuple[str, int]]:
    out = subprocess.run(
        ["git", "-C", str(repo), "ls-files", "-z", "--", "zapote"],
        check=True, capture_output=True,
    ).stdout.decode()
    return [(p, (repo / p).stat().st_size) for p in out.split("\0") if p and (repo / p).is_file()]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def plan_assets(entries, max_asset_bytes: int) -> list[list[tuple[str, int]]]:
    groups: list[list[tuple[str, int]]] = []
    current: list[tuple[str, int]] = []
    used = 0
    for path, size in sorted(entries):
        if size > max_asset_bytes:
            raise ValueError(f"{path} ({size} B) does not fit in one asset")
        if current and used + size > max_asset_bytes:
            groups.append(current)
            current, used = [], 0
        current.append((path, size))
        used += size
    if current:
        groups.append(current)
    return groups


def pack(repo: Path, out_dir: Path, release: str, max_asset_bytes: int = 1_500_000_000,
         max_bytes: int = MAX_TRACKED_BYTES, prior: dict | None = None) -> dict:
    """Archive currently tracked bulk as `release`; entries from `prior` (earlier
    releases, already untracked) are kept so `fetch` still restores them."""
    bulk = [(p, s) for p, s in tracked_files(repo) if is_bulk(p, s, max_bytes)]
    out_dir.mkdir(parents=True, exist_ok=True)
    prior = prior or {"files": [], "assets": []}
    if any(_asset_release(prior, a) == release for a in prior["assets"]):
        raise ValueError(f"release {release} is already in the manifest; use a new release name")
    files, assets = list(prior["files"]), [{**a, "release": _asset_release(prior, a)} for a in prior["assets"]]
    for index, group in enumerate(plan_assets(bulk, max_asset_bytes), 1):
        name = f"{release}-part{index:02d}.tar"
        part = out_dir / name
        with tarfile.open(part, "w") as tar:
            for path, size in group:
                tar.add(repo / path, arcname=path, recursive=False)
                files.append({"path": path, "bytes": size, "sha256": sha256_file(repo / path), "asset": name})
        assets.append({"name": name, "release": release, "bytes": part.stat().st_size, "sha256": sha256_file(part)})
    return {"schema": SCHEMA, "release": release, "assets": assets, "files": files}


def _asset_release(manifest: dict, asset: dict) -> str:
    # The first (2026-10-08) manifest recorded one top-level release.
    return asset.get("release", manifest.get("release"))


def extract_part(manifest: dict, asset: dict, part: Path, dest: Path) -> None:
    """Verify one asset and extract only the manifest's members from it."""
    if sha256_file(part) != asset["sha256"]:
        raise ValueError(f"{part}: sha256 does not match manifest")
    wanted = {f["path"] for f in manifest["files"]}
    # The "data" filter (3.12+, backported to 3.9.17+) also rejects links and
    # absolute names; older interpreters rely on the exact-name membership test.
    safety = {"filter": "data"} if hasattr(tarfile, "data_filter") else {}
    with tarfile.open(part) as tar:
        members = [m for m in tar.getmembers() if m.isfile() and m.name in wanted]
        tar.extractall(dest, members=members, **safety)


def verify_restored(manifest: dict, dest: Path) -> None:
    bad = [f["path"] for f in manifest["files"]
           if not (dest / f["path"]).is_file() or sha256_file(dest / f["path"]) != f["sha256"]]
    if bad:
        raise ValueError(f"{len(bad)} restored files missing or wrong, first: {bad[0]}")


def extract(manifest: dict, asset_dir: Path, dest: Path) -> None:
    for asset in manifest["assets"]:
        extract_part(manifest, asset, asset_dir / asset["name"], dest)
    verify_restored(manifest, dest)


def gh_download(release: str, name: str, into: Path) -> Path:
    subprocess.run(["gh", "release", "download", release, "-p", name, "-D", str(into)], check=True)
    return into / name


def fetch(manifest: dict, dest: Path, asset_dir: Path | None = None, download=gh_download) -> None:
    """Restore every archived file. Parts already in `asset_dir` are reused;
    the rest are downloaded one at a time and deleted after extraction, so
    peak temporary disk is one part (<= 1.5 GB), not the whole archive."""
    with tempfile.TemporaryDirectory() as tmp:
        for asset in manifest["assets"]:
            local = asset_dir / asset["name"] if asset_dir else None
            if local is not None and local.is_file():
                extract_part(manifest, asset, local, dest)
                continue
            part = download(_asset_release(manifest, asset), asset["name"], Path(tmp))
            try:
                extract_part(manifest, asset, part, dest)
            finally:
                part.unlink(missing_ok=True)
    verify_restored(manifest, dest)


def check(repo: Path, max_bytes: int = MAX_TRACKED_BYTES) -> list[str]:
    return [f"{p}: {s} B is bulk; archive it (zapote/tools/evidence_archive.py)"
            for p, s in tracked_files(repo) if is_bulk(p, s, max_bytes)]


def gitignore_block(manifest: dict, base: str = "zapote/") -> str:
    explicit = sorted("/" + f["path"][len(base):] for f in manifest["files"]
                      if f["path"].startswith(base) and not f["path"].endswith(BULK_SUFFIXES))
    # Inside the workspace the suffix rule does not apply, so a nested
    # .gitignore there gets only explicit paths (its globs would re-ignore
    # include_bytes! fixtures that zapote/.gitignore re-includes).
    suffixes = [] if base.startswith(WORKSPACE) else [f"*{s}" for s in BULK_SUFFIXES]
    exempt = [f"!/{WORKSPACE[len(base):]}**/*{s}" for s in BULK_SUFFIXES] if WORKSPACE.startswith(base) else []
    return "\n".join([GITIGNORE_BEGIN, *suffixes, *exempt, *explicit, GITIGNORE_END]) + "\n"


def apply_gitignores(repo: Path, manifest: dict) -> list[Path]:
    """Keep restored bulk ignored: write the block to zapote/.gitignore and to
    every nested .gitignore with a negation, because a deeper file's `!`
    pattern overrides its parents and a later line in the same file wins."""
    nested = [repo / p for p, _ in tracked_files(repo)
              if p.endswith("/.gitignore") and p != "zapote/.gitignore"
              and any(line.startswith("!") for line in (repo / p).read_text().splitlines())]
    written = []
    for ignore in [repo / "zapote/.gitignore", *nested]:
        text = ignore.read_text() if ignore.exists() else ""
        base = str(ignore.parent.relative_to(repo)) + "/"
        block = gitignore_block(manifest, base)
        if GITIGNORE_BEGIN in text and GITIGNORE_END in text:
            start = text.index(GITIGNORE_BEGIN)
            end = text.index(GITIGNORE_END) + len(GITIGNORE_END)
            after = text[end:].lstrip("\n")
            text = text[:start] + block + after
        else:
            text = text.rstrip("\n") + "\n" + block
        ignore.write_text(text)
        written.append(ignore)
    return written


def _repo_root() -> Path:
    return Path(subprocess.run(["git", "rev-parse", "--show-toplevel"], check=True,
                               capture_output=True, text=True).stdout.strip())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_pack = sub.add_parser("pack")
    p_pack.add_argument("--out", type=Path, required=True)
    p_pack.add_argument("--release", required=True)
    p_fetch = sub.add_parser("fetch")
    p_fetch.add_argument("--dest", type=Path)
    p_fetch.add_argument("--asset-dir", type=Path, help="reuse already-downloaded parts from this directory")
    sub.add_parser("check")
    args = parser.parse_args()
    repo = _repo_root()
    if args.cmd == "check":
        problems = check(repo)
        print("\n".join(problems) or "zapote tree budget: ok")
        return 1 if problems else 0
    if args.cmd == "pack":
        existing = repo / MANIFEST
        prior = json.loads(existing.read_text()) if existing.exists() else None
        manifest = pack(repo, args.out, args.release, prior=prior)
        (repo / MANIFEST).write_text(json.dumps(manifest, indent=1) + "\n")
        apply_gitignores(repo, manifest)
        print(f"{len(manifest['files'])} files in {len(manifest['assets'])} assets -> {args.out}")
        return 0
    manifest = json.loads((repo / MANIFEST).read_text())
    fetch(manifest, args.dest or repo, asset_dir=args.asset_dir)
    print(f"restored {len(manifest['files'])} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
