"""Keep bulky retained evidence out of git and restore it on demand.

A tracked file under zapote/ is bulk when it ends in .gz or .npz, or exceeds
5 MB. Bulk lives in GitHub release assets (plain tar parts); the manifest
zapote/evidence-archive.json records each file's path, size, sha256 and the
asset that holds it. `check` is the CI gate that keeps bulk from returning.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

SCHEMA = "zapote.evidence-archive.v1"
MANIFEST = "zapote/evidence-archive.json"
BULK_SUFFIXES = (".gz", ".npz")
MAX_TRACKED_BYTES = 5 * 1024 * 1024
GITIGNORE_BEGIN = "# --- evidence-archive (generated by tools/evidence_archive.py) ---"
GITIGNORE_END = "# --- end evidence-archive ---"


def is_bulk(path: str, size: int, max_bytes: int = MAX_TRACKED_BYTES) -> bool:
    return path.endswith(BULK_SUFFIXES) or size > max_bytes


def tracked_files(repo: Path) -> list[tuple[str, int]]:
    out = subprocess.run(
        ["git", "-C", str(repo), "ls-files", "-z", "--", "zapote"],
        check=True, capture_output=True,
    ).stdout.decode()
    return [(p, (repo / p).stat().st_size) for p in out.split("\0") if p and (repo / p).is_file()]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def plan_assets(entries, max_asset_bytes: int) -> list[list[tuple[str, int]]]:
    groups: list[list[tuple[str, int]]] = []
    current: list[tuple[str, int]] = []
    used = 0
    for path, size in sorted(entries):
        if size > max_asset_bytes:
            raise ValueError(f"{path} ({size} B) does not fit in one asset")
        if current and used + size > max_asset_bytes:
            groups.append(current)
            current, used = [], 0
        current.append((path, size))
        used += size
    if current:
        groups.append(current)
    return groups


def pack(repo: Path, out_dir: Path, release: str, max_asset_bytes: int = 1_500_000_000,
         max_bytes: int = MAX_TRACKED_BYTES) -> dict:
    bulk = [(p, s) for p, s in tracked_files(repo) if is_bulk(p, s, max_bytes)]
    out_dir.mkdir(parents=True, exist_ok=True)
    files, assets = [], []
    for index, group in enumerate(plan_assets(bulk, max_asset_bytes), 1):
        name = f"zapote-evidence-part{index:02d}.tar"
        part = out_dir / name
        with tarfile.open(part, "w") as tar:
            for path, size in group:
                tar.add(repo / path, arcname=path, recursive=False)
                files.append({"path": path, "bytes": size, "sha256": sha256_file(repo / path), "asset": name})
        assets.append({"name": name, "bytes": part.stat().st_size, "sha256": sha256_file(part)})
    return {"schema": SCHEMA, "release": release, "assets": assets, "files": files}


def extract(manifest: dict, asset_dir: Path, dest: Path) -> None:
    wanted = {f["path"]: f for f in manifest["files"]}
    for asset in manifest["assets"]:
        part = asset_dir / asset["name"]
        if sha256_file(part) != asset["sha256"]:
            raise ValueError(f"{part}: sha256 does not match manifest")
        with tarfile.open(part) as tar:
            members = [m for m in tar.getmembers() if m.isfile() and m.name in wanted]
            tar.extractall(dest, members=members)
    bad = [p for p, f in wanted.items()
           if not (dest / p).is_file() or sha256_file(dest / p) != f["sha256"]]
    if bad:
        raise ValueError(f"{len(bad)} restored files missing or wrong, first: {bad[0]}")


def check(repo: Path, max_bytes: int = MAX_TRACKED_BYTES) -> list[str]:
    return [f"{p}: {s} B is bulk; archive it (zapote/tools/evidence_archive.py)"
            for p, s in tracked_files(repo) if is_bulk(p, s, max_bytes)]


def gitignore_block(manifest: dict) -> str:
    explicit = sorted("/" + f["path"].removeprefix("zapote/") for f in manifest["files"]
                      if not f["path"].endswith(BULK_SUFFIXES))
    return "\n".join([GITIGNORE_BEGIN, *(f"*{s}" for s in BULK_SUFFIXES), *explicit, GITIGNORE_END]) + "\n"


def _repo_root() -> Path:
    return Path(subprocess.run(["git", "rev-parse", "--show-toplevel"], check=True,
                               capture_output=True, text=True).stdout.strip())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_pack = sub.add_parser("pack")
    p_pack.add_argument("--out", type=Path, required=True)
    p_pack.add_argument("--release", required=True)
    p_fetch = sub.add_parser("fetch")
    p_fetch.add_argument("--dest", type=Path)
    sub.add_parser("check")
    args = parser.parse_args()
    repo = _repo_root()
    if args.cmd == "check":
        problems = check(repo)
        print("\n".join(problems) or "zapote tree budget: ok")
        return 1 if problems else 0
    if args.cmd == "pack":
        manifest = pack(repo, args.out, args.release)
        (repo / MANIFEST).write_text(json.dumps(manifest, indent=1) + "\n")
        ignore = repo / "zapote/.gitignore"
        text = ignore.read_text()
        if GITIGNORE_BEGIN in text:
            text = text[: text.index(GITIGNORE_BEGIN)]
        ignore.write_text(text.rstrip("\n") + "\n" + gitignore_block(manifest))
        print(f"{len(manifest['files'])} files in {len(manifest['assets'])} assets -> {args.out}")
        return 0
    manifest = json.loads((repo / MANIFEST).read_text())
    with tempfile.TemporaryDirectory() as tmp:
        for asset in manifest["assets"]:
            subprocess.run(["gh", "release", "download", manifest["release"], "-p", asset["name"], "-D", tmp],
                           check=True)
        extract(manifest, Path(tmp), args.dest or repo)
    print(f"restored {len(manifest['files'])} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
