"""Retired oracle-comparison differential for the kicad_exporter geometry
kernels (snap_to_nearest_pad, generate_connector_segments).

The pinned oracle ``tests/io/_kicad_exporter_py_oracle.py`` was retired by
FREEZE on 2026-08-21 (batch 3): its golden vectors are baked into
``kicad_exporter_geometry.rs``'s own ``frozen_kicad_geom_tests`` module
(``frozen_snap_matches_golden_corpus`` /
``frozen_conn_matches_golden_corpus`` /
``frozen_kicad_geom_corpus_is_non_vacuous``), generated by
``scripts/oracle_freeze_specs/kicad_exporter_geometry.py`` (81 cases, 12
non-vacuity checks).

The oracle-comparison tests this file used to carry are fully superseded by
that frozen corpus. What remains below is a set of wiring checks.
"""

from __future__ import annotations

import temper_design_bundle_python as _tdb

_GEOM = _tdb.kicad_exporter_geometry


def test_snap_to_nearest_pad_callable_via_pyo3():
    got = _GEOM.snap_to_nearest_pad_py(0.0, 0.0, [(0.05, 0.05)], 0.15)
    assert got == (0.05, 0.05)


def test_generate_connector_segments_callable_via_pyo3():
    segs = [("GND", (0.0, 0.0), (1.0, 0.0), 0.25, "F.Cu")]
    pads = [("GND", [(2.5, 0.0)])]
    got = _GEOM.generate_connector_segments_py(segs, pads, 2.0)
    assert len(got) == 1
