"""Shipped-module delegation proof for the Rust write-board
geometry/formatting kernels (``temper_design_bundle_python.write_board_geometry``).

Wave 4, Phase 3 (formats/IO) -- migrates the two numeric kernels embedded in
``temper_placer/io/_write_board.py``: ``_reorient_pads``'s per-pad angle
update and ``state_to_placements``'s original-angle offset preservation.

The oracle-comparison tests that used to live here were retired by FREEZE on
2026-08-20 (batch 2): the pinned oracle
``tests/io/_write_board_py_oracle.py`` was deleted and its golden vectors
were baked into ``write_board_geometry.rs``'s own ``#[cfg(test)]`` corpus
(``frozen_write_board_geometry_matches_golden_corpus`` /
``frozen_write_board_geometry_corpus_is_non_vacuous``), generated by
``scripts/oracle_freeze_specs/write_board_geometry.py``. The two tests that
remain below are NOT part of the oracle differential (they assert production
wiring -- that the SHIPPED module actually calls the Rust kernel, Stage 7
concern) and are intentionally kept.
"""

from __future__ import annotations

from types import SimpleNamespace

import numpy as np
import pytest
import temper_design_bundle_python as _tdb

from temper_placer.core.state import PlacementState
from temper_placer.io import _write_board as shipped

_GEOM = _tdb.write_board_geometry


def test_write_placements_delegates_to_rust_update(tmp_path):
    """The SHIPPED `write_placements_to_pcb` must reach the Rust
    `update_footprint_positions_py` kernel, not just have a differential
    proving the kernel is correct in isolation. Monkeypatch the Rust
    symbol to raise; call the shipped entry point; the raise propagates.
    """
    from pathlib import Path

    sentinel = RuntimeError("REACHED_RUST_UPDATE_FP")

    def boom(*_a, **_k):
        raise sentinel

    original = _tdb.parse_engine.update_footprint_positions_py
    _tdb.parse_engine.update_footprint_positions_py = boom
    try:
        template = tmp_path / "template.kicad_pcb"
        template.write_text(
            '(kicad_pcb (version 20240108) (generator pcbnew)\n'
            '  (footprint "Lib:R1" (layer "F.Cu")\n'
            '    (at 50.0 60.0 90)\n'
            '    (property "Reference" "R1")\n'
            '    (pad "1" thru_hole circle (at 0 0 0) (size 1.5 1.5) (drill 0.8))\n'
            '  )\n'
            ')\n'
        )
        out = tmp_path / "out.kicad_pcb"
        with pytest.raises(RuntimeError, match="REACHED_RUST_UPDATE_FP"):
            shipped.write_placements_to_pcb(
                template, out,
                {"R1": shipped.PlacementUpdate(ref="R1", x=100.0, y=200.0, rotation=180.0)},
            )
    finally:
        _tdb.parse_engine.update_footprint_positions_py = original


def test_state_to_placements_delegates_to_rust():
    """The SHIPPED `state_to_placements` must reach the Rust
    `preserve_rotation_offset_py` kernel when an original (non-90°) angle
    is supplied, not just have a differential proving the kernel is
    correct in isolation."""
    sentinel = RuntimeError("REACHED_RUST_PRESERVE_OFFSET")

    def boom(*_a, **_k):
        raise sentinel

    state = PlacementState(
        positions=np.array([[10.0, 20.0]]),
        rotation_logits=np.array([[1.0, 0.0, 0.0, 0.0]]),
    )
    original_angles = {"U1": 45.0}

    original = _GEOM.preserve_rotation_offset_py
    _GEOM.preserve_rotation_offset_py = boom
    try:
        with pytest.raises(RuntimeError, match="REACHED_RUST_PRESERVE_OFFSET"):
            shipped.state_to_placements(state, ["U1"], original_angles=original_angles)
    finally:
        _GEOM.preserve_rotation_offset_py = original
