"""CP-SAT constraint encoder for PCL constraint types.

Public API surface for the CP-SAT placement solver module.
"""

from temper_placer.placer.cp_sat.audit import (
    AuditReport,
    AuditViolation,
    Placement,
    PlacementAuditor,
)
from temper_placer.placer.cp_sat.constraint_family_campaign import (
    ConstraintFamilyCampaignResult,
    ConstraintFamilyCampaignStatus,
    ConstraintFamilyFeasibilityCampaignStatus,
    ConstraintFamilyProbeResult,
    ConstraintFamilyProbeStatus,
    default_constraint_family_probes,
    run_constraint_family_campaign,
    run_constraint_family_feasibility_campaign,
)
from temper_placer.placer.cp_sat.constraint_family_campaign import (
    ConstraintFamilyProbe as ConstraintFamilyProbeSpec,
)
from temper_placer.placer.cp_sat.constraint_family_frontier import (
    ConstraintFamilyFrontier,
    ConstraintFamilyProbeKey,
    ConstraintFamilyProbeRecord,
    ConstraintFamilySearchFrontier,
    FamilyProbeKey,
    FamilyProbeRecord,
    FamilySearchFrontier,
    accepted_placement_covers,
    constraint_family_probe_key,
)
from temper_placer.placer.cp_sat.constraint_family_probe_planner import (
    ConstraintFamilyPlannerState,
    ConstraintFamilyProbe,
    ConstraintFamilyProbeKind,
    constraint_family_planner_state,
    plan_constraint_family_feasibility,
    plan_constraint_family_probes,
    plan_family_feasibility_probes,
)
from temper_placer.placer.cp_sat.constraint_family_real_board import (
    run_constraint_family_real_board_campaign,
    run_real_board_constraint_family_campaign,
    run_real_board_family_campaign,
)
from temper_placer.placer.cp_sat.constraint_family_schema import (
    ConstraintFamilyDefinition,
    ConstraintFamilySourceKind,
    constraint_family_definition,
    production_constraint_family_definitions,
    production_family_kwargs,
    validate_constraint_family_kwargs,
)
from temper_placer.placer.cp_sat.constraint_restoration_campaign import (
    BoundedDisplacementRadiusResult,
    BoundedDisplacementSweepResult,
    BoundedDisplacementSweepStatus,
    RestorationCampaignResult,
    RestorationCampaignStatus,
    RestorationLimits,
    RestorationStage,
    RestorationStageResult,
    RestorationStageStatus,
    SelectiveDisplacementCampaignResult,
    SelectiveDisplacementCampaignStatus,
    SelectiveDisplacementRoundResult,
    bounded_displacement_restoration_stages,
    default_restoration_stages,
    distance_tier_restoration_stages,
    neighborhood_batched_creepage_constraints,
    run_bounded_displacement_radius_sweep,
    run_bounded_displacement_restoration_campaign,
    run_constraint_restoration_campaign,
    run_selective_displacement_campaign,
)
from temper_placer.placer.cp_sat.creepage_lower_bounds import (
    CreepageLowerBoundReport,
    ThresholdCliqueBound,
    analyze_creepage_lower_bounds,
)
from temper_placer.placer.cp_sat.collision_cut_adapter import (
    RUST_MODEL_UNITS_PER_MM,
    apply_collision_cut,
    apply_collision_cuts,
)
from temper_placer.placer.cp_sat.creepage_territory_planner import (
    plan_creepage_displacement_groups,
    plan_creepage_territories,
)
from temper_placer.placer.cp_sat.displacement_deletion_campaign import (
    DisplacementDeletionCampaignResult,
    DisplacementDeletionCampaignStatus,
    DisplacementDeletionTestResult,
    run_deletion_testing_campaign,
    run_displacement_deletion_campaign,
)
from temper_placer.placer.cp_sat.displacement_deletion_frontier import (
    DeletionProbeKey,
    DeletionProbeRecord,
    DeletionSearchFrontier,
    DeletionSearchFrontierRecord,
    DeletionSearchKey,
    available_board_hash,
    canonical_json,
    deletion_probe_key,
)
from temper_placer.placer.cp_sat.encoder import (
    UNSUPPORTED_TYPES,
    CpSatPlacementResult,
    EncoderContext,
    encode_constraints,
    solve_placement,
)
from temper_placer.placer.cp_sat.envelope_preparation import (
    PreparedEnvelopeInputs,
    prepare_envelope_inputs,
)
from temper_placer.placer.cp_sat.envelope_solver import (
    EnvelopeBounds,
    EnvelopeSolveResult,
    EnvelopeSolveStatus,
    EnvelopeStatus,
    PairRequirement,
    PartitionPlan,
    solve_envelopes,
)
from temper_placer.placer.cp_sat.feedback import ConstraintDelta, FeedbackClassifier
from temper_placer.placer.cp_sat.gate import AcceptanceGate
from temper_placer.placer.cp_sat.hierarchical_displacement_campaign import (
    CoarseGroupDisplacementCampaignResult,
    CoarseGroupDisplacementRoundResult,
    run_coarse_group_displacement_core_experiment,
)
from temper_placer.placer.cp_sat.local_subenvelope_solver import (
    ComponentPairRequirement,
    ComponentSpec,
    LocalComponentBounds,
    LocalSubEnvelopeSolveResult,
    LocalSubEnvelopeSolveStatus,
    LocalSubEnvelopeStatus,
    pack_local_sub_envelope,
    solve_local_envelope,
    solve_local_sub_envelope,
)
from temper_placer.placer.cp_sat.loop import LoopResult, PlaceRouteLoop
from temper_placer.placer.cp_sat.model import (
    ComponentVars,
    CpSatModel,
    CpSolverSolution,
    SolveStatus,
)
from temper_placer.placer.cp_sat.production_constraint_family_inputs import (
    ProductionConstraintFamilyInputs,
    ProductionCreepageVerification,
    build_production_creepage_verifier,
    make_production_constraint_family_verifier,
    prepare_production_constraint_family_inputs,
    production_constraint_family_cache_projections,
    run_production_board_constraint_family_campaign,
    run_production_constraint_family_campaign,
    run_production_constraint_family_real_board_campaign,
)
from temper_placer.placer.cp_sat.production_stripped_instance import (
    ProductionStrippedDiagnostics,
    ProductionStrippedInstance,
    ProductionStrippedProbeReport,
    prepare_production_stripped_instance,
    run_production_stripped_probe,
)
from temper_placer.placer.cp_sat.stripped_creepage_solver import (
    StrippedCreepageSolveResult,
    StrippedCreepageSolveStatus,
    solve_stripped_creepage,
)
from temper_placer.placer.cp_sat.stripped_warm_start import (
    StrippedWarmStartResult,
    solve_production_stripped_instance_warm_start,
    solve_stripped_creepage_warm_start,
)

__all__ = [
    "AcceptanceGate",
    "AuditReport",
    "AuditViolation",
    "ComponentVars",
    "ConstraintDelta",
    "CreepageLowerBoundReport",
    "plan_creepage_displacement_groups",
    "plan_creepage_territories",
    "ComponentPairRequirement",
    "CoarseGroupDisplacementCampaignResult",
    "CoarseGroupDisplacementRoundResult",
    "DisplacementDeletionCampaignResult",
    "DisplacementDeletionCampaignStatus",
    "DisplacementDeletionTestResult",
    "DeletionProbeKey",
    "DeletionProbeRecord",
    "DeletionSearchKey",
    "DeletionSearchFrontier",
    "DeletionSearchFrontierRecord",
    "available_board_hash",
    "canonical_json",
    "deletion_probe_key",
    "ConstraintFamilyFrontier",
    "ConstraintFamilyProbeKey",
    "ConstraintFamilyProbeRecord",
    "ConstraintFamilySearchFrontier",
    "FamilyProbeKey",
    "FamilyProbeRecord",
    "FamilySearchFrontier",
    "accepted_placement_covers",
    "constraint_family_probe_key",
    "run_constraint_family_real_board_campaign",
    "run_real_board_constraint_family_campaign",
    "run_real_board_family_campaign",
    "ComponentPairRequirement",
    "ComponentSpec",
    "EnvelopeBounds",
    "EnvelopeSolveResult",
    "EnvelopeSolveStatus",
    "EnvelopeStatus",
    "PreparedEnvelopeInputs",
    "CpSatPlacementResult",
    "CpSatModel",
    "CpSolverSolution",
    "EncoderContext",
    "FeedbackClassifier",
    "LoopResult",
    "LocalComponentBounds",
    "LocalSubEnvelopeSolveResult",
    "LocalSubEnvelopeSolveStatus",
    "LocalSubEnvelopeStatus",
    "StrippedCreepageSolveResult",
    "StrippedCreepageSolveStatus",
    "ProductionStrippedDiagnostics",
    "ProductionStrippedInstance",
    "ProductionStrippedProbeReport",
    "ProductionCreepageVerification",
    "RestorationCampaignResult",
    "RestorationCampaignStatus",
    "RestorationLimits",
    "RestorationStage",
    "RestorationStageResult",
    "RestorationStageStatus",
    "ConstraintFamilyPlannerState",
    "ConstraintFamilyProbe",
    "ConstraintFamilyProbeKind",
    "ConstraintFamilyCampaignResult",
    "ConstraintFamilyCampaignStatus",
    "ConstraintFamilyFeasibilityCampaignStatus",
    "ConstraintFamilyProbeSpec",
    "ConstraintFamilyProbeResult",
    "ConstraintFamilyProbeStatus",
    "constraint_family_planner_state",
    "default_constraint_family_probes",
    "plan_constraint_family_feasibility",
    "plan_constraint_family_probes",
    "plan_family_feasibility_probes",
    "ConstraintFamilyDefinition",
    "ConstraintFamilySourceKind",
    "constraint_family_definition",
    "production_constraint_family_definitions",
    "production_family_kwargs",
    "validate_constraint_family_kwargs",
    "run_constraint_family_campaign",
    "run_constraint_family_feasibility_campaign",
    "ProductionConstraintFamilyInputs",
    "build_production_creepage_verifier",
    "make_production_constraint_family_verifier",
    "prepare_production_constraint_family_inputs",
    "production_constraint_family_cache_projections",
    "run_production_constraint_family_campaign",
    "run_production_constraint_family_real_board_campaign",
    "run_production_board_constraint_family_campaign",
    "SelectiveDisplacementCampaignResult",
    "SelectiveDisplacementCampaignStatus",
    "SelectiveDisplacementRoundResult",
    "BoundedDisplacementRadiusResult",
    "BoundedDisplacementSweepResult",
    "BoundedDisplacementSweepStatus",
    "StrippedWarmStartResult",
    "ThresholdCliqueBound",
    "PlaceRouteLoop",
    "Placement",
    "PlacementAuditor",
    "PairRequirement",
    "PartitionPlan",
    "SolveStatus",
    "solve_placement",
    "UNSUPPORTED_TYPES",
    "encode_constraints",
    "solve_envelopes",
    "pack_local_sub_envelope",
    "solve_local_envelope",
    "solve_local_sub_envelope",
    "solve_stripped_creepage",
    "prepare_production_stripped_instance",
    "run_production_stripped_probe",
    "default_restoration_stages",
    "distance_tier_restoration_stages",
    "bounded_displacement_restoration_stages",
    "neighborhood_batched_creepage_constraints",
    "run_bounded_displacement_restoration_campaign",
    "run_bounded_displacement_radius_sweep",
    "run_constraint_restoration_campaign",
    "run_coarse_group_displacement_core_experiment",
    "run_displacement_deletion_campaign",
    "run_deletion_testing_campaign",
    "run_selective_displacement_campaign",
    "solve_production_stripped_instance_warm_start",
    "solve_stripped_creepage_warm_start",
    "analyze_creepage_lower_bounds",
    "prepare_envelope_inputs",
]
