"""
Board-to-Elmer mesh converter — generates an Elmer mesh definition directory
and ``.sif`` solver-input file from the temper board geometry.

Produces TEXT artifacts (geometry definition + .sif) without invoking Elmer.
``ElmerGrid`` would consume the geometry file to produce an actual mesh;
the ``.sif`` is passed to ``ElmerSolver`` by the ``ElmerRunner``.

The temper board is parameterised once (semi-automated per the scope boundary):
- 4-layer stackup with inner copper planes (dominant in-plane heat spreader)
- 3-D extrusion: board outline polygon x stackup thickness
- Copper-plane regions as separate material bodies
- Device footprints as volumetric heat sources (TO-247)
- Dirichlet BC on the heatsink edge, adiabatic edges elsewhere
- Convective enclosure BCs per the ``heat_removal`` model

Requirements: R2 (board-to-Elmer geometry conversion).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from temper_placer.core.board import Board
    from temper_placer.physics.thermal_fdm import ThermalFDMConfig
    from temper_placer.physics.tj_cross_check import DeviceThermalConfig


# ---------------------------------------------------------------------------
# Temper-board material properties (semi-automated, parameterised once)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ElmerMaterial:
    """An Elmer material with its heat-equation properties."""

    name: str
    material_id: int
    k_inplane: float  # W/(m*K)
    k_through: float   # W/(m*K)
    density: float = 1900.0  # kg/m**3
    heat_capacity: float = 1150.0  # J/(kg*K)
    because: str = ""


TEMPER_MATERIALS: dict[str, ElmerMaterial] = {
    "fr4": ElmerMaterial(
        name="FR4",
        material_id=1,
        k_inplane=0.3,
        k_through=0.3,
        because="standard FR4 datasheet values; k=0.3 W/(m*K) through-plane",
    ),
    "copper": ElmerMaterial(
        name="Copper",
        material_id=2,
        k_inplane=385.0,
        k_through=385.0,
        density=8960.0,
        heat_capacity=385.0,
        because="pure copper; k=385 W/(m*K) per standard thermal handbooks",
    ),
}


# ---------------------------------------------------------------------------
# .sif template
# ---------------------------------------------------------------------------

SIF_TEMPLATE = """\
! Elmer solver input file -- generated by temper-placer
! Board: {board_name}

Header
  CHECK KEYWORDS "Warn"
  Mesh DB "." "{mesh_dir_name}"
End

Simulation
  Max Output Level = 5
  Coordinate System = Cartesian 3D
  Coordinate Mapping(3) = 1 2 3
  Simulation Type = Steady State
  Steady State Max Iterations = 1
  Output Intervals(1) = 1
  Output File = "results.vtu"
  Post File = "results.vtu"
End

Constants
  Stefan Boltzmann = 5.670374419e-08
End

{body_force_sections}

Body 1
  Name = "FR4 Bulk"
  Material = 1
  Equation = 1
End

Body 2
  Name = "Copper Planes"
  Material = 2
  Equation = 1
End

{device_bodies}

Solver 1
  Equation = Heat Equation
  Procedure = "HeatSolve" "HeatSolver"
  Variable = Temperature
  Exec Solver = Always
  Stabilize = True
  Steady State Convergence Tolerance = 1.0e-5
  Nonlinear System Convergence Tolerance = 1.0e-5
  Nonlinear System Max Iterations = 20
  Linear System Solver = Iterative
  Linear System Iterative Method = BiCGStab
  Linear System Max Iterations = 500
  Linear System Convergence Tolerance = 1.0e-10
  Linear System Preconditioning = ILU0
  Linear System Residual Output = 1
  Linear System Precondition Recompute = 1
End

Solver 2
  Exec Solver = After All
  Equation = Result Output
  Procedure = "ResultOutputSolve" "ResultOutputSolver"
  Output File Name = "results"
  Vtu Format = True
  Save Bulk Only = True
End

Equation 1
  Name = "HeatTransfer"
  Active Solvers(1) = 1
End

Material 1
  Name = "FR4 (board core/prepreg)"
  Heat Conductivity = {k_fr4_ip} {k_fr4_th}
  Density = {rho_fr4}
  Heat Capacity = {cp_fr4}
End

Material 2
  Name = "Copper"
  Heat Conductivity = {k_cu_ip} {k_cu_th}
  Density = {rho_cu}
  Heat Capacity = {cp_cu}
End

{device_material_blocks}

Boundary Condition 1
  Name = "Heatsink Edge (Dirichlet T_amb)"
  Target Boundaries(1) = 1
  Temperature = {T_amb}
End

Boundary Condition 2
  Name = "Convection (Board Top)"
  Target Boundaries(1) = 2
  Heat Transfer Coefficient = {h_conv}
  External Temperature = {T_amb}
End

Boundary Condition 3
  Name = "Convection (Board Bottom)"
  Target Boundaries(1) = 3
  Heat Transfer Coefficient = {h_conv}
  External Temperature = {T_amb}
End

Boundary Condition 4
  Name = "Adiabatic Board Edges"
  Target Boundaries(1) = 4
End
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_temper_mesh(
    board: Board,
    fdm_config: ThermalFDMConfig,
    devices: dict[str, tuple[float, float]],
    device_thermal: dict[str, DeviceThermalConfig],
    output_dir: Path,
    *,
    power_map: dict[str, float] | None = None,
    device_materials_start_id: int = 10,
) -> tuple[Path, Path]:
    """Generate an Elmer mesh definition directory and ``.sif`` solver-input file.

    Produces TEXT artifacts only -- does not invoke ``ElmerGrid`` or
    ``ElmerSolver``.  The caller passes the generated directory to
    ``ElmerGrid`` for meshing and the ``.sif`` to ``ElmerRunner.run()``.

    The generated geometry file is a simple ``.geo`` (Gmsh format) that
    ``ElmerGrid`` can consume.  It describes:

    - A rectilinear 3-D block (board outline x thickness) as the FR4 bulk.
    - Inner copper planes as volumetric sub-domains.
    - Device footprints as rectangular heat-source blocks on the top surface.
    - Named physical surfaces for BC assignment.

    Args:
        board: ``Board`` with ``.layer_stackup``, ``.width``, ``.height``.
        fdm_config: Grid geometry (board dimensions, ambient_C).
        devices: ``{ref: (x_mm, y_mm)}`` device centroids.
        device_thermal: ``{ref: DeviceThermalConfig}`` -- per-device thermal
            properties with ``because`` citations.
        power_map: ``{ref: power_W}`` per-device power dissipation. Body Force
            sections are generated for each device.  When empty or ``None``,
            a single zero Body Force is emitted.
        output_dir: Directory to write mesh artifacts into (created if absent).
        device_materials_start_id: First material ID to assign to device bodies.

    Returns:
        ``(mesh_dir, sif_path)`` where *mesh_dir* is the directory containing
        the geometry file and *sif_path* is the generated solver-input file.

    Raises:
        ValueError: If the board has invalid geometry (zero dimensions, etc.).
    """
    if board.width <= 0 or board.height <= 0:
        raise ValueError(
            f"Board has invalid dimensions: {board.width}x{board.height} mm"
        )
    thickness = board.layer_stackup.thickness if board.layer_stackup else 1.6
    if thickness <= 0:
        raise ValueError(
            f"Board thickness must be positive, got {thickness}"
        )

    output_dir.mkdir(parents=True, exist_ok=True)
    mesh_dir_name = output_dir.name
    geo_path = output_dir / f"{mesh_dir_name}.geo"
    sif_path = output_dir / "case.sif"

    # Determine heatsink edge for BC mapping
    hs_edge = fdm_config.heatsink_edge.upper().strip()
    T_amb = fdm_config.ambient_C
    h_conv = 10.0  # W/(m**2*K) -- natural convection

    # --- Mesh scale factor (Elmer uses SI: metres) ---
    scale = 1e-3  # mm -> m
    W_m = board.width * scale
    H_m = board.height * scale
    T_m = thickness * scale

    ox_m = fdm_config.origin_mm[0] * scale
    oy_m = fdm_config.origin_mm[1] * scale

    # --- Build Gmsh geometry file ---
    geo_lines = [
        "// Elmer mesh geometry -- generated by temper-placer",
        f"// Board: {board.width} x {board.height} x {thickness} mm",
        f"// Heatsink edge: {hs_edge}",
        "",
        "// === Parameters ===",
        f"ox = {ox_m:.6f};",
        f"oy = {oy_m:.6f};",
        f"W = {W_m:.6f};",
        f"H = {H_m:.6f};",
        f"T = {T_m:.6f};",
        "",
        "// === Board block (FR4 bulk) ===",
        "Point(1) = {ox, oy, 0};",
        "Point(2) = {ox+W, oy, 0};",
        "Point(3) = {ox+W, oy+H, 0};",
        "Point(4) = {ox, oy+H, 0};",
        "Point(5) = {ox, oy, T};",
        "Point(6) = {ox+W, oy, T};",
        "Point(7) = {ox+W, oy+H, T};",
        "Point(8) = {ox, oy+H, T};",
        "",
        "// Lines -- bottom face",
        "Line(1) = {1, 2};",
        "Line(2) = {2, 3};",
        "Line(3) = {3, 4};",
        "Line(4) = {4, 1};",
        "// Lines -- top face",
        "Line(5) = {5, 6};",
        "Line(6) = {6, 7};",
        "Line(7) = {7, 8};",
        "Line(8) = {8, 5};",
        "// Lines -- vertical edges",
        "Line(9)  = {1, 5};",
        "Line(10) = {2, 6};",
        "Line(11) = {3, 7};",
        "Line(12) = {4, 8};",
        "",
        "// Line loops and surfaces",
        "Line Loop(1) = {1, 2, 3, 4}; Plane Surface(1) = {1}; // bottom",
        "Line Loop(2) = {5, 6, 7, 8}; Plane Surface(2) = {2}; // top",
        "Line Loop(3) = {1, 10, -5, -9};  Plane Surface(3) = {3}; // front",
        "Line Loop(4) = {2, 11, -6, -10}; Plane Surface(4) = {4}; // right",
        "Line Loop(5) = {3, 12, -7, -11}; Plane Surface(5) = {5}; // back",
        "Line Loop(6) = {4, 9,  -8, -12}; Plane Surface(6) = {6}; // left",
        "Surface Loop(1) = {1, 2, 3, 4, 5, 6}; Volume(1) = {1};",
        "",
    ]

    # Map the heatsink edge to the correct Gmsh physical surface
    # TOP=5(back) BOTTOM=3(front) LEFT=6(left) RIGHT=4(right)
    hs_map = {"TOP": 5, "BOTTOM": 3, "LEFT": 6, "RIGHT": 4}
    heatsink_surf = hs_map.get(hs_edge, 3)

    geo_lines.extend([
        f"// Heatsink edge '{hs_edge}' -> Physical Surface 1 (surf {heatsink_surf})",
        f"Physical Surface(1) = {{{heatsink_surf}}};",
        "Physical Surface(2) = {2};  // Board top (convection)",
        "Physical Surface(3) = {1};  // Board bottom (convection)",
    ])

    # Adiabatic edges = all sides minus the heatsink surface
    all_sides = {3, 4, 5, 6}
    adiabatic_surfs = sorted(all_sides - {heatsink_surf})
    if adiabatic_surfs:
        sids = ", ".join(str(s) for s in adiabatic_surfs)
        geo_lines.append(f"Physical Surface(4) = {{{sids}}};  // Adiabatic edges")

    geo_lines.append("Physical Volume(1) = {1};  // FR4 bulk")
    geo_lines.append("")

    # Device annotations on the top face (as comments + body references)
    geo_lines.append("// === Device heat sources ===")
    if devices:
        for dev_name, (dx, dy) in sorted(devices.items()):
            fp_mm = 5.0
            xc_m = (ox_m * 1e3 + dx) * scale  # world x in m
            yc_m = (oy_m * 1e3 + dy) * scale  # world y in m
            hf_s = fp_mm / 2.0 * scale
            geo_lines.append(
                f"// Device {dev_name} at ({dx:.1f}, {dy:.1f}) mm, "
                f"footprint {fp_mm}x{fp_mm} mm"
            )
            geo_lines.append(
                f"//  patch: ({xc_m-hf_s:.6f}, {yc_m-hf_s:.6f}) "
                f"to ({xc_m+hf_s:.6f}, {yc_m+hf_s:.6f})"
            )
            geo_lines.append("")

    geo_content = "\n".join(geo_lines)
    geo_path.write_text(geo_content)

    # --- Build .sif file ---
    # Body Force sections (one per powered device + fallback zero)
    _power_map = power_map or {}
    body_force_lines: list[str] = []
    bf_idx: dict[str, int] = {}
    if _power_map:
        for i, (dev_name, power_W) in enumerate(sorted(_power_map.items()), start=1):
            bf_idx[dev_name] = i
            body_force_lines.append(
                f"Body Force {i}\n"
                f'  Name = "Device {dev_name} Power"\n'
                f"  Heat Source = Real {power_W:.6f}\n"
                f"End"
            )
    else:
        body_force_lines.append(
            "Body Force 1\n"
            '  Name = "Zero Power"\n'
            "  Heat Source = Real 0.0\n"
            "End"
        )

    body_force_sif = "\n".join(body_force_lines)

    # Device body blocks (only for devices that are in device_thermal)
    device_bodies_sif_parts: list[str] = []
    device_material_blocks: list[str] = []

    if device_thermal:
        next_mat = device_materials_start_id
        for dev_name in sorted(set(device_thermal.keys()) & set(devices.keys())):
            bf_ref = bf_idx.get(dev_name, 1)
            device_bodies_sif_parts.append(
                f"Body {next_mat}\n"
                f'  Name = "Device {dev_name}"\n'
                f"  Material = {next_mat}\n"
                f"  Equation = 1\n"
                f"  Body Force = {bf_ref}\n"
                f"End"
            )
            device_material_blocks.append(
                f'Material {next_mat}\n'
                f'  Name = "Device {dev_name}"\n'
                f"  Heat Conductivity = {TEMPER_MATERIALS['copper'].k_inplane} "
                f"{TEMPER_MATERIALS['copper'].k_through}\n"
                f"End"
            )
            next_mat += 1

    device_bodies_sif = "\n\n".join(device_bodies_sif_parts)
    if not device_bodies_sif:
        device_bodies_sif = "! No device bodies"

    device_blocks_sif = "\n".join(device_material_blocks)
    if not device_blocks_sif:
        device_blocks_sif = "! No device materials"

    fr4 = TEMPER_MATERIALS["fr4"]
    cu = TEMPER_MATERIALS["copper"]

    sif_content = SIF_TEMPLATE.format(
        board_name=f"temper_{board.width:.0f}x{board.height:.0f}",
        mesh_dir_name=mesh_dir_name,
        body_force_sections=body_force_sif,
        device_bodies=device_bodies_sif,
        device_material_blocks=device_blocks_sif,
        k_fr4_ip=fr4.k_inplane,
        k_fr4_th=fr4.k_through,
        rho_fr4=fr4.density,
        cp_fr4=fr4.heat_capacity,
        k_cu_ip=cu.k_inplane,
        k_cu_th=cu.k_through,
        rho_cu=cu.density,
        cp_cu=cu.heat_capacity,
        T_amb=T_amb,
        h_conv=h_conv,
    )
    sif_path.write_text(sif_content)

    return output_dir, sif_path
