"""Stub for the ``temper_orchestration`` extension (temper-orchestration
crate, Wave-4 Phase-5 cli/adapters/temper-workflow slice).

Mirrors the temper_design_bundle_python stub convention: the pyo3 extension
is imported by the delegation shims (``temper_placer.cli.timing``,
``temper_placer.cli.trace_commands``,
``temper_workflow.routing.route_and_measure``); the mypy gate resolves this
stub through ``mypy_path = "packages/temper-placer/stubs"``.

The crate grew from that first Wave-4 Phase-5 slice into the Rust
Orchestration Engine (plan 2026-08-09-001, U0 through E6/tail-tooling,
"Append-only per the U4 dispatch") across many incremental PRs, each landing
new ``#[pyclass]``/``#[pyfunction]`` entries in ``lib.rs``'s ``#[pymodule]``
block without a matching stub update -- the entries below (2026-08-12,
type-check gate paydown) close that gap by mirroring ``lib.rs`` exactly.
Signatures are permissive (``*args``/``**kwargs`` -> ``Any``) rather than
precisely typed, matching this file's own pre-existing convention for the
feasibility kernels below and ``decision_contracts.pyi``'s convention for
bare pyclasses: the goal is closing "Module has no attribute" / "not valid
as a type" mypy errors from a stub that fell behind an append-only Rust
surface, not re-deriving each stage's exact call signature. Keep in sync
with ``packages/temper-orchestration/src/lib.rs``'s ``#[pymodule]`` block.
"""

from __future__ import annotations

from typing import Any


def compare_stage(
    baseline_ms: float, current_ms: float, margin: float, floor_ms: float
) -> tuple[float, float, float, float, bool]:
    """The timing_check stage-comparison block: (delta_ms, delta_pct,
    effective_baseline, threshold_ms, passed)."""


def p95(values: list[float]) -> float:
    """round(sorted(values)[int(len(values) * 0.95)], 3) — raises
    IndexError on an empty list."""


def filter_decisions(decisions: Any, subject: Any) -> list[int]:
    """Original indices of the decisions whose d.get("subject") == subject."""


def find_rejected_alternative(
    decisions: Any, subject: Any, value: Any
) -> tuple[int, int] | None:
    """(decision_index, alternative_index) of the first match, or None."""


# Wave-4 pipeline-feasibility kernels (feasibility.rs, 2026-08-09) —
# convergence/preflight/derivation shims. Signatures permissive (the Rust
# side takes marshalled tuples/dicts asserted by the differential suite).
def component_area_ratio(*args: Any, **kwargs: Any) -> Any: ...
def derive_emi_max_dist(*args: Any, **kwargs: Any) -> Any: ...
def derive_si_max_placement_dist(*args: Any, **kwargs: Any) -> Any: ...
def derive_thermal_clearance(*args: Any, **kwargs: Any) -> Any: ...
def extract_min_clearance(*args: Any, **kwargs: Any) -> Any: ...
def isolation_barrier_too_large(*args: Any, **kwargs: Any) -> Any: ...
def loop_area_violation(*args: Any, **kwargs: Any) -> Any: ...
def mains_voltage_to_class_code(*args: Any, **kwargs: Any) -> Any: ...
def proximity_rule_impossible(*args: Any, **kwargs: Any) -> Any: ...
def zone_over_capacity(*args: Any, **kwargs: Any) -> Any: ...
def record_loss(*args: Any, **kwargs: Any) -> Any: ...
def check_success(*args: Any, **kwargs: Any) -> Any: ...
def is_converged(*args: Any, **kwargs: Any) -> Any: ...
def check_routability_regression(*args: Any, **kwargs: Any) -> Any: ...

# Rust Orchestration Engine (plan 2026-08-09-001) pyclasses/pyfunctions,
# appended as the crate grew past the original Wave-4 Phase-5 slice above.
# See module docstring: mirrors lib.rs's #[pymodule] registration exactly.

# convergence.rs — Phase-1 deliverable, bit-exact with pipeline/convergence.py
class TerminationReason:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class ConvergenceCriteria:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class ConvergenceState:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class ConvergenceChecker:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

# pipeline_state.rs — U4, bit-exact with pipeline/state.py
class PipelinePhase:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class PipelineConfig:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class PipelineState:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

# explainability.rs — Phase-A U8 data contracts, bit-exact with
# explainability/{decision,trace}.py. The former MarkdownReport export was
# differential-only and is intentionally not part of this stub.
class Alternative:
    value: Any
    rejection_reason: str
    constraint_violated: Any
    loss_if_chosen: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class Decision:
    id: str
    timestamp: Any
    phase: Any
    decision_type: Any
    subject: str
    value: Any
    previous_value: Any
    reason: str
    constraint_refs: Any
    loss_contribution: Any
    alternatives: Any
    epoch: Any
    iteration: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class DecisionTrace:
    run_id: str
    start_time: Any
    end_time: Any
    config_snapshot: Any
    decisions: Any
    final_positions: Any
    final_metrics: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add(self, decision: Decision) -> None: ...
    def query_subject(self, subject: str) -> list[Any]: ...
    def query_phase(self, phase: Any) -> list[Any]: ...
    def query_type(self, dtype: Any) -> list[Any]: ...
    def query_constraint(self, constraint_ref: str) -> list[Any]: ...
    def why(self, subject: str, *args: Any, **kwargs: Any) -> str: ...
    def why_not(self, *args: Any, **kwargs: Any) -> Any: ...
    def summary(self) -> dict[str, Any]: ...
class Entry:
    subject: str
    value: Any
    because: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class Trace:
    entries: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def empty() -> "Trace": ...
    def add(self, subject: str, value: Any, because: str) -> "Trace": ...

# deterministic_pipeline.rs — the PipelineRunner<BoardState> loop
# (deterministic/__init__.py's DeterministicPipeline delegates its `run` here).
class DeterministicPipeline:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def run(self, *args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def create_drc_aware_pipeline_stages(*args: Any, **kwargs: Any) -> Any: ...

# Phase D/E deterministic-stage + router_v6 orchestration run_* entry points.
# Each wraps a Stage<BoardState> implementor; see lib.rs's header comment for
# the per-stage Python-module mapping (deterministic/stages/*.py, router_v6/
# _pipeline_route.py, router_v6/_adapter_convert.py).
def run_config_attach(*args: Any, **kwargs: Any) -> Any: ...
def run_net_ordering(*args: Any, **kwargs: Any) -> Any: ...
def run_drc_oracle_setup(*args: Any, **kwargs: Any) -> Any: ...
def run_net_class_setup(*args: Any, **kwargs: Any) -> Any: ...
def run_zone_geometry(*args: Any, **kwargs: Any) -> Any: ...
def run_zone_assignment(*args: Any, **kwargs: Any) -> Any: ...
def run_slot_generation(*args: Any, **kwargs: Any) -> Any: ...
def run_clearance_grid_stage(*args: Any, **kwargs: Any) -> Any: ...
def run_hv_pad_set(*args: Any, **kwargs: Any) -> Any: ...
def run_grid_fence_check(*args: Any, **kwargs: Any) -> Any: ...
def run_grid_perf_budget(*args: Any, **kwargs: Any) -> Any: ...
def run_component_assignment(*args: Any, **kwargs: Any) -> Any: ...
def run_component_assignment_kernel(*args: Any, **kwargs: Any) -> Any: ...
def run_phased_validator_hv(*args: Any, **kwargs: Any) -> Any: ...
def run_zone_aware_slot_generation(*args: Any, **kwargs: Any) -> Any: ...
def run_phased_assignment(*args: Any, **kwargs: Any) -> Any: ...
def run_phase_select_best_slot(*args: Any, **kwargs: Any) -> Any: ...
def run_drc_validation(*args: Any, **kwargs: Any) -> Any: ...
def run_connectivity_validation(*args: Any, **kwargs: Any) -> Any: ...
def run_via_validation(*args: Any, **kwargs: Any) -> Any: ...
def run_via_deduplication(*args: Any, **kwargs: Any) -> Any: ...
def run_drc_sweep(*args: Any, **kwargs: Any) -> Any: ...
def run_automated_zero_drc(*args: Any, **kwargs: Any) -> Any: ...
def run_track_deduplication(*args: Any, **kwargs: Any) -> Any: ...
def run_short_circuit_detection(*args: Any, **kwargs: Any) -> Any: ...
def run_placement_validation(*args: Any, **kwargs: Any) -> Any: ...
def run_courtyard_check(*args: Any, **kwargs: Any) -> Any: ...
def run_fine_pitch_escape(*args: Any, **kwargs: Any) -> Any: ...
def run_hv_lv_partition(*args: Any, **kwargs: Any) -> Any: ...
def run_power_plane(*args: Any, **kwargs: Any) -> Any: ...
def run_layer_assignment(*args: Any, **kwargs: Any) -> Any: ...
def run_apply_placements(*args: Any, **kwargs: Any) -> Any: ...
def classify_feedback(*args: Any, **kwargs: Any) -> Any: ...
def handle_congestion(*args: Any, **kwargs: Any) -> Any: ...
def compute_heuristic_position(
    comp_ref: str, current_pos: tuple[float, float], net_name: str
) -> tuple[float, float]: ...
def find_critical_components(*args: Any, **kwargs: Any) -> Any: ...
def detect_persistent_ics(*args: Any, **kwargs: Any) -> Any: ...

# Deterministic coarse placement partition planner.  Pin records are
# ``(pin_name, net_name, pin_class)`` and net terminals are
# ``(component_ref, pin_name)``.  The result is
# ``(partition_id, component_refs, net_names, pin_classes)`` tuples.
def plan_component_partitions_py(*args: Any, **kwargs: Any) -> Any: ...
def partition_creepage_requirements_py(*args: Any, **kwargs: Any) -> Any: ...
def plan_grouped_creepage_cuts_py(*args: Any, **kwargs: Any) -> Any: ...
def plan_creepage_territories_py(*args: Any, **kwargs: Any) -> Any: ...
def plan_creepage_displacement_groups_py(*args: Any, **kwargs: Any) -> Any: ...
def plan_creepage_repair_frontier_py(*args: Any, **kwargs: Any) -> Any: ...
def normalize_stripped_creepage_py(*args: Any, **kwargs: Any) -> Any: ...
def verify_stripped_creepage_py(*args: Any, **kwargs: Any) -> Any: ...
def netclass_creepage_requirements_py(*args: Any, **kwargs: Any) -> Any: ...
def analyze_creepage_lower_bounds_py(*args: Any, **kwargs: Any) -> Any: ...
def compact_partition_envelopes_py(*args: Any, **kwargs: Any) -> Any: ...
def internal_component_creepage_requirements_py(*args: Any, **kwargs: Any) -> Any: ...

# clearance.rs
def get_clearance_py(*args: Any, **kwargs: Any) -> Any: ...
def run_clearance_check(*args: Any, **kwargs: Any) -> Any: ...
def run_creepage_check(*args: Any, **kwargs: Any) -> Any: ...
def classify_domain_partition_py(*args: Any, **kwargs: Any) -> Any: ...
def project_onto_barrier_axis_py(*args: Any, **kwargs: Any) -> Any: ...
def evaluate_isolator_feasibility_py(*args: Any, **kwargs: Any) -> Any: ...
def domain_clearance_constraints_py(*args: Any, **kwargs: Any) -> Any: ...
def keepaway_constraints_py(*args: Any, **kwargs: Any) -> Any: ...
def intra_footprint_conflicts_py(*args: Any, **kwargs: Any) -> Any: ...
def audit_domain_clearance_py(*args: Any, **kwargs: Any) -> Any: ...
def audit_domain_clearance_validator(*args: Any, **kwargs: Any) -> Any: ...

# channel_mapping.rs
def run_channel_mapping(*args: Any, **kwargs: Any) -> Any: ...
def run_fallback_channel_path(*args: Any, **kwargs: Any) -> Any: ...
def run_validated_two_pad_terminals(*args: Any, **kwargs: Any) -> Any: ...
def run_expand_all_pad_tree(*args: Any, **kwargs: Any) -> Any: ...
def run_assign_layer(*args: Any, **kwargs: Any) -> Any: ...
def run_channel_widths_edt(*args: Any, **kwargs: Any) -> Any: ...

# pipeline_route.rs — E6, router_v6/_pipeline_route.py + _adapter_convert.py
def run_select_sat_nets(*args: Any, **kwargs: Any) -> Any: ...
def run_build_clause_origin(*args: Any, **kwargs: Any) -> Any: ...
def run_select_routing_grids(*args: Any, **kwargs: Any) -> Any: ...
def run_next_tstamp(*args: Any, **kwargs: Any) -> Any: ...
def run_to_stage0_netclass_rules(*args: Any, **kwargs: Any) -> Any: ...
def run_write_route_segments(*args: Any, **kwargs: Any) -> Any: ...
def run_collect_pad_positions(*args: Any, **kwargs: Any) -> Any: ...
def run_build_route_payload(*args: Any, **kwargs: Any) -> Any: ...
def run_build_routing_result(*args: Any, **kwargs: Any) -> Any: ...
def run_summarize_batch_results(*args: Any, **kwargs: Any) -> Any: ...

# Phase C residual — pipeline/{dag_observability,bottleneck_report,metrics_observer}.py
class StageEvent:
    name: str
    kind: str
    iteration: Any
    duration_s: float
    reason: str
    outputs: Any
    error: Any
    feedback_contract: Any
    feedback_attempt: Any
    timestamp: float
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class PipelineExecutionLog:
    dag_topology: Any
    stage_order: Any
    stage_timings: Any
    retry_counts: Any
    feedback_activations: Any
    success: bool
    total_duration_s: float
    events: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
class BottleneckNetEntry:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class BottleneckRegion:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class CongestionHeatmapData:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class BottleneckReport:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class DeclaredArtifact:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class MetricsObserver:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class CrossValidationError(Exception): ...
class CanaryCheckError(Exception): ...

# stage_ledger.rs — final router_v6 orchestration slice
class CardinalitySnapshot:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
def snapshot_cardinality(*args: Any, **kwargs: Any) -> Any: ...
def diff_cardinality(*args: Any, **kwargs: Any) -> Any: ...

# reporter.rs — Wave-4 tail-tooling, regression/reporter.py
class BatteryVerdictReport:
    field_name: str
    verdict: str
    verdict_details: str
    cost_seconds: float
    budget_exceeded: bool
    event: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class MetricDelta:
    name: str
    baseline: float
    current: float
    delta: float
    regression: bool
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def message(self) -> str: ...
class BoardResult:
    board_id: str
    passed: bool
    metrics: Any
    baseline_metrics: Any
    deltas: Any
    warnings: Any
    errors: Any
    skipped: bool
    skip_reason: str
    board_shape: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class RegressionReporter:
    results: Any
    battery_verdicts: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_result(self, result: BoardResult) -> None: ...
    def has_failures(self) -> bool: ...
    def summary(self) -> str: ...

# ADDED 2026-08-18: both functions exist in the extension and are called from
# placer/cp_sat/netclass_constraints.py (:133, :243) but were never declared
# here, so mypy reported `Module has no attribute` and check_typecheck_gate
# failed closed on `main` -- blocking every open PR, including docs-only ones,
# because Fast Gates feeds the single required check. Declaring them is the
# fix, not a suppression: both were verified PRESENT at runtime before this
# was written.
def netclass_resolve_component_class_py(pin_infos: Any) -> Any: ...
def netclass_separated_constraints_py(*args: Any, **kwargs: Any) -> Any: ...
def netclass_separated_constraints_with_creepage_py(*args: Any, **kwargs: Any) -> Any: ...
def netclass_creepage_violations_py(*args: Any, **kwargs: Any) -> Any: ...

# The via annular-ring fabrication floor `Via::new` (pipeline_route.rs)
# enforces at construction, exported so Python derives the corrected pad
# geometry instead of restating it. See `lib.rs`'s `#[pymodule]`.
MIN_ANNULAR_RING_MM: float
ANNULAR_RING_TARGET_MM: float
