//! The loop's termination / gate / feedback DECISIONS — pyo3-free.
//!
//! Each function is the owned-data form of a decision the real loop bodies
//! currently express over Python objects. Extracting them onto the wasm32
//! tier is what "the loop logic is pyo3-free at its core" means concretely:
//! the sequencing (`pipeline.rs`), the ordering (`factory.rs`) and these
//! decisions are plain Rust control flow; the Python that surrounds them is
//! the data model + the leaf call-backs, not the decision itself.

/// The U-G dfm_fail_on raise decision (`router_pipeline.rs`): "critical"
/// raises iff critical_violations > 0, "all" raises iff total_violations > 0,
/// "none" never raises.
pub fn dfm_should_fail(fail_on: &str, critical: i64, total: i64) -> bool {
    match fail_on {
        "none" => false,
        "critical" => critical > 0,
        _ => total > 0,
    }
}

/// The U-G summary completion expression: `100 * success / max(1, success +
/// failure)` (CPython true division). The `:.1f` rendering stays on the
/// Python side (David-Gay via CPython `str.format`); the arithmetic is pure.
pub fn completion_pct(success: i64, failure: i64) -> f64 {
    100.0 * (success as f64) / ((success + failure).max(1) as f64)
}

/// The U-I `placement.status in ("infeasible", "model_invalid")` UNSAT check
/// (`cpsat_loop.rs::is_unsat_status`) — a pure string comparison once the
/// solver result's `status` is an owned `String`.
pub fn is_unsat_status(status: &str) -> bool {
    status == "infeasible" || status == "model_invalid"
}

/// The U-I field-round budget check (`cpsat_loop.rs`): "Field convergence
/// round limit (%d / %d) exceeded; exiting with UNMEASURED" fires iff
/// `counter >= limit`.
pub fn field_budget_exceeded(counter: i64, limit: i64) -> bool {
    counter >= limit
}

/// The U-F `if not raw_violations: break` termination (`feedback_loop.rs`) —
/// truthiness of the parsed DRC report. On owned data that truthiness is
/// `is_empty()`.
pub fn drc_report_is_clean(violation_count: usize) -> bool {
    violation_count == 0
}

/// The U-F `if not adjustment.adjustments: break` termination
/// (`feedback_loop.rs`) — truthiness of the adjustments dict. On owned data:
/// `is_empty()`.
pub fn adjustments_are_empty(adjustment_count: usize) -> bool {
    adjustment_count == 0
}

/// The U-F iteration cap: the oracle runs iterations `0..max_iterations`
/// (the runner's skip semantics are the loop's break semantics; an iteration
/// at `index` runs iff `index < max`).
pub fn iteration_cap_reached(index: u64, max_iterations: u64) -> bool {
    index >= max_iterations
}

#[cfg(any(test, feature = "wasm-registry"))]
#[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]
pub(crate) mod tests {
    use super::*;

    #[cfg_attr(test, test)]
    fn dfm_fail_on_decision_matches_oracle() {
        assert!(!dfm_should_fail("none", 5, 9));
        assert!(dfm_should_fail("critical", 1, 0));
        assert!(!dfm_should_fail("critical", 0, 9));
        assert!(dfm_should_fail("all", 0, 1));
        assert!(!dfm_should_fail("all", 0, 0));
    }

    #[cfg_attr(test, test)]
    fn completion_pct_matches_oracle() {
        assert_eq!(completion_pct(3, 1), 75.0);
        assert_eq!(completion_pct(0, 0), 0.0); // max(1, 0) denominator
        assert_eq!(completion_pct(5, 0), 100.0);
    }

    #[cfg_attr(test, test)]
    fn unsat_status_is_pure_string_compare() {
        assert!(is_unsat_status("infeasible"));
        assert!(is_unsat_status("model_invalid"));
        assert!(!is_unsat_status("optimal"));
        assert!(!is_unsat_status(""));
    }

    #[cfg_attr(test, test)]
    fn field_budget_is_inclusive_limit() {
        assert!(!field_budget_exceeded(2, 3));
        assert!(field_budget_exceeded(3, 3));
        assert!(field_budget_exceeded(4, 3));
    }

    #[cfg_attr(test, test)]
    fn feedback_termination_decisions_match_oracle_truthiness() {
        assert!(drc_report_is_clean(0));
        assert!(!drc_report_is_clean(1));
        assert!(adjustments_are_empty(0));
        assert!(!adjustments_are_empty(2));
        assert!(!iteration_cap_reached(0, 5));
        assert!(iteration_cap_reached(5, 5));
    }

    // --- BEGIN generated by scripts/gen_wasm_test_registry.py: tests ---
    pub const WASM_TESTS: &[(&str, fn())] = &[
        ("decisions::tests::dfm_fail_on_decision_matches_oracle", dfm_fail_on_decision_matches_oracle),
        ("decisions::tests::completion_pct_matches_oracle", completion_pct_matches_oracle),
        ("decisions::tests::unsat_status_is_pure_string_compare", unsat_status_is_pure_string_compare),
        ("decisions::tests::field_budget_is_inclusive_limit", field_budget_is_inclusive_limit),
        ("decisions::tests::feedback_termination_decisions_match_oracle_truthiness", feedback_termination_decisions_match_oracle_truthiness),
    ];
    // --- END generated by scripts/gen_wasm_test_registry.py: tests ---
}
