//! The U-E factory ORDER — pyo3-free.
//!
//! `drc_aware_stage_order` is the `create_drc_aware_pipeline()` stage-factory
//! ordering (`deterministic_pipeline.rs:110`). Its body is already pure Rust
//! (it maps a `&[&str]` constant to a `Vec<&'static str>`), but in
//! `temper-orchestration` it is gated `#[cfg(feature = "python")]` because it
//! lives in the same file as the pyclass that consumes it. Extracted here it
//! needs no gate at all — the wasm32 tier can pin the ordering the way it
//! already pins `dfm_should_fail` / `completion_pct` (the only two pure
//! kernels that currently survive `--no-default-features` in
//! `router_pipeline.rs`).

/// The canonical 23-stage DRC-aware order (verbatim from
/// `deterministic_pipeline.rs`'s `DRC_AWARE_STAGE_KINDS`).
pub const DRC_AWARE_STAGE_KINDS: &[&str] = &[
    "config_attach",
    "net_class_setup",
    "zone_geometry",
    "zone_assignment",
    "hv_lv_partition",
    "slot_generation",      // zone_aware -> zone_aware_slot_generation
    "component_assignment", // phased config -> phased_component_assignment
    "apply_placements",
    "courtyard_check",
    "apply_placements",
    "placement_validation",
    "drc_oracle_setup",
    "clearance_grid",
    "net_ordering",
    "layer_assignment",
    "power_plane",
    "fine_pitch_escape",
    "track_deduplication",
    "short_circuit_detection",
    "via_deduplication",
    "via_validation",
    "drc_validation",
    "connectivity_validation",
];

/// The canonical 23-stage order with the zone-aware and phased substitutions
/// applied (what `create_drc_aware_pipeline()` actually builds by default).
pub fn drc_aware_stage_order(zone_aware: bool, phased: bool) -> Vec<&'static str> {
    DRC_AWARE_STAGE_KINDS
        .iter()
        .map(|k| match *k {
            "slot_generation" => {
                if zone_aware { "zone_aware_slot_generation" } else { "slot_generation" }
            }
            "component_assignment" => {
                if phased { "phased_component_assignment" } else { "component_assignment" }
            }
            other => other,
        })
        .collect()
}

#[cfg(any(test, feature = "wasm-registry"))]
#[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]
pub(crate) mod tests {
    use super::*;

    #[cfg_attr(test, test)]
    fn default_order_is_the_canonical_23() {
        let order = drc_aware_stage_order(false, false);
        assert_eq!(order.len(), 23);
        // The two substitution sites keep their standard names by default.
        assert!(order.contains(&"slot_generation"));
        assert!(order.contains(&"component_assignment"));
        assert!(!order.contains(&"zone_aware_slot_generation"));
        assert!(!order.contains(&"phased_component_assignment"));
    }

    #[cfg_attr(test, test)]
    fn substitutions_fire_independently() {
        let both = drc_aware_stage_order(true, true);
        assert!(both.contains(&"zone_aware_slot_generation"));
        assert!(both.contains(&"phased_component_assignment"));
        assert!(!both.contains(&"slot_generation"));
        assert!(!both.contains(&"component_assignment"));

        let zone_only = drc_aware_stage_order(true, false);
        assert!(zone_only.contains(&"zone_aware_slot_generation"));
        assert!(zone_only.contains(&"component_assignment"));

        let phased_only = drc_aware_stage_order(false, true);
        assert!(phased_only.contains(&"slot_generation"));
        assert!(phased_only.contains(&"phased_component_assignment"));
    }

    // --- BEGIN generated by scripts/gen_wasm_test_registry.py: tests ---
    pub const WASM_TESTS: &[(&str, fn())] = &[
        ("factory::tests::default_order_is_the_canonical_23", default_order_is_the_canonical_23),
        ("factory::tests::substitutions_fire_independently", substitutions_fire_independently),
    ];
    // --- END generated by scripts/gen_wasm_test_registry.py: tests ---
}
