//! SPIKE POC — the pyo3-free orchestration loop core.
//!
//! This crate is the proof-of-concept for the assessment in
//! `docs/evidence/2026-08-12-orchestration-loop-wasm-spike.md` (the
//! companion note). It extracts the parts of `temper-orchestration` that are
//! already pyo3-free in *substance* — the loop sequencing, the termination /
//! gate / factory decisions, and a `CoreBoardState` with owned structs — into
//! a crate with no pyo3 dependency at all, so `cargo check --target
//! wasm32-unknown-unknown` proves the wasm32 tier can host them.
//!
//! # What this proves, and what it does not
//!
//! Proves:
//! * the `Stage<S>` trait + `PipelineRunner<S>` sequencing loop is pyo3-free
//!   and wasm32-compiles (it already survives `--no-default-features` in
//!   `temper-orchestration`; here it lives with no `python` feature at all);
//! * the loop DECISIONS (termination predicates, gate checks, factory
//!   ordering) are pure Rust control flow over owned data;
//! * a `CoreBoardState` whose fields are owned Rust structs (not
//!   `Option<Py<PyAny>>`) compiles for wasm32 — the exact transformation the
//!   pure-Rust data-model port (`/tmp/opencode/rust-pure-datamodel-brainstorm.md`
//!   U0-U4) will perform on the real `BoardState`.
//!
//! Does NOT prove (and is not attempting to):
//! * that the REAL U-E/U-F/U-G/U-I loop bodies are pyo3-free today — they are
//!   not; they thread `Py<PyAny>` call-backs and a Python `BoardState` through
//!   a side-channel. De-pythoning those bodies is exactly the data-model port,
//!   which is out of scope for a spike.
//! * that the copied items below are production-ready — they are faithful
//!   copies of `temper-orchestration`'s `stage`/`pipeline`/`board_state`
//!   (with the `Py<PyAny>` fields replaced by owned skeletons); a real
//!   extraction MOVES the originals rather than duplicating them.
//!
//! # The forced-move framing
//!
//! The wasm32 tier is a forcing function for the data-model port: a
//! `CoreBoardState` with owned fields is REQUIRED for the loop to run on
//! wasm32 (a `Py<PyAny>` cannot exist in a wasm32 module — there is no
//! interpreter to own it). The decision kernels and the sequencing loop are
//! extractable today; the full loop bodies follow once `CoreBoardState`'s
//! real (not skeleton) fields land.

pub mod board_state;
pub mod decisions;
pub mod factory;
pub mod pipeline;
pub mod stage;

// NOT gated on any feature: there is no `python` feature here, so every wasm32
// build compiles this module. Mirrors `temper-orchestration`'s own note that
// the registry must never be gated on `python`.
// In the real extraction this is generated by
// `scripts/gen_wasm_test_registry.py --crate temper-orchestration-core`.
#[cfg(feature = "wasm-registry")]
pub mod wasm_test_registry;
