//! The `Stage<S>` trait and its contract/error types — pyo3-free.
//!
//! Faithful copy of `temper-orchestration/src/stage.rs`'s trait and types,
//! with the `python`-feature default removed: there is no `BoardState` here
//! (that is the pyo3-held type), so `Stage` is always written with an
//! explicit `S`, exactly like the existing crate's
//! `#[cfg(not(feature = "python"))]` definition. A real extraction MOVES this
//! file into the core crate and re-exports it from `temper-orchestration`.

use std::borrow::Cow;
use std::fmt;

/// A single pipeline stage that transforms a typed state.
pub trait Stage<S> {
    fn name(&self) -> Cow<'static, str>;

    fn invariants(&self) -> &[InvariantSpec] {
        &[]
    }

    fn last_modified_regions(&self) -> Option<&[(f64, f64, f64, f64)]> {
        None
    }

    fn declared_writes(&self) -> &[DeclaredArtifact] {
        &[]
    }

    fn declared_reads(&self) -> &[DeclaredArtifact] {
        &[]
    }

    fn is_active(&self) -> bool {
        true
    }

    fn run(&self, state: S) -> Result<S, StageError>;
}

/// A named pipeline invariant (DRC fence contract).
#[derive(Debug, Clone)]
pub struct InvariantSpec {
    pub name: String,
    pub description: String,
    pub severity: InvariantSeverity,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InvariantSeverity {
    Error,
    Warning,
}

/// A contract artifact: something a stage produces or consumes.
#[derive(Debug, Clone)]
pub struct DeclaredArtifact {
    pub name: String,
    pub artifact_type: String,
}

/// A stage-level error.
#[derive(Debug, Clone, PartialEq)]
pub struct StageError {
    pub stage_name: String,
    pub message: String,
    pub kind: StageErrorKind,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StageErrorKind {
    Warning,
    Fatal,
    Infeasible,
}

impl StageError {
    pub fn new(
        stage_name: impl Into<String>,
        message: impl Into<String>,
        kind: StageErrorKind,
    ) -> Self {
        Self {
            stage_name: stage_name.into(),
            message: message.into(),
            kind,
        }
    }
}

impl fmt::Display for StageError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}: {:?}: {}", self.stage_name, self.kind, self.message)
    }
}

impl std::error::Error for StageError {}

#[cfg(any(test, feature = "wasm-registry"))]
#[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]
pub(crate) mod tests {
    use super::*;

    /// A trivial stage over `u32` used to pin the trait's shape.
    struct AddStage {
        name: &'static str,
        delta: u32,
        active: bool,
    }

    impl Stage<u32> for AddStage {
        fn name(&self) -> Cow<'static, str> {
            Cow::Borrowed(self.name)
        }
        fn is_active(&self) -> bool {
            self.active
        }
        fn run(&self, state: u32) -> Result<u32, StageError> {
            Ok(state + self.delta)
        }
    }

    #[cfg_attr(test, test)]
    fn stage_run_transforms_state() {
        let stage = AddStage {
            name: "add_one",
            delta: 1,
            active: true,
        };
        assert_eq!(stage.run(41), Ok(42));
        assert_eq!(stage.name(), Cow::Borrowed("add_one"));
        assert!(stage.is_active());
    }

    #[cfg_attr(test, test)]
    fn stage_error_roundtrip_and_display() {
        let err = StageError::new("convergence_check", "boom", StageErrorKind::Fatal);
        assert_eq!(err.stage_name, "convergence_check");
        assert_eq!(err.kind, StageErrorKind::Fatal);
        assert!(err.to_string().contains("convergence_check"));
        assert!(err.to_string().contains("boom"));
    }

    // --- BEGIN generated by scripts/gen_wasm_test_registry.py: tests ---
    pub const WASM_TESTS: &[(&str, fn())] = &[
        ("stage::tests::stage_run_transforms_state", stage_run_transforms_state),
        ("stage::tests::stage_error_roundtrip_and_display", stage_error_roundtrip_and_display),
    ];
    // --- END generated by scripts/gen_wasm_test_registry.py: tests ---
}
