//! The `wasm32` test registry for `temper-orchestration-core` (SPIKE POC).
//!
//! In the real extraction this file is generated by
//! `scripts/gen_wasm_test_registry.py --crate temper-orchestration-core`;
//! here it is hand-written to mirror the generated shape. One family
//! (`orchestration-core`), gated on `wasm-registry-orchestration-core`.
//!
//! A test fails by panicking; on `wasm32-unknown-unknown` a panic aborts
//! (the target has no unwinding), surfacing to the host as a WebAssembly
//! trap — the shared `temper-wasm-test-runner` catches it.

pub type WasmTest = (&'static str, fn());

/// All eligible tests, in a stable order.
pub const ALL: &[&[WasmTest]] = &[
    #[cfg(feature = "wasm-registry-orchestration-core")]
    crate::board_state::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration-core")]
    crate::decisions::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration-core")]
    crate::factory::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration-core")]
    crate::pipeline::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-orchestration-core")]
    crate::stage::tests::WASM_TESTS,
];

/// Total number of registered tests *in the currently-selected families*.
pub fn count() -> usize {
    ALL.iter().map(|m| m.len()).sum()
}

/// The test at `index` in the flattened registry.
pub fn get(index: usize) -> Option<&'static WasmTest> {
    let mut remaining = index;
    for module in ALL {
        if remaining < module.len() {
            return Some(&module[remaining]);
        }
        remaining -= module.len();
    }
    None
}
