//! Thermal FDM assembly kernels (U6) — the hot loops of
//! `temper_placer/physics/thermal_fdm.py`.
//!
//! Ported pieces:
//! - `assemble_system`: the 5-point stencil matrix assembly (harmonic-
//!   mean interface conductivity, Dirichlet heatsink face, Neumann
//!   adiabatic edges, optional vertical sink) — pure-Python per-cell
//!   loop in the reference.
//! - `trace_to_cell_coverage`: anti-aliased fat-trace rasterisation
//!   with 4x4 supersampling and point-to-segment distance tests.
//!
//! Wave 4 Phase 4 added the two physics-gated surfaces:
//! - `thermal_potential`: the five superposing potential-field
//!   components, the `linspace`/`meshgrid` grid builder, the weighted
//!   superposition, the two-pass greedy anchor search and the R24
//!   post-solve audit — the hot loops of
//!   `temper_placer/physics/thermal_potential.py`.
//! - `operating_point`: the coupling model `L_eff(k)`, the junction-
//!   temperature chain and ceiling arithmetic, the interior
//!   bounding-soundness scan and its audit, from
//!   `temper_placer/physics/operating_point.py`.
//!
//! Both carry the R24 discipline (soundness proof, BMC-exhaustive
//! validation on small N, post-solve audit) documented in
//! `VERIFICATION.md`.  `hostmath` holds the shared `dlsym`-resolved libm
//! and the Python/numpy comparison semantics they depend on.
//!
//! The sparse SOLVE is delegated to `solve::solve_sparse_lu_py` (faer
//! sparse LU), closing the last two scipy imports in the product surface
//! (`thermal_fdm.py` / `thermal_scorer.py`). The migration's measured
//! tolerance is recorded in `VERIFICATION.md` (KTD9 overturn, 2026-08-09).
//!
//! All arithmetic mirrors the Python reference's exact f64 operation
//! order so outputs are bit-identical (pinned by the differential
//! suite in packages/temper-placer/tests/physics/).

// WASM tier R1 (plan 2026-08-03-002): with `--no-default-features` the whole
// pyo3 surface (each module's `*_py` bridges) is not compiled, so the pure
// kernels they call look unused to rustc -- it cannot see past the cfg gate.
// Allow dead_code in that configuration only, exactly as `temper-geometry`
// does; the default (python) build keeps the lint.
#![cfg_attr(not(feature = "python"), allow(dead_code))]

pub mod copper_coverage;
pub mod device_power;
pub mod emi;
pub mod fdm;
pub mod geometric_metrics;
pub mod heat_removal;
pub mod hostmath;
pub mod inductance;
pub mod junction_temp;
pub mod operating_point;
pub mod parameter_bounds;
// Property-based campaigns (metamorphic/invariant relations) over four of
// this crate's pure kernels -- see the module doc comment for why it
// exists and which relations it asserts. Not gated on `python`: it must
// compile in the `--no-default-features` wasm32 build the registry below
// targets, exactly like every other module in this list.
pub mod property_campaigns;
pub mod rtd;
pub mod safety;
// Wholly a faer + pyo3 surface: `solve_sparse_lu` is the sparse-LU call and
// `solve_sparse_lu_py` is its only caller, so the module rides the `python`
// feature that `faer` itself rides (see Cargo.toml).  A
// `--no-default-features` build -- the wasm32 configuration -- has neither
// dependency in its graph and therefore does not compile this module.
#[cfg(feature = "python")]
pub mod solve;
pub mod thermal_edges;
pub mod thermal_potential;
pub mod thermal_scorer;
pub mod tj_cross_check;

// NOT gated on `python`. The wasm32 tier builds with --no-default-features,
// so an added `python` gate here would silently exclude the registry and the
// runner would fail to compile against it. `wasm-registry` is implied by every
// per-family feature and by `wasm-test-registry`, so any wasm build compiles
// this module.
// Generated by `scripts/gen_wasm_test_registry.py --crate temper-thermal`.
#[cfg(feature = "wasm-registry")]
pub mod wasm_test_registry;

#[cfg(feature = "python")]
use pyo3::prelude::*;

#[cfg(feature = "python")]
#[pymodule]
fn temper_thermal(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(fdm::assemble_system_py, m)?)?;
    m.add_function(wrap_pyfunction!(fdm::trace_to_cell_coverage, m)?)?;
    m.add_function(wrap_pyfunction!(solve::solve_sparse_lu_py, m)?)?;
    m.add_function(wrap_pyfunction!(rtd::rtd_resistance_to_code_py, m)?)?;
    m.add_function(wrap_pyfunction!(rtd::rtd_max31865_current_a_py, m)?)?;
    m.add_function(wrap_pyfunction!(rtd::rtd_max31865_voltage_v_py, m)?)?;
    m.add_function(wrap_pyfunction!(rtd::rtd_hardware_window_voltage_py, m)?)?;
    m.add_function(wrap_pyfunction!(rtd::rtd_reference_divider_voltage_v_py, m)?)?;
    m.add_function(wrap_pyfunction!(rtd::rtd_spi_rc_rise_time_ns_py, m)?)?;
    m.add_function(wrap_pyfunction!(rtd::rtd_threshold_adc_codes_py, m)?)?;
    m.add_function(wrap_pyfunction!(rtd::rtd_derive_hardware_window_py, m)?)?;
    m.add_function(wrap_pyfunction!(rtd::rtd_derive_max31865_hardware_window_py, m)?)?;
    m.add_function(wrap_pyfunction!(thermal_scorer::build_conductivity_field_py, m)?)?;
    m.add_function(wrap_pyfunction!(thermal_scorer::build_heat_source_field_py, m)?)?;
    m.add_function(wrap_pyfunction!(thermal_scorer::assemble_convective_system_py, m)?)?;
    m.add_function(wrap_pyfunction!(device_power::single_device_power_py, m)?)?;
    m.add_function(wrap_pyfunction!(junction_temp::estimate_junction_temp_py, m)?)?;
    m.add_function(wrap_pyfunction!(inductance::estimate_loop_inductance_py, m)?)?;
    m.add_function(wrap_pyfunction!(inductance::estimate_gate_inductance_py, m)?)?;
    m.add_function(wrap_pyfunction!(
        thermal_potential::thermal_potential_build_grid_py,
        m
    )?)?;
    m.add_function(wrap_pyfunction!(
        thermal_potential::thermal_potential_phi_edge_py,
        m
    )?)?;
    m.add_function(wrap_pyfunction!(
        thermal_potential::thermal_potential_phi_copper_py,
        m
    )?)?;
    m.add_function(wrap_pyfunction!(
        thermal_potential::thermal_potential_phi_coupling_py,
        m
    )?)?;
    m.add_function(wrap_pyfunction!(
        thermal_potential::thermal_potential_phi_exclusion_py,
        m
    )?)?;
    m.add_function(wrap_pyfunction!(
        thermal_potential::thermal_potential_phi_convection_py,
        m
    )?)?;
    m.add_function(wrap_pyfunction!(
        thermal_potential::thermal_potential_assign_anchors_py,
        m
    )?)?;
    m.add_function(wrap_pyfunction!(
        thermal_potential::thermal_potential_enforce_unique_py,
        m
    )?)?;
    m.add_function(wrap_pyfunction!(operating_point::operating_point_l_eff_py, m)?)?;
    m.add_function(wrap_pyfunction!(
        operating_point::operating_point_interior_k_grid_py,
        m
    )?)?;
    m.add_function(wrap_pyfunction!(
        operating_point::operating_point_extremes_py,
        m
    )?)?;
    m.add_function(wrap_pyfunction!(
        operating_point::operating_point_interior_scan_py,
        m
    )?)?;
    m.add_function(wrap_pyfunction!(operating_point::operating_point_audit_py, m)?)?;
    m.add_function(wrap_pyfunction!(emi::predict_radiated_emissions_py, m)?)?;
    m.add_function(wrap_pyfunction!(emi::check_emi_compliance_py, m)?)?;
    m.add_function(wrap_pyfunction!(safety::estimate_filter_delay_py, m)?)?;
    m.add_function(wrap_pyfunction!(safety::estimate_fault_response_time_py, m)?)?;
    m.add_function(wrap_pyfunction!(safety::is_safety_timing_valid_py, m)?)?;
    m.add_function(wrap_pyfunction!(heat_removal::build_h_field_py, m)?)?;
    m.add_function(wrap_pyfunction!(copper_coverage::copper_masks_py, m)?)?;
    m.add_function(wrap_pyfunction!(copper_coverage::copper_trace_accumulate_py, m)?)?;
    m.add_function(wrap_pyfunction!(tj_cross_check::distance_to_heatsink_edge_py, m)?)?;
    m.add_function(wrap_pyfunction!(tj_cross_check::device_cross_check_py, m)?)?;
    m.add_function(wrap_pyfunction!(parameter_bounds::classify_parameter_py, m)?)?;
    m.add_function(wrap_pyfunction!(parameter_bounds::worst_case_values_py, m)?)?;
    m.add_function(wrap_pyfunction!(geometric_metrics::measure_geometric_py, m)?)?;
    m.add_function(wrap_pyfunction!(thermal_edges::measure_thermal_edges_py, m)?)?;
    Ok(())
}
