//! The `wasm32` test registry for `temper-thermal`.
//!
//! Generated by `scripts/gen_wasm_test_registry.py`; run it after adding a
//! test to any listed module, and `--check` gates drift in CI.
//!
//! `cargo test`'s libtest harness cannot target `wasm32-unknown-unknown`,
//! so the Worker tier calls each test function individually instead of
//! running a test binary.  This module is the flat, indexable list of them.
//!
//! Only modules that survive `--no-default-features` appear here.  Tests
//! inside `#[cfg(feature = "python")]` modules are structurally absent
//! from a `wasm32` build and cannot be registered here at all.
//!
//! Two exclusion classes apply here, both structural:
//!
//! * `#[cfg(feature = "python")]` modules -- `solve`, whose sparse-LU
//!   kernel and its pyo3 bridge are one surface and which carries the
//!   `faer` dependency, so neither exists in a
//!   `--no-default-features` build.
//! * `proptest` modules use a dev-dependency, which is not linked into
//!   the ordinary (non-test) build this registry compiles into.  Unlike
//!   `temper-geometry`, this crate nests them *inside* its `tests`
//!   modules; each carries its own `#[cfg(test)]` and is censused
//!   separately, so nesting costs the enclosing module nothing.
//!
//! `scripts/gen_wasm_test_registry.py --crate temper-thermal --census`
//! prints the full module census with per-module counts.
//!
//! ## Families
//!
//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`
//! feature, as in `temper-drc-rs`.  This crate is a flat set of
//! physics kernels with no rule-family taxonomy, so it declares a
//! single family (`thermal`); the mechanism is in place if a
//! size-driven split is ever wanted.

/// A single test: its fully qualified name and a nullary callable.
///
/// Failure is signalled by panicking, exactly as under libtest.  On
/// `wasm32-unknown-unknown` a panic aborts (the target has no unwinding on
/// stable), which surfaces to the host as a WebAssembly trap -- so the
/// runner catches the trap rather than a `Result`.
pub type WasmTest = (&'static str, fn());

/// All 2637 eligible tests, in a stable order.  Each entry is
/// gated on the per-family `wasm-registry-<family>` feature; enable
/// all families (`wasm-test-registry`) or individual ones.
pub const ALL: &[&[WasmTest]] = &[
    #[cfg(feature = "wasm-registry-thermal")] crate::copper_coverage::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::device_power::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::emi::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::fdm::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::geometric_metrics::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::heat_removal::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::hostmath::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::inductance::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::junction_temp::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::operating_point::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::operating_point::tests::frozen_op_tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::parameter_bounds::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::property_campaigns::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::safety::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::thermal_constants::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::thermal_edges::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::thermal_potential::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::thermal_scorer::tests::WASM_TESTS,
    #[cfg(feature = "wasm-registry-thermal")] crate::tj_cross_check::tests::WASM_TESTS,
];

/// Total number of registered tests *in the currently-selected families*.
pub fn count() -> usize {
    ALL.iter().map(|m| m.len()).sum()
}

/// The test at `index` in the flattened registry.
pub fn get(index: usize) -> Option<&'static WasmTest> {
    let mut remaining = index;
    for module in ALL {
        if remaining < module.len() {
            return Some(&module[remaining]);
        }
        remaining -= module.len();
    }
    None
}
