"""Shared machinery for the FREEZE oracle-retirement generator (U4 of
``docs/plans/2026-08-11-003-feat-migration-pipeline-wire-and-retire-plan.md``).

Background
----------
The migration pipeline pins a verbatim pre-migration Python implementation
as a "differential oracle" for every migrated kernel (``docs/migration-
pipeline.md`` stage 3), and — before this plan — had no mechanism to ever
retire one. Result: 153+ ``_py_oracle.py`` files, 50,141+ LOC, that can
never run on the wasm32 tier (they need CPython) and grow with every
migration.

FREEZE is the plan's default disposition for a retirable oracle: run the
oracle once over a *declared* input corpus, bake the (input, output) pairs
into a Rust ``const`` array as a golden-vector regression test, delete the
Python oracle, and keep the differential — now comparing the Rust kernel
against the frozen vectors instead of a live CPython call. The regression
signal survives; the CPython dependency does not; the resulting test is
wasm32-tier-executable because it is plain Rust data + an ``assert_eq``
loop, no ``pyo3``, no ``proptest`` (a dev-dependency absent from the
tier's non-test build).

Q2 — the reason this module exists, not just a one-off script
---------------------------------------------------------------
A frozen corpus cannot find a bug in an input region it never sampled. This
repo has hit exactly that failure four times (see ``docs/evidence/
2026-08-11-native-only-is-an-upper-bound.md`` §7): ``temper-geometry``'s
keepout property, ``temper-thermal``'s overlap-area property, ``temper-
quality-oracle``'s IPC-2221 bracket property, and ``temper-io-types``'s 7
special-value gaps under uniform sampling. FREEZE reproduces this failure
class at scale unless the corpus generator both **measures** the fraction
of non-trivial/boundary cases it drew and **refuses** to emit a corpus
that does not clear a declared minimum for each such fraction. That is
what :func:`run_freeze` does: it is not optional plumbing, it is the gate
that makes FREEZE safe to apply repeatedly. Every :class:`FreezeSpec` must
declare at least one :class:`NonVacuityCheck`; a spec with an empty list is
rejected before it runs (see ``run_freeze``'s validation), mirroring the
precedent in ``packages/temper-geometry/src/creepage_check.rs`` /
``via_clearance.rs`` (PR #1007) and ``packages/temper-quality-oracle/src/
property_campaigns.rs`` (Kernel 5, IPC-2221 bracket), which measure hit
rates like "42/50 bracket-straddling" and assert a minimum before trusting
the campaign.

Design notes
------------
* One spec module per oracle, under ``scripts/oracle_freeze_specs/``,
  each exporting a module-level ``SPEC: FreezeSpec``. This mirrors this
  repo's existing generator convention (``scripts/gen_wasm_test_registry.py``
  hand-lists eligible modules per crate; there is no single mechanical rule
  that derives a Rust golden-vector block from an arbitrary Python function
  signature, so the per-oracle glue — how to call it, how to render its
  inputs/outputs as Rust literals, what "non-trivial" means for its domain —
  is inherent complexity, not accidental).
* Corpus generation is deterministic: either an explicit hand-curated list
  (reusing the oracle's own pre-existing differential test cases where they
  already form a good corpus) or a seeded :class:`SplitMix64` draw (the same
  PRNG and constants as ``packages/temper-orchestration/src/
  wasm_campaign_prng.rs`` / ``packages/temper-drc-rs/src/rules/drc/
  property_campaigns.rs``, reimplemented here in Python so a spec's corpus
  is reproducible without a Rust build).
* Floats are rendered as ``f64::from_bits(0x...)`` — bit-exact, including
  NaN/Infinity payloads, matching this repo's existing bit-exactness
  convention (``float.hex()`` comparisons in the differential suites this
  tool replaces) without depending on Rust's lack of stable hex-float
  literal syntax.
* Generated Rust is spliced into an EXISTING file between a pair of marker
  comments (``splice_generated_block``), the same idempotent-rewrite shape
  ``scripts/gen_wasm_test_registry.py`` already uses for its own
  ``BEGIN/END generated by`` blocks — chosen deliberately so a frozen
  corpus can live inside a kernel's own ``#[cfg(test)] mod tests`` (where
  the wasm-registry generator can already see it) rather than requiring a
  new crate module and a new ``mod`` declaration in ``lib.rs`` for every
  retired oracle.
"""

from __future__ import annotations

import struct
import sys
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _lib.repo import find_repo_root  # noqa: E402

REPO_ROOT = find_repo_root()


# --------------------------------------------------------------------------
# Deterministic PRNG — Python mirror of wasm_campaign_prng.rs's SplitMix64.
# --------------------------------------------------------------------------


class SplitMix64:
    """Same constants and update rule as this repo's Rust mirror campaigns
    (``packages/temper-orchestration/src/wasm_campaign_prng.rs``). Not
    required to be bit-identical to any Rust draw for FREEZE to be correct
    (the corpus is baked into Rust as data, not regenerated there) — reused
    only so this tool's determinism story matches the rest of the tier
    rather than introducing a fourth PRNG convention.
    """

    __slots__ = ("state",)
    _MASK = 0xFFFFFFFFFFFFFFFF

    def __init__(self, seed: int) -> None:
        self.state = seed & self._MASK

    def next_u64(self) -> int:
        self.state = (self.state + 0x9E3779B97F4A7C15) & self._MASK
        z = self.state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & self._MASK
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & self._MASK
        return z ^ (z >> 31)

    def next_f64(self) -> float:
        return (self.next_u64() >> 11) * (1.0 / (1 << 53))

    def range(self, lo: float, hi: float) -> float:
        return lo + self.next_f64() * (hi - lo)

    def range_i64(self, lo: int, hi: int) -> int:
        assert hi > lo
        return lo + (self.next_u64() % (hi - lo))

    def index(self, n: int) -> int:
        assert n > 0
        return self.next_u64() % n

    def boolean(self) -> bool:
        return self.next_u64() & 1 == 0


def rust_f64_literal(x: float) -> str:
    """Bit-exact ``f64::from_bits(0x...)`` rendering, including NaN/Infinity.

    Deliberately not a decimal literal: Rust has no stable hex-float syntax,
    and a decimal round-trip (``repr(x)`` -> Rust parses it back) is not
    guaranteed bit-exact for every double, only for "shortest repr" doubles
    Python happens to print losslessly. Bits are exact by construction.
    """
    bits = struct.unpack(">Q", struct.pack(">d", x))[0]
    return f"f64::from_bits(0x{bits:016X}_u64)"


# --------------------------------------------------------------------------
# Spec model
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class FreezeCase:
    """One corpus case: an opaque, spec-defined input plus the tags used
    for non-vacuity measurement. ``input`` is never interpreted by this
    module — only by the spec's own ``run_oracle``/``render_case``.
    """

    input: Any
    tags: frozenset[str]


@dataclass(frozen=True)
class NonVacuityCheck:
    """One generation-time coverage guard: at least ``min_fraction`` of the
    corpus must carry ``tag``, or the corpus is refused (Q2 — see this
    module's docstring). ``min_count`` is an alternative absolute-count form
    for tags that should appear at all (e.g. "every shape code exercised at
    least once") rather than at some percentage.
    """

    tag: str
    description: str
    min_fraction: float = 0.0
    min_count: int = 0

    def evaluate(self, cases_with_output: list[tuple[FreezeCase, Any]]) -> tuple[bool, int, int]:
        n = len(cases_with_output)
        hits = sum(1 for case, _ in cases_with_output if self.tag in case.tags)
        if self.min_count:
            ok = hits >= self.min_count
        else:
            ok = n > 0 and hits * 100 >= n * int(round(self.min_fraction * 100))
        return ok, hits, n


@dataclass(frozen=True)
class FreezeSpec:
    """Everything needed to freeze one oracle. See module docstring."""

    name: str
    description: str
    oracle_provenance: str  # human-readable: file + pinned commit, informational
    kernel_provenance: str  # human-readable: which .rs fn this compares against
    gen_cases: Callable[[], list[FreezeCase]]
    run_oracle: Callable[[Any], Any]  # FreezeCase.input -> raw oracle output
    non_vacuity: list[NonVacuityCheck]
    render_rust: Callable[[list[tuple[FreezeCase, Any]]], str]  # -> full generated block body
    rust_target_file: str  # repo-relative path to splice into
    insert_before_marker: str  # exact line already present in rust_target_file
    marker_name: str = ""  # defaults to `name` if unset
    extra_context: dict[str, Any] = field(default_factory=dict)

    def marker(self) -> str:
        return self.marker_name or self.name


# --------------------------------------------------------------------------
# Marker splice (same idempotent-rewrite shape as gen_wasm_test_registry.py)
# --------------------------------------------------------------------------


def _markers(marker_name: str) -> tuple[str, str]:
    begin = f"// --- BEGIN generated by scripts/gen_oracle_freeze.py: {marker_name} ---"
    end = f"// --- END generated by scripts/gen_oracle_freeze.py: {marker_name} ---"
    return begin, end


def splice_generated_block(
    text: str, marker_name: str, body: str, insert_before_marker: str
) -> str:
    """Insert or replace the ``marker_name`` generated block in ``text``.

    If the markers are already present, the content between them is
    replaced in place (idempotent regeneration — matches ``gen_wasm_test_
    registry.py``'s own rewrite behaviour). If absent, the block is
    inserted immediately before the first line equal to
    ``insert_before_marker`` (stripped comparison), so a frozen corpus can
    land inside an existing ``mod tests { ... }`` block, ahead of that
    module's own wasm-registry ``BEGIN/END`` markers, without hand-editing.
    """
    begin, end = _markers(marker_name)
    lines = text.splitlines(keepends=True)
    block = f"{begin}\n{body}\n{end}\n"

    begin_idx = None
    end_idx = None
    for i, line in enumerate(lines):
        if line.strip() == begin:
            begin_idx = i
        elif line.strip() == end and begin_idx is not None:
            end_idx = i
            break

    if begin_idx is not None and end_idx is not None:
        return "".join(lines[:begin_idx]) + block + "".join(lines[end_idx + 1 :])

    insert_idx = None
    for i, line in enumerate(lines):
        if line.strip() == insert_before_marker.strip():
            insert_idx = i
            break
    if insert_idx is None:
        raise ValueError(
            f"insert_before_marker {insert_before_marker!r} not found in target file "
            f"and no existing {begin!r}/{end!r} block to replace"
        )
    return "".join(lines[:insert_idx]) + block + "\n" + "".join(lines[insert_idx:])


# --------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------


class FreezeRefused(Exception):
    """Raised when a corpus fails a non-vacuity check — the generator
    refuses to emit it (Q2)."""


def run_freeze(spec: FreezeSpec, *, write: bool, check: bool = False) -> str:
    """Generate a spec's frozen corpus, enforce non-vacuity, and (unless
    ``check``) splice the result into its Rust target file.

    Returns a human-readable report. Raises :class:`FreezeRefused` if any
    non-vacuity check fails — this is a hard refusal, not a warning: Q2
    exists precisely so a bad corpus cannot silently ship.
    """
    if not spec.non_vacuity:
        raise ValueError(
            f"spec {spec.name!r} declares zero NonVacuityCheck entries — a FreezeSpec "
            f"MUST measure and assert non-triviality (Q2); refusing to run an "
            f"unguarded corpus generator."
        )

    cases = spec.gen_cases()
    if not cases:
        raise ValueError(f"spec {spec.name!r} generated zero cases")

    results: list[tuple[FreezeCase, Any]] = [(c, spec.run_oracle(c.input)) for c in cases]

    report_lines = [
        f"=== FREEZE {spec.name} ===",
        spec.description,
        f"oracle: {spec.oracle_provenance}",
        f"kernel: {spec.kernel_provenance}",
        f"corpus size: {len(results)}",
        "non-vacuity:",
    ]
    all_ok = True
    for nvc in spec.non_vacuity:
        ok, hits, n = nvc.evaluate(results)
        all_ok = all_ok and ok
        status = "PASS" if ok else "FAIL"
        target = f">={nvc.min_count}" if nvc.min_count else f">={nvc.min_fraction:.0%}"
        report_lines.append(f"  [{status}] {nvc.tag}: {hits}/{n} ({target}) -- {nvc.description}")

    report = "\n".join(report_lines)

    if not all_ok:
        raise FreezeRefused(
            f"{report}\n\nREFUSED: at least one non-vacuity check failed minimum -- "
            f"this corpus would be trivially satisfiable (Q2). Widen/rebias gen_cases(), "
            f"do not lower the threshold to make the check pass."
        )

    body = spec.render_rust(results)
    target_path = REPO_ROOT / spec.rust_target_file
    original = target_path.read_text(encoding="utf-8")
    new_text = splice_generated_block(original, spec.marker(), body, spec.insert_before_marker)

    if check:
        if new_text != original:
            raise FreezeRefused(
                f"{spec.rust_target_file} is out of date for spec {spec.name!r} -- "
                f"run `python3 scripts/gen_oracle_freeze.py --spec {spec.name}` and commit the result."
            )
        return report + "\n\nCHECK OK: generated block up to date."

    if write and new_text != original:
        target_path.write_text(new_text, encoding="utf-8")
        report += f"\n\nWROTE {spec.rust_target_file}"
    else:
        report += "\n\n(no write requested or no change)"

    return report
