#!/usr/bin/env python3
"""Generate (and drift-check) the ``wasm32`` test registry for ``temper-drc-rs``.

Why this exists
---------------
``cargo test``'s libtest harness cannot target ``wasm32-unknown-unknown``:
there is no process model, no threads, and no ``std::process::exit``.  So the
Worker tier cannot run ``cargo test`` -- it has to call each test *function*
individually from a ``wasm32`` entry point.

The obstacle is Rust privacy, not compilation.  Unit tests live in
``#[cfg(test)] mod tests { fn ... }``: both the module and the functions are
private, so nothing outside the defining module can name them.  A registry
built anywhere *else* in the crate therefore cannot reference them.

The fix used here is deliberately the boring one: emit a ``pub const``
**inside each test module**, where the private functions are in scope, and
aggregate those consts from the crate root.  No proc macro, no ``inventory``
link-section magic (which needs ``__wasm_call_ctors`` to actually fire on
``wasm32-unknown-unknown``), no build script.  The registry is plain Rust that
``grep`` can find and a reviewer can read.

What it does to the sources
---------------------------
For every eligible test module it rewrites the gate

    #[cfg(test)]
    mod tests {

into

    #[cfg(any(test, feature = "wasm-test-registry"))]
    #[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]
    pub(crate) mod tests {

It also rewrites ``#[test]`` to ``#[cfg_attr(test, test)]`` inside those
modules.  That second rewrite is not cosmetic: ``#[test]`` is a built-in macro
that *deletes* the function unless the crate is being compiled as a test
binary, so without it the registry would compile against functions that do not
exist.  Under a plain ``cargo test`` both rewrites collapse back to exactly
what was there before, so native behaviour is unchanged.

Usage
-----
    python3 scripts/gen_wasm_test_registry.py            # write
    python3 scripts/gen_wasm_test_registry.py --check    # CI drift gate

``--check`` is the gate: it regenerates into memory and fails if the committed
registry has drifted from the actual ``#[test]`` functions, so a test added to
an eligible module cannot silently stay out of the Worker tier.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CRATE = REPO_ROOT / "packages" / "temper-drc-rs"
SRC = CRATE / "src"

MARK = "generated by scripts/gen_wasm_test_registry.py"
BEGIN = f"// --- BEGIN {MARK}: {{ident}} ---"
END = f"// --- END {MARK}: {{ident}} ---"

GATE = '#[cfg(any(test, feature = "wasm-registry"))]'
# `dead_code` because in a non-test build the tests and their helpers are
# reachable only through the generated `WASM_TESTS` const, which rustc does
# not treat as a root for the `cdylib` compilation unit.
ALLOW = "#[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]"

# `#[test]` is a built-in macro that *erases* the function unless the crate is
# being compiled as a test binary, so a registry that merely made the module
# visible would still find nothing to call.  Rewriting to `#[cfg_attr(test,
# test)]` keeps the function in an ordinary build and leaves `cargo test`
# byte-for-byte identical in behaviour.
TEST_ATTR = "#[cfg_attr(test, test)]"

# (source file relative to src/, module ident).  Only modules that survive
# `--no-default-features` are listed: `router_clearance` and
# `violation_report` are `#[cfg(feature = "python")]` at the crate root, so
# their tests cannot exist in a `wasm32` build at all.
ELIGIBLE: list[tuple[str, str]] = [
    ("board.rs", "tests"),
    ("board.rs", "board_state_tests"),
    ("dfm.rs", "tests"),
    ("pyfmt.rs", "tests"),
    ("pymath.rs", "tests"),
    ("rules/mod.rs", "integration_tests"),
    ("rules/drc/clearance.rs", "tests"),
    ("rules/drc/property_campaigns.rs", "tests"),
    ("rules/drc/zone_containment.rs", "tests"),
    ("rules/emc/ground_plane.rs", "tests"),
    ("rules/emc/loop_area.rs", "tests"),
    ("rules/emc/noise_coupling.rs", "tests"),
    ("rules/erc/floating_pins.rs", "tests"),
    ("rules/erc/net_connectivity.rs", "tests"),
    ("rules/erc/power_domain.rs", "tests"),
    ("rules/safety/creepage.rs", "tests"),
    ("rules/safety/hv_lv_separation.rs", "tests"),
    ("rules/safety/isolation.rs", "tests"),
    ("rules/placement/thermal_constraint.rs", "tests"),
    ("rules/placement/thermal_via_count.rs", "tests"),
    ("rules/placement/wave_solder_keepout.rs", "tests"),
    ("rules/routing/power_pad_teardrop.rs", "tests"),
    ("types/clock.rs", "tests"),
    ("types/esd.rs", "tests"),
    ("types/fuse.rs", "tests"),
    ("types/guard.rs", "tests"),
    ("types/hv_net.rs", "tests"),
    ("types/magnetic.rs", "tests"),
    ("types/noise.rs", "tests"),
    ("types/vent.rs", "tests"),
    ("validation_kernels.rs", "tests"),
]

# Module → family classification for per-family WASM shards (Phase 1 U8).
# Modules under `rules/<family>/` map to that family; everything else is `infra`.
MODULE_FAMILY: dict[tuple[str, str], str] = {}
for _rel, _ident in ELIGIBLE:
    if _rel.startswith("rules/drc/"):
        MODULE_FAMILY[(_rel, _ident)] = "drc"
    elif _rel.startswith("rules/emc/"):
        MODULE_FAMILY[(_rel, _ident)] = "emc"
    elif _rel.startswith("rules/erc/"):
        MODULE_FAMILY[(_rel, _ident)] = "erc"
    elif _rel.startswith("rules/safety/"):
        MODULE_FAMILY[(_rel, _ident)] = "safety"
    elif _rel.startswith("rules/placement/"):
        MODULE_FAMILY[(_rel, _ident)] = "placement"
    elif _rel.startswith("rules/routing/"):
        MODULE_FAMILY[(_rel, _ident)] = "routing"
    elif _rel.startswith("rules/"):
        MODULE_FAMILY[(_rel, _ident)] = "infra"
    else:
        MODULE_FAMILY[(_rel, _ident)] = "infra"

FAMILIES = ["drc", "emc", "erc", "safety", "placement", "routing", "infra"]

TEST_FN = re.compile(r"^(\s*)#\[(?:test|cfg_attr\(test, test\))\]\s*$")
FN_NAME = re.compile(r"^\s*(?:pub\s+)?fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(")


def keep_test_fn(line: str) -> str:
    """``#[test]`` -> ``#[cfg_attr(test, test)]``, preserving indentation."""
    m = TEST_FN.match(line)
    return f"{m.group(1)}{TEST_ATTR}" if m else line


def module_path(rel: str) -> str:
    """``types/vent.rs`` -> ``types::vent``; ``rules/mod.rs`` -> ``rules``."""
    p = rel[: -len(".rs")]
    if p.endswith("/mod"):
        p = p[: -len("/mod")]
    return p.replace("/", "::")


# Direct (mod_path, ident) → family for the registry renderer.
FAMILY_BY_ENTRY: dict[tuple[str, str], str] = {
    (module_path(_rel), _ident): _fam for (_rel, _ident), _fam in MODULE_FAMILY.items()
}


def find_module_span(lines: list[str], ident: str) -> tuple[int, int, int]:
    """Locate ``mod <ident>`` and return ``(attr_start, decl_idx, body_end)``.

    ``body_end`` is the index of the closing brace line, or ``-1`` for a file
    module (``mod tests;``), whose body is a separate file.
    """
    decl = re.compile(
        rf"^\s*(?:pub(?:\([^)]*\))?\s+)?mod\s+{re.escape(ident)}\s*(\{{|;)\s*$"
    )
    for i, line in enumerate(lines):
        m = decl.match(line)
        if not m:
            continue
        # Walk backwards over the attribute block that gates this module.
        start = i
        while start > 0 and lines[start - 1].lstrip().startswith("#["):
            start -= 1
        if m.group(1) == ";":
            return start, i, -1
        depth = 0
        for j in range(i, len(lines)):
            depth += lines[j].count("{") - lines[j].count("}")
            if depth == 0:
                return start, i, j
        raise SystemExit(f"unbalanced braces for mod {ident}")
    raise SystemExit(f"could not find `mod {ident}`")


def collect_test_fns(lines: list[str]) -> list[str]:
    names = []
    for i, line in enumerate(lines):
        if not TEST_FN.match(line):
            continue
        for j in range(i + 1, min(i + 6, len(lines))):
            m = FN_NAME.match(lines[j])
            if m:
                names.append(m.group(1))
                break
            if not lines[j].lstrip().startswith("#["):
                break
    return names


def strip_generated(lines: list[str], ident: str) -> list[str]:
    """Drop only *this* module's generated block.

    Scoped by ident because one file can hold two test modules (`board.rs`),
    and a blanket strip would delete the sibling block on the second pass.
    """
    begin, end = BEGIN.format(ident=ident), END.format(ident=ident)
    out, skipping = [], False
    for line in lines:
        if line.strip() == begin:
            skipping = True
            continue
        if line.strip() == end:
            skipping = False
            continue
        if not skipping:
            out.append(line)
    return out


def generated_block(indent: str, mod_path: str, ident: str, fns: list[str]) -> list[str]:
    """The ``pub const`` that makes private ``#[test]`` fns reachable."""
    q = f"{mod_path}::{ident}"
    body = [
        f"{indent}{BEGIN.format(ident=ident)}",
        f"{indent}/// Every `#[test]` in this module, as a callable the `wasm32`",
        f"{indent}/// entry point can invoke by index.  Generated because these",
        f"{indent}/// functions are private to this module and unreachable from",
        f"{indent}/// anywhere a registry could otherwise live.",
        f"{indent}pub const WASM_TESTS: &[(&str, fn())] = &[",
    ]
    body += [f'{indent}    ("{q}::{fn}", {fn}),' for fn in fns]
    body += [f"{indent}];", f"{indent}{END.format(ident=ident)}"]
    return body


def render_root(entries: list[tuple[str, str, int]]) -> str:
    total = sum(n for _, _, n in entries)
    lines = [
        "//! The `wasm32` test registry for `temper-drc-rs`.",
        "//!",
        "//! Generated by `scripts/gen_wasm_test_registry.py`; run it after adding a",
        "//! test to any listed module, and `--check` gates drift in CI.",
        "//!",
        "//! `cargo test`'s libtest harness cannot target `wasm32-unknown-unknown`,",
        "//! so the Worker tier calls each test function individually instead of",
        "//! running a test binary.  This module is the flat, indexable list of them.",
        "//!",
        "//! Only modules that survive `--no-default-features` appear here.  Tests",
        "//! inside `#[cfg(feature = \"python\")]` modules are structurally absent",
        "//! from a `wasm32` build and are censused in the Phase 0 report instead.",
        "//!",
        "//! ## Per-family sharding (Phase 1 U8)",
        "//!",
        "//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`",
        "//! feature.  Building with only e.g. `--features wasm-registry-drc`",
        "//! includes only the DRC family's modules; with LTO, unreferenced test",
        "//! functions from other families are dead-stripped, producing a smaller",
        "//! `.wasm` module per Worker function.",
        "",
        "/// A single test: its fully qualified name and a nullary callable.",
        "///",
        "/// Failure is signalled by panicking, exactly as under libtest.  On",
        "/// `wasm32-unknown-unknown` a panic aborts (the target has no unwinding on",
        "/// stable), which surfaces to the host as a WebAssembly trap -- so the",
        "/// runner catches the trap rather than a `Result`.",
        "pub type WasmTest = (&'static str, fn());",
        "",
        f"/// All {total} eligible tests, in a stable order.  Each entry is",
        "/// gated on the per-family `wasm-registry-<family>` feature; enable",
        "/// all families (`wasm-test-registry`) or individual ones.",
        "pub const ALL: &[&[WasmTest]] = &[",
    ]
    for mod_path, ident, _ in entries:
        family = FAMILY_BY_ENTRY.get((mod_path, ident), "infra")
        lines.append(
            f"    #[cfg(feature = \"wasm-registry-{family}\")]"
            f" crate::{mod_path}::{ident}::WASM_TESTS,"
        )
    lines += [
        "];",
        "",
        "/// Total number of registered tests *in the currently-selected families*.",
        "pub fn count() -> usize {",
        "    ALL.iter().map(|m| m.len()).sum()",
        "}",
        "",
        "/// The test at `index` in the flattened registry.",
        "pub fn get(index: usize) -> Option<&'static WasmTest> {",
        "    let mut remaining = index;",
        "    for module in ALL {",
        "        if remaining < module.len() {",
        "            return Some(&module[remaining]);",
        "        }",
        "        remaining -= module.len();",
        "    }",
        "    None",
        "}",
        "",
    ]
    return "\n".join(lines)


def ancestor_decls(rel: str) -> list[tuple[str, str]]:
    """``(declaring file, module ident)`` for every ancestor module of ``rel``.

    `rules/drc/clearance.rs` is declared `mod clearance;` in `rules/drc/mod.rs`,
    which is `mod drc;` in `rules/mod.rs`, which is `mod rules;` in `lib.rs`.
    Each link has to be at least `pub(crate)` for the crate-root registry to
    name the test module at the end of the chain.
    """
    parts = rel[: -len(".rs")].split("/")
    if parts[-1] == "mod":
        parts.pop()
    out = []
    for i in range(len(parts) - 1, -1, -1):
        parent = "/".join(parts[:i])
        decl_file = f"{parent}/mod.rs" if parent else "lib.rs"
        out.append((decl_file, parts[i]))
    return out


def widen_mod_decl(text: str, ident: str) -> str:
    """Raise a private ``mod <ident>;`` to ``pub(crate)``; leave ``pub`` alone."""
    pattern = re.compile(rf"^(\s*)mod\s+{re.escape(ident)}\s*;\s*$", re.MULTILINE)
    return pattern.sub(rf"\g<1>pub(crate) mod {ident};", text)


def rewrite_module(text: str, rel: str, ident: str) -> tuple[str, str | None, list[str]]:
    """Gate + expose ``mod <ident>`` and append its generated registry block.

    Returns the new text for ``rel``, the new text for a file module's body
    file (or ``None`` for an inline module), and the test function names.
    """
    lines = strip_generated(text.splitlines(), ident)
    attr_start, decl_idx, body_end = find_module_span(lines, ident)
    indent = lines[decl_idx][: len(lines[decl_idx]) - len(lines[decl_idx].lstrip())]

    # Rewrite the gate, keeping any hand-written attributes other than the
    # `cfg(test)` being replaced and the allow re-added below.
    kept = [
        ln
        for ln in lines[attr_start:decl_idx]
        if "cfg(test)" not in ln
        and "wasm-test-registry" not in ln
        and "wasm-registry" not in ln
        and "clippy::unwrap_used" not in ln
        and "clippy::expect_used" not in ln
    ]
    header = [f"{indent}{GATE}", f"{indent}{ALLOW}"] + kept
    decl = lines[decl_idx]
    if not decl.lstrip().startswith(("pub ", "pub(")):
        decl = f"{indent}pub(crate) {decl.lstrip()}"

    if body_end == -1:
        # File module: the body lives in `<stem>/<ident>.rs`.
        body_path = SRC / rel[: -len(".rs")] / f"{ident}.rs"
        body_lines = strip_generated(body_path.read_text().splitlines(), ident)
        body_lines = [keep_test_fn(ln) for ln in body_lines]
        fns = collect_test_fns(body_lines)
        block = generated_block("", module_path(rel), ident, fns)
        while body_lines and not body_lines[-1].strip():
            body_lines.pop()
        body_text = "\n".join(body_lines + [""] + block) + "\n"
        new_lines = lines[:attr_start] + header + [decl] + lines[decl_idx + 1 :]
        return "\n".join(new_lines) + "\n", body_text, fns

    body = [keep_test_fn(ln) for ln in lines[decl_idx + 1 : body_end]]
    while body and not body[-1].strip():
        body.pop()  # keep regeneration idempotent
    fns = collect_test_fns(body)
    block = generated_block(indent + "    ", module_path(rel), ident, fns)
    new_lines = (
        lines[:attr_start]
        + header
        + [decl]
        + body
        + [""]
        + block
        + lines[body_end:]
    )
    return "\n".join(new_lines) + "\n", None, fns


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    args = ap.parse_args()

    pending: dict[Path, str] = {}
    entries: list[tuple[str, str, int]] = []

    for rel, ident in ELIGIBLE:
        path = SRC / rel
        # Read through `pending` so a file holding two test modules (board.rs)
        # accumulates both edits instead of the second discarding the first.
        text = pending.get(path) or path.read_text()
        new_text, body_text, fns = rewrite_module(text, rel, ident)
        pending[path] = new_text
        if body_text is not None:
            pending[SRC / rel[: -len(".rs")] / f"{ident}.rs"] = body_text
        entries.append((module_path(rel), ident, len(fns)))

        for decl_file, mod_ident in ancestor_decls(rel):
            decl_path = SRC / decl_file
            decl_text = pending.get(decl_path) or decl_path.read_text()
            pending[decl_path] = widen_mod_decl(decl_text, mod_ident)

    pending[SRC / "wasm_test_registry.rs"] = render_root(entries)

    drifted = []
    for path, text in pending.items():
        current = path.read_text() if path.exists() else None
        if current == text:
            continue
        drifted.append(path.relative_to(REPO_ROOT))
        if not args.check:
            path.write_text(text)

    total = sum(n for _, _, n in entries)
    if args.check:
        if drifted:
            print("wasm test registry is stale; run scripts/gen_wasm_test_registry.py")
            for p in drifted:
                print(f"  {p}")
            return 1
        print(f"wasm test registry up to date: {total} tests across {len(entries)} modules")
        return 0

    print(f"wrote registry: {total} tests across {len(entries)} modules")
    for p in drifted:
        print(f"  updated {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
