#!/usr/bin/env python3
"""Generate (and drift-check) a crate's ``wasm32`` test registry.

Why this exists
---------------
``cargo test``'s libtest harness cannot target ``wasm32-unknown-unknown``:
there is no process model, no threads, and no ``std::process::exit``.  So the
Worker tier cannot run ``cargo test`` -- it has to call each test *function*
individually from a ``wasm32`` entry point.

The obstacle is Rust privacy, not compilation.  Unit tests live in
``#[cfg(test)] mod tests { fn ... }``: both the module and the functions are
private, so nothing outside the defining module can name them.  A registry
built anywhere *else* in the crate therefore cannot reference them.

The fix used here is deliberately the boring one: emit a ``pub const``
**inside each test module**, where the private functions are in scope, and
aggregate those consts from the crate root.  No proc macro, no ``inventory``
link-section magic (which needs ``__wasm_call_ctors`` to actually fire on
``wasm32-unknown-unknown``), no build script.  The registry is plain Rust that
``grep`` can find and a reviewer can read.

What it does to the sources
---------------------------
For every eligible test module it rewrites the gate

    #[cfg(test)]
    mod tests {

into

    #[cfg(any(test, feature = "wasm-test-registry"))]
    #[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]
    pub(crate) mod tests {

It also rewrites ``#[test]`` to ``#[cfg_attr(test, test)]`` inside those
modules.  That second rewrite is not cosmetic: ``#[test]`` is a built-in macro
that *deletes* the function unless the crate is being compiled as a test
binary, so without it the registry would compile against functions that do not
exist.  Under a plain ``cargo test`` both rewrites collapse back to exactly
what was there before, so native behaviour is unchanged.

Which crates this covers
------------------------
One registry per crate, selected with ``--crate``.  ``temper-drc-rs`` was
first; ``temper-geometry`` followed once the same enabling work was done for
it.  The two differ only in how their eligible module list is decided:

* ``temper-drc-rs`` names its modules explicitly (``ELIGIBLE_DRC_RS``), which
  is what it has always done and what its committed registry was generated
  from.
* ``temper-geometry`` *discovers* them (:func:`discover_eligible`) and applies
  exclusion **predicates** with named reasons.  A hand-maintained list silently
  omits a newly added test module -- the drift gate only compares the registry
  against the list, so a module missing from the list is invisible to it.
  Discovery closes that hole: a new ``#[cfg(test)] mod`` in an eligible file
  makes ``--check`` fail until the registry is regenerated.

Usage
-----
    python3 scripts/gen_wasm_test_registry.py                          # write
    python3 scripts/gen_wasm_test_registry.py --check                  # CI gate
    python3 scripts/gen_wasm_test_registry.py --crate temper-geometry
    python3 scripts/gen_wasm_test_registry.py --census                 # explain

The gate has two arms, and it took a real escape to learn that one was not
enough:

1. **Drift.**  Regenerate into memory and fail if the committed registry has
   drifted from the actual ``#[test]`` functions, so a test added to a *listed*
   module cannot silently stay out of the Worker tier.
2. **Unregistered modules** (:func:`check_unregistered`).  Arm 1 iterates the
   list, so a whole module *missing* from the list is not drift to it -- it is
   invisible.  ``src/ipc.rs`` landed with the ``temper-ipc`` crate-fold on
   2026-08-09 and its eleven IPC-2221/2152 kernel tests sat outside the tier
   while ``--check`` reported green.  Arm 2 starts from the source: every
   ``#[cfg(test)]`` module holding ``#[test]`` functions must either be
   registered or carry a stated structural reason.

The gate is per-crate: run it once for each crate that has a registry.
``scripts/regen_derived.py`` does exactly that.

``--census`` prints every ``#[cfg(test)]`` module the crate has, registered or
not, with the reason for each exclusion.  Use it to check that an exclusion is
structural rather than convenient.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

MARK = "generated by scripts/gen_wasm_test_registry.py"
BEGIN = f"// --- BEGIN {MARK}: {{ident}} ---"
END = f"// --- END {MARK}: {{ident}} ---"

TEST_GATE = "#[cfg(test)]"
GATE = '#[cfg(any(test, feature = "wasm-registry"))]'
# `dead_code` because in a non-test build the tests and their helpers are
# reachable only through the generated `WASM_TESTS` const, which rustc does
# not treat as a root for the `cdylib` compilation unit.
ALLOW = "#[allow(dead_code, unused_imports, clippy::unwrap_used, clippy::expect_used)]"

# `#[test]` is a built-in macro that *erases* the function unless the crate is
# being compiled as a test binary, so a registry that merely made the module
# visible would still find nothing to call.  Rewriting to `#[cfg_attr(test,
# test)]` keeps the function in an ordinary build and leaves `cargo test`
# byte-for-byte identical in behaviour.
TEST_ATTR = "#[cfg_attr(test, test)]"

# (source file relative to src/, module ident).  Only modules that survive
# `--no-default-features` are listed: `router_clearance` and
# `violation_report` are `#[cfg(feature = "python")]` at the crate root, so
# their tests cannot exist in a `wasm32` build at all.
ELIGIBLE_DRC_RS: list[tuple[str, str]] = [
    ("board.rs", "tests"),
    ("board.rs", "board_state_tests"),
    ("dfm.rs", "tests"),
    # Added 2026-08-10.  `src/ipc.rs` arrived with the `temper-ipc` crate-fold
    # (840543e4) and was never added here, so the IPC-2221/2152 current-capacity
    # and trace-width kernels -- safety-relevant on this board -- had never run
    # on the tier.  Nothing reported it: the drift gate only compared this list
    # against the registry, and a module *missing from the list* is not drift.
    # `check_unregistered` (below) is the arm that closes that hole.
    ("ipc.rs", "tests"),
    ("pyfmt.rs", "tests"),
    ("pymath.rs", "tests"),
    ("rules/mod.rs", "integration_tests"),
    ("rules/drc/clearance.rs", "tests"),
    ("rules/drc/property_campaigns.rs", "tests"),
    ("rules/drc/zone_containment.rs", "tests"),
    ("rules/emc/ground_plane.rs", "tests"),
    ("rules/emc/loop_area.rs", "tests"),
    ("rules/emc/noise_coupling.rs", "tests"),
    ("rules/erc/floating_pins.rs", "tests"),
    ("rules/erc/net_connectivity.rs", "tests"),
    ("rules/erc/power_domain.rs", "tests"),
    ("rules/safety/creepage.rs", "tests"),
    ("rules/safety/hv_lv_separation.rs", "tests"),
    ("rules/safety/isolation.rs", "tests"),
    ("rules/placement/thermal_constraint.rs", "tests"),
    ("rules/placement/thermal_via_count.rs", "tests"),
    ("rules/placement/wave_solder_keepout.rs", "tests"),
    ("rules/routing/isolation_barrier.rs", "tests"),
    ("rules/routing/power_pad_teardrop.rs", "tests"),
    ("types/clock.rs", "tests"),
    ("types/esd.rs", "tests"),
    ("types/fuse.rs", "tests"),
    ("types/guard.rs", "tests"),
    ("types/hv_net.rs", "tests"),
    ("types/magnetic.rs", "tests"),
    ("types/noise.rs", "tests"),
    ("types/vent.rs", "tests"),
    ("validation_kernels.rs", "tests"),
]

def drc_rs_family(rel: str) -> str:
    """Family for a `temper-drc-rs` module (per-family WASM shards, Phase 1 U8).

    Modules under `rules/<family>/` map to that family; everything else is
    `infra`.
    """
    for family in ("drc", "emc", "erc", "safety", "placement", "routing"):
        if rel.startswith(f"rules/{family}/"):
            return family
    return "infra"


DRC_RS_FAMILIES = ["drc", "emc", "erc", "safety", "placement", "routing", "infra"]

# `temper-geometry` is a flat crate of independent kernels with no rule-family
# taxonomy to shard along, so it declares a single family.  The renderer keeps
# emitting per-family `#[cfg]` guards either way; the degenerate one-family map
# means one code path, and a real split can be introduced later (when there is
# a deployment reason for it) without touching the renderer.
GEOMETRY_FAMILIES = ["geometry"]

# `temper-thermal` is the same shape as `temper-geometry`: a flat set of
# physics kernels with no rule-family taxonomy, so one family.
THERMAL_FAMILIES = ["thermal"]

# The three crates registered on 2026-08-10 are all the same shape again --
# flat sets of kernels with no rule-family taxonomy -- so each declares one
# family named after the crate.  Keeping the degenerate one-family map means
# one renderer code path for every crate, and a size-driven split stays
# available without touching the renderer.
DESIGN_BUNDLE_FAMILIES = ["design-bundle"]
ROUTER_CORE_FAMILIES = ["router-core"]
CONSTRAINT_COMPILER_FAMILIES = ["constraint-compiler"]
QUALITY_ORACLE_FAMILIES = ["quality-oracle"]
IO_TYPES_FAMILIES = ["io-types"]

TEST_FN = re.compile(r"^(\s*)#\[(?:test|cfg_attr\(test, test\))\]\s*$")

# A *use* of the `proptest` dev-dependency: the `proptest!` macro or a
# `proptest::` path.  Deliberately not a bare substring search -- a module that
# merely says the word in a comment ("--- proptest: structural properties ---",
# or a note explaining why a nested module is gated) does not depend on the
# crate, and excluding it on that basis would drop real tests from the tier for
# a spelling.
PROPTEST_USE = re.compile(r"(?:^|[^A-Za-z0-9_])proptest\s*(?:!|::)")
FN_NAME = re.compile(r"^\s*(?:pub\s+)?fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(")


def keep_test_fn(line: str) -> str:
    """``#[test]`` -> ``#[cfg_attr(test, test)]``, preserving indentation."""
    m = TEST_FN.match(line)
    return f"{m.group(1)}{TEST_ATTR}" if m else line


def module_path(rel: str) -> str:
    """``types/vent.rs`` -> ``types::vent``; ``rules/mod.rs`` -> ``rules``."""
    p = rel[: -len(".rs")]
    if p.endswith("/mod"):
        p = p[: -len("/mod")]
    return p.replace("/", "::")


MOD_DECL = re.compile(
    r"^\s*(?:pub(?:\([^)]*\))?\s+)?mod\s+([A-Za-z_][A-Za-z0-9_]*)\s*(\{|;)\s*$"
)


def attr_block(lines: list[str], decl_idx: int) -> list[str]:
    """The ``#[...]`` lines immediately above ``decl_idx``.

    Immediately above is the operative word: this mirrors
    :func:`find_module_span`, which stops at the first non-attribute line.  A
    comment between an attribute and the ``mod`` therefore ends the block for
    both, so classification and rewriting always agree on what gates a module.
    """
    start = decl_idx
    while start > 0 and lines[start - 1].lstrip().startswith("#["):
        start -= 1
    return [ln.strip() for ln in lines[start:decl_idx]]


def is_test_gate(attr: str) -> bool:
    """Does ``attr`` gate a module on the test configuration?

    Both spellings count: the hand-written ``#[cfg(test)]`` and the ``GATE``
    this script rewrites it into.  Recognising the rewritten form is what makes
    regeneration idempotent -- otherwise the second run would see no test
    modules at all and emit an empty registry.
    """
    return attr.strip() in (TEST_GATE, GATE)


def looks_test_gated(lines: list[str], decl_idx: int) -> bool:
    """Is there a test gate above ``decl_idx``, comments notwithstanding?

    Deliberately more permissive than :func:`attr_block`: it scans back over
    comments and blank lines too, so a test module whose gate the rewriter
    *cannot* reach is still seen by discovery and reported rather than dropped.
    """
    i = decl_idx - 1
    while i >= 0 and (
        lines[i].lstrip().startswith(("#[", "//")) or not lines[i].strip()
    ):
        if is_test_gate(lines[i]):
            return True
        i -= 1
    return False


def nested_gated_mask(body: list[str]) -> list[bool]:
    """Which lines of ``body`` belong to a *nested* test-gated submodule.

    A test module can hold another test module::

        #[cfg(test)]
        mod tests {
            #[test] fn a() {}

            #[cfg(test)]
            mod proptests { proptest! { #[test] fn p(..) {} } }
        }

    The inner module is its own census entry (:func:`discover_eligible` finds
    it in the same sweep, because it carries its own gate), so its tests are
    *not* the outer module's.  Without this mask the outer module would both
    inherit the inner one's ``proptest`` exclusion and emit registry entries
    naming functions that are not in its scope -- neither of which compiles or
    counts correctly.

    Only submodules carrying their own gate are masked.  An ungated helper
    ``mod`` inside a test module is not a separate entry, so it stays part of
    its parent exactly as before -- which is why this cannot change what
    ``temper-drc-rs`` or ``temper-geometry`` already generate.

    Caveat, shared with :func:`attr_block`: an attribute is recognised only
    when it is written on ONE line.  Splitting ``#[allow(a, b, c)]`` across
    lines hides the gate from the scan, and the nested module's tests get
    attributed to its parent -- which does not compile (the parent cannot name
    them), so the failure is loud rather than silent, but keep such attributes
    on one line.
    """
    mask = [False] * len(body)
    i = 0
    while i < len(body):
        m = MOD_DECL.match(body[i])
        if m and m.group(2) == "{" and any(
            is_test_gate(a) for a in attr_block(body, i)
        ):
            depth = 0
            end = len(body) - 1
            for j in range(i, len(body)):
                depth += body[j].count("{") - body[j].count("}")
                mask[j] = True
                if depth == 0:
                    end = j
                    break
            i = end + 1
        else:
            i += 1
    return mask


def own_lines(body: list[str]) -> list[str]:
    """``body`` with every nested test-gated submodule removed."""
    return [ln for ln, hidden in zip(body, nested_gated_mask(body)) if not hidden]


def module_body(lines: list[str], decl_idx: int) -> list[str]:
    """The brace-balanced body of the inline module declared at ``decl_idx``."""
    depth = 0
    for j in range(decl_idx, len(lines)):
        depth += lines[j].count("{") - lines[j].count("}")
        if depth == 0:
            return lines[decl_idx : j + 1]
    raise SystemExit(f"unbalanced braces at line {decl_idx + 1}")


def submodule_path(src: Path, rel: str, ident: str) -> Path:
    """Where the body of a file module ``mod <ident>;`` declared in ``rel`` lives.

    Rust resolves this against the *directory* the declaring file owns, and a
    "mod-rs" file (``lib.rs``, ``foo/mod.rs``) owns the directory it sits in
    while a plain ``foo.rs`` owns ``foo/``.  Getting that wrong is silent: the
    body file simply is not found, the module is censused as having no tests,
    and real tests drop off the tier without a word.  That is exactly what
    happened to ``temper-rust-router-core``'s ``combinator/mod.rs``, whose
    ``#[cfg(test)] mod integration;`` body is ``combinator/integration.rs``,
    not ``combinator/mod/integration.rs``.
    """
    stem = rel[: -len(".rs")]
    if stem in ("lib", "main"):
        parent = ""
    elif stem.endswith("/mod"):
        parent = stem[: -len("/mod")]
    else:
        parent = stem
    return src / parent / f"{ident}.rs"


def feature_gated_modules(src: Path, features: tuple[str, ...]) -> dict[str, str]:
    """Top-level module idents gated on a feature absent from the wasm32 build.

    ``{ident: feature}``.  Their whole file is absent from a
    ``--no-default-features`` build, so every test inside is structurally
    unreachable on ``wasm32`` -- not skipped, not failing: not compiled.

    ``python`` is the usual one (pyo3 does not cross-compile to
    ``wasm32-unknown-unknown``), but it is not the only one: the
    ``temper-rust-router-core`` modules behind ``sat`` need ``rustsat-cadical``,
    a C++ solver that has no ``wasm32-unknown-unknown`` build either.  Which
    features are absent is therefore per-crate (``CrateSpec.absent_features``)
    rather than the single hard-coded ``python`` this used to assume.
    """
    lines = (src / "lib.rs").read_text().splitlines()
    gated: dict[str, str] = {}
    for i, line in enumerate(lines):
        m = MOD_DECL.match(line)
        if not m:
            continue
        attrs = attr_block(lines, i)
        for feature in features:
            if any(f'feature = "{feature}"' in a for a in attrs):
                gated[m.group(1)] = feature
                break
    return gated


@dataclass
class Discovered:
    """One ``#[cfg(test)]`` module found by the census."""

    rel: str
    ident: str
    tests: int
    excluded: str | None  # None = eligible; otherwise the reason


def discover_eligible(
    src: Path, absent_features: tuple[str, ...] = ("python",)
) -> list[Discovered]:
    """Every ``#[cfg(test)]`` module under ``src``, each with its verdict.

    Exclusions are *predicates with reasons*, never a hand-kept deny-list, so
    a module that becomes eligible (say, its ``python`` gate is lifted) is
    picked up automatically instead of staying silently out of the tier.
    """
    gated = feature_gated_modules(src, absent_features)
    out: list[Discovered] = []
    for path in sorted(src.rglob("*.rs")):
        rel = str(path.relative_to(src))
        lines = path.read_text().splitlines()
        for i, line in enumerate(lines):
            m = MOD_DECL.match(line)
            if not m or not looks_test_gated(lines, i):
                continue
            ident, inline = m.group(1), m.group(2) == "{"
            if inline:
                body = module_body(lines, i)
            else:
                # File module (`mod tests;`): the body is a separate file.
                body_path = submodule_path(src, rel, ident)
                body = body_path.read_text().splitlines() if body_path.exists() else []
            # A nested test-gated submodule is its own entry in this same
            # sweep, so its tests (and its dev-dependency imports) belong to
            # it, not to the module lexically containing it.
            body = own_lines(body)
            tests = sum(1 for ln in body if TEST_FN.match(ln))
            attrs = attr_block(lines, i)

            reason: str | None = None
            own_gate = next(
                (f for f in absent_features if any(f'feature = "{f}"' in a for a in attrs)),
                None,
            )
            file_gate = gated.get(rel[: -len(".rs")])
            if own_gate or file_gate:
                # The module does not exist in a wasm32 build at all.
                reason = f"{own_gate or file_gate}-gated"
            elif any(PROPTEST_USE.search(ln.split("//")[0]) for ln in body):
                # `proptest` is a dev-dependency: present under `cargo test`,
                # absent from the ordinary (non-test) build the registry is
                # compiled into.  Same exclusion `temper-drc-rs` makes by
                # leaving its own `proptests` modules out of ELIGIBLE_DRC_RS.
                reason = "proptest-dev-dependency"
            elif not any(is_test_gate(a) for a in attrs):
                # `looks_test_gated` saw a gate the rewriter cannot reach --
                # a comment sits between `#[cfg(test)]` and `mod`.  Report it
                # rather than dropping the module on the floor.
                reason = "gate-not-adjacent-to-mod"
            elif tests == 0:
                reason = "no-test-functions"

            out.append(Discovered(rel, ident, tests, reason))
    return out


@dataclass
class CrateSpec:
    """Everything the generator needs to know about one crate."""

    name: str
    # Explicit module list, or None to discover them.
    eligible: list[tuple[str, str]] | None
    families: list[str]
    family_of: object  # Callable[[str], str]
    # Cargo features whose modules cannot exist in the `--no-default-features`
    # wasm32 build.  `python` always qualifies (pyo3 does not cross-compile);
    # a crate whose non-default surface needs a native-only dependency adds it
    # here so those modules are excluded *with a stated reason* rather than
    # registered into a build that cannot compile them.
    absent_features: tuple[str, ...] = ("python",)
    # Tail of the "tests inside python-gated modules are absent" sentence.
    census_note: str = "are censused in the Phase 0 report instead"
    # The sharding section of the registry's module docstring.
    sharding_note: list[str] = field(
        default_factory=lambda: [
            "//! ## Per-family sharding (Phase 1 U8)",
            "//!",
            "//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`",
            "//! feature.  Building with only e.g. `--features wasm-registry-drc`",
            "//! includes only the DRC family's modules; with LTO, unreferenced test",
            "//! functions from other families are dead-stripped, producing a smaller",
            "//! `.wasm` module per Worker function.",
        ]
    )
    # Crate-specific paragraphs inserted before the sharding section.
    extra_notes: list[str] = field(default_factory=list)
    # `(declaring file, module ident)` for *test-support* modules: `#[cfg(test)]`
    # modules that hold no `#[test]` of their own but whose helpers registered
    # test modules call (`temper-quality-oracle`'s `tests_common`, shared by
    # `oracle::tests` and `thresholds::tests`).  They get the same gate widening
    # and visibility raise a registered module gets, and nothing else -- they
    # contribute no registry entries, so the census still calls them
    # `no-test-functions`.  Omitting one that is needed does not fail silently:
    # the `wasm-registry` build cannot resolve `crate::tests_common` and stops.
    test_support: list[tuple[str, str]] = field(default_factory=list)


CRATES: dict[str, CrateSpec] = {
    "temper-drc-rs": CrateSpec(
        name="temper-drc-rs",
        eligible=ELIGIBLE_DRC_RS,
        families=DRC_RS_FAMILIES,
        family_of=drc_rs_family,
    ),
    "temper-geometry": CrateSpec(
        name="temper-geometry",
        eligible=None,  # discovered
        families=GEOMETRY_FAMILIES,
        family_of=lambda _rel: "geometry",
        census_note="cannot be registered here at all",
        sharding_note=[
            "//! ## Families",
            "//!",
            "//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`",
            "//! feature, as in `temper-drc-rs`.  This crate is a flat set of",
            "//! independent kernels with no rule-family taxonomy, so it declares a",
            "//! single family (`geometry`) rather than inventing one; the mechanism",
            "//! is in place if a size-driven split is ever wanted.",
        ],
        extra_notes=[
            "//! Two exclusion classes apply here, both structural:",
            "//!",
            '//! * `#[cfg(feature = "python")]` modules (`escape_via`, `zone_pour`,',
            "//!   `geometry_kernels`, `congestion_tensor`, `fixed_copper`,",
            "//!   `area_sufficiency`, `occupancy_raster`) do not exist in a",
            "//!   `--no-default-features` build, so neither do their tests.",
            "//! * `proptest` modules use a dev-dependency, which is not linked into",
            "//!   the ordinary (non-test) build this registry compiles into.  The",
            "//!   same exclusion `temper-drc-rs` makes for its own `proptests`",
            "//!   modules.",
            "//!",
            "//! `scripts/gen_wasm_test_registry.py --crate temper-geometry --census`",
            "//! prints the full module census with per-module counts.",
            "//!",
            "//! A `#[should_panic]` test panics by design, and on this target a panic",
            "//! aborts into a trap -- indistinguishable over the C ABI from a genuine",
            "//! failure.  Those tests stay registered and are listed in",
            "//! `tools/wasm/wasm_expected_failures_geometry.json`, whose gate is",
            "//! bidirectional: one that stops panicking is reported, not ignored.",
        ],
    ),
    "temper-thermal": CrateSpec(
        name="temper-thermal",
        eligible=None,  # discovered, same as temper-geometry
        families=THERMAL_FAMILIES,
        family_of=lambda _rel: "thermal",
        census_note="cannot be registered here at all",
        sharding_note=[
            "//! ## Families",
            "//!",
            "//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`",
            "//! feature, as in `temper-drc-rs`.  This crate is a flat set of",
            "//! physics kernels with no rule-family taxonomy, so it declares a",
            "//! single family (`thermal`); the mechanism is in place if a",
            "//! size-driven split is ever wanted.",
        ],
        extra_notes=[
            "//! Two exclusion classes apply here, both structural:",
            "//!",
            '//! * `#[cfg(feature = "python")]` modules -- `solve`, whose sparse-LU',
            "//!   kernel and its pyo3 bridge are one surface and which carries the",
            "//!   `faer` dependency, so neither exists in a",
            "//!   `--no-default-features` build.",
            "//! * `proptest` modules use a dev-dependency, which is not linked into",
            "//!   the ordinary (non-test) build this registry compiles into.  Unlike",
            "//!   `temper-geometry`, this crate nests them *inside* its `tests`",
            "//!   modules; each carries its own `#[cfg(test)]` and is censused",
            "//!   separately, so nesting costs the enclosing module nothing.",
            "//!",
            "//! `scripts/gen_wasm_test_registry.py --crate temper-thermal --census`",
            "//! prints the full module census with per-module counts.",
        ],
    ),
    "temper-design-bundle": CrateSpec(
        name="temper-design-bundle",
        eligible=None,  # discovered
        families=DESIGN_BUNDLE_FAMILIES,
        family_of=lambda _rel: "design-bundle",
        census_note="cannot be registered here at all",
        sharding_note=[
            "//! ## Families",
            "//!",
            "//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`",
            "//! feature, as in `temper-drc-rs`.  This crate declares a single",
            "//! family (`design-bundle`): what survives `--no-default-features`",
            "//! is a flat set of parsers and validators with no taxonomy to shard",
            "//! along.",
        ],
        extra_notes=[
            "//! Two exclusion classes apply here, both structural:",
            "//!",
            '//! * `#[cfg(feature = "python")]` modules.  This crate is mostly a',
            "//!   pyo3 boundary -- the great majority of its modules are declared",
            "//!   under that gate in `lib.rs` -- so most of its `#[test]` functions",
            "//!   do not exist in a `--no-default-features` build.  They are not",
            "//!   skipped on `wasm32`: they are not compiled, exactly as they are",
            "//!   not compiled by the crate's own default-feature `cargo test`.",
            "//! * `proptest` modules use a dev-dependency, which is not linked into",
            "//!   the ordinary (non-test) build this registry compiles into.",
            "//!",
            "//! `scripts/gen_wasm_test_registry.py --crate temper-design-bundle",
            "//! --census` prints the full module census with per-module counts.",
        ],
    ),
    "temper-rust-router-core": CrateSpec(
        name="temper-rust-router-core",
        eligible=None,  # discovered
        families=ROUTER_CORE_FAMILIES,
        family_of=lambda _rel: "router-core",
        # `sat` joins `python` here: the modules behind it need
        # `rustsat-cadical`, a C++ SAT solver with no wasm32-unknown-unknown
        # build, so `--no-default-features` is the only configuration that
        # cross-compiles and those modules are absent from it.
        absent_features=("python", "sat"),
        census_note="cannot be registered here at all",
        sharding_note=[
            "//! ## Families",
            "//!",
            "//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`",
            "//! feature, as in `temper-drc-rs`.  One family (`router-core`): the",
            "//! solver-free core is a flat set of graph and rewrite kernels.",
        ],
        extra_notes=[
            "//! Three exclusion classes apply here, all structural:",
            "//!",
            '//! * `#[cfg(feature = "sat")]` modules -- `solver`, `bmc`,',
            "//!   `equivalence`, `watchdog`.  `sat` is a *default* feature, but it",
            "//!   pulls `rustsat-cadical`, a C++ solver with no",
            "//!   `wasm32-unknown-unknown` build, so those modules cannot exist on",
            "//!   this target at all.  This is the first crate on the tier whose",
            "//!   absent feature is not `python`.",
            '//! * `#[cfg(feature = "python")]` modules, as elsewhere on the tier.',
            "//! * `proptest` modules use a dev-dependency, which is not linked into",
            "//!   the ordinary (non-test) build this registry compiles into.",
            "//!",
            "//! `scripts/gen_wasm_test_registry.py --crate temper-rust-router-core",
            "//! --census` prints the full module census with per-module counts.",
        ],
    ),
    "temper-constraint-compiler": CrateSpec(
        name="temper-constraint-compiler",
        eligible=None,  # discovered
        families=CONSTRAINT_COMPILER_FAMILIES,
        family_of=lambda _rel: "constraint-compiler",
        # `sat` here only forwards to `temper-rust-router-core/sat`, and this
        # crate declares no module behind it, but naming it keeps the two
        # crates' verdicts consistent if one ever appears.
        absent_features=("python", "sat"),
        census_note="cannot be registered here at all",
        sharding_note=[
            "//! ## Families",
            "//!",
            "//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`",
            "//! feature, as in `temper-drc-rs`.  One family",
            "//! (`constraint-compiler`): the lowering tiers are a flat pipeline",
            "//! with no taxonomy to shard along.",
        ],
        extra_notes=[
            "//! Two exclusion classes apply here, both structural:",
            "//!",
            '//! * `#[cfg(feature = "python")]` modules -- `pcl_contracts` and',
            "//!   `pyo3_bridge`, plus `constraints::py`, which are the pyo3",
            "//!   boundary and do not exist in a `--no-default-features` build.",
            "//! * `proptest` modules use a dev-dependency, which is not linked into",
            "//!   the ordinary (non-test) build this registry compiles into.",
            "//!",
            "//! `scripts/gen_wasm_test_registry.py --crate temper-constraint-compiler",
            "//! --census` prints the full module census with per-module counts.",
        ],
    ),
    "temper-quality-oracle": CrateSpec(
        name="temper-quality-oracle",
        eligible=None,  # discovered
        families=QUALITY_ORACLE_FAMILIES,
        family_of=lambda _rel: "quality-oracle",
        census_note="cannot be registered here at all",
        # `tests_common` is `#[cfg(test)] #[path = "tests_common.rs"] mod` at the
        # crate root and holds no test of its own -- only the shared
        # `empty_spec` / `empty_placement` / `dummy_metrics` / `valid_metrics`
        # constructors that `oracle::tests` and `thresholds::tests` call.  It is
        # the first shared test-support module on the tier, so it is the first
        # entry this field has ever had.
        test_support=[("lib.rs", "tests_common")],
        sharding_note=[
            "//! ## Families",
            "//!",
            "//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`",
            "//! feature, as in `temper-drc-rs`.  One family (`quality-oracle`):",
            "//! the six-layer pipeline is a flat sequence of pure scoring",
            "//! kernels with no rule-family taxonomy to shard along.",
        ],
        extra_notes=[
            "//! Two exclusion classes apply here, both structural:",
            "//!",
            '//! * `#[cfg(feature = "python")]` modules -- `cluster_f::bindings`,',
            "//!   the pyo3 boundary for the cluster-F quality metrics, which does",
            "//!   not exist in a `--no-default-features` build.",
            "//! * `proptest` modules use a dev-dependency, which is not linked into",
            "//!   the ordinary (non-test) build this registry compiles into.",
            "//!",
            "//! One module is *not* an exclusion class but is worth naming:",
            "//! `tests_common` is a `#[cfg(test)]` module with no `#[test]` of its",
            "//! own, holding fixture constructors that two registered modules call.",
            "//! Its gate is widened alongside theirs (`CrateSpec.test_support`) so",
            "//! the registry build can see it; it contributes no entries.",
            "//!",
            "//! `scripts/gen_wasm_test_registry.py --crate temper-quality-oracle",
            "//! --census` prints the full module census with per-module counts.",
        ],
    ),
    "temper-io-types": CrateSpec(
        name="temper-io-types",
        eligible=None,  # discovered
        families=IO_TYPES_FAMILIES,
        family_of=lambda _rel: "io-types",
        census_note="cannot be registered here at all",
        sharding_note=[
            "//! ## Families",
            "//!",
            "//! Each module entry in `ALL` is gated on a `wasm-registry-<family>`",
            "//! feature, as in `temper-drc-rs`.  One family (`io-types`): what",
            "//! survives `--no-default-features` is a flat set of KiCad/DSN",
            "//! serialisers, parsers and placer CONTRACT kernels with no",
            "//! taxonomy to shard along.",
        ],
        extra_notes=[
            "//! Two exclusion classes apply here, both structural:",
            "//!",
            '//! * `#[cfg(feature = "python")]` modules -- `explain`, `report`,',
            "//!   `reference_aliases`, `footprint_library`, `dsn_pyo3` and",
            "//!   `zone_filler`.  Each is a *whole* pyo3 surface: its entry",
            "//!   points take and return `Bound<'_, PyAny>` and read Python",
            "//!   runtime semantics (`str()`, `yaml.safe_load`, `str.strip`)",
            "//!   back across the boundary, so there is no kernel underneath to",
            "//!   compile without pyo3.  Their tests are not skipped on",
            "//!   `wasm32`: they are not compiled.",
            "//! * `proptest` modules use a dev-dependency, which is not linked into",
            "//!   the ordinary (non-test) build this registry compiles into.",
            "//!",
            "//! `scripts/gen_wasm_test_registry.py --crate temper-io-types",
            "//! --census` prints the full module census with per-module counts.",
        ],
    ),
}


def select_crate(name: str) -> CrateSpec:
    """Point the module-level globals at ``name``'s crate.

    Globals rather than threaded parameters because
    ``tools/wasm/gen_test_family_map.py`` imports ``ELIGIBLE``, ``SRC`` and
    ``module_path`` from this module.  They keep meaning `temper-drc-rs` unless
    something calls this, so that importer is unaffected.
    """
    global CRATE_SPEC, CRATE, SRC, ELIGIBLE, FAMILIES, FAMILY_BY_ENTRY
    spec = CRATES[name]
    CRATE_SPEC = spec
    CRATE = REPO_ROOT / "packages" / name
    SRC = CRATE / "src"
    if spec.eligible is not None:
        ELIGIBLE = list(spec.eligible)
    else:
        ELIGIBLE = [
            (d.rel, d.ident)
            for d in discover_eligible(SRC, spec.absent_features)
            if not d.excluded
        ]
    FAMILIES = spec.families
    FAMILY_BY_ENTRY = {
        (module_path(rel), ident): spec.family_of(rel) for rel, ident in ELIGIBLE
    }
    return spec


# Default so importers (`tools/wasm/gen_test_family_map.py`) see the same
# `ELIGIBLE` / `SRC` they always did.
CRATE_SPEC = select_crate("temper-drc-rs")


def find_module_span(lines: list[str], ident: str) -> tuple[int, int, int]:
    """Locate ``mod <ident>`` and return ``(attr_start, decl_idx, body_end)``.

    ``body_end`` is the index of the closing brace line, or ``-1`` for a file
    module (``mod tests;``), whose body is a separate file.
    """
    decl = re.compile(
        rf"^\s*(?:pub(?:\([^)]*\))?\s+)?mod\s+{re.escape(ident)}\s*(\{{|;)\s*$"
    )
    for i, line in enumerate(lines):
        m = decl.match(line)
        if not m:
            continue
        # Walk backwards over the attribute block that gates this module.
        start = i
        while start > 0 and lines[start - 1].lstrip().startswith("#["):
            start -= 1
        if m.group(1) == ";":
            return start, i, -1
        depth = 0
        for j in range(i, len(lines)):
            depth += lines[j].count("{") - lines[j].count("}")
            if depth == 0:
                return start, i, j
        raise SystemExit(f"unbalanced braces for mod {ident}")
    raise SystemExit(f"could not find `mod {ident}`")


def fn_cfgs(lines: list[str], test_attr_idx: int) -> list[str]:
    """``#[cfg(...)]`` attributes attached to the test fn at ``test_attr_idx``.

    A test function can carry its own configuration gate --
    ``#[cfg(not(target_arch = "wasm32"))]`` on a test that asserts a native-host
    property, for instance.  The function then does not exist in a ``wasm32``
    build, so a registry entry naming it does not compile.  Collecting the gates
    here lets :func:`generated_block` repeat them on the entry, which keeps the
    registry exactly as configured as the functions it points at.

    Only the contiguous attribute/doc-comment block above the ``#[test]`` is
    scanned, so this cannot pick up an attribute belonging to a previous item.
    """
    cfgs = []
    i = test_attr_idx - 1
    while i >= 0:
        stripped = lines[i].strip()
        if stripped.startswith("#["):
            if stripped.startswith("#[cfg("):
                cfgs.append(stripped)
        elif not stripped.startswith("//"):
            break
        i -= 1
    return list(reversed(cfgs))


def collect_test_fns(lines: list[str]) -> list[tuple[str, list[str]]]:
    """``(fn name, its own #[cfg] attributes)`` for every test in ``lines``.

    The walk from ``#[test]`` down to its ``fn`` has to step over the
    attributes in between, and an attribute is not necessarily one line.
    ``temper-io-types``'s ``dag_expr::depth_boundary`` writes::

        #[cfg_attr(test, test)]
        #[allow(
            clippy::expect_used,
            reason = "..."
        )]
        fn rejects_the_first_frame_past_the_ceiling() {

    An earlier version scanned a fixed five-line window and stopped at the
    first line not *starting* with ``#[``, so the continuation line
    ``clippy::expect_used,`` ended the walk and the function was dropped from
    the registry — silently, because the drift arm regenerates through this
    same function and so agrees with itself.  ``--census`` counts ``#[test]``
    attributes directly and disagreed (144 vs 143), which is how it surfaced.

    Bracket depth is tracked instead, so a multi-line attribute is stepped
    over whole.  At depth 0 the walk still stops at the first line that is
    neither an attribute, a comment, nor blank, so it can never run past its
    own item into the next one.
    """
    names: list[tuple[str, list[str]]] = []
    for i, line in enumerate(lines):
        if not TEST_FN.match(line):
            continue
        depth = 0
        for j in range(i + 1, len(lines)):
            stripped = lines[j].strip()
            if depth == 0:
                m = FN_NAME.match(lines[j])
                if m:
                    names.append((m.group(1), fn_cfgs(lines, i)))
                    break
                if stripped and not stripped.startswith(("#[", "//")):
                    break
            depth = max(0, depth + lines[j].count("[") - lines[j].count("]"))
    return names


def strip_generated(lines: list[str], ident: str) -> list[str]:
    """Drop only *this* module's generated block.

    Scoped by ident because one file can hold two test modules (`board.rs`),
    and a blanket strip would delete the sibling block on the second pass.
    """
    begin, end = BEGIN.format(ident=ident), END.format(ident=ident)
    out, skipping = [], False
    for line in lines:
        if line.strip() == begin:
            skipping = True
            continue
        if line.strip() == end:
            skipping = False
            continue
        if not skipping:
            out.append(line)
    return out


def generated_block(
    indent: str, mod_path: str, ident: str, fns: list[tuple[str, list[str]]]
) -> list[str]:
    """The ``pub const`` that makes private ``#[test]`` fns reachable."""
    q = f"{mod_path}::{ident}"
    body = [
        f"{indent}{BEGIN.format(ident=ident)}",
        f"{indent}/// Every `#[test]` in this module, as a callable the `wasm32`",
        f"{indent}/// entry point can invoke by index.  Generated because these",
        f"{indent}/// functions are private to this module and unreachable from",
        f"{indent}/// anywhere a registry could otherwise live.",
        f"{indent}pub const WASM_TESTS: &[(&str, fn())] = &[",
    ]
    for fn, cfgs in fns:
        prefix = "".join(f"{cfg} " for cfg in cfgs)
        body.append(f'{indent}    {prefix}("{q}::{fn}", {fn}),')
    body += [f"{indent}];", f"{indent}{END.format(ident=ident)}"]
    return body


def render_root(entries: list[tuple[str, str, int]]) -> str:
    total = sum(n for _, _, n in entries)
    lines = [
        f"//! The `wasm32` test registry for `{CRATE_SPEC.name}`.",
        "//!",
        "//! Generated by `scripts/gen_wasm_test_registry.py`; run it after adding a",
        "//! test to any listed module, and `--check` gates drift in CI.",
        "//!",
        "//! `cargo test`'s libtest harness cannot target `wasm32-unknown-unknown`,",
        "//! so the Worker tier calls each test function individually instead of",
        "//! running a test binary.  This module is the flat, indexable list of them.",
        "//!",
        "//! Only modules that survive `--no-default-features` appear here.  Tests",
        "//! inside `#[cfg(feature = \"python\")]` modules are structurally absent",
        f"//! from a `wasm32` build and {CRATE_SPEC.census_note}.",
        "//!",
        *CRATE_SPEC.extra_notes,
        *(["//!"] if CRATE_SPEC.extra_notes else []),
        *CRATE_SPEC.sharding_note,
        "",
        "/// A single test: its fully qualified name and a nullary callable.",
        "///",
        "/// Failure is signalled by panicking, exactly as under libtest.  On",
        "/// `wasm32-unknown-unknown` a panic aborts (the target has no unwinding on",
        "/// stable), which surfaces to the host as a WebAssembly trap -- so the",
        "/// runner catches the trap rather than a `Result`.",
        "pub type WasmTest = (&'static str, fn());",
        "",
        f"/// All {total} eligible tests, in a stable order.  Each entry is",
        "/// gated on the per-family `wasm-registry-<family>` feature; enable",
        "/// all families (`wasm-test-registry`) or individual ones.",
        "pub const ALL: &[&[WasmTest]] = &[",
    ]
    for mod_path, ident, _ in entries:
        family = FAMILY_BY_ENTRY.get((mod_path, ident), "infra")
        lines.append(
            f"    #[cfg(feature = \"wasm-registry-{family}\")]"
            f" crate::{mod_path}::{ident}::WASM_TESTS,"
        )
    lines += [
        "];",
        "",
        "/// Total number of registered tests *in the currently-selected families*.",
        "pub fn count() -> usize {",
        "    ALL.iter().map(|m| m.len()).sum()",
        "}",
        "",
        "/// The test at `index` in the flattened registry.",
        "pub fn get(index: usize) -> Option<&'static WasmTest> {",
        "    let mut remaining = index;",
        "    for module in ALL {",
        "        if remaining < module.len() {",
        "            return Some(&module[remaining]);",
        "        }",
        "        remaining -= module.len();",
        "    }",
        "    None",
        "}",
        "",
    ]
    return "\n".join(lines)


def ancestor_decls(rel: str) -> list[tuple[str, str]]:
    """``(declaring file, module ident)`` for every ancestor module of ``rel``.

    `rules/drc/clearance.rs` is declared `mod clearance;` in `rules/drc/mod.rs`,
    which is `mod drc;` in `rules/mod.rs`, which is `mod rules;` in `lib.rs`.
    Each link has to be at least `pub(crate)` for the crate-root registry to
    name the test module at the end of the chain.
    """
    parts = rel[: -len(".rs")].split("/")
    if parts[-1] == "mod":
        parts.pop()
    out = []
    for i in range(len(parts) - 1, -1, -1):
        parent = "/".join(parts[:i])
        decl_file = f"{parent}/mod.rs" if parent else "lib.rs"
        out.append((decl_file, parts[i]))
    return out


def widen_mod_decl(text: str, ident: str) -> str:
    """Raise a private ``mod <ident>;`` to ``pub(crate)``; leave ``pub`` alone."""
    # `[ \t]*$` rather than `\s*$`: `\s` spans newlines, so the looser form
    # swallowed the blank line after the declaration it rewrote.
    pattern = re.compile(rf"^([ \t]*)mod\s+{re.escape(ident)}[ \t]*;[ \t]*$", re.MULTILINE)
    return pattern.sub(rf"\g<1>pub(crate) mod {ident};", text)


# `#[cfg(test)]` sitting directly above a file-module declaration
# (`#[cfg(test)]\nmod integration;`), tolerating other attributes in between.
def _mod_gate_pattern(ident: str) -> re.Pattern[str]:
    return re.compile(
        rf"^([ \t]*)"
        + re.escape(TEST_GATE)
        + r"([ \t]*\n(?:[ \t]*#\[[^\n]*\][ \t]*\n)*"
        + rf"[ \t]*(?:pub(?:\([^)]*\))?[ \t]+)?mod[ \t]+{re.escape(ident)}[ \t]*;)",
        re.MULTILINE,
    )


def widen_mod_gate(text: str, ident: str) -> str:
    """Widen a ``#[cfg(test)]`` on the *declaration* of file module ``ident``.

    Visibility is only half of what a registry entry needs: the declaration
    itself can be test-gated, and then the whole file is absent from the
    ordinary build the registry compiles into.  ``temper-rust-router-core``'s
    ``combinator/mod.rs`` does exactly that with ``#[cfg(test)] mod
    integration;`` -- its 8 round-trip tests live in a file that only exists
    under ``cargo test``.

    Widening the gate to the same ``GATE`` the test modules get keeps
    ``cargo test`` identical (``any(test, ...)`` is still ``test``) and makes
    the file present whenever ``wasm-registry`` is on.  Idempotent: ``GATE`` is
    not ``#[cfg(test)]``, so a second pass matches nothing.
    """
    return _mod_gate_pattern(ident).sub(rf"\g<1>{GATE}\g<2>", text)


def rewrite_module(text: str, rel: str, ident: str) -> tuple[str, str | None, list[str]]:
    """Gate + expose ``mod <ident>`` and append its generated registry block.

    Returns the new text for ``rel``, the new text for a file module's body
    file (or ``None`` for an inline module), and the test function names.
    """
    lines = strip_generated(text.splitlines(), ident)
    attr_start, decl_idx, body_end = find_module_span(lines, ident)
    indent = lines[decl_idx][: len(lines[decl_idx]) - len(lines[decl_idx].lstrip())]

    # Rewrite the gate, keeping any hand-written attributes other than the
    # `cfg(test)` being replaced and the allow re-added below.
    kept = [
        ln
        for ln in lines[attr_start:decl_idx]
        if "cfg(test)" not in ln
        and "wasm-test-registry" not in ln
        and "wasm-registry" not in ln
        and "clippy::unwrap_used" not in ln
        and "clippy::expect_used" not in ln
    ]
    header = [f"{indent}{GATE}", f"{indent}{ALLOW}"] + kept
    decl = lines[decl_idx]
    if not decl.lstrip().startswith(("pub ", "pub(")):
        decl = f"{indent}pub(crate) {decl.lstrip()}"

    if body_end == -1:
        # File module: the body lives in `<stem>/<ident>.rs`.
        body_path = submodule_path(SRC, rel, ident)
        body_lines = strip_generated(body_path.read_text().splitlines(), ident)
        hidden = nested_gated_mask(body_lines)
        body_lines = [
            ln if nested else keep_test_fn(ln)
            for ln, nested in zip(body_lines, hidden)
        ]
        fns = collect_test_fns(own_lines(body_lines))
        block = generated_block("", module_path(rel), ident, fns)
        while body_lines and not body_lines[-1].strip():
            body_lines.pop()
        body_text = "\n".join(body_lines + [""] + block) + "\n"
        new_lines = lines[:attr_start] + header + [decl] + lines[decl_idx + 1 :]
        return "\n".join(new_lines) + "\n", body_text, fns

    body = lines[decl_idx + 1 : body_end]
    hidden = nested_gated_mask(body)
    # A nested test-gated submodule keeps its `#[test]` attributes verbatim:
    # it is not compiled into the registry build, and rewriting inside a
    # `proptest!` invocation would change what that macro sees.
    body = [ln if nested else keep_test_fn(ln) for ln, nested in zip(body, hidden)]
    while body and not body[-1].strip():
        body.pop()  # keep regeneration idempotent
    fns = collect_test_fns(own_lines(body))
    block = generated_block(indent + "    ", module_path(rel), ident, fns)
    new_lines = (
        lines[:attr_start]
        + header
        + [decl]
        + body
        + [""]
        + block
        + lines[body_end:]
    )
    return "\n".join(new_lines) + "\n", None, fns


def check_unregistered() -> list[Discovered]:
    """Test modules that could register but do not.  The gate's second arm.

    The first arm compares the committed registry against ``ELIGIBLE`` and so
    can only see a test added to a module already on the list.  A module that
    is *absent* from the list is not drift to it -- it is invisible.  That is
    not hypothetical: ``src/ipc.rs`` landed with the ``temper-ipc`` crate-fold
    on 2026-08-09, and its eleven IPC-2221/2152 kernel tests sat outside the
    tier for a day while ``--check`` reported green.

    So this arm starts from the source instead of from the list: every
    ``#[cfg(test)]`` module holding ``#[test]`` functions must either be
    registered or carry a *stated* structural reason for not being
    (:func:`discover_eligible`'s predicates).  Silent absence is no longer a
    representable state.
    """
    listed = set(ELIGIBLE)
    return [
        d
        for d in discover_eligible(SRC, CRATE_SPEC.absent_features)
        if not d.excluded and d.tests and (d.rel, d.ident) not in listed
    ]


def print_census() -> None:
    """Every ``#[cfg(test)]`` module, registered or not, with its reason.

    For a crate that names its modules explicitly, membership of ``ELIGIBLE``
    is what decides "registered" -- and a module the predicates call eligible
    but the list omits is called out, because that is the hole a hand-kept list
    has and the drift gate cannot see.
    """
    found = discover_eligible(SRC, CRATE_SPEC.absent_features)
    listed = set(ELIGIBLE)
    for d in found:
        if CRATE_SPEC.eligible is not None and not d.excluded:
            if (d.rel, d.ident) not in listed:
                d.excluded = "not-in-explicit-list"
    kept = [d for d in found if not d.excluded]
    dropped = [d for d in found if d.excluded]
    print(f"{CRATE_SPEC.name} census: {len(found)} `#[cfg(test)]` modules")
    print(f"  registered: {len(kept)} modules, {sum(d.tests for d in kept)} tests")
    for d in kept:
        print(f"    {d.rel}::{d.ident}  {d.tests}")
    print(f"  excluded:   {len(dropped)} modules, {sum(d.tests for d in dropped)} tests")
    for d in dropped:
        print(f"    {d.rel}::{d.ident}  {d.tests}  [{d.excluded}]")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    ap.add_argument(
        "--crate",
        default="temper-drc-rs",
        choices=sorted(CRATES),
        help="which crate's registry to generate (default: temper-drc-rs)",
    )
    ap.add_argument(
        "--census",
        action="store_true",
        help="list every `#[cfg(test)]` module and why any is excluded, then exit",
    )
    args = ap.parse_args()
    select_crate(args.crate)

    if args.census:
        print_census()
        return 0

    pending: dict[Path, str] = {}
    entries: list[tuple[str, str, int]] = []

    for rel, ident in ELIGIBLE:
        path = SRC / rel
        # Read through `pending` so a file holding two test modules (board.rs)
        # accumulates both edits instead of the second discarding the first.
        text = pending.get(path) or path.read_text()
        new_text, body_text, fns = rewrite_module(text, rel, ident)
        pending[path] = new_text
        if body_text is not None:
            pending[submodule_path(SRC, rel, ident)] = body_text
        entries.append((module_path(rel), ident, len(fns)))

        for decl_file, mod_ident in ancestor_decls(rel):
            decl_path = SRC / decl_file
            decl_text = pending.get(decl_path) or decl_path.read_text()
            pending[decl_path] = widen_mod_gate(
                widen_mod_decl(decl_text, mod_ident), mod_ident
            )

    # Test-support modules: same gate widening and visibility raise, no entries.
    # Done after the loop so a crate that both registers a module in a file and
    # names a support module in it accumulates both edits through `pending`.
    for decl_file, mod_ident in CRATE_SPEC.test_support:
        decl_path = SRC / decl_file
        decl_text = pending.get(decl_path) or decl_path.read_text()
        pending[decl_path] = widen_mod_gate(
            widen_mod_decl(decl_text, mod_ident), mod_ident
        )

    pending[SRC / "wasm_test_registry.rs"] = render_root(entries)

    drifted = []
    for path, text in pending.items():
        current = path.read_text() if path.exists() else None
        if current == text:
            continue
        drifted.append(path.relative_to(REPO_ROOT))
        if not args.check:
            path.write_text(text)

    total = sum(n for _, _, n in entries)
    suffix = "" if args.crate == "temper-drc-rs" else f" [{args.crate}]"

    # Second gate arm: a module that could register but is not on the list.
    # Checked in write mode too -- regenerating cannot invent a list entry, so
    # this needs a human either way.
    unregistered = check_unregistered()
    if unregistered:
        print(
            f"{len(unregistered)} test module(s) hold `#[test]` functions, are"
            " not registered, and have no stated reason not to be:"
        )
        for d in unregistered:
            print(f"  {d.rel}::{d.ident}  ({d.tests} tests)")
        print(
            "Add each to ELIGIBLE in this script (and regenerate), or -- if it"
            " genuinely cannot compile into a non-test build -- give"
            " discover_eligible() a predicate that names the reason."
        )
        return 1

    if args.check:
        if drifted:
            print(
                "wasm test registry is stale; run scripts/gen_wasm_test_registry.py"
                f" --crate {args.crate}"
            )
            for p in drifted:
                print(f"  {p}")
            return 1
        print(
            f"wasm test registry up to date: {total} tests across"
            f" {len(entries)} modules{suffix}"
        )
        return 0

    print(f"wrote registry: {total} tests across {len(entries)} modules{suffix}")
    for p in drifted:
        print(f"  updated {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
