#!/usr/bin/env python3
"""Generate pcb/temper.kicad_dru from TEMPER_NET_CLASSES in design_rules.py.

Usage (from repo root):
    uv run python scripts/generate_kicad_dru.py
"""

from pathlib import Path

from temper_placer.core.design_rules import TEMPER_NET_CLASSES

# Repo root is two levels up from this script (scripts/generate_kicad_dru.py)
REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "pcb" / "temper.kicad_dru"

# KiCad uses "Ground" as the net-class name; our Python dict uses "GND"
KICAD_NAME_MAP = {
    "GND": "Ground",
}

_SEP = "# " + "=" * 66


def kicad_class_name(python_key: str) -> str:
    """Return the KiCad net-class name for a given Python dict key."""
    return KICAD_NAME_MAP.get(python_key, python_key)


def fmt_mm(value: float) -> str:
    """Format a float as a KiCad mm string (no trailing zeros beyond 4 dp)."""
    # Use up to 4 decimal places, strip unnecessary trailing zeros after the dot
    s = f"{value:.4f}".rstrip("0").rstrip(".")
    # Always keep at least one decimal digit so "3" becomes "3.0"
    if "." not in s:
        s += ".0"
    return f"{s}mm"


def generate_dru() -> str:
    """Return the full contents of the KiCad DRU file as a string."""
    lines: list[str] = []

    # KiCad custom design rules format header
    lines.append("# Custom Design Rules for Temper Induction Heater")
    lines.append("# IEC 60335-1 / IEC 60664-1 compliant")
    lines.append("#")
    lines.append("# IMPORTANT: This board REQUIRES conformal coating for safety!")
    lines.append(
        "# Without coating, TO-247 packages violate IEC 60664-1 clearances."
    )
    lines.append("#")
    lines.append(
        "# Generated by scripts/generate_kicad_dru.py"
        " -- do not edit by hand."
    )
    lines.append("")
    lines.append("(version 1)")
    lines.append("")

    # -------------------------------------------------------------------------
    # Static rules: same-footprint and fine-pitch exceptions
    # -------------------------------------------------------------------------
    lines.append(_SEP)
    lines.append("# RULE 1: Allow reduced clearance within same footprint")
    lines.append(
        "# This handles TO-247, SOT-23, QFN packages"
        " where pad pitch < net class clearance"
    )
    lines.append(_SEP)
    lines.append('(rule "Same footprint pads"')
    lines.append(
        "   (condition \"A.insideCourtyard('*')"
        " && B.insideCourtyard('*')"
        " && A.Footprint == B.Footprint\")"
    )
    lines.append("   (constraint clearance (min 0.1mm))")
    lines.append(")")
    lines.append("")
    lines.append(_SEP)
    lines.append("# RULE 1a: Fine-pitch IC pads (QFN, BGA with 0.4mm pitch)")
    lines.append(_SEP)
    lines.append('(rule "Fine pitch IC pads"')
    lines.append(
        "   (condition \"A.Type == 'Pad' && A.Attribute == 'SMD'"
        " && B.Type == 'Pad' && B.Attribute == 'SMD'"
        " && A.Footprint == B.Footprint\")"
    )
    lines.append("   (constraint clearance (min 0.1mm))")
    lines.append(")")
    lines.append("")

    # -------------------------------------------------------------------------
    # Inter-class clearance rules (static constants — derived from IEC standards
    # and physical package constraints, not from TEMPER_NET_CLASSES directly)
    # -------------------------------------------------------------------------
    lines.append(_SEP)
    lines.append("# RULE 2: AC Mains isolation - 6mm to everything except itself")
    lines.append("# IEC 60335-1 basic insulation for 240V AC")
    lines.append(_SEP)
    lines.append('(rule "AC Mains to LV"')
    lines.append(
        "   (condition \"A.NetClass == 'ACMains'"
        " && B.NetClass != 'ACMains'"
        " && B.NetClass != 'HighVoltage'\")"
    )
    lines.append("   (constraint clearance (min 6.0mm))")
    lines.append(")")
    lines.append("")
    lines.append(_SEP)
    lines.append(
        "# RULE 3: AC Mains to High Voltage - 3mm"
        " (both isolated from earth)"
    )
    lines.append(
        "# Reduced clearance since both are on same side of isolation barrier"
    )
    lines.append(_SEP)
    lines.append('(rule "AC Mains to HV"')
    lines.append(
        "   (condition \"A.NetClass == 'ACMains'"
        " && B.NetClass == 'HighVoltage'\")"
    )
    lines.append("   (constraint clearance (min 3.0mm))")
    lines.append(")")
    lines.append("")
    lines.append(_SEP)
    lines.append("# RULE 4: High Voltage DC bus - 2mm to LV")
    lines.append("# 400V DC bus after rectification")
    lines.append(
        "# NOTE: IEC 60664-1 at 400V working voltage may require"
        " 3.0mm+ clearance -- verify before HV bring-up"
    )
    lines.append(_SEP)
    lines.append('(rule "HV to LV"')
    lines.append(
        "   (condition \"A.NetClass == 'HighVoltage'"
        " && B.NetClass != 'HighVoltage'"
        " && B.NetClass != 'ACMains'\")"
    )
    lines.append("   (constraint clearance (min 2.0mm))")
    lines.append(")")
    lines.append("")
    lines.append(_SEP)
    lines.append(
        "# RULE 4a/4b: HighVoltageIsolated -- the gate-drive floating"
        " bootstrap supply"
    )
    lines.append("#")
    lines.append(
        "# GAP CLOSED (2026-07-28): this netclass carried ZERO clearance or"
        " creepage"
    )
    lines.append(
        "# rules anywhere in this generator until now (grep -c"
        " HighVoltageIsolated"
    )
    lines.append(
        "# scripts/generate_kicad_dru.py returned 0) -- the exact class RULE"
        " 1's own"
    )
    lines.append(
        "# cross-domain guard fix used to re-home U7's secondary bias nets"
        " (VSSA/VDDA,"
    )
    lines.append(
        "# hb.gate_hs.driver-p2/-p1-1) into, per"
        " docs/evidence/2026-07-28-drc-rule1-"
    )
    lines.append(
        "# netclass-redo.md sec 5. Moving those nets into a netclass that"
        " itself"
    )
    lines.append(
        "# enforced nothing left them with only KiCad's per-netclass"
        " baseline (6.0mm"
    )
    lines.append(
        "# clearance, from pcb/temper.kicad_pro's own"
        " net_settings.classes/packages/"
    )
    lines.append(
        "# temper-placer/configs/netclass_rules.yaml) and NO creepage"
        " protection at all."
    )
    lines.append("#")
    lines.append(
        "# WHAT THE CLASS ACTUALLY IS: elec/domain_manifest.yaml declares"
        " +5V_ISO,"
    )
    lines.append(
        "# VBOOT_H, VBOOT_L, hb.gate_hs.driver-p1-1 (VDDA) and"
        " hb.gate_hs.driver-p2"
    )
    lines.append(
        "# (VSSA) -- every net this project assigns to the"
        " HighVoltageIsolated"
    )
    lines.append(
        "# netclass -- as members of the SAME `HV` domain as ac_l/+170V_BUS/"
        "SW_NODE,"
    )
    lines.append(
        "# not a third, separate domain. \"Isolated\" here names a"
        " gate-driver-internal"
    )
    lines.append(
        "# galvanic barrier (the UCC21550's own primary/secondary split),"
        " not a"
    )
    lines.append(
        "# barrier this netclass's nets sit on the far side of relative to"
        " the rest of"
    )
    lines.append(
        "# HV -- they float WITH the switch node, one gate-drive-current"
        " resistor"
    )
    lines.append(
        "# downstream of GATE_HS/SW_NODE (see the redo doc's own tracing)."
        " That means"
    )
    lines.append(
        "# this class needs exactly the asymmetric treatment"
        " docs/evidence/2026-07-28-"
    )
    lines.append(
        "# hv-isolated-rules-and-creepage-triage.md sets out: REINFORCED"
        " separation from"
    )
    lines.append(
        "# the LV/SELV side (the real barrier), but only FUNCTIONAL"
        " separation from its"
    )
    lines.append(
        "# own HV/ACMains neighbours (same side of that barrier -- exactly"
        " the relationship"
    )
    lines.append(
        "# RULE 3 (\"AC Mains to HV\") already models for ACMains vs."
        " HighVoltage)."
    )
    lines.append("#")
    lines.append(
        "# 4a relaxes the pair to the same 2.0mm figure RULE 4 (\"HV to"
        " LV\") already"
    )
    lines.append(
        "# uses for intra-HV-domain separation -- a documented, deliberate"
        " reduction below"
    )
    lines.append(
        "# the 6.0mm per-netclass baseline that would otherwise apply,"
        " justified because"
    )
    lines.append(
        "# both sides sit on the same side of the reinforced barrier (same"
        " category of"
    )
    lines.append(
        "# reduction RULE 3 already makes, not a safety loosening -- see the"
        " evidence doc)."
    )
    lines.append(
        "# 4b is the real, new protection: reinforced clearance against"
        " every other"
    )
    lines.append(
        "# (LV/SELV) netclass, at the same 2.0mm figure RULE 4 uses for"
        " HighVoltage."
    )
    lines.append(
        "# NOTE: this generator has no creepage-constraint concept yet"
        " (no rule anywhere"
    )
    lines.append(
        "# in this file emits KiCad's `creepage` constraint kind, and no"
        " PD2/PD3"
    )
    lines.append(
        "# pollution-degree figure has been derived for this class) --"
        " HighVoltageIsolated"
    )
    lines.append(
        "# gets the same clearance-only treatment every other class in"
        " this file has today."
    )
    lines.append(
        "# Creepage enforcement (HV_CREEPAGE_ENFORCED_MM) is a separate,"
        " larger unit that"
    )
    lines.append(
        "# adds the constraint kind generator-wide and derives its own"
        " cited figure; when"
    )
    lines.append(
        "# it lands, this class should get the same reinforced creepage"
        " every other"
    )
    lines.append("# HV-domain-to-LV rule in this file gets.")
    lines.append(_SEP)
    # Matches RULE 4's existing "HV to LV" clearance figure (this file,
    # unchanged) -- not a new number, just this class's share of it.
    _HV_ISOLATED_CLEARANCE_MM = 2.0
    lines.append('(rule "HighVoltageIsolated same side"')
    lines.append(
        "   (condition \"A.NetClass == 'HighVoltageIsolated'"
        " && (B.NetClass == 'HighVoltage' || B.NetClass == 'ACMains')\")"
    )
    lines.append(f"   (constraint clearance (min {fmt_mm(_HV_ISOLATED_CLEARANCE_MM)}))")
    lines.append(")")
    lines.append("")
    lines.append('(rule "HighVoltageIsolated to LV"')
    lines.append(
        "   (condition \"A.NetClass == 'HighVoltageIsolated'"
        " && B.NetClass != 'HighVoltageIsolated'"
        " && B.NetClass != 'HighVoltage'"
        " && B.NetClass != 'ACMains'\")"
    )
    lines.append(f"   (constraint clearance (min {fmt_mm(_HV_ISOLATED_CLEARANCE_MM)}))")
    lines.append(")")
    lines.append("")
    lines.append(_SEP)
    lines.append("# RULE 5: High Voltage internal - relaxed for same footprint")
    lines.append("# TO-247 IGBTs have 5.45mm pin pitch (1.95mm edge-to-edge)")
    lines.append("#")
    lines.append("# WARNING: This violates IEC 60664-1 PD2 (needs 2.0mm for 400V)")
    lines.append(
        "# REQUIRES: Conformal coating to achieve PD1 (needs 0.8mm for 400V)"
    )
    lines.append(_SEP)
    lines.append('(rule "HV internal same footprint"')
    lines.append(
        "   (condition \"A.NetClass == 'HighVoltage'"
        " && B.NetClass == 'HighVoltage'"
        " && A.insideCourtyard(B.Reference)\")"
    )
    lines.append("   (constraint clearance (min 1.5mm))")
    lines.append(")")
    lines.append("")
    lines.append(_SEP)
    lines.append("# RULE 6: Gate drive signals near HV - 0.5mm minimum")
    lines.append("# Gate resistors placed close to IGBTs")
    lines.append("#")
    lines.append(
        "# Split into two rules 2026-07-28 (R4) alongside the GateDrive ->"
        " GateDriveHV/GateDriveSELV class split -- a single condition"
    )
    lines.append(
        "# naming the old 'GateDrive' string would now match zero nets"
        " (silent, always-dead coverage; see docs/solutions/best-practices/"
    )
    lines.append(
        "# a-rule-that-matches-nothing-reads-as-coverage-2026-07-28.md)."
        " Both halves keep the original 0.5mm figure -- this unit changes"
    )
    lines.append(
        "# the class model, not the clearance value."
    )
    lines.append(_SEP)
    lines.append('(rule "GateDriveHV near HV"')
    lines.append(
        "   (condition \"A.NetClass == 'GateDriveHV'"
        " && B.NetClass == 'HighVoltage'\")"
    )
    lines.append("   (constraint clearance (min 0.5mm))")
    lines.append(")")
    lines.append("")
    lines.append('(rule "GateDriveSELV near HV"')
    lines.append(
        "   (condition \"A.NetClass == 'GateDriveSELV'"
        " && B.NetClass == 'HighVoltage'\")"
    )
    lines.append("   (constraint clearance (min 0.5mm))")
    lines.append(")")
    lines.append("")
    lines.append(_SEP)
    lines.append("# RULE 7: Power nets internal - allow SOT-23 pitch")
    lines.append(_SEP)
    lines.append('(rule "Power internal same footprint"')
    lines.append(
        "   (condition \"A.NetClass == 'Power'"
        " && B.NetClass == 'Power'"
        " && A.insideCourtyard(B.Reference)\")"
    )
    lines.append("   (constraint clearance (min 0.2mm))")
    lines.append(")")
    lines.append("")
    lines.append(_SEP)
    lines.append("# RULE 8: Ground to everything - standard clearance")
    lines.append("# GND is a reference, not a hazard")
    lines.append(_SEP)
    lines.append('(rule "Ground clearance"')
    lines.append(
        "   (condition \"A.NetClass == 'Ground' || B.NetClass == 'Ground'\")"
    )
    lines.append("   (constraint clearance (min 0.15mm))")
    lines.append(")")
    lines.append("")
    lines.append(_SEP)
    lines.append("# RULE 9: USB differential pair - tight coupling")
    lines.append(_SEP)
    lines.append('(rule "USB differential"')
    lines.append(
        "   (condition \"A.NetClass == 'HighSpeed'"
        " && B.NetClass == 'HighSpeed'\")"
    )
    lines.append("   (constraint clearance (min 0.1mm))")
    lines.append(")")
    lines.append("")
    lines.append(_SEP)
    lines.append("# RULE 10: Default routing clearance")
    lines.append("# Standard 0.2mm for signal traces")
    lines.append(_SEP)
    lines.append('(rule "Default routing"')
    lines.append("   (condition \"A.Type == 'Track' || B.Type == 'Track'\")")
    lines.append("   (constraint clearance (min 0.2mm))")
    lines.append(")")
    lines.append("")

    # -------------------------------------------------------------------------
    # Per-class trace-width rules generated from TEMPER_NET_CLASSES
    # -------------------------------------------------------------------------
    lines.append(_SEP)
    lines.append(
        "# TRACE WIDTH RULES"
        " (generated from TEMPER_NET_CLASSES in design_rules.py)"
    )
    lines.append(_SEP)
    lines.append("")

    # Emit in a stable order (same as definition order in design_rules.py)
    class_order = [
        "ACMains",
        "HighVoltage",
        "FinePitch",
        "Power",
        # Split 2026-07-28 (R4): "GateDrive" no longer exists as a key in
        # TEMPER_NET_CLASSES -- both halves must be listed or this loop
        # KeyErrors.
        "GateDriveHV",
        "GateDriveSELV",
        "GND",
        "HighSpeed",
        "Signal",
        "HighCurrent",
    ]

    for py_key in class_order:
        nc = TEMPER_NET_CLASSES[py_key]
        kicad_name = kicad_class_name(py_key)
        width_str = fmt_mm(nc.trace_width)
        rule_label = f"{kicad_name} trace width"
        cond = f"A.Type == 'Track' && A.NetClass == '{kicad_name}'"
        lines.append(f'(rule "{rule_label}"')
        lines.append(f'   (condition "{cond}")')
        lines.append(f"   (constraint track_width (min {width_str}))")
        lines.append(")")
        lines.append("")

    # -------------------------------------------------------------------------
    # Hole clearance rules (static)
    # -------------------------------------------------------------------------
    lines.append(_SEP)
    lines.append("# HOLE CLEARANCE RULES")
    lines.append(_SEP)
    lines.append("")
    lines.append('(rule "Via hole clearance"')
    lines.append("   (constraint hole_clearance (min 0.25mm))")
    lines.append(")")
    lines.append("")
    lines.append('(rule "PTH hole to hole"')
    lines.append("   (constraint hole_to_hole (min 0.5mm))")
    lines.append(")")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    content = generate_dru()
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {len(content.splitlines())} lines to {OUTPUT_PATH}")
    print()
    print(content)


if __name__ == "__main__":
    main()
