"""Retired oracle-comparison differential for the slot_generation grid kernel
(``generate_slots_for_zone``).

The pinned oracle ``tests/deterministic/stages/_slot_generation_py_oracle.py``
was retired by FREEZE on 2026-08-21 (batch 3): its golden vectors are baked
into ``deterministic_stages.rs``'s own ``frozen_slot_generation_tests``
module (``frozen_slot_generation_matches_golden_corpus`` /
``frozen_slot_generation_corpus_is_non_vacuous``), generated by
``scripts/oracle_freeze_specs/slot_generation.py`` (105 cases, 6 non-vacuity
checks).

The oracle-comparison tests this file used to carry are fully superseded by
that frozen corpus. What remains below is a single wiring check: the
pyo3-visible ``generate_slots_for_zone`` the production shim delegates
through must still be callable and must return the Rust kernel's output
shape.
"""

from __future__ import annotations

import temper_design_bundle_python as _tdb

_RS = _tdb.deterministic_stages


def test_shipped_kernel_callable_via_pyo3():
    """The pyo3-visible ``generate_slots_for_zone`` the production shim
    delegates to must exist and return the expected grid shape on a
    representative input -- a Stage-7 wiring check, not a differential."""
    got = list(_RS.generate_slots_for_zone(0.0, 0.0, 10.0, 10.0, 2.0))
    assert len(got) == 25
    assert got[0] == (1.0, 1.0)
    assert got[24] == (9.0, 9.0)
