"""Retired oracle-comparison differential for the validator slot-grid
kernels (``_infer_slot_spacing`` / ``_build_slot_index`` /
``_slots_within_radius``).

The pinned oracle
``tests/deterministic/stages/_phased_component_assignment_validator_py_oracle.py``
was retired by FREEZE on 2026-08-20 (batch 2): its golden vectors are baked
into ``deterministic_leaves.rs``'s own ``frozen_slot_grid_tests`` module
(``frozen_slot_grid_matches_golden_corpus`` /
``frozen_slot_grid_corpus_is_non_vacuous``), generated by
``scripts/oracle_freeze_specs/slot_grid_validator.py`` (73 cases, 12
non-vacuity checks).

The oracle-comparison tests this file used to carry are fully superseded by
that frozen corpus. What remains below is a single wiring check: the
pyo3-visible kernels the production
``validate_phased_component_assignment_hv`` shim delegates through must
still be callable and agree with each other on a representative grid.
Property-based coverage of these kernels survives independently in
``test_phased_component_assignment_validator_pbt.py`` and the Rust-side
``slot_grid_proptests`` module (hypothesis / proptest, no oracle import).
"""

from __future__ import annotations

import temper_design_bundle_python as _tdb

_RS = _tdb.deterministic_leaves


def test_shipped_kernels_callable_via_pyo3():
    """The pyo3-visible slot-grid kernels the production validator shim
    delegates to must exist and agree end-to-end on a representative
    input -- a Stage-7 wiring check, not a differential."""
    slots = [(0.0, 0.0), (5.0, 0.0), (10.0, 0.0), (0.0, 5.0), (5.0, 5.0)]
    spacing = _RS.infer_slot_spacing_py(slots)
    assert spacing == 5.0
    index = _RS.build_slot_index_py(slots, spacing)
    assert (0, 0) in index and (1, 0) in index and (0, 1) in index
    within = _RS.slots_within_radius_py((0.0, 0.0), 6.0, index, spacing)
    # Raster (di, dj) scan order around the center cell: (0,0) cell first,
    # then (0,1) before (1,0); (5.0, 5.0) is sqrt(50) > 6 and excluded.
    assert [(x, y) for x, y in within] == [(0.0, 0.0), (0.0, 5.0), (5.0, 0.0)]
