"""Retired oracle-comparison differential for the fine_pitch_escape kernels
(``_calculate_min_pin_pitch`` / ``_get_escape_layer_for_net``).

The pinned oracle
``tests/deterministic/stages/_fine_pitch_escape_py_oracle.py`` was retired
by FREEZE on 2026-08-20 (batch 2): its golden vectors are baked into
``deterministic_leaves.rs``'s own ``frozen_fine_pitch_tests`` module
(``frozen_fine_pitch_matches_golden_corpus`` /
``frozen_fine_pitch_corpus_is_non_vacuous``), generated by
``scripts/oracle_freeze_specs/fine_pitch_escape.py`` (64 cases, 11
non-vacuity checks).

The oracle-comparison tests this file used to carry are fully superseded by
that frozen corpus. What remains below is a single wiring check: the
pyo3-visible kernels the production ``FinePitchEscapeStage`` shim delegates
through must still be callable and agree on a representative input.
"""

from __future__ import annotations

import temper_design_bundle_python as _tdb

_RS = _tdb.deterministic_leaves


class _Pin:
    def __init__(self, position):
        self.position = position


def test_shipped_kernels_callable_via_pyo3():
    """The pyo3-visible kernels the production shim delegates to must
    exist and return expected values on representative inputs -- a Stage-7
    wiring check, not a differential."""
    pins = [_Pin((0.0, 0.0)), _Pin((1.0, 0.0)), _Pin((0.0, 1.0))]
    assert _RS.min_pin_pitch_py(pins) == 1.0
    assert _RS.min_pin_pitch_py([]) is None
    l2 = {"PWM_H", "SPI_CLK"}
    l3 = {"I_SENSE"}
    assert _RS.escape_layer_for_net_py("PWM_H", l2, l3, 1, 2) == (2, "In2.Cu")
    assert _RS.escape_layer_for_net_py("I_SENSE", l2, l3, 1, 2) == (3, "B.Cu")
    assert _RS.escape_layer_for_net_py("OTHER", l2, l3, 1, 2) == (1, "In1.Cu")
