"""Retired oracle-comparison differential for the power_plane reassignment
kernel (``recompute_plane_assignments``).

The pinned oracle ``tests/deterministic/stages/_power_plane_py_oracle.py``
was retired by FREEZE on 2026-08-20 (batch 2): its golden vectors are baked
into ``deterministic_leaves.rs``'s own ``frozen_power_plane_tests`` module
(``frozen_power_plane_matches_golden_corpus`` /
``frozen_power_plane_corpus_is_non_vacuous``), generated by
``scripts/oracle_freeze_specs/power_plane.py`` (54 cases, 9 non-vacuity
checks).

The oracle-comparison tests this file used to carry are fully superseded by
that frozen corpus. What remains below is a single wiring check: the
pyo3-visible ``recompute_plane_assignments`` the production
``PowerPlaneStage.run`` delegates through must still be callable and must
return the Rust kernel's output shape. (Unlike the other batch-2
retirements, the production shim delegates through this same
``deterministic_leaves`` submodule the differential drove directly, so the
wiring check exercises the pyo3 boundary itself rather than a separate
module entry point.)
"""

from __future__ import annotations

import temper_design_bundle_python as _tdb

_RS = _tdb.deterministic_leaves


def test_shipped_kernel_callable_via_pyo3():
    """The pyo3-visible `recompute_plane_assignments` the production shim
    delegates to must exist and return the expected (net, layer, is_plane)
    shape on a representative input -- a Stage-7 wiring check, not a
    differential."""
    existing = [_tdb.LayerAssignment("GND", 0, True, False)]
    got = _RS.recompute_plane_assignments(existing, ["GND"], {"GND": 1}, ["GND"])
    assert len(got) == 1
    assert got[0].net_name == "GND"
    assert got[0].layer == 1
    assert got[0].is_plane is True
