"""Retired oracle-comparison differential for the zone_aware_slot_generation
geometry kernels (point_in_polygon, slot_intersects_iso, min_distance_to_polygon,
point_to_segment_distance).

The pinned oracle ``tests/deterministic/stages/_zone_aware_slot_generation_py_oracle.py``
was retired by FREEZE on 2026-08-21 (batch 3): its golden vectors are baked
into ``deterministic_phase.rs``'s own ``frozen_zone_aware_tests`` module
(``frozen_pip_matches_golden_corpus`` / ``frozen_iso_matches_golden_corpus`` /
``frozen_ptsd_matches_golden_corpus`` / ``frozen_mdp_matches_golden_corpus`` /
``frozen_zone_aware_corpus_is_non_vacuous``), generated by
``scripts/oracle_freeze_specs/zone_aware_slot_generation.py`` (450 cases, 20
non-vacuity checks).

The oracle-comparison tests this file used to carry are fully superseded by
that frozen corpus. What remains below is a set of wiring checks: the
pyo3-visible kernels the production stage delegates through must still be
callable and return the expected output shape.
"""

from __future__ import annotations

import temper_design_bundle_python as _tdb
import temper_geometry as _tg

_DP = _tdb.deterministic_phase


def test_point_in_polygon_callable_via_pyo3():
    got = _DP.point_in_polygon_py(5.0, 5.0, [(0.0, 0.0), (10.0, 0.0), (10.0, 10.0), (0.0, 10.0)])
    assert got is True


def test_slot_intersects_iso_callable_via_pyo3():
    got = _DP.slot_intersects_iso_py((2.0, 2.0), [((0.0, 0.0), (4.0, 4.0))])
    assert got is True


def test_min_distance_to_polygon_callable_via_pyo3():
    got = _DP.min_distance_to_polygon_py(0.0, 1.0, [(0.0, 0.0), (1.0, 0.0), (1.0, 1.0)])
    assert got > 0.0


def test_point_to_segment_distance_callable_via_pyo3():
    got = _tg.point_to_segment_distance_py(0.0, 1.0, 0.0, 0.0, 2.0, 0.0)
    assert got == 1.0
