#!/usr/bin/env python3
"""Regenerate native-21's component/net delta against native-20 from the frozen exports.

    python3 native-21/part_changes.py   ->  native-21/change-inventory.json, native-21/PART-CHANGES.md

Instances are matched by source path (the text after "PowerStage120V::" in the
netlist sheetpath); attributes come from resolved-components.json, references and
net memberships from default.net. Nets are compared as sets of (reference, pin).
"""
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
PS = HERE.parent
BASE, NEW = PS / "native-20" / "frozen", HERE / "frozen"


def load(folder: Path):
    net = (folder / "default.net").read_text()
    refs = {}
    for m in re.finditer(r'\(comp \(ref "([^"]+)"\).*?\(sheetpath \(names "[^"]*::([^"]+)"\)', net, re.S):
        refs[m.group(2)] = m.group(1)
    attrs = {}
    for c in json.loads((folder / "resolved-components.json").read_text())["components"]:
        attrs[c["address"].split("::", 1)[1]] = c["attributes"]
    comps = {p: {"reference": refs.get(p), **{k: attrs[p].get(k) for k in ("designator_prefix", "footprint", "manufacturer", "mpn", "value")}}
             for p in attrs}
    nets = {}
    for m in re.finditer(r'\(net \(code "\d+"\) \(name "([^"]+)"\)(.*?)\)\s*(?=\(net |\)\s*\)\s*$)', net, re.S):
        nets[m.group(1)] = sorted([r, p] for r, p in re.findall(r'\(node \(ref "([^"]+)"\) \(pin "([^"]+)"\)', m.group(2)))
    return comps, nets


def main():
    c0, n0 = load(BASE)
    c1, n1 = load(NEW)
    changed = [{"path": p, "before": c0.get(p), "after": c1.get(p)}
               for p in sorted(set(c0) | set(c1)) if c0.get(p) != c1.get(p)]
    nets = [{"net": n, "before": n0.get(n), "after": n1.get(n)}
            for n in sorted(set(n0) | set(n1)) if n0.get(n) != n1.get(n)]
    inv = {"baseline": "native-20/frozen", "components_before": len(c0), "components_after": len(c1),
           "changed_components": changed, "changed_nets": nets}
    (HERE / "change-inventory.json").write_text(json.dumps(inv, indent=1) + "\n")
    rows = []
    for ch in changed:
        b, a = ch["before"], ch["after"]
        if a is None:
            rows.append(f"| {ch['path']} | {b['reference']} | remove {b['mpn']} | — | — | {b['footprint']} |")
            continue
        if b is None:
            action = "add"
        elif b["mpn"] != a["mpn"]:
            action = f"replace {b['mpn']}"
        else:
            action = "change " + ", ".join(k for k in a if a[k] != b.get(k))
        rows.append(f"| {ch['path']} | {a['reference']} | {action} | {a['mpn']} | {a.get('value') or '—'} | {a['footprint']} |")
    md = ["# Native-21 exact component delta", "",
          "Generated by `native-21/part_changes.py` from the two compiler-resolved exports "
          "(native-20/frozen vs native-21/frozen) by instance path. Unlisted parts keep their "
          "reference and selected part. Net membership changes are enumerated in `change-inventory.json`.",
          "", f"Components: {len(c0)} → {len(c1)}; changed instances: {len(changed)}; changed nets: {len(nets)}.", "",
          "| Instance | Ref | Action / old part | New selected part | Value | Footprint |", "|---|---|---|---|---|---|"] + rows
    (HERE / "PART-CHANGES.md").write_text("\n".join(md) + "\n")
    print(len(c0), len(c1), len(changed), len(nets))


if __name__ == "__main__":
    main()
