"""Retired oracle-comparison differential for the operating_point numeric
kernels (l_eff, thermal_chain, extreme_point, interior_k_grid).

The pinned oracle ``tests/physics/_operating_point_py_oracle.py`` was
retired by FREEZE on 2026-08-21 (batch 3): its golden vectors are baked
into ``operating_point.rs``'s own ``frozen_op_tests`` module
(``frozen_l_eff_matches_golden_corpus`` /
``frozen_thermal_chain_matches_golden_corpus`` /
``frozen_extreme_point_matches_golden_corpus`` /
``frozen_interior_k_grid_matches`` /
``frozen_op_corpus_is_non_vacuous``), generated by
``scripts/oracle_freeze_specs/operating_point.py`` (127 cases, 10
non-vacuity checks).

The oracle-comparison tests (including the BMC exhaustive and audit tests
that used the oracle as a reference) are fully superseded by that frozen
corpus. The BMC/audit properties they tested (exhaustive soundness,
fail-capability, audit correctness) should be reworked as pure Rust tests
in a follow-up — the frozen corpus covers the numeric kernels, and the
audit/BMC properties are about the Rust kernel's behavior, not the
oracle's. What remains below is a set of wiring checks.
"""

from __future__ import annotations

import temper_thermal as _tt


def test_l_eff_callable_via_pyo3():
    got = _tt.operating_point_l_eff_py(100e-6, 10e-6, 0.5)
    assert got > 0.0


def test_interior_k_grid_callable_via_pyo3():
    got = _tt.operating_point_interior_k_grid_py(11)
    assert len(got) == 9  # i=1..9 for N=11
