"""Type stubs for `temper_design_bundle_python.channel_skeleton_contracts`.

Compiled from `packages/temper-design-bundle/src/channel_skeleton_contracts.rs`.
Keep in sync with that file.
"""
from __future__ import annotations
from typing import Any

class SkeletonGraph:
    def __init__(self) -> None: ...
    def add_node(self, node: Any, pos: Any) -> None: ...
    def add_edge(self, u: Any, v: Any, weight: float | None = ...) -> None: ...
    def number_of_nodes(self) -> int: ...
    def number_of_edges(self) -> int: ...
    @property
    def nodes(self) -> list[Any]: ...
    @property
    def edges(self) -> list[tuple[Any, Any]]: ...
    def edges_with_data(self) -> list[tuple[Any, Any, dict[str, float]]]: ...
    def is_connected(self) -> bool: ...
    def connected_components(self) -> list[list[Any]]: ...
