"""Stubs for the `deterministic_leaves` submodule of the pyo3 extension.

Mirrors packages/temper-design-bundle/src/deterministic_leaves.rs. Signatures
are permissive (`Any`) where the Rust side takes marshalled tuples/dicts whose
precise shape is asserted by the differential suites, not by the type checker.
"""

from __future__ import annotations

from typing import Any

def assign_components_to_slots(*args: Any, **kwargs: Any) -> Any: ...
def assign_layer_by_net_class_py(*args: Any, **kwargs: Any) -> Any: ...
def assign_layers(*args: Any, **kwargs: Any) -> Any: ...
def build_slot_index_py(*args: Any, **kwargs: Any) -> Any: ...
def escape_layer_for_net_py(*args: Any, **kwargs: Any) -> Any: ...
def infer_slot_spacing_py(*args: Any, **kwargs: Any) -> Any: ...
def min_pin_pitch_py(*args: Any, **kwargs: Any) -> Any: ...
def recompute_plane_assignments(*args: Any, **kwargs: Any) -> Any: ...
def slots_within_radius_py(*args: Any, **kwargs: Any) -> Any: ...
