"""Type stubs for `temper_design_bundle_python.model_builder`.

Compiled from `packages/temper-design-bundle/src/model_builder.rs`. Keep in
sync with that file.
"""
from __future__ import annotations
from typing import Any

class Variable:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class NetChannelVar:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class NetLayerVar:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ViaVar:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class OrderVar:
    name: str
    var_type: str
    net1_idx: int
    net2_idx: int
    channel_id: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Constraint:
    name: str
    description: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class CapacityConstraint:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DiffPairConstraint:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class LayerConstraint:
    name: str
    description: str
    net_idx: int
    channel_id: str
    allowed: bool
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ChannelSeparationConstraint:
    name: str
    description: str
    group_a_indices: list[int]
    group_b_indices: list[int]
    min_slots: int
    channel_id: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ConstraintModel:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_variable(self, var: Any) -> None: ...
    def add_constraint(self, constraint: Any) -> None: ...
    def solve_native(
        self,
        net_names: list[str],
        conflict_limit: int | None = ...,
        time_limit_ms: int | None = ...,
    ) -> dict[str, Any]: ...
    def audit_native(self, assignments: dict[str, bool], net_names: list[str]) -> list[dict[str, Any]]: ...
    def native_clause_origins(self) -> list[str]: ...
    def native_model_supported(self) -> bool: ...
    @property
    def variable_count(self) -> int: ...
    @property
    def constraint_count(self) -> int: ...
    @property
    def variables(self) -> list[Any]: ...
    @property
    def constraints(self) -> list[Any]: ...
    @property
    def net_channel_vars(self) -> dict[Any, Any]: ...
    @property
    def bundle_channel_vars(self) -> dict[Any, Any]: ...
    @property
    def via_vars(self) -> dict[Any, Any]: ...

class ModelBuilder:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def build(self) -> ConstraintModel: ...

class ConstraintModelEmptyError(Exception): ...
