"""Type stubs for `temper_design_bundle_python.specification_contracts`."""
from __future__ import annotations
from typing import Any

class EMISpec:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class PcbSpecification:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class SafetySpec:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class SignalIntegritySpec:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class ThermalSpec:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
