#!/usr/bin/env python3
"""CI gate for the transition-table mutation sweep (R40, P1).

Reads the sweep report written by
``firmware/test/mutate_transition_table.py --sweep``
(default: ``firmware/test/build/mutations/report.json``) and fails when:

  - any mutant is **live** (the regenerated tests would not catch the spec
    change -- a test defect per KTD3, never a spec approval),
  - any mutation **errored** (generation/build failure -- a coverage gap, the
    mutation was never evaluated),
  - any row was **skipped** (row-coverage assertion: ``rows_covered`` must
    equal ``rows_total``), or
  - the report is **stale** (``generated_at`` older than
    ``--max-report-age-seconds``).

Freshness rule (review fix for the A4 scheduled-workflow fallback): the gate
must never pass on stale data. CI runs the full sweep in the same job,
immediately before this gate, so the report is fresh by construction. If the
sweep ever moves to a scheduled workflow, this check keeps the gate fail-closed
on any report older than the configured window -- a committed or
previously-generated report cannot satisfy the gate.

Exit codes
----------
  0 - OK: zero live mutants, zero errors, full row coverage, fresh report.
  2 - Violation: a live mutant, a mutation error, or a skipped row.
  5 - Tool error: report missing/malformed, wrong schema version, stale
      report, or a failed baseline recorded in the report. Fail-closed, never
      a silent pass (docs/METHODOLOGY.md Sec 5).
"""

from __future__ import annotations

import argparse
import datetime
import json
import sys
from pathlib import Path

EXIT_OK = 0
EXIT_VIOLATION = 2
EXIT_TOOL_ERROR = 5

DEFAULT_REPORT = "firmware/test/build/mutations/report.json"
SCHEMA_VERSION = 1
# CI runs the sweep immediately before the gate, so a few minutes is ample; the
# window exists to reject stale/committed reports if the sweep is scheduled.
DEFAULT_MAX_REPORT_AGE_SECONDS = 3600


def _parse_timestamp(value):
    """Parse an ISO-8601 timestamp (with or without timezone suffix)."""
    text = str(value).strip()
    try:
        dt = datetime.datetime.fromisoformat(text)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=datetime.UTC)
    return dt


def run_gate(report_path, max_age_seconds=DEFAULT_MAX_REPORT_AGE_SECONDS,
             now=None):
    """Evaluate a sweep report; returns (exit_code, message)."""
    path = Path(report_path)
    if not path.exists():
        return EXIT_TOOL_ERROR, (
            f"FAIL: sweep report not found at {path}. The mutation sweep must "
            f"run (firmware/test/mutate_transition_table.py --sweep) in the "
            f"same job before this gate."
        )

    try:
        report = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError) as exc:
        return EXIT_TOOL_ERROR, f"FAIL: sweep report {path} is malformed: {exc}"

    if not isinstance(report, dict) or report.get("schema_version") != SCHEMA_VERSION:
        return EXIT_TOOL_ERROR, (
            f"FAIL: sweep report {path} has unsupported schema "
            f"(schema_version={report.get('schema_version') if isinstance(report, dict) else '?'}); "
            f"expected {SCHEMA_VERSION}. Regenerate with the current driver."
        )

    # Freshness check: reject reports older than the window so a scheduled or
    # committed report can never satisfy the gate.
    generated_at = _parse_timestamp(report.get("generated_at", ""))
    if generated_at is None:
        return EXIT_TOOL_ERROR, (
            f"FAIL: sweep report {path} has no parseable generated_at; "
            f"cannot verify freshness."
        )
    now = now or datetime.datetime.now(datetime.UTC)
    age = (now - generated_at).total_seconds()
    if age > max_age_seconds:
        return EXIT_TOOL_ERROR, (
            f"FAIL: sweep report {path} is stale ({int(age)}s old, limit "
            f"{max_age_seconds}s). The gate must run on a report generated by "
            f"the current run, not a committed/stale artifact."
        )

    if report.get("baseline_pass") is not True:
        return EXIT_TOOL_ERROR, (
            f"FAIL: sweep report {path} records baseline_pass != true; the "
            f"scratch harness itself failed, so no mutation verdict is "
            f"meaningful."
        )

    rows_total = int(report.get("rows_total", 0))
    rows_covered = int(report.get("rows_covered", -1))
    rows_swept = int(report.get("rows_swept", -1))

    problems = []

    # Row-coverage assertion: every row of the manifest must have been swept.
    if rows_covered != rows_total or rows_swept != rows_total:
        skipped = rows_total - rows_covered
        problems.append(
            f"row coverage: {rows_covered}/{rows_total} covered "
            f"({rows_swept}/{rows_total} swept; {skipped} row(s) skipped)"
        )

    errors = report.get("errors_list", [])
    if errors:
        for e in errors:
            problems.append(
                f"mutation error: row {e.get('row_index')} "
                f"({e.get('event')}) op={e.get('op')}: "
                f"{str(e.get('evidence', ''))[:160]}"
            )

    live = report.get("live_mutants", [])
    if live:
        for m in live:
            problems.append(
                f"LIVE MUTANT: row {m.get('row_index')} "
                f"({m.get('from')} + {m.get('event')}) op={m.get('op')} "
                f"target={m.get('mutated_target')} fault={m.get('mutated_fault')} "
                f"reason={m.get('reason')}"
            )

    score = report.get("mutation_score")
    score_text = f"mutation score: {score}" if score is not None else "mutation score: n/a"

    if problems:
        return EXIT_VIOLATION, (
            "FAIL: transition-table mutation gate\n  " + "\n  ".join(problems)
            + f"\n  (killed {report.get('killed')}, live {report.get('live')}, "
            f"equivalent {report.get('equivalent')}, errors {report.get('errors')}; {score_text})"
        )

    return EXIT_OK, (
        f"PASS: transition-table mutation gate ({score_text}; "
        f"{report.get('killed')} killed, {report.get('live')} live, "
        f"{report.get('equivalent')} equivalent, {report.get('errors')} errors; "
        f"rows {rows_covered}/{rows_total} covered)"
    )


def main(argv=None):
    parser = argparse.ArgumentParser(
        description=(
            "Transition-table mutation gate: fail on live mutants, mutation "
            "errors, skipped rows, or a stale sweep report."
        )
    )
    parser.add_argument(
        "--report", type=str, default=DEFAULT_REPORT,
        help=f"path to the sweep report JSON (default: {DEFAULT_REPORT})",
    )
    parser.add_argument(
        "--max-report-age-seconds", type=int,
        default=DEFAULT_MAX_REPORT_AGE_SECONDS,
        help="maximum age of generated_at before the report is considered stale",
    )
    args = parser.parse_args(argv)

    exit_code, message = run_gate(
        args.report, max_age_seconds=args.max_report_age_seconds
    )
    print(message)
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
