#!/usr/bin/env python3
"""Generate firmware/tools/proof_record.json from invariants.yaml + the
current transition model.

Plan: docs/plans/2026-08-02-028-feat-state-machine-model-check-plan.md (U7).

Per invariant: the predicate (as declared in invariants.yaml), the
base-case evidence (state_induction invariants only), the per-edge (or
reachability) verification evidence count, and the verdict. The record is
regenerated FROM SOURCE on every run (KTD5: it reruns the invariants
module over the shared U1 model -- it is never hand-edited), so it cannot
go stale relative to the manifest without the CI gate
(scripts/check_firmware_invariants.py) catching the drift.

Usage:
    python3 firmware/tools/gen_proof_record.py

The script is idempotent -- it only overwrites proof_record.json when the
generated content differs from the current file (same discipline as
gen_config.py / gen_transition_table.py).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from invariants import INVARIANTS_YAML, evaluate_all, load_invariant_specs
from transition_model import REPO_ROOT, ModelParseError, TRANSITION_YAML, build_model

OUTPUT_PATH = Path(__file__).resolve().parent / "proof_record.json"


def build_proof_record() -> dict:
    model = build_model()
    specs = load_invariant_specs()
    results = evaluate_all(model, specs)

    return {
        "$schema_note": (
            "Generated by firmware/tools/gen_proof_record.py. DO NOT EDIT BY HAND -- "
            "a hand-edited record fails scripts/check_firmware_invariants.py's drift "
            "check the moment it diverges from a fresh regeneration."
        ),
        "manifest_source": str(TRANSITION_YAML.relative_to(REPO_ROOT)),
        "invariants_source": str(INVARIANTS_YAML.relative_to(REPO_ROOT)),
        "model_state_count": len(model.states),
        "model_edge_count": len(model.edges),
        "invariant_count": len(results),
        "all_passed": all(r.passed for r in results),
        "invariants": [r.to_dict() for r in results],
    }


def render(record: dict) -> str:
    return json.dumps(record, indent=2, sort_keys=False) + "\n"


def main() -> int:
    try:
        record = build_proof_record()
    except ModelParseError as exc:
        print(f"MODEL PARSE ERROR: {exc}", file=sys.stderr)
        return 1

    rendered = render(record)

    if OUTPUT_PATH.exists() and OUTPUT_PATH.read_text() == rendered:
        print("proof_record.json up to date")
        return 0

    OUTPUT_PATH.write_text(rendered)
    print(f"proof_record.json regenerated ({record['invariant_count']} invariants, "
          f"all_passed={record['all_passed']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
